#created on: Mar 24, 2008
package org.kuali.student.enrollment.prerequisite

#list any import classes here.

import org.kuali.student.rules.util.Constraint;


#declare any global variables here

rule "Sum constraint true"

    when 
        constraint : Constraint(constraintID == "A true constraintID from DB")
        Boolean(booleanValue == Boolean.TRUE) from constraint.apply("A")
        
    then
    	System.out.println("We are in true then");
end

rule "Sum constraint false"

    when 
        constraint : Constraint(constraintID == "A false constraintID from DB")
        Boolean(booleanValue == Boolean.TRUE) from constraint.apply("A")
        
    then
    	System.out.println("We are in false then");
end