-- Creating the permissions for add, edit, and delete proposal comments.
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND, DESC_TXT, KIM_TYP_ID, NM, NMSPC_CD, OBJ_ID, PERM_TMPL_ID, VER_NBR)
  VALUES ('Y', null, (SELECT KIM_TYP_ID FROM KRIM_TYP_T WHERE NM = 'Reference Type Permission' AND NMSPC_CD = 'KS-SYS'), 'Add a Comment for Proposals', 'KS-SYS', '3BAAD6EBAEF1423BAF1B6130724CBFB8', CONCAT('KS-', KS_RICE_ID_S.NEXTVAL), 1)
/
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND, DESC_TXT, KIM_TYP_ID, NM, NMSPC_CD, OBJ_ID, PERM_TMPL_ID, VER_NBR)
  VALUES ('Y', null, (SELECT KIM_TYP_ID FROM KRIM_TYP_T WHERE NM = 'Reference Type Permission' AND NMSPC_CD = 'KS-SYS'), 'Edit a Comment for Proposals', 'KS-SYS', '6DE4958FC7E444B1A1F2DE3B7F1B83FB', CONCAT('KS-', KS_RICE_ID_S.NEXTVAL), 1)
/
INSERT INTO KRIM_PERM_TMPL_T (ACTV_IND, DESC_TXT, KIM_TYP_ID, NM, NMSPC_CD, OBJ_ID, PERM_TMPL_ID, VER_NBR)
  VALUES ('Y', null, (SELECT KIM_TYP_ID FROM KRIM_TYP_T WHERE NM = 'Reference Type Permission' AND NMSPC_CD = 'KS-SYS'), 'Delete a Comment for Proposals', 'KS-SYS', 'E2AA9AE669064EA6A05BDCAA9AFB67C2', CONCAT('KS-', KS_RICE_ID_S.NEXTVAL), 1)
/

INSERT INTO KRIM_PERM_T (ACTV_IND, DESC_TXT, NM, NMSPC_CD, OBJ_ID, PERM_ID, PERM_TMPL_ID, VER_NBR)
  VALUES ('Y', 'Authorizes users to add a Comment for Proposals.', 'Add a Comment for Proposals', 'KS-CM', '2A71D1CB617E4529981892495499ECCA', CONCAT('KS-', KS_RICE_ID_S.NEXTVAL), (SELECT PERM_TMPL_ID FROM KRIM_PERM_TMPL_T WHERE NM = 'Add a Comment for Proposals' AND NMSPC_CD = 'KS-SYS'), 1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND, DESC_TXT, NM, NMSPC_CD, OBJ_ID, PERM_ID, PERM_TMPL_ID, VER_NBR)
  VALUES ('Y', 'Authorizes users to edit a Comment for Proposals.', 'Edit a Comment for Proposals', 'KS-CM', '19FAFFC257EA46D0B77692D5780D6D32', CONCAT('KS-', KS_RICE_ID_S.NEXTVAL), (SELECT PERM_TMPL_ID FROM KRIM_PERM_TMPL_T WHERE NM = 'Edit a Comment for Proposals' AND NMSPC_CD = 'KS-SYS'), 1)
/
INSERT INTO KRIM_PERM_T (ACTV_IND, DESC_TXT, NM, NMSPC_CD, OBJ_ID, PERM_ID, PERM_TMPL_ID, VER_NBR)
  VALUES ('Y', 'Authorizes users to delete a Comment for Proposals.', 'Delete a Comment for Proposals', 'KS-CM', 'CE875E1130864FBD844F9DC18CC0C84E', CONCAT('KS-', KS_RICE_ID_S.NEXTVAL), (SELECT PERM_TMPL_ID FROM KRIM_PERM_TMPL_T WHERE NM = 'Delete a Comment for Proposals' AND NMSPC_CD = 'KS-SYS'), 1)
/

INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID, ATTR_VAL, KIM_ATTR_DEFN_ID, KIM_TYP_ID, OBJ_ID, PERM_ID, VER_NBR)
  VALUES (CONCAT('KS-', KS_RICE_ID_S.NEXTVAL), 'referenceType.clu.proposal', (SELECT KIM_ATTR_DEFN_ID FROM KRIM_ATTR_DEFN_T WHERE NM = 'ksReferenceTypeKey' AND NMSPC_CD = 'KS-SYS'), (SELECT KIM_TYP_ID FROM KRIM_TYP_T WHERE NM = 'Reference Type Permission' AND NMSPC_CD = 'KS-SYS'), '036F65009457426E867C07D29DFF47A6', (SELECT PERM_ID FROM KRIM_PERM_T WHERE NM = 'Add a Comment for Proposals' AND NMSPC_CD = 'KS-CM'), 1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID, ATTR_VAL, KIM_ATTR_DEFN_ID, KIM_TYP_ID, OBJ_ID, PERM_ID, VER_NBR)
  VALUES (CONCAT('KS-', KS_RICE_ID_S.NEXTVAL), 'referenceType.clu.proposal', (SELECT KIM_ATTR_DEFN_ID FROM KRIM_ATTR_DEFN_T WHERE NM = 'ksReferenceTypeKey' AND NMSPC_CD = 'KS-SYS'), (SELECT KIM_TYP_ID FROM KRIM_TYP_T WHERE NM = 'Reference Type Permission' AND NMSPC_CD = 'KS-SYS'), 'E4567E16481F44A6B7F825C2DE89248C', (SELECT PERM_ID FROM KRIM_PERM_T WHERE NM = 'Edit a Comment for Proposals' AND NMSPC_CD = 'KS-CM'), 1)
/
INSERT INTO KRIM_PERM_ATTR_DATA_T (ATTR_DATA_ID, ATTR_VAL, KIM_ATTR_DEFN_ID, KIM_TYP_ID, OBJ_ID, PERM_ID, VER_NBR)
  VALUES (CONCAT('KS-', KS_RICE_ID_S.NEXTVAL), 'referenceType.clu.proposal', (SELECT KIM_ATTR_DEFN_ID FROM KRIM_ATTR_DEFN_T WHERE NM = 'ksReferenceTypeKey' AND NMSPC_CD = 'KS-SYS'), (SELECT KIM_TYP_ID FROM KRIM_TYP_T WHERE NM = 'Reference Type Permission' AND NMSPC_CD = 'KS-SYS'), '2A08DEB7D0F74C6AA639184A3E18B069', (SELECT PERM_ID FROM KRIM_PERM_T WHERE NM = 'Delete a Comment for Proposals' AND NMSPC_CD = 'KS-CM'), 1)
/
