
package org.kuali.student.poc.personidentity.person.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by the CXF 2.0.4-incubator
 * Thu Mar 27 11:42:24 EDT 2008
 * Generated source version: 2.0.4-incubator
 * 
 */

@XmlRootElement(name = "searchForPeopleByPersonAttributeSetType", namespace = "http://student.kuali.org/poc/wsdl/personidentity/person")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "searchForPeopleByPersonAttributeSetType", namespace = "http://student.kuali.org/poc/wsdl/personidentity/person")

public class SearchForPeopleByPersonAttributeSetType {

    @XmlElement(name = "personAttributeSetTypeKey")
    private java.lang.String personAttributeSetTypeKey;
    @XmlElement(name = "personCriteria")
    private org.kuali.student.poc.personidentity.person.dto.PersonCriteria personCriteria;

    public java.lang.String getPersonAttributeSetTypeKey() {
        return this.personAttributeSetTypeKey;
    }
    
    public void setPersonAttributeSetTypeKey( java.lang.String newPersonAttributeSetTypeKey ) {
        this.personAttributeSetTypeKey = newPersonAttributeSetTypeKey;
    }
    
    public org.kuali.student.poc.personidentity.person.dto.PersonCriteria getPersonCriteria() {
        return this.personCriteria;
    }
    
    public void setPersonCriteria( org.kuali.student.poc.personidentity.person.dto.PersonCriteria newPersonCriteria ) {
        this.personCriteria = newPersonCriteria;
    }
    
}

