
package org.kuali.student.rules.rulemanagement.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.1.2
 * Thu Jan 15 15:29:33 EST 2009
 * Generated source version: 2.1.2
 */

@XmlRootElement(name = "fetchBusinessRuleInfoByAnchor", namespace = "http://student.kuali.org/wsdl/brms/RuleManagement")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fetchBusinessRuleInfoByAnchor", namespace = "http://student.kuali.org/wsdl/brms/RuleManagement")

public class FetchBusinessRuleInfoByAnchor {

    @XmlElement(name = "arg0")
    private org.kuali.student.rules.rulemanagement.dto.BusinessRuleAnchorInfoDTO arg0;

    public org.kuali.student.rules.rulemanagement.dto.BusinessRuleAnchorInfoDTO getArg0() {
        return this.arg0;
    }

    public void setArg0(org.kuali.student.rules.rulemanagement.dto.BusinessRuleAnchorInfoDTO newArg0)  {
        this.arg0 = newArg0;
    }

}

