-- remaining R1 Activity Offering Types into KSEN_TYPE table
INSERT INTO KSEN_TYPE (TYPE_KEY,OBJ_ID,NAME,DESCR_PLAIN,DESCR_FORMATTED,EFF_DT,EXPIR_DT,REF_OBJECT_URI,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.lu.type.activity.Directed', null, 'Directed','The exchange of opinions or questions on course material, directed by the instructor.','The exchange of opinions or questions on course material, directed by the instructor.', null, null, 'http://student.kuali.org/wsdl/lui/LuiInfo', 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPE (TYPE_KEY,OBJ_ID,NAME,DESCR_PLAIN,DESCR_FORMATTED,EFF_DT,EXPIR_DT,REF_OBJECT_URI,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.lu.type.activity.Discussion', null, 'Discussion','The exchange of opinions or questions on course material.','The exchange of opinions or questions on course material.', null, null, 'http://student.kuali.org/wsdl/lui/LuiInfo', 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPE (TYPE_KEY,OBJ_ID,NAME,DESCR_PLAIN,DESCR_FORMATTED,EFF_DT,EXPIR_DT,REF_OBJECT_URI,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.lu.type.activity.Homework', null, 'Homework','Students doing homework, problem sets and reading assignments and writing','Students doing homework, problem sets and reading assignments and writing', null, null, 'http://student.kuali.org/wsdl/lui/LuiInfo', 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPE (TYPE_KEY,OBJ_ID,NAME,DESCR_PLAIN,DESCR_FORMATTED,EFF_DT,EXPIR_DT,REF_OBJECT_URI,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.lu.type.activity.Lab', null, 'Lab','Student working on projects in a defined laboratory space. Instructors are on-hand for students to ask questions and guidance.','Student working on projects in a defined laboratory space. Instructors are on-hand for students to ask questions and guidance.', null, null, 'http://student.kuali.org/wsdl/lui/LuiInfo', 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPE (TYPE_KEY,OBJ_ID,NAME,DESCR_PLAIN,DESCR_FORMATTED,EFF_DT,EXPIR_DT,REF_OBJECT_URI,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.lu.type.activity.Lecture', null, 'Lecture','Instructor presentation of course materials.','Instructor presentation of course materials.', null, null, 'http://student.kuali.org/wsdl/lui/LuiInfo', 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPE (TYPE_KEY,OBJ_ID,NAME,DESCR_PLAIN,DESCR_FORMATTED,EFF_DT,EXPIR_DT,REF_OBJECT_URI,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.lu.type.activity.Tutorial', null, 'Tutorial','Instructor or assistant walking through a learning practice.','Instructor or assistant walking through a learning practice.', null, null, 'http://student.kuali.org/wsdl/lui/LuiInfo', 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPE (TYPE_KEY,OBJ_ID,NAME,DESCR_PLAIN,DESCR_FORMATTED,EFF_DT,EXPIR_DT,REF_OBJECT_URI,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.lu.type.activity.WebDiscussion', null, 'Web Discuss','Web-based or technologically-mediated activities replacing standard discussion sections','Web-based or technologically-mediated activities replacing standard discussion sections', null, null, 'http://student.kuali.org/wsdl/lui/LuiInfo', 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPE (TYPE_KEY,OBJ_ID,NAME,DESCR_PLAIN,DESCR_FORMATTED,EFF_DT,EXPIR_DT,REF_OBJECT_URI,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.lu.type.activity.WebLecture', null, 'Web Lecture','Instructor presentation of course materials via the web','Instructor presentation of course materials via the web', null, null, 'http://student.kuali.org/wsdl/lui/LuiInfo', 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/

-- Several missing AO Types
INSERT INTO KSEN_TYPE (TYPE_KEY,OBJ_ID,NAME,DESCR_PLAIN,DESCR_FORMATTED,EFF_DT,EXPIR_DT,REF_OBJECT_URI,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.lui.type.activity.offering.clerkship', null, 'Clerkship','Student works as a clerk for a working professional.','Student works as a clerk for a working professional.', null, null, 'http://student.kuali.org/wsdl/lui/LuiInfo', 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPE (TYPE_KEY,OBJ_ID,NAME,DESCR_PLAIN,DESCR_FORMATTED,EFF_DT,EXPIR_DT,REF_OBJECT_URI,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.lui.type.activity.offering.clinic', null, 'Clinic','Student participates in both observing and executing health care delivery in a clinic setting.','Student participates in both observing and executing health care delivery in a clinic setting.', null, null, 'http://student.kuali.org/wsdl/lui/LuiInfo', 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPE (TYPE_KEY,OBJ_ID,NAME,DESCR_PLAIN,DESCR_FORMATTED,EFF_DT,EXPIR_DT,REF_OBJECT_URI,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.lui.type.activity.offering.conference', null, 'Conference','Student attend a conference and optionally present their research results.','Student attend a conference and optionally present their research results.', null, null, 'http://student.kuali.org/wsdl/lui/LuiInfo', 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPE (TYPE_KEY,OBJ_ID,NAME,DESCR_PLAIN,DESCR_FORMATTED,EFF_DT,EXPIR_DT,REF_OBJECT_URI,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.lui.type.activity.offering.practicum', null, 'Practicum','Student has supervised practical application of theory similar to an junior professional in a professional setting.','Student has supervised practical application of theory similar to an junior professional in a professional setting.', null, null, 'http://student.kuali.org/wsdl/lui/LuiInfo', 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPE (TYPE_KEY,OBJ_ID,NAME,DESCR_PLAIN,DESCR_FORMATTED,EFF_DT,EXPIR_DT,REF_OBJECT_URI,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.lui.type.activity.offering.quiz', null, 'Quiz','Discussion of course material, quizzes, tests and other exercises.','Discussion of course material, quizzes, tests and other exercises.', null, null, 'http://student.kuali.org/wsdl/lui/LuiInfo', 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPE (TYPE_KEY,OBJ_ID,NAME,DESCR_PLAIN,DESCR_FORMATTED,EFF_DT,EXPIR_DT,REF_OBJECT_URI,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.lui.type.activity.offering.seminar', null, 'Seminar','Student participate in discussing specific topics in small groups with faculty.','Student participate in discussing specific topics in small groups with faculty.', null, null, 'http://student.kuali.org/wsdl/lui/LuiInfo', 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/

-- R1 Course and Format types in KSEN_TYPE
INSERT INTO KSEN_TYPE (TYPE_KEY,OBJ_ID,NAME,DESCR_PLAIN,DESCR_FORMATTED,EFF_DT,EXPIR_DT,REF_OBJECT_URI,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.lu.type.CreditCourse', null, 'Credit Course','An course offered for academic credit','An course offered for academic credit', null, null, 'http://student.kuali.org/wsdl/course/CourseInfo', 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPE (TYPE_KEY,OBJ_ID,NAME,DESCR_PLAIN,DESCR_FORMATTED,EFF_DT,EXPIR_DT,REF_OBJECT_URI,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.lu.type.CreditCourseFormatShell', null, 'Credit Course Format','A shell for course formats','A shell for course formats', null, null, 'http://student.kuali.org/wsdl/course/FormatInfo', 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/

-- Groupings
INSERT INTO KSEN_TYPE (TYPE_KEY,OBJ_ID,NAME,DESCR_PLAIN,DESCR_FORMATTED,EFF_DT,EXPIR_DT,REF_OBJECT_URI,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.lu.type.grouping.activity', null, 'All Activity Types', 'All of these types of activities: Lecture, Lab, Discussion, etc.', 'All of these types of activities: Lecture, Lab, Discussion, etc.',null, null, 'http://student.kuali.org/wsdl/course/ActivityInfo', 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/


INSERT INTO KSEN_TYPE (TYPE_KEY,OBJ_ID,NAME,DESCR_PLAIN,DESCR_FORMATTED,EFF_DT,EXPIR_DT,REF_OBJECT_URI,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.lui.type.grouping.activity', null, 'All Activity Offering Types', 'All of these types of activity offerings: Lecture, Lab, Discussion, etc.', 'All of these types of activity offerings: Lecture, Lab, Discussion, etc.',null, null, 'http://student.kuali.org/wsdl/courseOffering/ActivityOfferingInfo', 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/

-- Activity Type Groupings
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lu.type.grouping.activity.kuali.lu.type.activity.clerkship', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lu.type.grouping.activity', 'kuali.lu.type.activity.clerkship', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lu.type.grouping.activity.kuali.lu.type.activity.clinic', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lu.type.grouping.activity', 'kuali.lu.type.activity.clinic', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lu.type.grouping.activity.kuali.lu.type.activity.conference', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lu.type.grouping.activity', 'kuali.lu.type.activity.conference', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lu.type.grouping.activity.kuali.lu.type.activity.independentstudy', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lu.type.grouping.activity', 'kuali.lu.type.activity.independentstudy', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lu.type.grouping.activity.kuali.lu.type.activity.practicum', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lu.type.grouping.activity', 'kuali.lu.type.activity.practicum', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lu.type.grouping.activity.kuali.lu.type.activity.quiz', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lu.type.grouping.activity', 'kuali.lu.type.activity.quiz', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lu.type.grouping.activity.kuali.lu.type.activity.seminar', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lu.type.grouping.activity', 'kuali.lu.type.activity.seminar', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lu.type.grouping.activity.kuali.lu.type.activity.studio', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lu.type.grouping.activity', 'kuali.lu.type.activity.studio', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lu.type.grouping.activity.kuali.lu.type.activity.Directed', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lu.type.grouping.activity', 'kuali.lu.type.activity.Directed', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lu.type.grouping.activity.kuali.lu.type.activity.Discussion', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lu.type.grouping.activity', 'kuali.lu.type.activity.Discussion', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lu.type.grouping.activity.kuali.lu.type.activity.Homework', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lu.type.grouping.activity', 'kuali.lu.type.activity.Homework', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lu.type.grouping.activity.kuali.lu.type.activity.Lab', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lu.type.grouping.activity', 'kuali.lu.type.activity.Lab', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lu.type.grouping.activity.kuali.lu.type.activity.Lecture', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lu.type.grouping.activity', 'kuali.lu.type.activity.Lecture', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lu.type.grouping.activity.kuali.lu.type.activity.Tutorial', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lu.type.grouping.activity', 'kuali.lu.type.activity.Tutorial', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lu.type.grouping.activity.kuali.lu.type.activity.WebDiscussion', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lu.type.grouping.activity', 'kuali.lu.type.activity.WebDiscussion', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lu.type.grouping.activity.kuali.lu.type.activity.WebLecture', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lu.type.grouping.activity', 'kuali.lu.type.activity.WebLecture', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/

-- Activity Offering Type Groupings
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lui.type.grouping.activity.kuali.lui.type.activity.offering.lecture', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lui.type.grouping.activity', 'kuali.lui.type.activity.offering.lecture', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lui.type.grouping.activity.kuali.lui.type.activity.offering.lab', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lui.type.grouping.activity', 'kuali.lui.type.activity.offering.lab', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lui.type.grouping.activity.kuali.lui.type.activity.offering.discussion', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lui.type.grouping.activity', 'kuali.lui.type.activity.offering.discussion', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lui.type.grouping.activity.kuali.lui.type.activity.offering.tutorial', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lui.type.grouping.activity', 'kuali.lui.type.activity.offering.tutorial', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lui.type.grouping.activity.kuali.lui.type.activity.offering.weblecture', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lui.type.grouping.activity', 'kuali.lui.type.activity.offering.weblecture', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lui.type.grouping.activity.kuali.lui.type.activity.offering.webdiscussion', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lui.type.grouping.activity', 'kuali.lui.type.activity.offering.webdiscussion', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lui.type.grouping.activity.kuali.lui.type.activity.offering.directed', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lui.type.grouping.activity', 'kuali.lui.type.activity.offering.directed', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lui.type.grouping.activity.kuali.lui.type.activity.offering.studio', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lui.type.grouping.activity', 'kuali.lui.type.activity.offering.studio', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lui.type.grouping.activity.kuali.lui.type.activity.offering.correspond', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lui.type.grouping.activity', 'kuali.lui.type.activity.offering.correspond', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lui.type.grouping.activity.kuali.lui.type.activity.offering.activity', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lui.type.grouping.activity', 'kuali.lui.type.activity.offering.activity', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lui.type.grouping.activity.kuali.lui.type.activity.offering.colloquium', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lui.type.grouping.activity', 'kuali.lui.type.activity.offering.colloquium', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lui.type.grouping.activity.kuali.lui.type.activity.offering.demonstration', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lui.type.grouping.activity', 'kuali.lui.type.activity.offering.demonstration', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lui.type.grouping.activity.kuali.lui.type.activity.offering.field', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lui.type.grouping.activity', 'kuali.lui.type.activity.offering.field', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lui.type.grouping.activity.kuali.lui.type.activity.offering.homework', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lui.type.grouping.activity', 'kuali.lui.type.activity.offering.homework', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lui.type.grouping.activity.kuali.lui.type.activity.offering.independ', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lui.type.grouping.activity', 'kuali.lui.type.activity.offering.independ', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lui.type.grouping.activity.kuali.lui.type.activity.offering.internship', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lui.type.grouping.activity', 'kuali.lui.type.activity.offering.internship', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lui.type.grouping.activity.kuali.lui.type.activity.offering.private', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lui.type.grouping.activity', 'kuali.lui.type.activity.offering.private', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lui.type.grouping.activity.kuali.lui.type.activity.offering.recitation', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lui.type.grouping.activity', 'kuali.lui.type.activity.offering.recitation', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lui.type.grouping.activity.kuali.lui.type.activity.offering.research', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lui.type.grouping.activity', 'kuali.lui.type.activity.offering.research', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lui.type.grouping.activity.kuali.lui.type.activity.offering.selfpaced', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lui.type.grouping.activity', 'kuali.lui.type.activity.offering.selfpaced', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lui.type.grouping.activity.kuali.lui.type.activity.offering.compbased', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lui.type.grouping.activity', 'kuali.lui.type.activity.offering.compbased', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID,OBJ_ID,TYPETYPE_RELTN_TYPE,TYPETYPE_RELTN_STATE,EFF_DT,EXPIR_DT,OWNER_TYPE_ID,RELATED_TYPE_ID,RANK,VER_NBR,CREATETIME,CREATEID,UPDATETIME,UPDATEID) VALUES ('kuali.type.type.relation.type.group.kuali.lui.type.grouping.activity.kuali.lui.type.activity.offering.videoconf', null, 'kuali.type.type.relation.type.group', 'kuali.type.type.relation.state.active', null, null, 'kuali.lui.type.grouping.activity', 'kuali.lui.type.activity.offering.videoconf', 0, 0, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/

-- TypeType relations mapping LU types to their allowed LUI types
INSERT INTO KSEN_TYPETYPE_RELTN (ID, OBJ_ID, VER_NBR, EFF_DT, EXPIR_DT, TYPETYPE_RELTN_TYPE, TYPETYPE_RELTN_STATE, OWNER_TYPE_ID, RELATED_TYPE_ID, RANK,CREATETIME,CREATEID,UPDATETIME,UPDATEID) values ('kuali.lu.lui.type.type.relation.allowed.course', null, 0, to_date('2011-01-01', 'YYYY-MM-DD'), to_date('2100-01-01', 'YYYY-MM-DD'), 'kuali.type.type.relation.type.allowed','kuali.type.type.relation.state.active','kuali.lu.type.CreditCourse', 'kuali.lui.type.course.offering', 1, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID, OBJ_ID, VER_NBR, EFF_DT, EXPIR_DT, TYPETYPE_RELTN_TYPE, TYPETYPE_RELTN_STATE, OWNER_TYPE_ID, RELATED_TYPE_ID, RANK,CREATETIME,CREATEID,UPDATETIME,UPDATEID) values ('kuali.lu.lui.type.type.relation.allowed.format', null, 0, to_date('2011-01-01', 'YYYY-MM-DD'), to_date('2100-01-01', 'YYYY-MM-DD'), 'kuali.type.type.relation.type.allowed','kuali.type.type.relation.state.active','kuali.lu.type.CreditCourseFormatShell', 'kuali.lui.type.course.format.offering', 1, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/

INSERT INTO KSEN_TYPETYPE_RELTN (ID, OBJ_ID, VER_NBR, EFF_DT, EXPIR_DT, TYPETYPE_RELTN_TYPE, TYPETYPE_RELTN_STATE,OWNER_TYPE_ID, RELATED_TYPE_ID, RANK,CREATETIME,CREATEID,UPDATETIME,UPDATEID) values ('kuali.lu.lui.type.type.relation.allowed.Clerkship', null, 0, to_date( '2011-01-01', 'YYYY-MM-DD'), to_date('2100-01-01', 'YYYY-MM-DD'), 'kuali.type.type.relation.type.allowed','kuali.type.type.relation.state.active','kuali.lu.type.activity.clerkship', 'kuali.lui.type.activity.offering.clerkship', 1, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID, OBJ_ID, VER_NBR, EFF_DT, EXPIR_DT, TYPETYPE_RELTN_TYPE, TYPETYPE_RELTN_STATE,OWNER_TYPE_ID, RELATED_TYPE_ID, RANK,CREATETIME,CREATEID,UPDATETIME,UPDATEID) values ('kuali.lu.lui.type.type.relation.allowed.Clinic', null, 0, to_date( '2011-01-01', 'YYYY-MM-DD'), to_date('2100-01-01', 'YYYY-MM-DD'), 'kuali.type.type.relation.type.allowed','kuali.type.type.relation.state.active','kuali.lu.type.activity.clinic', 'kuali.lui.type.activity.offering.clinic', 1, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID, OBJ_ID, VER_NBR, EFF_DT, EXPIR_DT, TYPETYPE_RELTN_TYPE, TYPETYPE_RELTN_STATE,OWNER_TYPE_ID, RELATED_TYPE_ID, RANK,CREATETIME,CREATEID,UPDATETIME,UPDATEID) values ('kuali.lu.lui.type.type.relation.allowed.Conference', null, 0, to_date( '2011-01-01', 'YYYY-MM-DD'), to_date('2100-01-01', 'YYYY-MM-DD'), 'kuali.type.type.relation.type.allowed','kuali.type.type.relation.state.active','kuali.lu.type.activity.conference', 'kuali.lui.type.activity.offering.conference', 1, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID, OBJ_ID, VER_NBR, EFF_DT, EXPIR_DT, TYPETYPE_RELTN_TYPE, TYPETYPE_RELTN_STATE,OWNER_TYPE_ID, RELATED_TYPE_ID, RANK,CREATETIME,CREATEID,UPDATETIME,UPDATEID) values ('kuali.lu.lui.type.type.relation.allowed.Directed', null, 0, to_date( '2011-01-01', 'YYYY-MM-DD'), to_date('2100-01-01', 'YYYY-MM-DD'), 'kuali.type.type.relation.type.allowed','kuali.type.type.relation.state.active','kuali.lu.type.activity.Directed', 'kuali.lui.type.activity.offering.directed', 1, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID, OBJ_ID, VER_NBR, EFF_DT, EXPIR_DT, TYPETYPE_RELTN_TYPE, TYPETYPE_RELTN_STATE,OWNER_TYPE_ID, RELATED_TYPE_ID, RANK,CREATETIME,CREATEID,UPDATETIME,UPDATEID) values ('kuali.lu.lui.type.type.relation.allowed.Discussion', null, 0, to_date( '2011-01-01', 'YYYY-MM-DD'), to_date('2100-01-01', 'YYYY-MM-DD'), 'kuali.type.type.relation.type.allowed','kuali.type.type.relation.state.active','kuali.lu.type.activity.Discussion', 'kuali.lui.type.activity.offering.discussion', 1, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID, OBJ_ID, VER_NBR, EFF_DT, EXPIR_DT, TYPETYPE_RELTN_TYPE, TYPETYPE_RELTN_STATE,OWNER_TYPE_ID, RELATED_TYPE_ID, RANK,CREATETIME,CREATEID,UPDATETIME,UPDATEID) values ('kuali.lu.lui.type.type.relation.allowed.Homework', null, 0, to_date( '2011-01-01', 'YYYY-MM-DD'), to_date('2100-01-01', 'YYYY-MM-DD'), 'kuali.type.type.relation.type.allowed','kuali.type.type.relation.state.active','kuali.lu.type.activity.Homework', 'kuali.lui.type.activity.offering.homework', 1, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID, OBJ_ID, VER_NBR, EFF_DT, EXPIR_DT, TYPETYPE_RELTN_TYPE, TYPETYPE_RELTN_STATE,OWNER_TYPE_ID, RELATED_TYPE_ID, RANK,CREATETIME,CREATEID,UPDATETIME,UPDATEID) values ('kuali.lu.lui.type.type.relation.allowed.IndependentStudy', null, 0, to_date( '2011-01-01', 'YYYY-MM-DD'), to_date('2100-01-01', 'YYYY-MM-DD'), 'kuali.type.type.relation.type.allowed','kuali.type.type.relation.state.active','kuali.lu.type.activity.independentstudy', 'kuali.lui.type.activity.offering.independ', 1, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID, OBJ_ID, VER_NBR, EFF_DT, EXPIR_DT, TYPETYPE_RELTN_TYPE, TYPETYPE_RELTN_STATE,OWNER_TYPE_ID, RELATED_TYPE_ID, RANK,CREATETIME,CREATEID,UPDATETIME,UPDATEID) values ('kuali.lu.lui.type.type.relation.allowed.Lab', null, 0, to_date( '2011-01-01', 'YYYY-MM-DD'), to_date('2100-01-01', 'YYYY-MM-DD'), 'kuali.type.type.relation.type.allowed','kuali.type.type.relation.state.active','kuali.lu.type.activity.Lab', 'kuali.lui.type.activity.offering.lab', 1, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID, OBJ_ID, VER_NBR, EFF_DT, EXPIR_DT, TYPETYPE_RELTN_TYPE, TYPETYPE_RELTN_STATE,OWNER_TYPE_ID, RELATED_TYPE_ID, RANK,CREATETIME,CREATEID,UPDATETIME,UPDATEID) values ('kuali.lu.lui.type.type.relation.allowed.Lecture', null, 0, to_date( '2011-01-01', 'YYYY-MM-DD'), to_date('2100-01-01', 'YYYY-MM-DD'), 'kuali.type.type.relation.type.allowed','kuali.type.type.relation.state.active','kuali.lu.type.activity.Lecture', 'kuali.lui.type.activity.offering.lecture', 1, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID, OBJ_ID, VER_NBR, EFF_DT, EXPIR_DT, TYPETYPE_RELTN_TYPE, TYPETYPE_RELTN_STATE,OWNER_TYPE_ID, RELATED_TYPE_ID, RANK,CREATETIME,CREATEID,UPDATETIME,UPDATEID) values ('kuali.lu.lui.type.type.relation.allowed.Practicum', null, 0, to_date( '2011-01-01', 'YYYY-MM-DD'), to_date('2100-01-01', 'YYYY-MM-DD'), 'kuali.type.type.relation.type.allowed','kuali.type.type.relation.state.active','kuali.lu.type.activity.practicum', 'kuali.lui.type.activity.offering.practicum', 1, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID, OBJ_ID, VER_NBR, EFF_DT, EXPIR_DT, TYPETYPE_RELTN_TYPE, TYPETYPE_RELTN_STATE,OWNER_TYPE_ID, RELATED_TYPE_ID, RANK,CREATETIME,CREATEID,UPDATETIME,UPDATEID) values ('kuali.lu.lui.type.type.relation.allowed.Quiz', null, 0, to_date( '2011-01-01', 'YYYY-MM-DD'), to_date('2100-01-01', 'YYYY-MM-DD'), 'kuali.type.type.relation.type.allowed','kuali.type.type.relation.state.active','kuali.lu.type.activity.quiz', 'kuali.lui.type.activity.offering.quiz', 1, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID, OBJ_ID, VER_NBR, EFF_DT, EXPIR_DT, TYPETYPE_RELTN_TYPE, TYPETYPE_RELTN_STATE,OWNER_TYPE_ID, RELATED_TYPE_ID, RANK,CREATETIME,CREATEID,UPDATETIME,UPDATEID) values ('kuali.lu.lui.type.type.relation.allowed.Seminar', null, 0, to_date( '2011-01-01', 'YYYY-MM-DD'), to_date('2100-01-01', 'YYYY-MM-DD'), 'kuali.type.type.relation.type.allowed','kuali.type.type.relation.state.active','kuali.lu.type.activity.seminar', 'kuali.lui.type.activity.offering.seminar', 1, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID, OBJ_ID, VER_NBR, EFF_DT, EXPIR_DT, TYPETYPE_RELTN_TYPE, TYPETYPE_RELTN_STATE,OWNER_TYPE_ID, RELATED_TYPE_ID, RANK,CREATETIME,CREATEID,UPDATETIME,UPDATEID) values ('kuali.lu.lui.type.type.relation.allowed.Studio', null, 0, to_date( '2011-01-01', 'YYYY-MM-DD'), to_date('2100-01-01', 'YYYY-MM-DD'), 'kuali.type.type.relation.type.allowed','kuali.type.type.relation.state.active','kuali.lu.type.activity.studio', 'kuali.lui.type.activity.offering.studio', 1, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID, OBJ_ID, VER_NBR, EFF_DT, EXPIR_DT, TYPETYPE_RELTN_TYPE, TYPETYPE_RELTN_STATE,OWNER_TYPE_ID, RELATED_TYPE_ID, RANK,CREATETIME,CREATEID,UPDATETIME,UPDATEID) values ('kuali.lu.lui.type.type.relation.allowed.Tutorial', null, 0, to_date( '2011-01-01', 'YYYY-MM-DD'), to_date('2100-01-01', 'YYYY-MM-DD'), 'kuali.type.type.relation.type.allowed','kuali.type.type.relation.state.active','kuali.lu.type.activity.Tutorial', 'kuali.lui.type.activity.offering.tutorial', 1, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID, OBJ_ID, VER_NBR, EFF_DT, EXPIR_DT, TYPETYPE_RELTN_TYPE, TYPETYPE_RELTN_STATE,OWNER_TYPE_ID, RELATED_TYPE_ID, RANK,CREATETIME,CREATEID,UPDATETIME,UPDATEID) values ('kuali.lu.lui.type.type.relation.allowed.WebDiscuss', null, 0, to_date( '2011-01-01', 'YYYY-MM-DD'), to_date('2100-01-01', 'YYYY-MM-DD'), 'kuali.type.type.relation.type.allowed','kuali.type.type.relation.state.active','kuali.lu.type.activity.WebDiscussion', 'kuali.lui.type.activity.offering.webdiscussion', 1, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/
INSERT INTO KSEN_TYPETYPE_RELTN (ID, OBJ_ID, VER_NBR, EFF_DT, EXPIR_DT, TYPETYPE_RELTN_TYPE, TYPETYPE_RELTN_STATE,OWNER_TYPE_ID, RELATED_TYPE_ID, RANK,CREATETIME,CREATEID,UPDATETIME,UPDATEID) values ('kuali.lu.lui.type.type.relation.allowed.WebLecture', null, 0, to_date( '2011-01-01', 'YYYY-MM-DD'), to_date('2100-01-01', 'YYYY-MM-DD'), 'kuali.type.type.relation.type.allowed','kuali.type.type.relation.state.active','kuali.lu.type.activity.WebLecture', 'kuali.lui.type.activity.offering.weblecture', 1, to_date('2012-03-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null,null)
/