/*
 * Copyright 2009 The Kuali Foundation Licensed under the
 * Educational Community License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License. You may
 * obtain a copy of the License at
 * 
 * http://www.osedu.org/licenses/ECL-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an "AS IS"
 * BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.21 at 02:14:18 PM PDT 
//

package org.kuali.student.core.enumerable.dto;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.kuali.student.core.dictionary.dto.Context;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;code&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *         &lt;element name=&quot;abbrevValue&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *         &lt;element name=&quot;effectiveDate&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}date&quot;/&gt;
 *         &lt;element name=&quot;expirationDate&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}date&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element name=&quot;sortKey&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot;/&gt;
 *         &lt;element ref=&quot;{http://www.dto.dictionary.student.kuali.org}contexts&quot;/&gt;
 *         &lt;element name=&quot;value&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "code", "abbrevValue", "effectiveDate",
		"expirationDate", "sortKey", "contexts", "value" })
@XmlRootElement(name = "enumeratedValue")
public class EnumeratedValue implements Serializable {

	private static final long serialVersionUID = 1L;

	@XmlElement(required = true)
	private String code;

	@XmlElement(required = true)
	private String abbrevValue;

	@XmlElement(required = true)
	private Date effectiveDate;

	@XmlElement(required = false)
	private Date expirationDate;

	@XmlElement(required = false)
	private Integer sortKey;

	@XmlElement(required = true)
	private List<Context> contexts;

	@XmlElement(required = true)
	private String value;

	/**
	 * Gets the value of the code property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCode() {
		return code;
	}

	/**
	 * Sets the value of the code property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCode(String value) {
		this.code = value;
	}

	/**
	 * Gets the value of the abbrevValue property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAbbrevValue() {
		return abbrevValue;
	}

	/**
	 * Sets the value of the abbrevValue property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAbbrevValue(String value) {
		this.abbrevValue = value;
	}

	/**
	 * Gets the value of the effectiveDate property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getEffectiveDate() {
		return effectiveDate;
	}

	/**
	 * Sets the value of the effectiveDate property.
	 * 
	 * @param value
	 *            allowed object is {@link Date }
	 * 
	 */
	public void setEffectiveDate(Date value) {
		this.effectiveDate = value;
	}

	/**
	 * Gets the value of the expirationDate property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getExpirationDate() {
		return expirationDate;
	}

	/**
	 * Sets the value of the expirationDate property.
	 * 
	 * @param value
	 *            allowed object is {@link Date }
	 * 
	 */
	public void setExpirationDate(Date value) {
		this.expirationDate = value;
	}

	/**
	 * Gets the value of the sortKey property.
	 * 
	 */
	public Integer getSortKey() {
		return sortKey;
	}

	/**
	 * Sets the value of the sortKey property.
	 * 
	 */
	public void setSortKey(Integer value) {
		this.sortKey = value;
	}

	/**
	 * Gets the value of the contexts property.
	 * 
	 * @return possible object is {@link Contexts }
	 * 
	 */
	public List<Context> getContexts() {
		if (contexts == null) {
			contexts = new ArrayList<Context>();
		}
		return contexts;
	}

	/**
	 * Sets the value of the contexts property.
	 * 
	 * @param value
	 *            allowed object is {@link Contexts }
	 * 
	 */
	public void setContexts(List<Context> value) {
		this.contexts = value;
	}

	/**
	 * Gets the value of the key property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getValue() {
		return value;
	}

	/**
	 * Sets the value of the key property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setValue(String value) {
		this.value = value;
	}

}
