
package org.kuali.student.core.atp.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.2
 * Tue Mar 31 14:06:06 EDT 2009
 * Generated source version: 2.2
 */

@XmlRootElement(name = "getAtpsByDates", namespace = "http://student.kuali.org/core/atp")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getAtpsByDates", namespace = "http://student.kuali.org/core/atp", propOrder = {"startDate","endDate"})

public class GetAtpsByDates {

    @XmlElement(name = "startDate")
    private java.util.Date startDate;
    @XmlElement(name = "endDate")
    private java.util.Date endDate;

    public java.util.Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(java.util.Date newStartDate)  {
        this.startDate = newStartDate;
    }

    public java.util.Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(java.util.Date newEndDate)  {
        this.endDate = newEndDate;
    }

}

