
package edu.umd.ks.poc.lum.lu.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by the CXF 2.0.4-incubator
 * Fri Apr 18 16:30:06 EDT 2008
 * Generated source version: 2.0.4-incubator
 * 
 */

@XmlRootElement(name = "fetchLui", namespace = "http://edu.umd.ks/poc/lum/lu")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fetchLui", namespace = "http://edu.umd.ks/poc/lum/lu")

public class FetchLui {

    @XmlElement(name = "luiId")
    private java.lang.String luiId;

    public java.lang.String getLuiId() {
        return this.luiId;
    }
    
    public void setLuiId( java.lang.String newLuiId ) {
        this.luiId = newLuiId;
    }
    
}

