
package edu.umd.ks.poc.lum.lu.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.1
 * Tue Sep 30 14:46:43 EDT 2008
 * Generated source version: 2.1
 */

@XmlRootElement(name = "removeLuAttributeTypeInfoResponse", namespace = "http://edu.umd.ks/poc/lum/lu")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "removeLuAttributeTypeInfoResponse", namespace = "http://edu.umd.ks/poc/lum/lu")

public class RemoveLuAttributeTypeInfoResponse {

    @XmlElement(name = "return")
    private edu.umd.ks.poc.lum.lu.dto.Status _return;

    public edu.umd.ks.poc.lum.lu.dto.Status getReturn() {
        return this._return;
    }

    public void setReturn(edu.umd.ks.poc.lum.lu.dto.Status new_return)  {
        this._return = new_return;
    }

}

