
package edu.umd.ks.poc.lum.lu.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by the CXF 2.0.4-incubator
 * Fri Apr 18 16:30:06 EDT 2008
 * Generated source version: 2.0.4-incubator
 * 
 */

@XmlRootElement(name = "removeCluSetFromCluSet", namespace = "http://edu.umd.ks/poc/lum/lu")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "removeCluSetFromCluSet", namespace = "http://edu.umd.ks/poc/lum/lu")

public class RemoveCluSetFromCluSet {

    @XmlElement(name = "cluSetId")
    private java.lang.String cluSetId;
    @XmlElement(name = "removedCluSetId")
    private java.lang.String removedCluSetId;

    public java.lang.String getCluSetId() {
        return this.cluSetId;
    }
    
    public void setCluSetId( java.lang.String newCluSetId ) {
        this.cluSetId = newCluSetId;
    }
    
    public java.lang.String getRemovedCluSetId() {
        return this.removedCluSetId;
    }
    
    public void setRemovedCluSetId( java.lang.String newRemovedCluSetId ) {
        this.removedCluSetId = newRemovedCluSetId;
    }
    
}

