
package edu.umd.ks.poc.lum.lu.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by the CXF 2.0.4-incubator
 * Fri Apr 18 16:30:06 EDT 2008
 * Generated source version: 2.0.4-incubator
 * 
 */

@XmlRootElement(name = "searchForLuiRelations", namespace = "http://edu.umd.ks/poc/lum/lu")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "searchForLuiRelations", namespace = "http://edu.umd.ks/poc/lum/lu")

public class SearchForLuiRelations {

    @XmlElement(name = "luiRelationCriteria")
    private edu.umd.ks.poc.lum.lu.dto.LuiRelationCriteria luiRelationCriteria;

    public edu.umd.ks.poc.lum.lu.dto.LuiRelationCriteria getLuiRelationCriteria() {
        return this.luiRelationCriteria;
    }
    
    public void setLuiRelationCriteria( edu.umd.ks.poc.lum.lu.dto.LuiRelationCriteria newLuiRelationCriteria ) {
        this.luiRelationCriteria = newLuiRelationCriteria;
    }
    
}

