
package edu.umd.ks.poc.lum.lu.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by the CXF 2.0.4-incubator
 * Fri Apr 18 16:30:06 EDT 2008
 * Generated source version: 2.0.4-incubator
 * 
 */

@XmlRootElement(name = "searchForCluIds", namespace = "http://edu.umd.ks/poc/lum/lu")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "searchForCluIds", namespace = "http://edu.umd.ks/poc/lum/lu")

public class SearchForCluIds {

    @XmlElement(name = "cluCriteria")
    private edu.umd.ks.poc.lum.lu.dto.CluCriteria cluCriteria;

    public edu.umd.ks.poc.lum.lu.dto.CluCriteria getCluCriteria() {
        return this.cluCriteria;
    }
    
    public void setCluCriteria( edu.umd.ks.poc.lum.lu.dto.CluCriteria newCluCriteria ) {
        this.cluCriteria = newCluCriteria;
    }
    
}

