
package edu.umd.ks.poc.lum.lu.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.1
 * Tue Sep 30 14:46:43 EDT 2008
 * Generated source version: 2.1
 */

@XmlRootElement(name = "updateLuAttributeTypeInfo", namespace = "http://edu.umd.ks/poc/lum/lu")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateLuAttributeTypeInfo", namespace = "http://edu.umd.ks/poc/lum/lu")

public class UpdateLuAttributeTypeInfo {

    @XmlElement(name = "luAttributeTypeInfo")
    private edu.umd.ks.poc.lum.lu.dto.LuAttributeTypeInfo luAttributeTypeInfo;

    public edu.umd.ks.poc.lum.lu.dto.LuAttributeTypeInfo getLuAttributeTypeInfo() {
        return this.luAttributeTypeInfo;
    }

    public void setLuAttributeTypeInfo(edu.umd.ks.poc.lum.lu.dto.LuAttributeTypeInfo newLuAttributeTypeInfo)  {
        this.luAttributeTypeInfo = newLuAttributeTypeInfo;
    }

}

