
package org.kuali.student.lum.lu.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.2
 * Thu Jan 21 10:05:23 PST 2010
 * Generated source version: 2.2
 */

@XmlRootElement(name = "createClu", namespace = "http://student.kuali.org/wsdl/lu")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "createClu", namespace = "http://student.kuali.org/wsdl/lu", propOrder = {"luTypeKey","cluInfo"})

public class CreateClu {

    @XmlElement(name = "luTypeKey")
    private java.lang.String luTypeKey;
    @XmlElement(name = "cluInfo")
    private org.kuali.student.lum.lu.dto.CluInfo cluInfo;

    public java.lang.String getLuTypeKey() {
        return this.luTypeKey;
    }

    public void setLuTypeKey(java.lang.String newLuTypeKey)  {
        this.luTypeKey = newLuTypeKey;
    }

    public org.kuali.student.lum.lu.dto.CluInfo getCluInfo() {
        return this.cluInfo;
    }

    public void setCluInfo(org.kuali.student.lum.lu.dto.CluInfo newCluInfo)  {
        this.cluInfo = newCluInfo;
    }

}

