

ALTER TABLE KSEN_ROOM
    ADD CONSTRAINT KSEN_ROOM_FK1 FOREIGN KEY (BUILDING_ID)
    REFERENCES KSEN_ROOM_BUILDING (ID)
/


ALTER TABLE KSEN_ROOM_ACCESS_TYPE
    ADD CONSTRAINT KSEN_ROOM_ACCESS_TYPE_FK1 FOREIGN KEY (ROOM_ID)
    REFERENCES KSEN_ROOM (ID)
/


ALTER TABLE KSEN_ROOM_ATTR
    ADD CONSTRAINT KSEN_ROOM_ATTR_FK1 FOREIGN KEY (OWNER_ID)
    REFERENCES KSEN_ROOM (ID)
/



ALTER TABLE KSEN_ROOM_BUILDING_ATTR
    ADD CONSTRAINT KSEN_ROOM_BUILDING_ATTR_FK1 FOREIGN KEY (OWNER_ID)
    REFERENCES KSEN_ROOM_BUILDING (ID)
/


ALTER TABLE KSEN_ROOM_FIXED_RSRC
    ADD CONSTRAINT KSEN_ROOM_FIXED_RSRC_FK1 FOREIGN KEY (ROOM_ID)
    REFERENCES KSEN_ROOM (ID)
/


ALTER TABLE KSEN_ROOM_FIXED_RSRC_ATTR
    ADD CONSTRAINT KSEN_ROOM_FIXED_RSRC_ATTR_FK1 FOREIGN KEY (OWNER_ID)
    REFERENCES KSEN_ROOM_FIXED_RSRC (ID)
/


ALTER TABLE KSEN_ROOM_RESP_ORG
    ADD CONSTRAINT KSEN_ROOM_RESP_ORG_FK1 FOREIGN KEY (ROOM_ID)
    REFERENCES KSEN_ROOM (ID)
/


ALTER TABLE KSEN_ROOM_RESP_ORG_ATTR
    ADD CONSTRAINT KSEN_ROOM_RESP_ORG_ATTR_FK1 FOREIGN KEY (OWNER_ID)
    REFERENCES KSEN_ROOM_RESP_ORG (ID)
/


ALTER TABLE KSEN_ROOM_USAGE
    ADD CONSTRAINT KSEN_ROOM_USAGE_FK1 FOREIGN KEY (ROOM_ID)
    REFERENCES KSEN_ROOM (ID)
/


ALTER TABLE KSEN_ROOM_USAGE_ATTR
    ADD CONSTRAINT KSEN_ROOM_USAGE_ATTR_FK1 FOREIGN KEY (OWNER_ID)
    REFERENCES KSEN_ROOM_USAGE (ID)
/

