
package org.kuali.student.core.document.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.2
 * Tue Jun 16 14:57:19 EDT 2009
 * Generated source version: 2.2
 */

@XmlRootElement(name = "updateDocument", namespace = "http://student.kuali.org/core/document")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateDocument", namespace = "http://student.kuali.org/core/document", propOrder = {"documentId","documentInfo"})

public class UpdateDocument {

    @XmlElement(name = "documentId")
    private java.lang.String documentId;
    @XmlElement(name = "documentInfo")
    private org.kuali.student.core.document.dto.DocumentInfo documentInfo;

    public java.lang.String getDocumentId() {
        return this.documentId;
    }

    public void setDocumentId(java.lang.String newDocumentId)  {
        this.documentId = newDocumentId;
    }

    public org.kuali.student.core.document.dto.DocumentInfo getDocumentInfo() {
        return this.documentInfo;
    }

    public void setDocumentInfo(org.kuali.student.core.document.dto.DocumentInfo newDocumentInfo)  {
        this.documentInfo = newDocumentInfo;
    }

}

