CREATE UNIQUE INDEX KSEN_TYPE_P ON KSEN_TYPE
(TYPE_KEY   ASC)
/
ALTER TABLE KSEN_TYPE
	ADD CONSTRAINT  KSEN_TYPE_P PRIMARY KEY (TYPE_KEY)
/
CREATE  INDEX KSEN_TYPE_I1 ON KSEN_TYPE
(REF_OBJECT_URI   ASC)
/
CREATE UNIQUE INDEX KSEN_TYPE_ATTR_P ON KSEN_TYPE_ATTR
(ID   ASC)
/
ALTER TABLE KSEN_TYPE_ATTR
	ADD CONSTRAINT  KSEN_TYPE_ATTR_P PRIMARY KEY (ID)
/
CREATE  INDEX KSEN_TYPE_ATTR_IF1 ON KSEN_TYPE_ATTR
(OWNER_ID   ASC)
/
CREATE UNIQUE INDEX KSEN_TYPETYPE_RELTN_P ON KSEN_TYPETYPE_RELTN
(ID   ASC)
/
ALTER TABLE KSEN_TYPETYPE_RELTN
	ADD CONSTRAINT  KSEN_TYPETYPE_RELTN_P PRIMARY KEY (ID)
/
CREATE  INDEX KSEN_TYPETYPE_RELTN_IF1 ON KSEN_TYPETYPE_RELTN
(OWNER_TYPE_ID   ASC)
/
CREATE  INDEX KSEN_TYPETYPE_RELTN_IF2 ON KSEN_TYPETYPE_RELTN
(RELATED_TYPE_ID   ASC)
/
CREATE UNIQUE INDEX KSEN_TYPETYPE_RELTN_ATTR_P ON KSEN_TYPETYPE_RELTN_ATTR
(ID   ASC)
/
ALTER TABLE KSEN_TYPETYPE_RELTN_ATTR
	ADD CONSTRAINT  KSEN_TYPETYPE_RELTN_ATTR_P PRIMARY KEY (ID)
/
CREATE  INDEX KSEN_TYPETYPE_RELTN_ATTR_IF1 ON KSEN_TYPETYPE_RELTN_ATTR
(OWNER_ID   ASC)
/
ALTER TABLE KSEN_TYPE_ATTR
	ADD (CONSTRAINT KSEN_TYPE_ATTR_FK1 FOREIGN KEY (OWNER_ID) REFERENCES KSEN_TYPE (TYPE_KEY))
/
ALTER TABLE KSEN_TYPETYPE_RELTN
	ADD (CONSTRAINT KSEN_TYPETYPE_RELTN_FK1 FOREIGN KEY (OWNER_TYPE_ID) REFERENCES KSEN_TYPE (TYPE_KEY))
/
ALTER TABLE KSEN_TYPETYPE_RELTN
	ADD (CONSTRAINT KSEN_TYPETYPE_RELTN_FK2 FOREIGN KEY (RELATED_TYPE_ID) REFERENCES KSEN_TYPE (TYPE_KEY))
/
ALTER TABLE KSEN_TYPETYPE_RELTN_ATTR
	ADD (CONSTRAINT KSEN_TYPETYPE_RELTN_ATTR_FK1 FOREIGN KEY (OWNER_ID) REFERENCES KSEN_TYPETYPE_RELTN (ID))
/
