
ALTER TABLE KSLR_RESCOMP
    ADD CONSTRAINT KSLR_RESCOMP_FK1 FOREIGN KEY (TYPE)
    REFERENCES KSLR_RESCOMP_TYPE (TYPE_KEY)
/

ALTER TABLE KSLR_RESCOMP
    ADD CONSTRAINT KSLR_RESCOMP_FK2 FOREIGN KEY (RT_DESCR_ID)
    REFERENCES KSLR_RICH_TEXT_T (ID)
/


ALTER TABLE KSLR_RESCOMP_ATTR
    ADD CONSTRAINT KSLR_RESCOMP_ATTR_FK1 FOREIGN KEY (OWNER)
    REFERENCES KSLR_RESCOMP (ID)
/




ALTER TABLE KSLR_RESCOMP_TYPE_ATTR
    ADD CONSTRAINT KSLR_RESCOMP_TYPE_ATTR_FK1 FOREIGN KEY (OWNER)
    REFERENCES KSLR_RESCOMP_TYPE (TYPE_KEY)
/


ALTER TABLE KSLR_RESULT_VALUE
    ADD CONSTRAINT KSLR_RESULT_VALUE_FK1 FOREIGN KEY (RSLT_COMP_ID)
    REFERENCES KSLR_RESCOMP (ID)
/



ALTER TABLE KSLR_SCALE
    ADD CONSTRAINT KSLR_SCALE_FK1 FOREIGN KEY (RT_DESCR_ID)
    REFERENCES KSLR_RICH_TEXT_T (ID)
/


ALTER TABLE KSLR_SCALE_ATTR
    ADD CONSTRAINT KSLR_SCALE_ATTR_FK1 FOREIGN KEY (OWNER)
    REFERENCES KSLR_SCALE (ID)
/
