
ALTER TABLE KSAP_ATP
    ADD CONSTRAINT KSAP_ATP_FK1 FOREIGN KEY (TYPE)
    REFERENCES KSAP_ATP_TYPE (TYPE_KEY)
/

ALTER TABLE KSAP_ATP
    ADD CONSTRAINT KSAP_ATP_FK2 FOREIGN KEY (RT_DESCR_ID)
    REFERENCES KSAP_RICH_TEXT_T (ID)
/


ALTER TABLE KSAP_ATP_ATTR
    ADD CONSTRAINT KSAP_ATP_ATTR_FK1 FOREIGN KEY (OWNER)
    REFERENCES KSAP_ATP (ID)
/



ALTER TABLE KSAP_ATP_DUR_TYPE_ATTR
    ADD CONSTRAINT KSAP_ATP_DUR_TYPE_ATTR_FK1 FOREIGN KEY (OWNER)
    REFERENCES KSAP_ATP_DUR_TYPE (TYPE_KEY)
/



ALTER TABLE KSAP_ATP_SEASONAL_TYPE_ATTR
    ADD CONSTRAINT KSAP_ATP_SEAS_TYPE_ATTR_FK1 FOREIGN KEY (OWNER)
    REFERENCES KSAP_ATP_SEASONAL_TYPE (TYPE_KEY)
/


ALTER TABLE KSAP_ATP_TYPE
    ADD CONSTRAINT KSAP_ATP_TYPE_FK1 FOREIGN KEY (SEASONAL_TYPE)
    REFERENCES KSAP_ATP_SEASONAL_TYPE (TYPE_KEY)
/

ALTER TABLE KSAP_ATP_TYPE
    ADD CONSTRAINT KSAP_ATP_TYPE_FK2 FOREIGN KEY (DUR_TYPE)
    REFERENCES KSAP_ATP_DUR_TYPE (TYPE_KEY)
/


ALTER TABLE KSAP_ATP_TYPE_ATTR
    ADD CONSTRAINT KSAP_ATP_TYPE_ATTR_FK1 FOREIGN KEY (OWNER)
    REFERENCES KSAP_ATP_TYPE (TYPE_KEY)
/


ALTER TABLE KSAP_DT_RANGE
    ADD CONSTRAINT KSAP_DT_RANGE_FK1 FOREIGN KEY (DT_RANGE_TYPE_ID)
    REFERENCES KSAP_DT_RANGE_TYPE (TYPE_KEY)
/

ALTER TABLE KSAP_DT_RANGE
    ADD CONSTRAINT KSAP_DT_RANGE_FK2 FOREIGN KEY (RT_DESCR_ID)
    REFERENCES KSAP_RICH_TEXT_T (ID)
/

ALTER TABLE KSAP_DT_RANGE
    ADD CONSTRAINT KSAP_DT_RANGE_FK3 FOREIGN KEY (ATP_ID)
    REFERENCES KSAP_ATP (ID)
/


ALTER TABLE KSAP_DT_RANGE_ATTR
    ADD CONSTRAINT KSAP_DT_RANGE_ATTR_FK1 FOREIGN KEY (OWNER)
    REFERENCES KSAP_DT_RANGE (DATERANGE_KEY)
/



ALTER TABLE KSAP_DT_RANGE_TYPE_ATTR
    ADD CONSTRAINT KSAP_DT_RANGE_TYPE_ATTR_FK1 FOREIGN KEY (OWNER)
    REFERENCES KSAP_DT_RANGE_TYPE (TYPE_KEY)
/


ALTER TABLE KSAP_MLSTN
    ADD CONSTRAINT KSAP_MLSTN_FK1 FOREIGN KEY (ATP_ID)
    REFERENCES KSAP_ATP (ID)
/

ALTER TABLE KSAP_MLSTN
    ADD CONSTRAINT KSAP_MLSTN_FK2 FOREIGN KEY (RT_DESCR_ID)
    REFERENCES KSAP_RICH_TEXT_T (ID)
/

ALTER TABLE KSAP_MLSTN
    ADD CONSTRAINT KSAP_MLSTN_FK3 FOREIGN KEY (MLSTN_TYPE_ID)
    REFERENCES KSAP_MLSTN_TYPE (TYPE_KEY)
/


ALTER TABLE KSAP_MLSTN_ATTR
    ADD CONSTRAINT KSAP_MLSTN_ATTR_FK1 FOREIGN KEY (OWNER)
    REFERENCES KSAP_MLSTN (ID)
/



ALTER TABLE KSAP_MLSTN_TYPE_ATTR
    ADD CONSTRAINT KSAP_MLSTN_TYPE_ATTR_FK1 FOREIGN KEY (OWNER)
    REFERENCES KSAP_MLSTN_TYPE (TYPE_KEY)
/

