insert into KSEN_TYPE (TYPE_KEY, OBJ_ID, NAME, DESCR_PLAIN, DESCR_FORMATTED, EFF_DT, EXPIR_DT, REF_OBJECT_URI, VER_NBR, CREATETIME, CREATEID, UPDATETIME, UPDATEID) values ('kuali.atp.milestone.firstdayofclasses', null, 'First day of classes', 'First day of classes', 'First day of classes', null, null, 'http://student.kuali.org/wsdl/atp/MilestoneInfo', 0, to_date('2012-08-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null, null)
/
insert into KSEN_TYPE (TYPE_KEY, OBJ_ID, NAME, DESCR_PLAIN, DESCR_FORMATTED, EFF_DT, EXPIR_DT, REF_OBJECT_URI, VER_NBR, CREATETIME, CREATEID, UPDATETIME, UPDATEID) values ('kuali.atp.milestone.lastdayofregistration', null, 'Last day of registration', 'Last day of registration', 'Last day of registration', null, null, 'http://student.kuali.org/wsdl/atp/MilestoneInfo', 0, to_date('2012-08-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null, null)
/
insert into KSEN_TYPE (TYPE_KEY, OBJ_ID, NAME, DESCR_PLAIN, DESCR_FORMATTED, EFF_DT, EXPIR_DT, REF_OBJECT_URI, VER_NBR, CREATETIME, CREATEID, UPDATETIME, UPDATEID) values ('kuali.atp.milestone.endoffirstweekofclasses', null, 'End of first week of classes', 'End of first week of classes', 'End of first week of classes', null, null, 'http://student.kuali.org/wsdl/atp/MilestoneInfo', 0, to_date('2012-08-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null, null)
/
insert into KSEN_TYPE (TYPE_KEY, OBJ_ID, NAME, DESCR_PLAIN, DESCR_FORMATTED, EFF_DT, EXPIR_DT, REF_OBJECT_URI, VER_NBR, CREATETIME, CREATEID, UPDATETIME, UPDATEID) values ('kuali.atp.milestone.monthpriortostartofclasses', null, 'Month prior to start of classes', 'Month prior to start of classes', 'Month prior to start of classes', null, null, 'http://student.kuali.org/wsdl/atp/MilestoneInfo', 0, to_date('2012-08-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null, null)
/
insert into KSEN_TYPE (TYPE_KEY, OBJ_ID, NAME, DESCR_PLAIN, DESCR_FORMATTED, EFF_DT, EXPIR_DT, REF_OBJECT_URI, VER_NBR, CREATETIME, CREATEID, UPDATETIME, UPDATEID) values ('kuali.milestone.type.group.seatpool', null, 'Grouping type for seatpool milestone types', 'Grouping type for seatpool milestone types', 'Grouping type for seatpool milestone types', null, null, 'http://student.kuali.org/wsdl/atp/AtpInfo', 1, to_date('2012-08-01', 'YYYY-MM-DD'), 'SYSTEMLOADER', null, null)
/
