--Context
INSERT INTO KRMS_CNTXT_T (ACTV,CNTXT_ID,DESC_TXT,NM,NMSPC_CD,TYP_ID,VER_NBR)
  VALUES ('Y',CONCAT('KS-KRMS-CNTXT-', KS_RICE_ID_S.NEXTVAL),'FinalExamMatrix','Final Exam Matrix Rules','KS-SYS',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.agenda.type.final.exam'),0)
/

--Agendas and References
INSERT INTO KRMS_AGENDA_T (ACTV,AGENDA_ID,CNTXT_ID,INIT_AGENDA_ITM_ID,NM,TYP_ID,VER_NBR)
  VALUES ('Y',CONCAT('KS-KRMS-AGENDA-', KS_RICE_ID_S.NEXTVAL),(SELECT CNTXT_ID FROM KRMS_CNTXT_T WHERE DESC_TXT = 'FinalExamMatrix'),null,'Fall Standard Final Exam Rules',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.agenda.type.final.exam.standard'),0)
/
INSERT INTO KRMS_REF_OBJ_KRMS_OBJ_T (ACTV,COLLECTION_NM,KRMS_DSCR_TYP,KRMS_OBJ_ID,NMSPC_CD,REF_DSCR_TYP,REF_OBJ_ID,REF_OBJ_KRMS_OBJ_ID,VER_NBR)
  VALUES ('Y','FinalExamMatrix','Agenda',CONCAT('KS-KRMS-AGENDA-', KS_RICE_ID_S.CURRVAL),'KS-SYS','kuali.atp.type.group.term','kuali.atp.type.Fall',CONCAT('KS-KRMS-REF-OBJ-KRMS-OBJ-', KS_RICE_ID_S.NEXTVAL),0)
/

INSERT INTO KRMS_AGENDA_T (ACTV,AGENDA_ID,CNTXT_ID,INIT_AGENDA_ITM_ID,NM,TYP_ID,VER_NBR)
  VALUES ('Y',CONCAT('KS-KRMS-AGENDA-', KS_RICE_ID_S.NEXTVAL),(SELECT CNTXT_ID FROM KRMS_CNTXT_T WHERE DESC_TXT = 'FinalExamMatrix'),null,'Fall Common Final Exam Rules',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.agenda.type.final.exam.common'),0)
/
INSERT INTO KRMS_REF_OBJ_KRMS_OBJ_T (ACTV,COLLECTION_NM,KRMS_DSCR_TYP,KRMS_OBJ_ID,NMSPC_CD,REF_DSCR_TYP,REF_OBJ_ID,REF_OBJ_KRMS_OBJ_ID,VER_NBR)
  VALUES ('Y','FinalExamMatrix','Agenda',CONCAT('KS-KRMS-AGENDA-', KS_RICE_ID_S.CURRVAL),'KS-SYS','kuali.atp.type.group.term','kuali.atp.type.Fall',CONCAT('KS-KRMS-REF-OBJ-KRMS-OBJ-', KS_RICE_ID_S.NEXTVAL),0)
/

--Agenda Items
INSERT INTO KRMS_AGENDA_ITM_T (AGENDA_ID,AGENDA_ITM_ID,RULE_ID,VER_NBR)
  VALUES ((SELECT AGENDA_ID FROM KRMS_AGENDA_T WHERE NM = 'Fall Standard Final Exam Rules'),CONCAT('KS-KRMS-AGENDA-ITM-', KS_RICE_ID_S.NEXTVAL),null,1)
/
UPDATE KRMS_AGENDA_T set INIT_AGENDA_ITM_ID = CONCAT('KS-KRMS-AGENDA-ITM-', KS_RICE_ID_S.CURRVAL) WHERE NM = 'Fall Standard Final Exam Rules'
/
INSERT INTO KRMS_AGENDA_ITM_T (AGENDA_ID,AGENDA_ITM_ID,RULE_ID,VER_NBR)
  VALUES ((SELECT AGENDA_ID FROM KRMS_AGENDA_T WHERE NM = 'Fall Common Final Exam Rules'),CONCAT('KS-KRMS-AGENDA-ITM-', KS_RICE_ID_S.NEXTVAL),null,1)
/
UPDATE KRMS_AGENDA_T set INIT_AGENDA_ITM_ID = CONCAT('KS-KRMS-AGENDA-ITM-', KS_RICE_ID_S.CURRVAL) WHERE NM = 'Fall Common Final Exam Rules'
/