package org.kuali.student.wsdl.atp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Thu Aug 26 16:26:25 EDT 2010
 * Generated source version: 2.2.3
 * 
 */
 
@WebService(targetNamespace = "http://student.kuali.org/wsdl/atp", name = "AtpService")
@XmlSeeAlso({org.kuali.student.wsdl.exceptions.ObjectFactory.class,org.kuali.student.wsdl.search.ObjectFactory.class,org.kuali.student.wsdl.dictionary.ObjectFactory.class,org.kuali.student.wsdl.organization.ObjectFactory.class,ObjectFactory.class})
public interface AtpService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "validateAtp", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.ValidateAtp")
    @ResponseWrapper(localName = "validateAtpResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.ValidateAtpResponse")
    @WebMethod
    public java.util.List<org.kuali.student.wsdl.atp.ValidationResultInfo> validateAtp(
        @WebParam(name = "validationType", targetNamespace = "")
        java.lang.String validationType,
        @WebParam(name = "atpInfo", targetNamespace = "")
        org.kuali.student.wsdl.atp.AtpInfo atpInfo
    ) throws OperationFailedException, InvalidParameterException, MissingParameterException, DoesNotExistException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAtpDurationTypes", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetAtpDurationTypes")
    @ResponseWrapper(localName = "getAtpDurationTypesResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetAtpDurationTypesResponse")
    @WebMethod
    public java.util.List<org.kuali.student.wsdl.atp.AtpDurationTypeInfo> getAtpDurationTypes() throws OperationFailedException;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "searchResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", partName = "parameters")
    @WebMethod
    public org.kuali.student.wsdl.organization.SearchResponse search(
        @WebParam(partName = "parameters", name = "search", targetNamespace = "http://student.kuali.org/wsdl/atp")
        org.kuali.student.wsdl.organization.Search parameters
    ) throws MissingParameterException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAtpTypes", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetAtpTypes")
    @ResponseWrapper(localName = "getAtpTypesResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetAtpTypesResponse")
    @WebMethod
    public java.util.List<org.kuali.student.wsdl.atp.AtpTypeInfo> getAtpTypes() throws OperationFailedException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "removeMilestone", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.RemoveMilestone")
    @ResponseWrapper(localName = "removeMilestoneResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.RemoveMilestoneResponse")
    @WebMethod
    public org.kuali.student.wsdl.atp.StatusInfo removeMilestone(
        @WebParam(name = "milestoneKey", targetNamespace = "")
        java.lang.String milestoneKey
    ) throws OperationFailedException, PermissionDeniedException, InvalidParameterException, MissingParameterException, DoesNotExistException;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getSearchCriteriaTypesResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", partName = "parameters")
    @WebMethod
    public org.kuali.student.wsdl.search.GetSearchCriteriaTypesResponse getSearchCriteriaTypes(
        @WebParam(partName = "parameters", name = "getSearchCriteriaTypes", targetNamespace = "http://student.kuali.org/wsdl/atp")
        org.kuali.student.wsdl.search.GetSearchCriteriaTypes parameters
    ) throws OperationFailedException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addMilestone", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.AddMilestone")
    @ResponseWrapper(localName = "addMilestoneResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.AddMilestoneResponse")
    @WebMethod
    public org.kuali.student.wsdl.atp.MilestoneInfo addMilestone(
        @WebParam(name = "atpKey", targetNamespace = "")
        java.lang.String atpKey,
        @WebParam(name = "milestoneKey", targetNamespace = "")
        java.lang.String milestoneKey,
        @WebParam(name = "milestoneInfo", targetNamespace = "")
        org.kuali.student.wsdl.atp.MilestoneInfo milestoneInfo
    ) throws OperationFailedException, PermissionDeniedException, InvalidParameterException, MissingParameterException, DataValidationErrorException, AlreadyExistsException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getMilestoneTypesForAtpType", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetMilestoneTypesForAtpType")
    @ResponseWrapper(localName = "getMilestoneTypesForAtpTypeResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetMilestoneTypesForAtpTypeResponse")
    @WebMethod
    public java.util.List<org.kuali.student.wsdl.atp.MilestoneTypeInfo> getMilestoneTypesForAtpType(
        @WebParam(name = "atpTypeKey", targetNamespace = "")
        java.lang.String atpTypeKey
    ) throws OperationFailedException, InvalidParameterException, MissingParameterException, DoesNotExistException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAtpSeasonalType", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetAtpSeasonalType")
    @ResponseWrapper(localName = "getAtpSeasonalTypeResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetAtpSeasonalTypeResponse")
    @WebMethod
    public org.kuali.student.wsdl.atp.AtpSeasonalTypeInfo getAtpSeasonalType(
        @WebParam(name = "atpSeasonalTypeKey", targetNamespace = "")
        java.lang.String atpSeasonalTypeKey
    ) throws OperationFailedException, InvalidParameterException, MissingParameterException, DoesNotExistException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAtpsByDates", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetAtpsByDates")
    @ResponseWrapper(localName = "getAtpsByDatesResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetAtpsByDatesResponse")
    @WebMethod
    public java.util.List<org.kuali.student.wsdl.atp.AtpInfo> getAtpsByDates(
        @WebParam(name = "startDate", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar endDate
    ) throws OperationFailedException, InvalidParameterException, MissingParameterException;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getSearchResultTypeResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", partName = "parameters")
    @WebMethod
    public org.kuali.student.wsdl.search.GetSearchResultTypeResponse getSearchResultType(
        @WebParam(partName = "parameters", name = "getSearchResultType", targetNamespace = "http://student.kuali.org/wsdl/atp")
        org.kuali.student.wsdl.search.GetSearchResultType parameters
    ) throws OperationFailedException, InvalidParameterException, MissingParameterException, DoesNotExistException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAtpSeasonalTypes", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetAtpSeasonalTypes")
    @ResponseWrapper(localName = "getAtpSeasonalTypesResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetAtpSeasonalTypesResponse")
    @WebMethod
    public java.util.List<org.kuali.student.wsdl.atp.AtpSeasonalTypeInfo> getAtpSeasonalTypes() throws OperationFailedException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDateRangeType", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetDateRangeType")
    @ResponseWrapper(localName = "getDateRangeTypeResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetDateRangeTypeResponse")
    @WebMethod
    public org.kuali.student.wsdl.atp.DateRangeTypeInfo getDateRangeType(
        @WebParam(name = "dateRangeTypeKey", targetNamespace = "")
        java.lang.String dateRangeTypeKey
    ) throws OperationFailedException, InvalidParameterException, MissingParameterException, DoesNotExistException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getMilestonesByDatesAndType", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetMilestonesByDatesAndType")
    @ResponseWrapper(localName = "getMilestonesByDatesAndTypeResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetMilestonesByDatesAndTypeResponse")
    @WebMethod
    public java.util.List<org.kuali.student.wsdl.atp.MilestoneInfo> getMilestonesByDatesAndType(
        @WebParam(name = "milestoneTypeKey", targetNamespace = "")
        java.lang.String milestoneTypeKey,
        @WebParam(name = "startDate", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar endDate
    ) throws OperationFailedException, InvalidParameterException, MissingParameterException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateMilestone", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.UpdateMilestone")
    @ResponseWrapper(localName = "updateMilestoneResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.UpdateMilestoneResponse")
    @WebMethod
    public org.kuali.student.wsdl.atp.MilestoneInfo updateMilestone(
        @WebParam(name = "milestoneKey", targetNamespace = "")
        java.lang.String milestoneKey,
        @WebParam(name = "milestoneInfo", targetNamespace = "")
        org.kuali.student.wsdl.atp.MilestoneInfo milestoneInfo
    ) throws OperationFailedException, VersionMismatchException, PermissionDeniedException, InvalidParameterException, MissingParameterException, DataValidationErrorException, DoesNotExistException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAtpType", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetAtpType")
    @ResponseWrapper(localName = "getAtpTypeResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetAtpTypeResponse")
    @WebMethod
    public org.kuali.student.wsdl.atp.AtpTypeInfo getAtpType(
        @WebParam(name = "atpTypeKey", targetNamespace = "")
        java.lang.String atpTypeKey
    ) throws OperationFailedException, InvalidParameterException, MissingParameterException, DoesNotExistException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDateRangeTypesForAtpType", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetDateRangeTypesForAtpType")
    @ResponseWrapper(localName = "getDateRangeTypesForAtpTypeResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetDateRangeTypesForAtpTypeResponse")
    @WebMethod
    public java.util.List<org.kuali.student.wsdl.atp.DateRangeTypeInfo> getDateRangeTypesForAtpType(
        @WebParam(name = "atpTypeKey", targetNamespace = "")
        java.lang.String atpTypeKey
    ) throws OperationFailedException, InvalidParameterException, MissingParameterException, DoesNotExistException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDateRangeTypes", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetDateRangeTypes")
    @ResponseWrapper(localName = "getDateRangeTypesResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetDateRangeTypesResponse")
    @WebMethod
    public java.util.List<org.kuali.student.wsdl.atp.DateRangeTypeInfo> getDateRangeTypes() throws OperationFailedException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getMilestoneTypes", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetMilestoneTypes")
    @ResponseWrapper(localName = "getMilestoneTypesResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetMilestoneTypesResponse")
    @WebMethod
    public java.util.List<org.kuali.student.wsdl.atp.MilestoneTypeInfo> getMilestoneTypes() throws OperationFailedException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateDateRange", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.UpdateDateRange")
    @ResponseWrapper(localName = "updateDateRangeResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.UpdateDateRangeResponse")
    @WebMethod
    public org.kuali.student.wsdl.atp.DateRangeInfo updateDateRange(
        @WebParam(name = "dateRangeKey", targetNamespace = "")
        java.lang.String dateRangeKey,
        @WebParam(name = "dateRangeInfo", targetNamespace = "")
        org.kuali.student.wsdl.atp.DateRangeInfo dateRangeInfo
    ) throws OperationFailedException, VersionMismatchException, PermissionDeniedException, InvalidParameterException, MissingParameterException, DataValidationErrorException, DoesNotExistException;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getSearchResultTypesResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", partName = "parameters")
    @WebMethod
    public org.kuali.student.wsdl.search.GetSearchResultTypesResponse getSearchResultTypes(
        @WebParam(partName = "parameters", name = "getSearchResultTypes", targetNamespace = "http://student.kuali.org/wsdl/atp")
        org.kuali.student.wsdl.search.GetSearchResultTypes parameters
    ) throws OperationFailedException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAtpsByDate", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetAtpsByDate")
    @ResponseWrapper(localName = "getAtpsByDateResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetAtpsByDateResponse")
    @WebMethod
    public java.util.List<org.kuali.student.wsdl.atp.AtpInfo> getAtpsByDate(
        @WebParam(name = "searchDate", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar searchDate
    ) throws OperationFailedException, InvalidParameterException, MissingParameterException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getMilestonesByAtp", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetMilestonesByAtp")
    @ResponseWrapper(localName = "getMilestonesByAtpResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetMilestonesByAtpResponse")
    @WebMethod
    public java.util.List<org.kuali.student.wsdl.atp.MilestoneInfo> getMilestonesByAtp(
        @WebParam(name = "atpKey", targetNamespace = "")
        java.lang.String atpKey
    ) throws OperationFailedException, InvalidParameterException, MissingParameterException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getMilestonesByDates", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetMilestonesByDates")
    @ResponseWrapper(localName = "getMilestonesByDatesResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetMilestonesByDatesResponse")
    @WebMethod
    public java.util.List<org.kuali.student.wsdl.atp.MilestoneInfo> getMilestonesByDates(
        @WebParam(name = "startDate", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar endDate
    ) throws OperationFailedException, InvalidParameterException, MissingParameterException;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getSearchTypesResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", partName = "parameters")
    @WebMethod
    public org.kuali.student.wsdl.search.GetSearchTypesResponse getSearchTypes(
        @WebParam(partName = "parameters", name = "getSearchTypes", targetNamespace = "http://student.kuali.org/wsdl/atp")
        org.kuali.student.wsdl.search.GetSearchTypes parameters
    ) throws OperationFailedException;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getSearchTypesByResultResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", partName = "parameters")
    @WebMethod
    public org.kuali.student.wsdl.search.GetSearchTypesByResultResponse getSearchTypesByResult(
        @WebParam(partName = "parameters", name = "getSearchTypesByResult", targetNamespace = "http://student.kuali.org/wsdl/atp")
        org.kuali.student.wsdl.search.GetSearchTypesByResult parameters
    ) throws OperationFailedException, InvalidParameterException, MissingParameterException, DoesNotExistException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDateRangesByDate", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetDateRangesByDate")
    @ResponseWrapper(localName = "getDateRangesByDateResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetDateRangesByDateResponse")
    @WebMethod
    public java.util.List<org.kuali.student.wsdl.atp.DateRangeInfo> getDateRangesByDate(
        @WebParam(name = "searchDate", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar searchDate
    ) throws OperationFailedException, InvalidParameterException, MissingParameterException;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getSearchTypeResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", partName = "parameters")
    @WebMethod
    public org.kuali.student.wsdl.search.GetSearchTypeResponse getSearchType(
        @WebParam(partName = "parameters", name = "getSearchType", targetNamespace = "http://student.kuali.org/wsdl/atp")
        org.kuali.student.wsdl.search.GetSearchType parameters
    ) throws OperationFailedException, InvalidParameterException, MissingParameterException, DoesNotExistException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDateRangesByAtp", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetDateRangesByAtp")
    @ResponseWrapper(localName = "getDateRangesByAtpResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetDateRangesByAtpResponse")
    @WebMethod
    public java.util.List<org.kuali.student.wsdl.atp.DateRangeInfo> getDateRangesByAtp(
        @WebParam(name = "atpKey", targetNamespace = "")
        java.lang.String atpKey
    ) throws OperationFailedException, InvalidParameterException, MissingParameterException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "removeDateRange", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.RemoveDateRange")
    @ResponseWrapper(localName = "removeDateRangeResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.RemoveDateRangeResponse")
    @WebMethod
    public org.kuali.student.wsdl.atp.StatusInfo removeDateRange(
        @WebParam(name = "dateRangeKey", targetNamespace = "")
        java.lang.String dateRangeKey
    ) throws OperationFailedException, PermissionDeniedException, InvalidParameterException, MissingParameterException, DoesNotExistException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getMilestone", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetMilestone")
    @ResponseWrapper(localName = "getMilestoneResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetMilestoneResponse")
    @WebMethod
    public org.kuali.student.wsdl.atp.MilestoneInfo getMilestone(
        @WebParam(name = "milestoneKey", targetNamespace = "")
        java.lang.String milestoneKey
    ) throws OperationFailedException, InvalidParameterException, MissingParameterException, DoesNotExistException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAtp", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetAtp")
    @ResponseWrapper(localName = "getAtpResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetAtpResponse")
    @WebMethod
    public org.kuali.student.wsdl.atp.AtpInfo getAtp(
        @WebParam(name = "atpKey", targetNamespace = "")
        java.lang.String atpKey
    ) throws OperationFailedException, InvalidParameterException, MissingParameterException, DoesNotExistException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAtpsByAtpType", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetAtpsByAtpType")
    @ResponseWrapper(localName = "getAtpsByAtpTypeResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetAtpsByAtpTypeResponse")
    @WebMethod
    public java.util.List<org.kuali.student.wsdl.atp.AtpInfo> getAtpsByAtpType(
        @WebParam(name = "atpTypeKey", targetNamespace = "")
        java.lang.String atpTypeKey
    ) throws OperationFailedException, InvalidParameterException, MissingParameterException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addDateRange", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.AddDateRange")
    @ResponseWrapper(localName = "addDateRangeResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.AddDateRangeResponse")
    @WebMethod
    public org.kuali.student.wsdl.atp.DateRangeInfo addDateRange(
        @WebParam(name = "atpKey", targetNamespace = "")
        java.lang.String atpKey,
        @WebParam(name = "dateRangeKey", targetNamespace = "")
        java.lang.String dateRangeKey,
        @WebParam(name = "dateRangeInfo", targetNamespace = "")
        org.kuali.student.wsdl.atp.DateRangeInfo dateRangeInfo
    ) throws OperationFailedException, PermissionDeniedException, InvalidParameterException, MissingParameterException, DataValidationErrorException, AlreadyExistsException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDateRange", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetDateRange")
    @ResponseWrapper(localName = "getDateRangeResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetDateRangeResponse")
    @WebMethod
    public org.kuali.student.wsdl.atp.DateRangeInfo getDateRange(
        @WebParam(name = "dateRangeKey", targetNamespace = "")
        java.lang.String dateRangeKey
    ) throws OperationFailedException, InvalidParameterException, MissingParameterException, DoesNotExistException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createAtp", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.CreateAtp")
    @ResponseWrapper(localName = "createAtpResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.CreateAtpResponse")
    @WebMethod
    public org.kuali.student.wsdl.atp.AtpInfo createAtp(
        @WebParam(name = "atpTypeKey", targetNamespace = "")
        java.lang.String atpTypeKey,
        @WebParam(name = "atpKey", targetNamespace = "")
        java.lang.String atpKey,
        @WebParam(name = "atpInfo", targetNamespace = "")
        org.kuali.student.wsdl.atp.AtpInfo atpInfo
    ) throws OperationFailedException, PermissionDeniedException, InvalidParameterException, MissingParameterException, DataValidationErrorException, AlreadyExistsException;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getSearchTypesByCriteriaResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", partName = "parameters")
    @WebMethod
    public org.kuali.student.wsdl.search.GetSearchTypesByCriteriaResponse getSearchTypesByCriteria(
        @WebParam(partName = "parameters", name = "getSearchTypesByCriteria", targetNamespace = "http://student.kuali.org/wsdl/atp")
        org.kuali.student.wsdl.search.GetSearchTypesByCriteria parameters
    ) throws OperationFailedException, InvalidParameterException, MissingParameterException, DoesNotExistException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "validateDateRange", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.ValidateDateRange")
    @ResponseWrapper(localName = "validateDateRangeResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.ValidateDateRangeResponse")
    @WebMethod
    public java.util.List<org.kuali.student.wsdl.atp.ValidationResultInfo> validateDateRange(
        @WebParam(name = "validationType", targetNamespace = "")
        java.lang.String validationType,
        @WebParam(name = "dateRangeInfo", targetNamespace = "")
        org.kuali.student.wsdl.atp.DateRangeInfo dateRangeInfo
    ) throws OperationFailedException, InvalidParameterException, MissingParameterException, DoesNotExistException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "validateMilestone", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.ValidateMilestone")
    @ResponseWrapper(localName = "validateMilestoneResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.ValidateMilestoneResponse")
    @WebMethod
    public java.util.List<org.kuali.student.wsdl.atp.ValidationResultInfo> validateMilestone(
        @WebParam(name = "validationType", targetNamespace = "")
        java.lang.String validationType,
        @WebParam(name = "milestoneInfo", targetNamespace = "")
        org.kuali.student.wsdl.atp.MilestoneInfo milestoneInfo
    ) throws OperationFailedException, InvalidParameterException, MissingParameterException, DoesNotExistException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAtpDurationType", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetAtpDurationType")
    @ResponseWrapper(localName = "getAtpDurationTypeResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetAtpDurationTypeResponse")
    @WebMethod
    public org.kuali.student.wsdl.atp.AtpDurationTypeInfo getAtpDurationType(
        @WebParam(name = "atpDurationTypeKey", targetNamespace = "")
        java.lang.String atpDurationTypeKey
    ) throws OperationFailedException, InvalidParameterException, MissingParameterException, DoesNotExistException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteAtp", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.DeleteAtp")
    @ResponseWrapper(localName = "deleteAtpResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.DeleteAtpResponse")
    @WebMethod
    public org.kuali.student.wsdl.atp.StatusInfo deleteAtp(
        @WebParam(name = "atpKey", targetNamespace = "")
        java.lang.String atpKey
    ) throws OperationFailedException, PermissionDeniedException, InvalidParameterException, MissingParameterException, DoesNotExistException;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getSearchCriteriaTypeResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", partName = "parameters")
    @WebMethod
    public org.kuali.student.wsdl.search.GetSearchCriteriaTypeResponse getSearchCriteriaType(
        @WebParam(partName = "parameters", name = "getSearchCriteriaType", targetNamespace = "http://student.kuali.org/wsdl/atp")
        org.kuali.student.wsdl.search.GetSearchCriteriaType parameters
    ) throws OperationFailedException, InvalidParameterException, MissingParameterException, DoesNotExistException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateAtp", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.UpdateAtp")
    @ResponseWrapper(localName = "updateAtpResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.UpdateAtpResponse")
    @WebMethod
    public org.kuali.student.wsdl.atp.AtpInfo updateAtp(
        @WebParam(name = "atpKey", targetNamespace = "")
        java.lang.String atpKey,
        @WebParam(name = "atpInfo", targetNamespace = "")
        org.kuali.student.wsdl.atp.AtpInfo atpInfo
    ) throws OperationFailedException, VersionMismatchException, PermissionDeniedException, InvalidParameterException, MissingParameterException, DataValidationErrorException, DoesNotExistException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getMilestoneType", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetMilestoneType")
    @ResponseWrapper(localName = "getMilestoneTypeResponse", targetNamespace = "http://student.kuali.org/wsdl/atp", className = "org.kuali.student.wsdl.atp.GetMilestoneTypeResponse")
    @WebMethod
    public org.kuali.student.wsdl.atp.MilestoneTypeInfo getMilestoneType(
        @WebParam(name = "milestoneTypeKey", targetNamespace = "")
        java.lang.String milestoneTypeKey
    ) throws OperationFailedException, InvalidParameterException, MissingParameterException, DoesNotExistException;
}
