DECLARE temp NUMBER;
BEGIN
SELECT COUNT(*) INTO temp FROM user_tables WHERE
table_name =
'KS_DB_VERSION';
IF temp <= 0 THEN EXECUTE IMMEDIATE 'CREATE
    TABLE KS_DB_VERSION
    (
        VERSION VARCHAR2(255),
        MODULE_NAME VARCHAR2(255),
        UPGRADE_TIME TIMESTAMP(6)
    )'; END IF;
END;
/

insert into KS_DB_VERSION (VERSION, MODULE_NAME, UPGRADE_TIME) values ('1.1.0', 'lum', SYSDATE)
/
