-- non-UMD reference data
Insert into KRMS_CMPND_PROP_PROPS_T (CMPND_PROP_ID,PROP_ID) values ('KS-KRMS-PROP-14460','KS-KRMS-PROP-10266')
/
INSERT INTO KRMS_CMPND_PROP_PROPS_T (CMPND_PROP_ID,PROP_ID) VALUES ('KS-KRMS-PROP-14579','KS-KRMS-PROP-10267')
/
INSERT INTO KRMS_CMPND_PROP_PROPS_T (CMPND_PROP_ID,PROP_ID) VALUES ('KS-KRMS-PROP-14713','KS-KRMS-PROP-10256')
/
Insert into KRMS_CMPND_PROP_PROPS_T (CMPND_PROP_ID,PROP_ID) values ('KS-KRMS-PROP-10259','KS-KRMS-PROP-10255')
/
Insert into KRMS_CMPND_PROP_PROPS_T (CMPND_PROP_ID,PROP_ID) values ('KS-KRMS-PROP-10259','KS-KRMS-PROP-10260')
/
Insert into KRMS_CMPND_PROP_PROPS_T (CMPND_PROP_ID,PROP_ID) values ('KS-KRMS-PROP-14067','KS-KRMS-PROP-10268')
/