Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11633','CourseOffering','KS-KRMS-AGENDA-11642','Agenda','6f4597e1-4df6-4697-960d-4633c95813ca','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11634','CourseOffering','KS-KRMS-AGENDA-11643','Agenda','ddca6d81-5afe-4f97-ae9e-2962a71c640d','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11635','CourseOffering','KS-KRMS-AGENDA-11644','Agenda','19bb06aa-a076-4937-8fc4-acccf85b9828','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11636','CourseOffering','KS-KRMS-AGENDA-11645','Agenda','591811e9-2f79-4a30-87df-d52c23ece266','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11637','CourseOffering','KS-KRMS-AGENDA-11646','Agenda','b4d29631-5bf5-4b87-ba9c-e96290773959','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11638','CourseOffering','KS-KRMS-AGENDA-11647','Agenda','b42a5add-c003-4e76-a5db-f3bf4e9df873','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11639','CourseOffering','KS-KRMS-AGENDA-11648','Agenda','c24dc181-fdf8-42f0-acd3-99b0557690c2','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11640','CourseOffering','KS-KRMS-AGENDA-11649','Agenda','0452a908-9dc0-4653-966e-b3c9f26ea746','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11641','CourseOffering','KS-KRMS-AGENDA-11650','Agenda','20ee579b-3ac1-4708-b07e-c6f5ab939963','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11642','CourseOffering','KS-KRMS-AGENDA-11651','Agenda','da771868-8217-4779-b100-c0bd171cae8a','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11643','CourseOffering','KS-KRMS-AGENDA-11652','Agenda','20560029-ab47-4746-9123-e9002f63ec6e','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11644','CourseOffering','KS-KRMS-AGENDA-11653','Agenda','ec209040-20a2-48e2-ad5a-1e3aa02d499f','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11645','CourseOffering','KS-KRMS-AGENDA-11654','Agenda','fa089c19-308e-4996-8bc6-e78467cda2fd','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11646','CourseOffering','KS-KRMS-AGENDA-11655','Agenda','97dced0b-c580-4d74-b426-3a142613c451','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11647','CourseOffering','KS-KRMS-AGENDA-11656','Agenda','de21023c-2432-4cc3-a052-3e54c6c36dc8','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11648','CourseOffering','KS-KRMS-AGENDA-11657','Agenda','44ffeb07-05ff-409f-b806-b2bb5c591989','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11649','CourseOffering','KS-KRMS-AGENDA-11658','Agenda','2331ab10-a658-4a2e-acd2-0f7274295f5c','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11650','CourseOffering','KS-KRMS-AGENDA-11659','Agenda','774e1ed1-b2f6-4bc5-83ef-9c27f275a06f','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11651','CourseOffering','KS-KRMS-AGENDA-11660','Agenda','215457bf-236c-4e68-b759-b9390a71e178','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11652','CourseOffering','KS-KRMS-AGENDA-11661','Agenda','4ac25b25-f8a0-459d-890b-f0d8adf0170c','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11653','CourseOffering','KS-KRMS-AGENDA-11662','Agenda','cd05c291-7bf3-4ea7-bfb6-0432b32013ac','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11654','CourseOffering','KS-KRMS-AGENDA-11663','Agenda','c28af84f-d257-43d2-b43b-7dc7f07fcccf','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11655','CourseOffering','KS-KRMS-AGENDA-11664','Agenda','3cbfe0c9-9f2d-4b9f-a362-5c8a2fd91d17','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11656','CourseOffering','KS-KRMS-AGENDA-11665','Agenda','5d173609-7c64-4b7a-bc16-b51c1f0905b7','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11657','CourseOffering','KS-KRMS-AGENDA-11666','Agenda','f1505c66-a5f4-4fe3-b9a4-4beb88002614','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11658','CourseOffering','KS-KRMS-AGENDA-11667','Agenda','50ac4dc3-30b3-4f17-bf9d-f3409a7dc8d7','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11659','CourseOffering','KS-KRMS-AGENDA-11668','Agenda','a555677c-4fdd-44e6-bbd3-49f0ed1a5252','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11660','CourseOffering','KS-KRMS-AGENDA-11669','Agenda','bf0d858d-fc47-44f4-9eb6-bd9d47d856a4','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11661','CourseOffering','KS-KRMS-AGENDA-11670','Agenda','8e7fa3b9-9560-4f2e-88c5-59c29dc9f126','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11662','CourseOffering','KS-KRMS-AGENDA-11671','Agenda','455ed826-50de-4a92-ba09-60da7722e315','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11663','CourseOffering','KS-KRMS-AGENDA-11672','Agenda','0f074dc5-91ec-4a9d-9f27-decbdbb79e8e','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11664','CourseOffering','KS-KRMS-AGENDA-11673','Agenda','2d1945d1-5923-494c-a8df-22490483aec1','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11665','CourseOffering','KS-KRMS-AGENDA-11674','Agenda','fd21026f-086e-4cd4-be6b-05ddde120b69','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11666','CourseOffering','KS-KRMS-AGENDA-11675','Agenda','3e41692e-d32e-4709-b659-382daef72d32','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11667','CourseOffering','KS-KRMS-AGENDA-11676','Agenda','3878fd27-bd5f-4547-94c7-969a725f1b3e','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11668','CourseOffering','KS-KRMS-AGENDA-11677','Agenda','54a1f697-b8b8-478a-be64-b728fddcf9c4','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11669','CourseOffering','KS-KRMS-AGENDA-11678','Agenda','87df8aed-2868-4e52-ad3c-19796969702f','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11670','CourseOffering','KS-KRMS-AGENDA-11679','Agenda','8daa31a5-a12c-459d-9210-81bff91de04f','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11671','CourseOffering','KS-KRMS-AGENDA-11680','Agenda','a9aadcbd-dfae-436d-bf71-5ce3079a21a0','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11672','CourseOffering','KS-KRMS-AGENDA-11681','Agenda','afa3f491-9f31-41a6-8fb2-e122de0c2705','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11673','CourseOffering','KS-KRMS-AGENDA-11682','Agenda','bc6a0281-c8e6-40ec-8413-3e5836a05e52','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11674','CourseOffering','KS-KRMS-AGENDA-11683','Agenda','d2916a9b-5253-49c0-b660-5e1b12b36f05','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11675','CourseOffering','KS-KRMS-AGENDA-11684','Agenda','f6f63909-59a7-47a1-8f40-e019c6af7bcd','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11676','CourseOffering','KS-KRMS-AGENDA-11685','Agenda','2ac31757-e96f-4440-b899-4abe8b45b9cb','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11677','CourseOffering','KS-KRMS-AGENDA-11686','Agenda','9d6310d5-a4fa-4d75-a9d6-35d3aee62622','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11678','CourseOffering','KS-KRMS-AGENDA-11687','Agenda','e8729cde-1afa-4d3c-aecb-055651de0155','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11679','CourseOffering','KS-KRMS-AGENDA-11688','Agenda','dc6c5174-0f95-4ab1-b880-2bdc05bf4dc6','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11680','CourseOffering','KS-KRMS-AGENDA-11689','Agenda','759bba9a-0ccf-4ddd-bdb9-8abe46f2b784','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11681','CourseOffering','KS-KRMS-AGENDA-11690','Agenda','116c6d6a-4da3-4922-894b-fd7c868835b8','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11682','CourseOffering','KS-KRMS-AGENDA-11691','Agenda','26a78093-b489-4eb7-8671-74e5c1aac82a','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11683','CourseOffering','KS-KRMS-AGENDA-11692','Agenda','5ea24d4a-4c2f-40a0-b2d2-80c61edcd438','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11684','CourseOffering','KS-KRMS-AGENDA-11693','Agenda','41d7a5dc-408d-42ef-b4ed-86a0760c6104','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11685','CourseOffering','KS-KRMS-AGENDA-11694','Agenda','86f0b22d-32d3-4e98-ae98-7e466cb7f7fb','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11686','CourseOffering','KS-KRMS-AGENDA-11695','Agenda','f37332df-a330-4419-8ba9-43adf7526c19','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11687','CourseOffering','KS-KRMS-AGENDA-11696','Agenda','a6e22a6d-9118-488f-b560-cb08a5a5e67c','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11688','CourseOffering','KS-KRMS-AGENDA-11697','Agenda','c9f64290-4926-4d84-98b0-b83d812d1aed','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11689','CourseOffering','KS-KRMS-AGENDA-11698','Agenda','ccacb87d-fb1a-45e3-a7ba-6426108a68da','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11690','CourseOffering','KS-KRMS-AGENDA-11699','Agenda','4a6f4368-2a17-4bef-b62c-872fa66f8211','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11691','CourseOffering','KS-KRMS-AGENDA-11700','Agenda','5535ff93-0d40-4883-92ea-5f6e34655677','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11692','CourseOffering','KS-KRMS-AGENDA-11701','Agenda','db15e453-e064-4897-88f4-d05c381aa79c','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11693','CourseOffering','KS-KRMS-AGENDA-11702','Agenda','d2d9c623-1407-450d-81b0-8a9a04a6a3cc','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11694','CourseOffering','KS-KRMS-AGENDA-11703','Agenda','4775a35b-fe83-4ac2-8630-c0b4558a913d','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11695','CourseOffering','KS-KRMS-AGENDA-11704','Agenda','ffeffe93-79cf-4cf2-bedd-ffbad2128c77','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11696','CourseOffering','KS-KRMS-AGENDA-11705','Agenda','04c96d30-ff49-4f6f-b6da-b0c18ae825b8','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11697','CourseOffering','KS-KRMS-AGENDA-11706','Agenda','3ec29254-cce5-4a11-b2d5-4d6a7b8f1136','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11698','CourseOffering','KS-KRMS-AGENDA-11707','Agenda','be1052b5-5c16-4a1c-94a7-73de24f62556','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11699','CourseOffering','KS-KRMS-AGENDA-11708','Agenda','5e4ae1c0-1757-437c-841c-237c62c2d9df','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11700','CourseOffering','KS-KRMS-AGENDA-11709','Agenda','9dd9724e-efd6-4d31-9624-b46450b57027','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11701','CourseOffering','KS-KRMS-AGENDA-11710','Agenda','ded47cf3-9560-4ba5-91bf-acf74b0c31b9','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11702','CourseOffering','KS-KRMS-AGENDA-11711','Agenda','eecdef60-1fcf-4e18-b7fe-d22e1bda5ef4','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11703','CourseOffering','KS-KRMS-AGENDA-11712','Agenda','b407841c-0bd3-4f50-9a38-4e312632745d','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11704','CourseOffering','KS-KRMS-AGENDA-11713','Agenda','bc54bfe3-72be-47dc-b993-f3ce7fb115d1','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11705','CourseOffering','KS-KRMS-AGENDA-11714','Agenda','5b3c37a6-7572-4a88-96c3-dc1d44f53666','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11706','CourseOffering','KS-KRMS-AGENDA-11715','Agenda','852e6b6d-6506-45b9-8137-f04b4bf5092c','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11707','CourseOffering','KS-KRMS-AGENDA-11716','Agenda','34296855-c304-4073-a69f-06261b56c934','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11708','CourseOffering','KS-KRMS-AGENDA-11717','Agenda','6c7c7840-73aa-48b5-b641-302a5f6367e8','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11709','CourseOffering','KS-KRMS-AGENDA-11718','Agenda','81c4ed32-0a77-4a67-9572-36ef227d79b2','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11710','CourseOffering','KS-KRMS-AGENDA-11719','Agenda','d1e91560-489b-4153-a433-85af8cd7eacd','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11711','CourseOffering','KS-KRMS-AGENDA-11720','Agenda','5bff7d60-ba98-4931-84e5-49cfe277cc50','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11712','CourseOffering','KS-KRMS-AGENDA-11721','Agenda','8486ece6-c5bb-45d4-b7f8-44447b2c8abd','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11713','CourseOffering','KS-KRMS-AGENDA-11722','Agenda','994b5530-8c9f-49bb-ba7a-9fe3f13f9b44','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11714','CourseOffering','KS-KRMS-AGENDA-11723','Agenda','49104ca3-aa50-43f2-ad68-c15f56a6b32c','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11715','CourseOffering','KS-KRMS-AGENDA-11724','Agenda','256892a0-de49-4aee-9fec-e659256c3af7','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11716','CourseOffering','KS-KRMS-AGENDA-11725','Agenda','9fc91894-4275-4e7c-92ea-8703d67d02c0','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11717','CourseOffering','KS-KRMS-AGENDA-11726','Agenda','e4714f32-6174-495a-96ea-4598509bd55c','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11718','CourseOffering','KS-KRMS-AGENDA-11727','Agenda','075b54a0-133a-4e58-9b89-99cb1498e0f0','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11719','CourseOffering','KS-KRMS-AGENDA-11728','Agenda','26a79829-b42c-441b-b9cf-0d8f7a35629f','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11720','CourseOffering','KS-KRMS-AGENDA-11729','Agenda','84d4cc82-a24f-4775-8374-a5a4ebcab530','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11721','CourseOffering','KS-KRMS-AGENDA-11730','Agenda','9a3126b4-bcad-403a-87ba-ddc438141039','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11722','CourseOffering','KS-KRMS-AGENDA-11731','Agenda','c567753a-6ad7-4014-96dd-d476a1241bb4','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11723','CourseOffering','KS-KRMS-AGENDA-11732','Agenda','ed154e38-cbbf-4c52-baf6-54ebfe3538d2','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11724','CourseOffering','KS-KRMS-AGENDA-11733','Agenda','0994250e-3bdf-4fa7-8bbf-a9d6ba1d4a96','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11725','CourseOffering','KS-KRMS-AGENDA-11734','Agenda','7dade84a-80eb-4b41-b589-4cd312e47db9','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11726','CourseOffering','KS-KRMS-AGENDA-11735','Agenda','a35ae6ea-652c-4e1b-b053-089123dca4b6','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11727','CourseOffering','KS-KRMS-AGENDA-11736','Agenda','b18d15d2-0357-463a-9032-26f6caaf87b4','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11728','CourseOffering','KS-KRMS-AGENDA-11737','Agenda','aa369f1b-c68d-48b5-b057-7f39b248f1f1','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11729','CourseOffering','KS-KRMS-AGENDA-11738','Agenda','067a9041-daae-4b75-9105-2a1712e4464a','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11730','CourseOffering','KS-KRMS-AGENDA-11739','Agenda','3a7d5985-02ca-4ff7-83fc-75909528786d','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11731','CourseOffering','KS-KRMS-AGENDA-11740','Agenda','088d856b-6e1e-4f74-8a5a-760449b25cc6','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11732','CourseOffering','KS-KRMS-AGENDA-11741','Agenda','e70d4d89-074b-44b5-9b9d-0c2251b55966','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11733','CourseOffering','KS-KRMS-AGENDA-11742','Agenda','031b74e9-b72a-4cb0-8d65-11b2b76022e6','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11734','CourseOffering','KS-KRMS-AGENDA-11743','Agenda','6c910aec-2972-49a0-aa73-4d20bab20c42','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11735','CourseOffering','KS-KRMS-AGENDA-11744','Agenda','ad0653ed-b829-4c48-af30-45703e073eca','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11736','CourseOffering','KS-KRMS-AGENDA-11745','Agenda','89f8d1ab-18ca-4f26-8560-ebc82a214a73','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11737','CourseOffering','KS-KRMS-AGENDA-11746','Agenda','9ee777fc-55de-4c0a-b830-42dd30012dbd','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11738','CourseOffering','KS-KRMS-AGENDA-11747','Agenda','60a7623e-784a-4a68-a454-379ff5adf1cb','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11739','CourseOffering','KS-KRMS-AGENDA-11748','Agenda','5f683bcf-501e-4b7a-a40a-ed14e51a82b9','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11740','CourseOffering','KS-KRMS-AGENDA-11749','Agenda','59fedaaa-e123-4689-8a4c-c4c327be63b7','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11741','CourseOffering','KS-KRMS-AGENDA-11750','Agenda','8c8ed771-2e0e-46c0-ae7e-ccb2773abd2d','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11742','CourseOffering','KS-KRMS-AGENDA-11751','Agenda','483d6c1c-72a4-46d6-a46c-93451f07d12c','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11743','CourseOffering','KS-KRMS-AGENDA-11752','Agenda','19e6f37a-1a72-4542-9397-c536c8f13eed','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11744','CourseOffering','KS-KRMS-AGENDA-11753','Agenda','78e9eb94-3bb4-4935-b119-b8a6c1eefb44','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11745','CourseOffering','KS-KRMS-AGENDA-11754','Agenda','9afc90f8-a1ce-47f9-9833-4b48e665b83d','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11746','CourseOffering','KS-KRMS-AGENDA-11755','Agenda','877ab3f3-2eff-49fa-8c7e-f89e35497f54','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11747','CourseOffering','KS-KRMS-AGENDA-11756','Agenda','fccf688f-685d-4dae-84e9-610807445d33','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11748','CourseOffering','KS-KRMS-AGENDA-11757','Agenda','92f16bdf-3fed-4728-8993-8e7469d660c9','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11749','CourseOffering','KS-KRMS-AGENDA-11758','Agenda','f30dfd98-e7c9-42b4-bc29-54323826d411','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11750','CourseOffering','KS-KRMS-AGENDA-11759','Agenda','ad4051e1-3ba2-44bf-b89c-3832b55eb473','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11751','CourseOffering','KS-KRMS-AGENDA-11760','Agenda','30930997-03a7-4301-8df4-f037605bb47b','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11752','CourseOffering','KS-KRMS-AGENDA-11761','Agenda','45297ff5-8c62-4ee1-8c7c-e22c138e12db','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11753','CourseOffering','KS-KRMS-AGENDA-11762','Agenda','2580ca0a-fbb1-4747-a4c5-b906e7b8ea12','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11754','CourseOffering','KS-KRMS-AGENDA-11763','Agenda','6d96c4f2-677d-4d70-b396-3c9bff3e4ac9','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11755','CourseOffering','KS-KRMS-AGENDA-11764','Agenda','b5bfb12c-d0dc-4d5a-a0f5-62f48769a3b9','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11756','CourseOffering','KS-KRMS-AGENDA-11765','Agenda','22f75db7-d9ac-4da7-ba0c-6def7b544718','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11757','CourseOffering','KS-KRMS-AGENDA-11766','Agenda','050179ae-b0a7-4654-b60b-efe43eb6dc17','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11758','CourseOffering','KS-KRMS-AGENDA-11767','Agenda','9930d57f-d4ee-4029-be49-0bd478d4c175','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11759','CourseOffering','KS-KRMS-AGENDA-11768','Agenda','7cb7df16-0f6f-4e38-91c4-e6382537789d','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11760','CourseOffering','KS-KRMS-AGENDA-11769','Agenda','a3295808-3c0d-482b-aac9-5964f18f58b4','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11761','CourseOffering','KS-KRMS-AGENDA-11770','Agenda','eb942c03-0e7e-4bd7-a774-d26cb1c64f25','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11762','CourseOffering','KS-KRMS-AGENDA-11771','Agenda','aa2aab7b-b76e-4e68-bd22-3e8c7e93c835','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11763','CourseOffering','KS-KRMS-AGENDA-11772','Agenda','587bdefb-39f0-4627-95e0-f23ec74eedb9','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11764','CourseOffering','KS-KRMS-AGENDA-11773','Agenda','65810eb5-1512-49e5-9b46-ee5542d234e2','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11765','CourseOffering','KS-KRMS-AGENDA-11774','Agenda','54a54861-fca3-41a5-ad5f-fcc611bc0149','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11766','CourseOffering','KS-KRMS-AGENDA-11775','Agenda','6bcb0519-7b3b-44aa-8382-c2f062082c62','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11767','CourseOffering','KS-KRMS-AGENDA-11776','Agenda','1d11945f-5fe1-42ab-870d-d5b4d3fc1ba5','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11768','CourseOffering','KS-KRMS-AGENDA-11777','Agenda','b421eeff-f858-4e23-96ec-bd12471bf326','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11769','CourseOffering','KS-KRMS-AGENDA-11778','Agenda','e6894f2d-fa8c-47e2-8869-6cd443836ba4','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11770','CourseOffering','KS-KRMS-AGENDA-11779','Agenda','0c5fcfef-11dd-4e89-b9ab-a28b4b2d7fb0','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11771','CourseOffering','KS-KRMS-AGENDA-11780','Agenda','b5a51944-7966-47c8-9e49-903c85fd30fb','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11772','CourseOffering','KS-KRMS-AGENDA-11781','Agenda','136cfb12-9b91-46ba-a176-af417449527c','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11773','CourseOffering','KS-KRMS-AGENDA-11782','Agenda','b42055d3-671c-4c7e-af4b-1da579277637','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11774','CourseOffering','KS-KRMS-AGENDA-11783','Agenda','9bf403ac-e1ac-45d1-842e-442ae4984e71','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11775','CourseOffering','KS-KRMS-AGENDA-11784','Agenda','93ad4328-e7c4-4a52-b6b6-d5878416abc4','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11776','CourseOffering','KS-KRMS-AGENDA-11785','Agenda','097fee89-3f6c-4ff2-887e-c06afcff28ab','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11777','CourseOffering','KS-KRMS-AGENDA-11786','Agenda','61c3c379-a6c7-4f55-92c9-b38b38b703b7','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11778','CourseOffering','KS-KRMS-AGENDA-11787','Agenda','808d4df8-9780-4553-bb5b-e7c6df8f7550','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11779','CourseOffering','KS-KRMS-AGENDA-11788','Agenda','86bfeb70-f5e3-4b02-834f-53a67bc825be','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11780','CourseOffering','KS-KRMS-AGENDA-11789','Agenda','b6e1cf4d-e056-4e4c-81d0-1088a6aea6e0','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11781','CourseOffering','KS-KRMS-AGENDA-11790','Agenda','efacd4e3-7b01-4c40-8433-ddd93219e168','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11782','CourseOffering','KS-KRMS-AGENDA-11791','Agenda','a2955a85-ca3f-4e1b-9327-6b7a612e82aa','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11783','CourseOffering','KS-KRMS-AGENDA-11792','Agenda','a74e81c6-a581-44c9-85d9-7585b7c19715','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11784','CourseOffering','KS-KRMS-AGENDA-11793','Agenda','8102a69b-84ee-4821-ac13-0db5dc500ab7','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11785','CourseOffering','KS-KRMS-AGENDA-11794','Agenda','e1ee5297-e8df-41ca-863a-ad750f71aeb0','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11786','CourseOffering','KS-KRMS-AGENDA-11795','Agenda','cef1f697-fa74-4b68-a1c5-b6b2b62ff73d','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11787','CourseOffering','KS-KRMS-AGENDA-11796','Agenda','e0ed00e0-fede-4e11-881e-c899d3487c88','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11788','CourseOffering','KS-KRMS-AGENDA-11797','Agenda','9c7df0ed-b121-44dd-ada0-ae30210a79c3','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11789','CourseOffering','KS-KRMS-AGENDA-11798','Agenda','ad37535b-b5b3-405d-b558-44f366938dbe','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11790','CourseOffering','KS-KRMS-AGENDA-11799','Agenda','6fa3c3c1-f7d0-42de-a6f0-aa1c37e98566','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11791','CourseOffering','KS-KRMS-AGENDA-11800','Agenda','fdfd8711-e66e-4618-8321-f4bc74062792','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11792','CourseOffering','KS-KRMS-AGENDA-11801','Agenda','9416aebd-ff32-4204-9ef4-b9eac9990102','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11793','CourseOffering','KS-KRMS-AGENDA-11802','Agenda','98e72ae9-2d60-4216-834c-90ce094c7101','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11794','CourseOffering','KS-KRMS-AGENDA-11803','Agenda','f6c520dc-bb8c-4a1b-a0e6-423e224811b5','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11795','CourseOffering','KS-KRMS-AGENDA-11804','Agenda','f765d5f9-c1f0-45de-a677-ab9ad758f1fb','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11796','CourseOffering','KS-KRMS-AGENDA-11805','Agenda','1d9e36ba-d17e-4977-9eae-f908fd411362','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11797','CourseOffering','KS-KRMS-AGENDA-11806','Agenda','97c1843c-c0e7-44f4-9b28-3b38a592c24d','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11798','CourseOffering','KS-KRMS-AGENDA-11807','Agenda','e8dac437-f6a8-46dd-8ed8-6c1143d194e5','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11799','CourseOffering','KS-KRMS-AGENDA-11808','Agenda','ff883e0c-f100-48ad-a158-3b84f3cb17dd','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11800','CourseOffering','KS-KRMS-AGENDA-11809','Agenda','7cdd5c71-5cca-4469-b0ed-9083e94ffc5a','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11801','CourseOffering','KS-KRMS-AGENDA-11810','Agenda','abf9196f-a0d2-4558-b47b-308bf0257c35','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11802','CourseOffering','KS-KRMS-AGENDA-11811','Agenda','6f6719f3-a416-4863-8a80-81cdca53d9f8','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11803','CourseOffering','KS-KRMS-AGENDA-11812','Agenda','60556923-b372-47cc-be8d-3e34a7d62fd8','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11804','CourseOffering','KS-KRMS-AGENDA-11813','Agenda','d4b0c19a-09d9-41ea-a3a6-0ff5c1a02fa2','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11805','CourseOffering','KS-KRMS-AGENDA-11814','Agenda','870f21e1-c44f-416e-bdad-b63f58ab5201','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11806','CourseOffering','KS-KRMS-AGENDA-11815','Agenda','53fa8783-bd3c-47c2-aeb5-8f7dd901dcac','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11807','CourseOffering','KS-KRMS-AGENDA-11816','Agenda','53ccaf5f-3790-442e-b9e0-463d1e5d69f0','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11808','CourseOffering','KS-KRMS-AGENDA-11817','Agenda','6daf0595-8283-464e-bc25-36740a1e2ef7','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11809','CourseOffering','KS-KRMS-AGENDA-11818','Agenda','8be414db-39b2-479c-9386-1ea3d788f97a','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11810','CourseOffering','KS-KRMS-AGENDA-11819','Agenda','97ca0c50-4286-45a4-9d3f-d2385c88dc04','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11811','CourseOffering','KS-KRMS-AGENDA-11820','Agenda','b4c8f482-af4c-4939-b00f-6c90597a1aaa','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11812','CourseOffering','KS-KRMS-AGENDA-11821','Agenda','b8df2d80-0a59-482c-b098-2830f1061c6f','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11813','CourseOffering','KS-KRMS-AGENDA-11822','Agenda','c98c549f-3284-438c-907a-ca30eb58428d','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11814','CourseOffering','KS-KRMS-AGENDA-11823','Agenda','2e46125f-03cc-4e7f-b39e-3b7320c7f6c7','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11815','CourseOffering','KS-KRMS-AGENDA-11824','Agenda','cde14b2e-62cd-48d5-a7ca-ef629fbdc94a','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11816','CourseOffering','KS-KRMS-AGENDA-11825','Agenda','d2d6f51e-ecba-46a3-b59c-167bd568657e','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11817','CourseOffering','KS-KRMS-AGENDA-11826','Agenda','578f8c63-04c5-446e-81ab-f7e96d119135','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11818','CourseOffering','KS-KRMS-AGENDA-11827','Agenda','a45d1bcd-88e4-403e-934b-e3c845865066','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11819','CourseOffering','KS-KRMS-AGENDA-11828','Agenda','ce952e26-0dfc-4903-9879-de76dfd20d52','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11820','CourseOffering','KS-KRMS-AGENDA-11829','Agenda','49ba43d0-d5da-4d31-9ef0-c5ddf947bc52','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11821','CourseOffering','KS-KRMS-AGENDA-11830','Agenda','c84f4345-43e2-4614-a0c8-b07979255b2b','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11822','CourseOffering','KS-KRMS-AGENDA-11831','Agenda','717f613e-9b73-4315-9b88-25e3bd03f08d','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11823','CourseOffering','KS-KRMS-AGENDA-11832','Agenda','2267c521-6398-4017-ac5c-30ee24c48854','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11824','CourseOffering','KS-KRMS-AGENDA-11833','Agenda','a6d1cd26-ff6a-4323-8267-23b2ef2a16a3','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11825','CourseOffering','KS-KRMS-AGENDA-11834','Agenda','bb4913fe-d354-43d1-ab11-36efcb754d46','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11826','CourseOffering','KS-KRMS-AGENDA-11835','Agenda','f49a4305-4dbd-48e6-8d3c-a1b5e93a85a7','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11827','CourseOffering','KS-KRMS-AGENDA-11836','Agenda','9c98b778-def8-453e-954c-579dc84e26fa','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11828','CourseOffering','KS-KRMS-AGENDA-11837','Agenda','fe428ac6-68c4-4509-a7b4-9834a2c6a17e','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11829','CourseOffering','KS-KRMS-AGENDA-11838','Agenda','357a9a6f-c67f-48f1-a07d-e748d6b140af','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11830','CourseOffering','KS-KRMS-AGENDA-11839','Agenda','71efd160-2c1c-485e-833b-8923ce371f9e','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11831','CourseOffering','KS-KRMS-AGENDA-11840','Agenda','73828f6b-6123-45d1-9147-d56cfec6b18c','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11832','CourseOffering','KS-KRMS-AGENDA-11841','Agenda','dbb97e50-b737-4b3c-955e-4d81e9f58b1f','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11833','CourseOffering','KS-KRMS-AGENDA-11842','Agenda','f4df6060-9ce8-4a0b-88de-c3cb85e0d0ca','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11834','CourseOffering','KS-KRMS-AGENDA-11843','Agenda','605e8fb7-4082-4142-889d-db9b6e406a86','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11835','CourseOffering','KS-KRMS-AGENDA-11844','Agenda','d4b02d05-5391-47ad-a8b1-13cad0f683f2','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11836','CourseOffering','KS-KRMS-AGENDA-11845','Agenda','0605a1c6-9e7f-43fc-930d-160e23962dbb','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11837','CourseOffering','KS-KRMS-AGENDA-11846','Agenda','99f82ba5-ad01-4489-b446-99ea8f62d292','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11838','CourseOffering','KS-KRMS-AGENDA-11847','Agenda','22a2c9db-f1dc-427d-95ce-49a5ee25c5e8','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11839','CourseOffering','KS-KRMS-AGENDA-11848','Agenda','671cd822-834b-4b55-af3f-631ae85033b6','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11840','CourseOffering','KS-KRMS-AGENDA-11849','Agenda','23f45fe5-4a89-4f03-9925-caf1a377e531','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11841','CourseOffering','KS-KRMS-AGENDA-11850','Agenda','7c685fab-c924-4c43-a9c2-bf0f41b964ad','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11842','CourseOffering','KS-KRMS-AGENDA-11851','Agenda','af70dace-d04c-445d-bc40-43dfa4860144','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11843','CourseOffering','KS-KRMS-AGENDA-11852','Agenda','977f5cfe-dc4d-4cbb-9526-b15011630e05','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11844','CourseOffering','KS-KRMS-AGENDA-11853','Agenda','5a5efee0-3bd7-411a-b369-103dafd9e511','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11845','CourseOffering','KS-KRMS-AGENDA-11854','Agenda','6f2cb68a-b09d-4b2b-8459-7fe17de11055','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11846','CourseOffering','KS-KRMS-AGENDA-11855','Agenda','ad8229d3-dbca-4830-a9cd-4fb1b8b36143','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11847','CourseOffering','KS-KRMS-AGENDA-11856','Agenda','da1ade3d-ebca-40f3-b1f1-ceb24290384e','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11848','CourseOffering','KS-KRMS-AGENDA-11857','Agenda','ecfe534a-c526-4805-904c-644bc5b59aa7','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11849','CourseOffering','KS-KRMS-AGENDA-11858','Agenda','56802cf2-5577-4163-9fa7-a356396e8d45','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11850','CourseOffering','KS-KRMS-AGENDA-11859','Agenda','5fc5ff07-eb70-4c0a-b549-124eb879c8cb','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11851','CourseOffering','KS-KRMS-AGENDA-11860','Agenda','ee786c4b-57c9-4237-9519-4bdb961ca5d4','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11852','CourseOffering','KS-KRMS-AGENDA-11861','Agenda','59c680a6-b97c-4fc9-87c2-b2e48b8c8c83','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11853','CourseOffering','KS-KRMS-AGENDA-11862','Agenda','c823b30e-b075-41dd-bd19-05d5644b8ca6','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11854','CourseOffering','KS-KRMS-AGENDA-11863','Agenda','a59d59cc-6af1-40f2-95c6-a605a82d35b0','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11855','CourseOffering','KS-KRMS-AGENDA-11864','Agenda','8f367f09-baf4-45cf-a16d-6a3646d3a205','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11856','CourseOffering','KS-KRMS-AGENDA-11865','Agenda','643d3af4-8db8-4e5a-9704-bcea2d0f9829','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11857','CourseOffering','KS-KRMS-AGENDA-11866','Agenda','e67d87d6-8d89-401a-86ac-08ca8bd5195b','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11858','CourseOffering','KS-KRMS-AGENDA-11867','Agenda','15ddce85-8838-414e-bdf8-da589ccdec1d','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11859','CourseOffering','KS-KRMS-AGENDA-11868','Agenda','6561ecc7-846f-427e-bcd2-092aeebc7b55','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11860','CourseOffering','KS-KRMS-AGENDA-11869','Agenda','a3583263-6ecd-409b-ba83-a2c37c5f5b57','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11861','CourseOffering','KS-KRMS-AGENDA-11870','Agenda','a7be321b-1c7a-418a-ba13-ec20892256c7','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11862','CourseOffering','KS-KRMS-AGENDA-11871','Agenda','c29c4cc3-58cf-4254-9967-843f364b0cf1','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11863','CourseOffering','KS-KRMS-AGENDA-11872','Agenda','c38d22d5-debd-4aee-9f57-6fc6a0b3540b','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11864','CourseOffering','KS-KRMS-AGENDA-11873','Agenda','d2b8930e-b615-4a2e-99fb-df513c4d0283','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11865','CourseOffering','KS-KRMS-AGENDA-11874','Agenda','ce30b18d-5003-430c-9b8d-07d320785f4d','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11866','CourseOffering','KS-KRMS-AGENDA-11875','Agenda','d77e987a-47a8-4e0b-9d57-b496bb1c0bbd','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11867','CourseOffering','KS-KRMS-AGENDA-11876','Agenda','427b91ca-dc9e-4188-9538-b0b793cdce54','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11868','CourseOffering','KS-KRMS-AGENDA-11877','Agenda','89309ceb-878f-4a3f-94bb-752e751c986d','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11869','CourseOffering','KS-KRMS-AGENDA-11878','Agenda','88173470-7e01-4b30-8c67-aa9720e1ca46','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11870','CourseOffering','KS-KRMS-AGENDA-11879','Agenda','f2f1fa62-6f04-48f7-ab98-6a83e7ffcbb0','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11871','CourseOffering','KS-KRMS-AGENDA-11880','Agenda','8446f32c-047e-4bd2-b9af-7451cdc14f89','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11872','CourseOffering','KS-KRMS-AGENDA-11881','Agenda','a36f55be-fa47-4eab-923f-4b0bd35ee697','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11873','CourseOffering','KS-KRMS-AGENDA-11882','Agenda','554e8683-bffa-4cf6-bed8-b6bdbf1b9359','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11874','CourseOffering','KS-KRMS-AGENDA-11883','Agenda','bd2178f9-597d-4eb6-a1c3-5c53dad69d72','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11875','CourseOffering','KS-KRMS-AGENDA-11884','Agenda','ac725ab1-d886-4e55-b09a-c3b41e41adbc','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11876','CourseOffering','KS-KRMS-AGENDA-11885','Agenda','821eb198-f199-42d7-a102-5ca9fb1b8e00','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11877','CourseOffering','KS-KRMS-AGENDA-11886','Agenda','97134099-1307-4c0b-b64b-6b7ff97a7e69','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11878','CourseOffering','KS-KRMS-AGENDA-11887','Agenda','6483a682-99cb-49f0-8218-c9d3bd8437af','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11879','CourseOffering','KS-KRMS-AGENDA-11888','Agenda','e960defa-3c0c-4bf6-bb2f-0ec13d80096d','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11880','CourseOffering','KS-KRMS-AGENDA-11889','Agenda','2429d23b-4293-4c78-b2fe-6f837ab2f121','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11881','CourseOffering','KS-KRMS-AGENDA-11890','Agenda','c0f8bc43-886e-4f6d-8306-4809cc7f3a8c','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11882','CourseOffering','KS-KRMS-AGENDA-11891','Agenda','82b97445-2f9b-49b8-839a-2e61a5f78786','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11883','CourseOffering','KS-KRMS-AGENDA-11892','Agenda','438c5eb6-4340-4a56-b74f-634c0393390c','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11884','CourseOffering','KS-KRMS-AGENDA-11893','Agenda','80f6db4d-0aa8-47f2-a638-a9961c0e2eae','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11885','CourseOffering','KS-KRMS-AGENDA-11894','Agenda','84eb9460-3a90-41ec-bc1a-e7cd92faf0dc','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11886','CourseOffering','KS-KRMS-AGENDA-11895','Agenda','c0784e9b-cfbf-4a52-a319-dfb16619d4d3','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11887','CourseOffering','KS-KRMS-AGENDA-11896','Agenda','d26a0b48-1b4b-4a0f-bfdd-f6f33869c527','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11888','CourseOffering','KS-KRMS-AGENDA-11897','Agenda','de4ca7fe-0824-49cd-b2d3-8cc3621e978f','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11889','CourseOffering','KS-KRMS-AGENDA-11898','Agenda','eccc7c54-24f7-46cd-81ca-76ebcc131bd9','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11890','CourseOffering','KS-KRMS-AGENDA-11899','Agenda','fffcff08-331b-420e-bf1b-0631c3ac0ad5','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11891','CourseOffering','KS-KRMS-AGENDA-11900','Agenda','3bbd4bd7-003e-4560-9683-4fa6cd1b3b5d','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11892','CourseOffering','KS-KRMS-AGENDA-11901','Agenda','00905570-addc-40ec-bdb6-e1ce635e05be','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11893','CourseOffering','KS-KRMS-AGENDA-11902','Agenda','33148f61-b2da-44a7-86ba-ed06c009c555','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11894','CourseOffering','KS-KRMS-AGENDA-11903','Agenda','4d535f9c-5971-4668-a0da-215a5ae4e5a2','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11895','CourseOffering','KS-KRMS-AGENDA-11904','Agenda','716faf6a-426a-4e39-b9ab-15d8bb15b93c','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11896','CourseOffering','KS-KRMS-AGENDA-11905','Agenda','8ab488f9-ffe3-452b-9326-7f49f3130641','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11897','CourseOffering','KS-KRMS-AGENDA-11906','Agenda','9ac5e072-a9cc-4646-a3c6-ef7f1ded83a0','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11898','CourseOffering','KS-KRMS-AGENDA-11907','Agenda','e915b5b1-7b2e-4166-a293-091245dcbdb2','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11899','CourseOffering','KS-KRMS-AGENDA-11908','Agenda','e9a30bdb-667d-4831-86b4-7e3796309cbc','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11900','CourseOffering','KS-KRMS-AGENDA-11909','Agenda','e9c4e961-e9db-45ce-b4b2-d83aec0dbd0d','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11901','CourseOffering','KS-KRMS-AGENDA-11910','Agenda','c8beee82-c736-48c0-ae94-50f43ee5d6eb','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11902','CourseOffering','KS-KRMS-AGENDA-11911','Agenda','8654b604-c60c-4042-a726-f02dfbed5362','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11903','CourseOffering','KS-KRMS-AGENDA-11912','Agenda','12536289-900d-4a13-a9ed-4a63ae3295b0','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11904','CourseOffering','KS-KRMS-AGENDA-11913','Agenda','2d176b34-bb47-4a9a-b423-d4da4675dc1c','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11905','CourseOffering','KS-KRMS-AGENDA-11914','Agenda','4238bd82-ccc0-4dc9-b1ac-ffbbaf1e4e0b','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11906','CourseOffering','KS-KRMS-AGENDA-11915','Agenda','439e9a06-ca61-4dc6-b827-2e5b1fbaa1d4','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11907','CourseOffering','KS-KRMS-AGENDA-11916','Agenda','5eea1b4d-c2c7-451e-b667-5b5c023f6d3d','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11908','CourseOffering','KS-KRMS-AGENDA-11917','Agenda','8f9a1188-4d01-40f7-ad82-2dd22b7b28d6','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11909','CourseOffering','KS-KRMS-AGENDA-11918','Agenda','cb611853-db92-44d2-a983-2bf0faeb0541','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11910','CourseOffering','KS-KRMS-AGENDA-11919','Agenda','d55f3531-b165-4566-9723-ff62f4cabeb0','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11911','CourseOffering','KS-KRMS-AGENDA-11920','Agenda','3bd925af-bc10-41de-ae7e-35d62ded96f1','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11912','CourseOffering','KS-KRMS-AGENDA-11921','Agenda','bc3cafeb-5c1a-452c-9ab3-dabb992d1178','kuali.lui.type.course.offering','KS-SYS','Y',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (REF_OBJ_KRMS_OBJ_ID,COLLECTION_NM,KRMS_OBJ_ID,KRMS_DSCR_TYP,REF_OBJ_ID,REF_DSCR_TYP,NMSPC_CD,ACTV,VER_NBR) values ('KS-KRMS-REF-OBJ-KRMS-OBJ-11913','CourseOffering','KS-KRMS-AGENDA-11922','Agenda','edda3734-51dc-461c-a406-62b6deb68783','kuali.lui.type.course.offering','KS-SYS','Y',1)
/