Update krms_nl_tmpl_t set tmpl = '#if($courseCluSet.getCluList().size() == 1)$courseCluSet.getCluSetAsCode()#{else}#set($a=$courseCluSet.getCluSetAsCode().lastIndexOf(","))#set($b=1)#set($c=$a+$b)#set($d=$courseCluSet.getCluSetAsCode().lastIndexOf(")"))#if($courseCluSet.getCluList().size() > 2)#set($courses=$courseCluSet.getCluSetAsCode().substring(1,$a)+", and"+$courseCluSet.getCluSetAsCode().substring($c, $d))#{else}#set($courses=$courseCluSet.getCluSetAsCode().substring(1,$a)+" and"+$courseCluSet.getCluSetAsCode().substring($c, $d))#end$courses#end' where typ_id = '10018' and nl_usage_id = 'KS-KRMS-NL-USAGE-1005'
/
Update krms_nl_tmpl_t set tmpl = 'a minimum of $intValue $NLHelper.getProperGrammar($intValue, "course") from #if($courseCluSet.getCluList().size() == 1)$courseCluSet.getCluSetAsCode()#{else}#set($a=$courseCluSet.getCluSetAsCode().lastIndexOf(","))#set($b=1)#set($c=$a+$b)#set($d=$courseCluSet.getCluSetAsCode().lastIndexOf(")"))#if($courseCluSet.getCluList().size() > 2)#set($courses=$courseCluSet.getCluSetAsCode().substring(1,$a)+", or"+$courseCluSet.getCluSetAsCode().substring($c, $d))#{else}#set($courses=$courseCluSet.getCluSetAsCode().substring(1,$a)+" or"+$courseCluSet.getCluSetAsCode().substring($c, $d))#end$courses#end' where typ_id = '10019' and nl_usage_id = 'KS-KRMS-NL-USAGE-1005'
/
Update krms_nl_tmpl_t set tmpl = 'any courses from #if($courseCluSet.getCluList().size() == 1)$courseCluSet.getCluSetAsCode()#{else}#set($a=$courseCluSet.getCluSetAsCode().lastIndexOf(","))#set($b=1)#set($c=$a+$b)#set($d=$courseCluSet.getCluSetAsCode().lastIndexOf(")"))#if($courseCluSet.getCluList().size() > 2)#set($courses=$courseCluSet.getCluSetAsCode().substring(1,$a)+", or"+$courseCluSet.getCluSetAsCode().substring($c, $d))#{else}#set($courses=$courseCluSet.getCluSetAsCode().substring(1,$a)+" or"+$courseCluSet.getCluSetAsCode().substring($c, $d))#end$courses#end' where typ_id = '10020' and nl_usage_id = 'KS-KRMS-NL-USAGE-1005'
/
Update krms_nl_tmpl_t set tmpl = 'no more than $intValue $NLHelper.getProperGrammar($intValue, "credit") from #if($courseCluSet.getCluList().size() == 1)$courseCluSet.getCluSetAsCode()#{else}#set($a=$courseCluSet.getCluSetAsCode().lastIndexOf(","))#set($b=1)#set($c=$a+$b)#set($d=$courseCluSet.getCluSetAsCode().lastIndexOf(")"))#if($courseCluSet.getCluList().size() > 2)#set($courses=$courseCluSet.getCluSetAsCode().substring(1,$a)+", or"+$courseCluSet.getCluSetAsCode().substring($c, $d))#{else}#set($courses=$courseCluSet.getCluSetAsCode().substring(1,$a)+" or"+$courseCluSet.getCluSetAsCode().substring($c, $d))#end$courses#end' where typ_id = '10021' and nl_usage_id = 'KS-KRMS-NL-USAGE-1005'
/
Update krms_nl_tmpl_t set tmpl = 'any credits from #if($courseCluSet.getCluList().size() == 1)$courseCluSet.getCluSetAsCode()#{else}#set($a=$courseCluSet.getCluSetAsCode().lastIndexOf(","))#set($b=1)#set($c=$a+$b)#set($d=$courseCluSet.getCluSetAsCode().lastIndexOf(")"))#if($courseCluSet.getCluList().size() > 2)#set($courses=$courseCluSet.getCluSetAsCode().substring(1,$a)+", or"+$courseCluSet.getCluSetAsCode().substring($c, $d))#{else}#set($courses=$courseCluSet.getCluSetAsCode().substring(1,$a)+" or"+$courseCluSet.getCluSetAsCode().substring($c, $d))#end$courses#end' where typ_id = '10022' and nl_usage_id = 'KS-KRMS-NL-USAGE-1005'
/
Update krms_nl_tmpl_t set tmpl = '#if($courseCluSet.getCluList().size() == 1)$courseCluSet.getCluSetAsCode()#{else}#set($a=$courseCluSet.getCluSetAsCode().lastIndexOf(","))#set($b=1)#set($c=$a+$b)#set($d=$courseCluSet.getCluSetAsCode().lastIndexOf(")"))#if($courseCluSet.getCluList().size() > 2)#set($courses=$courseCluSet.getCluSetAsCode().substring(1,$a)+", and"+$courseCluSet.getCluSetAsCode().substring($c, $d))#{else}#set($courses=$courseCluSet.getCluSetAsCode().substring(1,$a)+" and"+$courseCluSet.getCluSetAsCode().substring($c, $d))#end$courses#end' where typ_id = '10023' and nl_usage_id = 'KS-KRMS-NL-USAGE-1005'
/
Update krms_nl_tmpl_t set tmpl = 'a minimum of $intValue $NLHelper.getProperGrammar($intValue, "course") from #if($courseCluSet.getCluList().size() == 1)$courseCluSet.getCluSetAsCode()#{else}#set($a=$courseCluSet.getCluSetAsCode().lastIndexOf(","))#set($b=1)#set($c=$a+$b)#set($d=$courseCluSet.getCluSetAsCode().lastIndexOf(")"))#if($courseCluSet.getCluList().size() > 2)#set($courses=$courseCluSet.getCluSetAsCode().substring(1,$a)+", or"+$courseCluSet.getCluSetAsCode().substring($c, $d))#{else}#set($courses=$courseCluSet.getCluSetAsCode().substring(1,$a)+" or"+$courseCluSet.getCluSetAsCode().substring($c, $d))#end$courses#end' where typ_id = '10024' and nl_usage_id = 'KS-KRMS-NL-USAGE-1005'
/
Update krms_nl_tmpl_t set tmpl = 'a minimum GPA of $intValue in #if($courseCluSet.getCluList().size() == 1)$courseCluSet.getCluSetAsCode()#{else}#set($a=$courseCluSet.getCluSetAsCode().lastIndexOf(","))#set($b=1)#set($c=$a+$b)#set($d=$courseCluSet.getCluSetAsCode().lastIndexOf(")"))#if($courseCluSet.getCluList().size() > 2)#set($courses=$courseCluSet.getCluSetAsCode().substring(1,$a)+", or"+$courseCluSet.getCluSetAsCode().substring($c, $d))#{else}#set($courses=$courseCluSet.getCluSetAsCode().substring(1,$a)+" or"+$courseCluSet.getCluSetAsCode().substring($c, $d))#end$courses#end' where typ_id = '10025' and nl_usage_id = 'KS-KRMS-NL-USAGE-1005'
/
Update krms_nl_tmpl_t set tmpl = 'must not have earned a grade of $grade or higher in #if($courseCluSet.getCluList().size() == 1)$courseCluSet.getCluSetAsCode()#{else}#set($a=$courseCluSet.getCluSetAsCode().lastIndexOf(","))#set($b=1)#set($c=$a+$b)#set($d=$courseCluSet.getCluSetAsCode().lastIndexOf(")"))#if($courseCluSet.getCluList().size() > 2)#set($courses=$courseCluSet.getCluSetAsCode().substring(1,$a)+", or"+$courseCluSet.getCluSetAsCode().substring($c, $d))#{else}#set($courses=$courseCluSet.getCluSetAsCode().substring(1,$a)+" or"+$courseCluSet.getCluSetAsCode().substring($c, $d))#end$courses#end' where typ_id = '10026' and nl_usage_id = 'KS-KRMS-NL-USAGE-1005'
/
Update krms_nl_tmpl_t set tmpl = 'a minimum grade of $grade in #if($courseCluSet.getCluList().size() == 1)$courseCluSet.getCluSetAsCode()#{else}#set($a=$courseCluSet.getCluSetAsCode().lastIndexOf(","))#set($b=1)#set($c=$a+$b)#set($d=$courseCluSet.getCluSetAsCode().lastIndexOf(")"))#if($courseCluSet.getCluList().size() > 2)#set($courses=$courseCluSet.getCluSetAsCode().substring(1,$a)+", and"+$courseCluSet.getCluSetAsCode().substring($c, $d))#{else}#set($courses=$courseCluSet.getCluSetAsCode().substring(1,$a)+" and"+$courseCluSet.getCluSetAsCode().substring($c, $d))#end$courses#end' where typ_id = '10027' and nl_usage_id = 'KS-KRMS-NL-USAGE-1005'
/
Update krms_nl_tmpl_t set tmpl = 'a minimum of $intValue $NLHelper.getProperGrammar($intValue, "course") from #if($courseCluSet.getCluList().size() == 1)$courseCluSet.getCluSetAsCode()#{else}#set($a=$courseCluSet.getCluSetAsCode().lastIndexOf(","))#set($b=1)#set($c=$a+$b)#set($d=$courseCluSet.getCluSetAsCode().lastIndexOf(")"))#if($courseCluSet.getCluList().size() > 2)#set($courses=$courseCluSet.getCluSetAsCode().substring(1,$a)+", and"+$courseCluSet.getCluSetAsCode().substring($c, $d))#{else}#set($courses=$courseCluSet.getCluSetAsCode().substring(1,$a)+" and"+$courseCluSet.getCluSetAsCode().substring($c, $d))#end$courses#end with a minimum grade of $grade' where typ_id = '10028' and nl_usage_id = 'KS-KRMS-NL-USAGE-1005'
/
Update krms_nl_tmpl_t set tmpl = 'no more than $intValue $NLHelper.getProperGrammar($intValue, "course") from #if($courseCluSet.getCluList().size() == 1)$courseCluSet.getCluSetAsCode()#{else}#set($a=$courseCluSet.getCluSetAsCode().lastIndexOf(","))#set($b=1)#set($c=$a+$b)#set($d=$courseCluSet.getCluSetAsCode().lastIndexOf(")"))#if($courseCluSet.getCluList().size() > 2)#set($courses=$courseCluSet.getCluSetAsCode().substring(1,$a)+", or"+$courseCluSet.getCluSetAsCode().substring($c, $d))#{else}#set($courses=$courseCluSet.getCluSetAsCode().substring(1,$a)+" or"+$courseCluSet.getCluSetAsCode().substring($c, $d))#end$courses#end' where typ_id = '10053' and nl_usage_id = 'KS-KRMS-NL-USAGE-1005'
/
Update krms_nl_tmpl_t set tmpl = 'a minimum of $intValue $NLHelper.getProperGrammar($intValue, "course") from #if($courseCluSet.getCluList().size() == 1)$courseCluSet.getCluSetAsCode()#{else}#set($a=$courseCluSet.getCluSetAsCode().lastIndexOf(","))#set($b=1)#set($c=$a+$b)#set($d=$courseCluSet.getCluSetAsCode().lastIndexOf(")"))#if($courseCluSet.getCluList().size() > 2)#set($courses=$courseCluSet.getCluSetAsCode().substring(1,$a)+", or"+$courseCluSet.getCluSetAsCode().substring($c, $d))#{else}#set($courses=$courseCluSet.getCluSetAsCode().substring(1,$a)+" or"+$courseCluSet.getCluSetAsCode().substring($c, $d))#end$courses#end' where typ_id = '10054' and nl_usage_id = 'KS-KRMS-NL-USAGE-1005'
/
