
INSERT INTO KRMS_NL_TMPL_T (LANG_CD,NL_TMPL_ID,NL_USAGE_ID,TMPL,TYP_ID,VER_NBR)
  VALUES ('en', 'KS-KRMS-NL-TMPL-1409','KS-KRMS-NL-USAGE-1000','Enrollment Eligibility','10002',0)
/
INSERT INTO KRMS_NL_TMPL_T (LANG_CD,NL_TMPL_ID,NL_USAGE_ID,TMPL,TYP_ID,VER_NBR)
  VALUES ('en', 'KS-KRMS-NL-TMPL-1410','KS-KRMS-NL-USAGE-1000','Credit Constraints','10003',0)
/
INSERT INTO KRMS_NL_TMPL_T (LANG_CD,NL_TMPL_ID,NL_USAGE_ID,TMPL,TYP_ID,VER_NBR)
  VALUES ('en', 'KS-KRMS-NL-TMPL-1411','KS-KRMS-NL-USAGE-1000','Antirequisite','10005',0)
/
INSERT INTO KRMS_NL_TMPL_T (LANG_CD,NL_TMPL_ID,NL_USAGE_ID,TMPL,TYP_ID,VER_NBR)
  VALUES ('en', 'KS-KRMS-NL-TMPL-1412','KS-KRMS-NL-USAGE-1000','Corequisite','10006',0)
/
INSERT INTO KRMS_NL_TMPL_T (LANG_CD,NL_TMPL_ID,NL_USAGE_ID,TMPL,TYP_ID,VER_NBR)
  VALUES ('en', 'KS-KRMS-NL-TMPL-1413','KS-KRMS-NL-USAGE-1000','Recommended Preparation','10008',0)
/
INSERT INTO KRMS_NL_TMPL_T (LANG_CD,NL_TMPL_ID,NL_USAGE_ID,TMPL,TYP_ID,VER_NBR)
  VALUES ('en', 'KS-KRMS-NL-TMPL-1414','KS-KRMS-NL-USAGE-1000','Student Eligibility & Prerequisite','10010',0)
/
INSERT INTO KRMS_NL_TMPL_T (LANG_CD,NL_TMPL_ID,NL_USAGE_ID,TMPL,TYP_ID,VER_NBR)
  VALUES ('en', 'KS-KRMS-NL-TMPL-1415','KS-KRMS-NL-USAGE-1000','Repeatable for Credit','10011',0)
/
INSERT INTO KRMS_NL_TMPL_T (LANG_CD,NL_TMPL_ID,NL_USAGE_ID,TMPL,TYP_ID,VER_NBR)
  VALUES ('en', 'KS-KRMS-NL-TMPL-1416','KS-KRMS-NL-USAGE-1000','Course that Restricts Credits','10012',0)
/