INSERT INTO KREW_DOC_TYP_PROC_T (DOC_TYP_ID, DOC_TYP_PROC_ID, INIT_IND, NM, VER_NBR)
  VALUES ('KS-KREW-DOC-TYP-3052', 'KS-KREW-DOC-TYP-PROC-3032', 1, 'PRIMARY', 2)
/

INSERT INTO KREW_DOC_TYP_PROC_T (DOC_TYP_ID, DOC_TYP_PROC_ID, INIT_IND, NM, VER_NBR)
  VALUES ('KS-KREW-DOC-TYP-3053', 'KS-KREW-DOC-TYP-PROC-3033', 1, 'PRIMARY', 2)
/