CREATE TABLE KSEN_LUI_CAPACITY_ATTR
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	ATTR_KEY             VARCHAR2(255) NULL ,
	ATTR_VALUE           VARCHAR2(4000) NULL ,
	OWNER_ID             VARCHAR2(255) NULL
)
/

ALTER TABLE KSEN_LUI_CAPACITY_ATTR
	ADD CONSTRAINT  KSEN_LUI_CAPACITY_ATTR_P PRIMARY KEY (ID)
/