
CREATE TABLE KSEN_LUI
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	LUI_TYPE             VARCHAR2(255) NOT NULL ,
	LUI_STATE            VARCHAR2(255) NOT NULL ,
	NAME                 VARCHAR2(255) NULL ,
	DESCR_PLAIN          VARCHAR2(4000) NULL ,
	DESCR_FORMATTED      VARCHAR2(4000) NULL ,
	EFF_DT               TIMESTAMP(6) NULL ,
	EXPIR_DT             TIMESTAMP(6) NULL ,
	CLU_ID               VARCHAR2(255) NULL ,
	ATP_ID               VARCHAR2(255) NULL ,
	MAX_SEATS            NUMBER(10) NULL ,
	MIN_SEATS            NUMBER(10) NULL ,
	REF_URL              VARCHAR2(255) NULL ,
	VER_NBR              NUMBER(19) NOT NULL ,
	CREATETIME           TIMESTAMP(6) NOT NULL ,
	CREATEID             VARCHAR2(255) NOT NULL ,
	UPDATETIME           TIMESTAMP(6) NULL ,
	UPDATEID             VARCHAR2(255) NULL 
);



CREATE UNIQUE INDEX KSEN_LUI_P ON KSEN_LUI
(ID   ASC);




CREATE  INDEX KSEN_LUI_I1 ON KSEN_LUI
(CLU_ID   ASC,ATP_ID   ASC);






CREATE TABLE KSEN_LUI_ATTR
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	ATTR_KEY             VARCHAR2(255) NULL ,
	ATTR_VALUE           VARCHAR2(2000) NULL ,
	OWNER_ID             VARCHAR2(255) NULL 
);



CREATE UNIQUE INDEX KSEN_LUI_ATTR_P ON KSEN_LUI_ATTR
(ID   ASC);




CREATE TABLE KSEN_LUI_CLUCLU_RELTN
(
	ID                   VARCHAR2(255) NOT NULL ,
	LUI_ID               VARCHAR2(255) NOT NULL ,
	CLUCLU_RELTN_ID      VARCHAR2(255) NOT NULL 
);



CREATE UNIQUE INDEX KSEN_LUI_CLUCLU_RELTN_P ON KSEN_LUI_CLUCLU_RELTN
(ID   ASC);




CREATE UNIQUE INDEX kSEN_LUI_CLUCLU_RELTN_I1 ON KSEN_LUI_CLUCLU_RELTN
(LUI_ID   ASC,CLUCLU_RELTN_ID   ASC);




CREATE  INDEX KSEN_LUI_CLUCLU_RELTN_IF1 ON KSEN_LUI_CLUCLU_RELTN
(LUI_ID   ASC);





CREATE TABLE KSEN_LUI_IDENT
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	LUI_ID_TYPE          VARCHAR2(255) NOT NULL ,
	LUI_ID_STATE         VARCHAR2(255) NOT NULL ,
	LUI_CD               VARCHAR2(255) NULL ,
	SHRT_NAME            VARCHAR2(255) NULL ,
	LNG_NAME             VARCHAR2(255) NULL ,
	DIVISION             VARCHAR2(255) NULL ,
	SUFX_CD              VARCHAR2(255) NULL ,
	VARTN                VARCHAR2(255) NULL ,
	VER_NBR              NUMBER(19) NOT NULL ,
	CREATETIME           TIMESTAMP(6) NOT NULL ,
	CREATEID             VARCHAR2(255) NOT NULL ,
	UPDATETIME           TIMESTAMP(6) NULL ,
	UPDATEID             VARCHAR2(255) NULL ,
	LUI_ID               VARCHAR2(255) NULL 
);



CREATE UNIQUE INDEX KSEN_LUI_IDENT_P ON KSEN_LUI_IDENT
(ID   ASC);




CREATE  INDEX KSEN_LUI_IDENT_IF1 ON KSEN_LUI_IDENT
(LUI_ID   ASC);



CREATE TABLE KSEN_LUI_IDENT_ATTR
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	ATTR_KEY             VARCHAR2(255) NULL ,
	ATTR_VALUE           VARCHAR2(2000) NULL ,
	OWNER_ID             VARCHAR2(255) NULL 
);



CREATE UNIQUE INDEX KSEN_LUI_IDENT_ATTR_P ON KSEN_LUI_IDENT_ATTR
(ID   ASC);



CREATE  INDEX KSEN_LUI_IDENT_ATTR_IF1 ON KSEN_LUI_IDENT_ATTR
(OWNER_ID   ASC);



CREATE UNIQUE INDEX KSEN_LUI_LU_CD_ATTR_P ON KSEN_LUI_LU_CD_ATTR
(ID   ASC);


CREATE TABLE KSEN_LUILUI_RELTN
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	LUILUI_RELTN_TYPE    VARCHAR2(255) NOT NULL ,
	LUILUI_RELTN_STATE   VARCHAR2(255) NOT NULL ,
	NAME                 VARCHAR2(255) NOT NULL ,
	DESCR_PLAIN          VARCHAR2(4000) NULL ,
	DESCR_FORMATTED      VARCHAR2(4000) NULL ,
	LUI_ID               VARCHAR2(255) NULL ,
	RELATED_LUI_ID       VARCHAR2(255) NULL ,
	EFF_DT               TIMESTAMP(6) NULL ,
	EXPIR_DT             TIMESTAMP(6) NULL ,
	VER_NBR              NUMBER(19) NOT NULL ,
	CREATETIME           TIMESTAMP(6) NOT NULL ,
	CREATEID             VARCHAR2(255) NOT NULL ,
	UPDATETIME           TIMESTAMP(6) NULL ,
	UPDATEID             VARCHAR2(255) NULL 
);



CREATE UNIQUE INDEX KSEN_LUILUI_RELTN_P ON KSEN_LUILUI_RELTN
(ID   ASC);



CREATE  INDEX KSEN_LUILUI_RELTN_I1 ON KSEN_LUILUI_RELTN
(LUILUI_RELTN_TYPE   ASC,RELATED_LUI_ID   ASC);



CREATE  INDEX KSEN_LUILUI_RELTN_I2 ON KSEN_LUILUI_RELTN
(LUILUI_RELTN_TYPE   ASC,LUI_ID   ASC);



CREATE TABLE KSEN_LUILUI_RELTN_ATTR
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	ATTR_KEY             VARCHAR2(255) NULL ,
	ATTR_VALUE           VARCHAR2(2000) NULL ,
	OWNER_ID             VARCHAR2(255) NULL 
);



CREATE UNIQUE INDEX KSEN_LUILUI_RELTN_ATTR_P ON KSEN_LUILUI_RELTN_ATTR
(ID   ASC);

