-----------------------------------------------------------------------------
-- KSEN_LUI
-----------------------------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
  SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_LUI';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_LUI CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_LUI
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	LUI_TYPE             VARCHAR2(255) NOT NULL ,
	LUI_STATE            VARCHAR2(255) NOT NULL ,
	NAME                 VARCHAR2(255) NULL ,
	DESCR_PLAIN          VARCHAR2(4000) NOT NULL ,
	DESCR_FORMATTED      VARCHAR2(4000) NULL ,
	EFF_DT               TIMESTAMP(6) NULL ,
	EXPIR_DT             TIMESTAMP(6) NULL ,
	CLU_ID               VARCHAR2(255) NULL ,
	ATP_ID               VARCHAR2(255) NULL ,
	MAX_SEATS            NUMBER(10) NULL ,
	MIN_SEATS            NUMBER(10) NULL ,
	REF_URL              VARCHAR2(255) NULL ,
	VER_NBR              NUMBER(19) NULL ,
	CREATETIME           TIMESTAMP(6) NULL ,
	CREATEID             VARCHAR2(255) NULL ,
	UPDATETIME           TIMESTAMP(6) NULL ,
	UPDATEID             VARCHAR2(255) NULL 
)
/

CREATE UNIQUE INDEX KSEN_LUI_P ON KSEN_LUI
(ID   ASC)
/

CREATE  INDEX KSEN_LUI_I1 ON KSEN_LUI
(CLU_ID   ASC,ATP_ID   ASC)
/

-----------------------------------------------------------------------------
-- KSEN_LUILUI_RELTN
-----------------------------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
  SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_LUILUI_RELTN';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_LUILUI_RELTN CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_LUILUI_RELTN
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	LUILUI_RELTN_TYPE    VARCHAR2(255) NOT NULL ,
	LUILUI_RELTN_STATE      VARCHAR2(255) NOT NULL ,
	NAME                 VARCHAR2(255) NOT NULL ,
	DESCR_PLAIN          VARCHAR2(4000) NOT NULL ,
	DESCR_FORMATTED      VARCHAR2(4000) NULL ,
	LUI_ID               VARCHAR2(255) NULL ,
	RELATED_LUI_ID       VARCHAR2(255) NULL ,
	EFF_DT               TIMESTAMP(6) NULL ,
	EXPIR_DT             TIMESTAMP(6) NULL ,
	VER_NBR              NUMBER(19) NULL ,
	CREATETIME           TIMESTAMP(6) NULL ,
	CREATEID             VARCHAR2(255) NULL ,
	UPDATETIME           TIMESTAMP(6) NULL ,
	UPDATEID             VARCHAR2(255) NULL 
)
/

CREATE UNIQUE INDEX KSEN_LUILUI_RELTN_P ON KSEN_LUILUI_RELTN
(ID   ASC)
/

CREATE  INDEX KSEN_LUILUI_RELTN_I1 ON KSEN_LUILUI_RELTN
(LUILUI_RELTN_TYPE   ASC,RELATED_LUI_ID   ASC)
/

CREATE  INDEX KSEN_LUILUI_RELTN_I2 ON KSEN_LUILUI_RELTN
(LUILUI_RELTN_TYPE   ASC,LUI_ID   ASC)
/

--------------------------------------------------------
--  KSEN_LUILUI_RELTN_ATTR
--------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
  SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_LUILUI_RELTN_ATTR';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_LUILUI_RELTN_ATTR CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

  CREATE TABLE KSEN_LUILUI_RELTN_ATTR
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	ATTR_KEY             VARCHAR2(255) NULL ,
	ATTR_VALUE           VARCHAR2(2000) NULL ,
	OWNER_ID             VARCHAR2(255) NULL 
) 
/

CREATE UNIQUE INDEX KSEN_LUILUI_RELTN_ATTR_P ON KSEN_LUILUI_RELTN_ATTR
  (ID   ASC)
/

-----------------------------------------------------------------------------
-- KSEN_LUI_ATTR
-----------------------------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
  SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_LUI_ATTR';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_LUI_ATTR CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_LUI_ATTR
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	ATTR_KEY             VARCHAR2(255) NULL ,
	ATTR_VALUE           VARCHAR2(2000) NULL ,
	OWNER_ID             VARCHAR2(255) NULL 
)
/

CREATE UNIQUE INDEX KSEN_LUI_ATTR_P ON KSEN_LUI_ATTR
(ID   ASC)
/

--------------------------------------------------------
--  KSEN_LUI_IDENT
--------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
  SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_LUI_IDENT';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_LUI_IDENT CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

      
CREATE TABLE KSEN_LUI_IDENT
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	LUI_ID_TYPE          VARCHAR2(255) NOT NULL ,
	LUI_ID_STATE         VARCHAR2(255) NOT NULL ,
	LUI_CD               VARCHAR2(255) NULL ,
	SHRT_NAME            VARCHAR2(255) NULL ,
	LNG_NAME             VARCHAR2(255) NULL ,
	DIVISION             VARCHAR2(255) NULL ,
	SUFX_CD              VARCHAR2(255) NULL ,
	VARTN                VARCHAR2(255) NULL ,
	VER_NBR              NUMBER(19) NULL ,
	CREATETIME           TIMESTAMP(6) NULL ,
	CREATEID             VARCHAR2(255) NULL ,
	UPDATETIME           TIMESTAMP(6) NULL ,
	UPDATEID             VARCHAR2(255) NULL ,
	LUI_ID               VARCHAR2(255) NULL 
)
/

CREATE UNIQUE INDEX KSEN_LUI_IDENT_P ON KSEN_LUI_IDENT
(ID   ASC)
/

--------------------------------------------------------
--  KSEN_LUI_IDENT_ATTR
--------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
  SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_LUI_IDENT_ATTR';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_LUI_IDENT_ATTR CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_LUI_IDENT_ATTR
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	ATTR_KEY             VARCHAR2(255) NULL ,
	ATTR_VALUE           VARCHAR2(2000) NULL ,
	OWNER_ID             VARCHAR2(255) NULL 
) 
/

CREATE UNIQUE INDEX KSEN_LUI_IDENT_ATTR_P ON KSEN_LUI_IDENT_ATTR
(ID   ASC)
/

CREATE  INDEX KSEN_LUI_IDENT_ATTR_IF1 ON KSEN_LUI_IDENT_ATTR
(OWNER_ID   ASC)
/

--------------------------------------------------------
--  KSEN_LUI_LU_CD
--------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
  SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_LUI_LU_CD';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_LUI_LU_CD CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_LUI_LU_CD
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	LUI_LUCD_TYPE        VARCHAR2(255) NOT NULL ,
	DESCR_PLAIN          VARCHAR2(4000) NOT NULL ,
	DESCR_FORMATTED      VARCHAR2(4000) NULL ,
	VALUE                VARCHAR2(255) NULL ,
	VER_NBR              NUMBER(19) NULL ,
	CREATEID             VARCHAR2(255) NULL ,
	CREATETIME           TIMESTAMP(6) NULL ,
	UPDATEID             VARCHAR2(255) NULL ,
	UPDATETIME           TIMESTAMP(6) NULL ,
	LUI_ID               VARCHAR2(255) NULL 
)
/

CREATE UNIQUE INDEX KSEN_LUI_LU_CD_P ON KSEN_LUI_LU_CD
(ID   ASC)
/

--------------------------------------------------------
--  KSEN_LUI_LUCD_ATTR
--------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
  SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_LUI_LU_CD_ATTR';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_LUI_LU_CD_ATTR CASCADE CONSTRAINTS PURGE'; END IF;
END;
/
      
CREATE TABLE KSEN_LUI_LU_CD_ATTR
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	ATTR_KEY             VARCHAR2(255) NULL ,
	ATTR_VALUE           VARCHAR2(2000) NULL ,
	OWNER_ID             VARCHAR2(255) NULL 
)
/

CREATE UNIQUE INDEX KSEN_LUI_LU_CD_ATTR_P ON KSEN_LUI_LU_CD_ATTR
(ID   ASC)
/

--------------------------------------------------------
--  KSEN_LUI_MTG_SCHE
--------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
  SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_LUI_MTG_SCHE';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_LUI_MTG_SCHE CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_LUI_MTG_SCHE
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	SPACE_ID             VARCHAR2(255) NULL ,
	SCHEDULE_ID          VARCHAR2(255) NULL ,
	LUI_ID               VARCHAR2(255) NULL 
)
/
 
CREATE UNIQUE INDEX KSEN_LUI_MTG_SCHE_P ON KSEN_LUI_MTG_SCHE
(ID   ASC)
/

--------------------------------------------------------
--  KSEN_LUI_MTG_SCHE_ATTR
--------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
  SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_LUI_MTG_SCHE_ATTR';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_LUI_MTG_SCHE_ATTR CASCADE CONSTRAINTS PURGE'; END IF;
END;
/ 
 
CREATE TABLE KSEN_LUI_MTG_SCHE_ATTR
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	ATTR_KEY             VARCHAR2(255) NULL ,
	ATTR_VALUE           VARCHAR2(2000) NULL ,
	OWNER_ID             VARCHAR2(255) NULL 
)
/ 

CREATE UNIQUE INDEX KSEN_LUI_MTG_SCHE_ATTR_P ON KSEN_LUI_MTG_SCHE_ATTR
(ID   ASC)
/

CREATE  INDEX KSEN_LUI_MTG_SCHE_ATTR_IF1 ON KSEN_LUI_MTG_SCHE_ATTR
(OWNER_ID   ASC)
/

--------------------------------------------------------
--  KSEN_LUI_RESULT_VAL_GRP
--------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
  SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_LUI_RESULT_VAL_GRP';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_LUI_RESULT_VAL_GRP CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_LUI_RESULT_VAL_GRP
(
	ID                   VARCHAR2(255) NOT NULL ,
	LUI_ID               VARCHAR2(255) NULL ,
	RESULT_VAL_GRP_ID    VARCHAR2(255) NULL 
)
/

CREATE UNIQUE INDEX KSEN_LUI_RESULT_VAL_GRP_P ON KSEN_LUI_RESULT_VAL_GRP
(ID   ASC)
/

CREATE UNIQUE INDEX KSEN_LUI_RESULT_VAL_GRP_I1 ON KSEN_LUI_RESULT_VAL_GRP
(LUI_ID   ASC,RESULT_VAL_GRP_ID   ASC)
/

CREATE  INDEX KSEN_LUI_RESULT_VAL_GRP_IF1 ON KSEN_LUI_RESULT_VAL_GRP
(LUI_ID   ASC)
/

--------------------------------------------------------
--  KSEN_LUI_AFFILIATED_ORG
--------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
  SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_LUI_AFFILIATED_ORG';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_LUI_AFFILIATED_ORG CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_LUI_AFFILIATED_ORG
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	AFFILIATED_ORG_TYPE  VARCHAR2(255) NOT NULL ,
	AFFILIATED_ORG_STATE VARCHAR2(255) NOT NULL ,
	ORG_ID               VARCHAR2(255) NOT NULL ,
	PERCENTAGE           NUMBER NULL ,
	EFF_DT               TIMESTAMP(6) NULL ,
	EXPIR_DT             TIMESTAMP(6) NULL ,
	VER_NBR              NUMBER(19) NULL ,
	CREATETIME           TIMESTAMP(6) NULL ,
	CREATEID             VARCHAR2(255) NULL ,
	UPDATETIME           TIMESTAMP(6) NULL ,
	UPDATEID             VARCHAR2(255) NULL ,
	EXPENDITURE_ID       VARCHAR2(255) NULL ,
	REVENUE_ID           VARCHAR2(255) NULL 
)
/

CREATE UNIQUE INDEX KSEN_LUI_AFFILIATED_ORG_P ON KSEN_LUI_AFFILIATED_ORG
(ID   ASC)
/

CREATE  INDEX KSEN_LUI_AFFILIATED_ORG_IF1 ON KSEN_LUI_AFFILIATED_ORG
(EXPENDITURE_ID   ASC)
/

CREATE  INDEX KSEN_LUI_AFFILIATED_ORG_IF2 ON KSEN_LUI_AFFILIATED_ORG
(REVENUE_ID   ASC)
/

--------------------------------------------------------
--  KSEN_LUI_AFFIL_ORG_ATTR
--------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
  SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_LUI_AFFIL_ORG_ATTR';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_LUI_AFFIL_ORG_ATTR CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_LUI_AFFIL_ORG_ATTR
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	ATTR_KEY             VARCHAR2(255) NULL ,
	ATTR_VALUE           VARCHAR2(2000) NULL ,
	OWNER_ID             VARCHAR2(255) NULL 
)
/

CREATE UNIQUE INDEX KSEN_LUI_AFFIL_ORG_ATTR_P ON KSEN_LUI_AFFIL_ORG_ATTR
(ID   ASC)
/

CREATE  INDEX KSEN_LUI_AFFIL_ORG_ATTR_IF1 ON KSEN_LUI_AFFIL_ORG_ATTR
(OWNER_ID   ASC)
/

--------------------------------------------------------
--  KSEN_LUI_CAPACITY
--------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
  SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_LUI_CAPACITY';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_LUI_CAPACITY CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_LUI_CAPACITY
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	LUI_CAPACITY_TYPE    VARCHAR2(255) NOT NULL ,
	LUI_CAPACITY_STATE   VARCHAR2(255) NOT NULL ,
	NAME                 VARCHAR2(255) NULL ,
	DESCR_PLAIN          VARCHAR2(4000) NOT NULL ,
	DESCR_FORMATTED      VARCHAR(4000) NULL ,
	MAX_SEATS            NUMBER NULL ,
	PROCESSING_ORDER     NUMBER NULL ,
	EFF_DT               TIMESTAMP(6) NULL ,
	EXPIR_DT             TIMESTAMP(6) NULL ,
	VER_NBR              NUMBER(19) NULL ,
	CREATETIME           TIMESTAMP(6) NULL ,
	CREATEID             VARCHAR2(255) NULL ,
	UPDATETIME           TIMESTAMP(6) NULL ,
	UPDATEID             VARCHAR2(255) NULL 
)
/

CREATE UNIQUE INDEX KSEN_LUI_CAPACITY_P ON KSEN_LUI_CAPACITY
(ID   ASC)
/

CREATE  INDEX KSEN_LUI_CAPACITY_I1 ON KSEN_LUI_CAPACITY
(LUI_CAPACITY_TYPE   ASC)
/

--------------------------------------------------------
--  KSEN_LUI_CLUCLU_RELTN
--------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
  SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_LUI_CLUCLU_RELTN';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_LUI_CLUCLU_RELTN CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_LUI_CLUCLU_RELTN
(
	ID                   VARCHAR2(255) NOT NULL ,
	LUI_ID               VARCHAR2(255) NULL ,
	CLUCLU_RELTN_ID      VARCHAR2(255) NULL 
)
/

CREATE UNIQUE INDEX KSEN_LUI_CLUCLU_RELTN_P ON KSEN_LUI_CLUCLU_RELTN
(ID   ASC)
/

CREATE UNIQUE INDEX kSEN_LUI_CLUCLU_RELTN_I1 ON KSEN_LUI_CLUCLU_RELTN
(LUI_ID   ASC,CLUCLU_RELTN_ID   ASC)
/

CREATE  INDEX KSEN_LUI_CLUCLU_RELTN_IF1 ON KSEN_LUI_CLUCLU_RELTN
(LUI_ID   ASC)
/

--------------------------------------------------------
--  KSEN_LUI_CURRENCY_AMT
--------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
  SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_LUI_CURRENCY_AMT';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_LUI_CURRENCY_AMT CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_LUI_CURRENCY_AMT
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	CURRENCY_TYPE        VARCHAR2(255) NULL ,
	CURRENCY_QUANTITY    NUMBER NULL ,
	VER_NBR              NUMBER(19) NULL ,
	CREATETIME           TIMESTAMP(6) NULL ,
	CREATEID             VARCHAR2(255) NULL ,
	UPDATETIME           TIMESTAMP(6) NULL ,
	UPDATEID             VARCHAR2(255) NULL ,
	FEE_ID               VARCHAR2(255) NULL 
)
/

CREATE UNIQUE INDEX KSEN_LUI_CURRENCY_AMT_P ON KSEN_LUI_CURRENCY_AMT
(ID   ASC)
/

CREATE  INDEX KSEN_LUI_CURRENCY_AMT_IF1 ON KSEN_LUI_CURRENCY_AMT
(FEE_ID   ASC)
/

--------------------------------------------------------
--  KSEN_LUI_EXPEND_ATTR
--------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
  SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_LUI_EXPEND_ATTR';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_LUI_EXPEND_ATTR CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_LUI_EXPEND_ATTR
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	ATTR_KEY             VARCHAR2(255) NULL ,
	ATTR_VALUE           VARCHAR2(2000) NULL ,
	OWNER_ID             VARCHAR2(255) NULL 
)
/

CREATE UNIQUE INDEX KSEN_LUI_EXPEND_ATTR_P ON KSEN_LUI_EXPEND_ATTR
(ID   ASC)
/

CREATE  INDEX KSEN_LUI_EXPEND_ATTR_IF1 ON KSEN_LUI_EXPEND_ATTR
(OWNER_ID   ASC)
/

--------------------------------------------------------
--  KSEN_LUI_EXPENDITURE
--------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
  SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_LUI_EXPENDITURE';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_LUI_EXPENDITURE CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_LUI_EXPENDITURE
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	VER_NBR              NUMBER(19) NULL ,
	CREATETIME           TIMESTAMP(6) NULL ,
	CREATEID             VARCHAR2(255) NULL ,
	UPDATETIME           TIMESTAMP(6) NULL ,
	UPDATEID             VARCHAR2(255) NULL ,
	LUI_ID               VARCHAR2(255) NULL 
)
/

CREATE UNIQUE INDEX KSEN_LUI_EXPENDITURE_P ON KSEN_LUI_EXPENDITURE
(ID   ASC)
/

CREATE  INDEX KSEN_LUI_EXPENDITURE_IF1 ON KSEN_LUI_EXPENDITURE
(LUI_ID   ASC)
/

--------------------------------------------------------
--  KSEN_LUI_FEE
--------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
  SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_LUI_FEE';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_LUI_FEE CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_LUI_FEE
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	FEE_TYPE             VARCHAR2(255) NULL ,
	RATE_TYPE            VARCHAR2(255) NULL ,
	DESCR_PLAIN          VARCHAR2(4000) NOT NULL ,
	DESCR_FORMATTED      VARCHAR2(4000) NULL ,
	FEE_KEY              VARCHAR2(255) NULL ,
	VER_NBR              NUMBER(19) NULL ,
	CREATETIME           TIMESTAMP(6) NULL ,
	CREATEID             VARCHAR2(255) NULL ,
	UPDATETIME           TIMESTAMP(6) NULL ,
	UPDATEID             VARCHAR2(255) NULL ,
	LUI_ID               VARCHAR2(255) NULL 
)
/

CREATE UNIQUE INDEX KSEN_LUI_FEE_P ON KSEN_LUI_FEE
(ID   ASC)
/

CREATE  INDEX KSEN_LUI_FEE_IF1 ON KSEN_LUI_FEE
(LUI_ID   ASC)
/

--------------------------------------------------------
--  KSEN_LUI_FEE_ATTR
--------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
  SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_LUI_FEE_ATTR';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_LUI_FEE_ATTR CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_LUI_FEE_ATTR
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	ATTR_KEY             VARCHAR2(255) NULL ,
	ATTR_VALUE           VARCHAR2(2000) NULL ,
	OWNER_ID             VARCHAR2(255) NULL 
)
/

CREATE UNIQUE INDEX KSEN_LUI_FEE_ATTR_P ON KSEN_LUI_FEE_ATTR
(ID   ASC)
/

CREATE  INDEX KSEN_LUI_FEE_ATTR_IF1 ON KSEN_LUI_FEE_ATTR
(OWNER_ID   ASC)
/

--------------------------------------------------------
--  KSEN_LUI_REVENUE
--------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
  SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_LUI_REVENUE';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_LUI_REVENUE CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_LUI_REVENUE
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	FEE_TYPE             VARCHAR2(255) NULL ,
	VER_NBR              NUMBER(19) NULL ,
	CREATETIME           TIMESTAMP(6) NULL ,
	CREATEID             VARCHAR2(255) NULL ,
	UPDATETIME           TIMESTAMP(6) NULL ,
	UPDATEID             VARCHAR2(255) NULL ,
	LUI_ID               VARCHAR2(255) NULL 
)
/

CREATE UNIQUE INDEX KSEN_LUI_REVENUE_P ON KSEN_LUI_REVENUE
(ID   ASC)
/

CREATE  INDEX KSEN_LUI_REVENUE_IF1 ON KSEN_LUI_REVENUE
(LUI_ID   ASC)
/

--------------------------------------------------------
--  KSEN_LUI_REVENUE_ATTR
--------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
  SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_LUI_REVENUE_ATTR';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_LUI_REVENUE_ATTR CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_LUI_REVENUE_ATTR
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	ATTR_KEY             VARCHAR2(255) NULL ,
	ATTR_VALUE           VARCHAR2(2000) NULL ,
	OWNER_ID             VARCHAR2(255) NULL 
)
/

CREATE UNIQUE INDEX KSEN_LUI_REVENUE_ATTR_P ON KSEN_LUI_REVENUE_ATTR
(ID   ASC)
/

CREATE  INDEX KSEN_LUI_REVENUE_ATTR_IF1 ON KSEN_LUI_REVENUE_ATTR
(OWNER_ID   ASC)
/

--------------------------------------------------------
--  KSEN_LUI_UNITS_CONT_OWNER
--------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
  SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_LUI_UNITS_CONT_OWNER';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_LUI_UNITS_CONT_OWNER CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_LUI_UNITS_CONT_OWNER
(
	ID                   VARCHAR2(255) NOT NULL ,
	LUI_ID               VARCHAR2(255) NULL ,
	ORG_ID               VARCHAR2(255) NULL 
)
/

CREATE UNIQUE INDEX KSEN_LUI_UNITS_CONT_OWNER_P ON KSEN_LUI_UNITS_CONT_OWNER
(ID   ASC)
/

CREATE UNIQUE INDEX KSEN_LUI_UNITS_CONT_OWNER_I1 ON KSEN_LUI_UNITS_CONT_OWNER
(LUI_ID   ASC,ORG_ID   ASC)
/

CREATE  INDEX KSEN_LUI_UNITS_CONT_OWNER_IF1 ON KSEN_LUI_UNITS_CONT_OWNER
(LUI_ID   ASC)
/

--------------------------------------------------------
--  KSEN_LUI_UNITS_DEPLOYMENT
--------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
  SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_LUI_UNITS_DEPLOYMENT';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_LUI_UNITS_DEPLOYMENT CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_LUI_UNITS_DEPLOYMENT
(
	ID                   VARCHAR2(255) NOT NULL ,
	LUI_ID               VARCHAR2(255) NULL ,
	ORG_ID               VARCHAR2(255) NULL 
)
/

CREATE UNIQUE INDEX KSEN_LUI_UNITS_DEPLOYMENT_P ON KSEN_LUI_UNITS_DEPLOYMENT
(ID   ASC)
/

CREATE UNIQUE INDEX KSEN_LUI_UNITS_DEPLOYMENT_I1 ON KSEN_LUI_UNITS_DEPLOYMENT
(LUI_ID   ASC,ORG_ID   ASC)
/

CREATE  INDEX KSEN_LUI_UNITS_DEPLOYMENT_IF1 ON KSEN_LUI_UNITS_DEPLOYMENT
(LUI_ID   ASC)
/

--------------------------------------------------------
--  KSEN_LUICAPACITY_RELTN
--------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
  SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_LUICAPACITY_RELTN';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_LUICAPACITY_RELTN CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_LUICAPACITY_RELTN
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	LUI_ID               VARCHAR2(255) NULL ,
	LUI_CAPACITY_ID      VARCHAR2(255) NULL ,
	VER_NBR              NUMBER(19) NULL ,
	CREATETIME           TIMESTAMP(6) NULL ,
	CREATEID             VARCHAR2(255) NULL ,
	UPDATETIME           TIMESTAMP(6) NULL ,
	UPDATEID             VARCHAR2(255) NULL 
)
/

CREATE UNIQUE INDEX KSEN_REVENUE_P ON KSEN_LUICAPACITY_RELTN
(ID   ASC)
/

CREATE  INDEX KSEN_LUICAPACITY_RELTN_IF1 ON KSEN_LUICAPACITY_RELTN
(LUI_ID   ASC)
/

CREATE  INDEX KSEN_LUICAPACITY_RELTN_IF2 ON KSEN_LUICAPACITY_RELTN
(LUI_CAPACITY_ID   ASC)
/
