CREATE TABLE KSEM_ENUM_TABLE_T
(
      ID NUMBER(19),
      ENUM_KEY VARCHAR2(255),
      NAME VARCHAR2(255),
      DESCR VARCHAR2(255),
      OBJ_ID VARCHAR(36) default SYS_GUID() NOT NULL,
      VER_NBR NUMBER(8) default 1 NOT NULL,
      CONSTRAINT KSEM_ENUM_TABLE_P1 PRIMARY KEY (ID),
      CONSTRAINT KSEM_ENUM_TABLE_C1 UNIQUE (ENUM_KEY)
)
/
CREATE SEQUENCE KSEM_ENUM_TABLE_S INCREMENT BY 1 START WITH 2020 NOMAXVALUE NOCYCLE NOCACHE ORDER
/
CREATE TABLE KSEM_CTX_T
(
      ID NUMBER(19),
      ENUM_TABLE_ID NUMBER(19),
      CTX_KEY VARCHAR2(255),
      CTX_VAL VARCHAR2(255),
      OBJ_ID VARCHAR(36) default SYS_GUID() NOT NULL,
      VER_NBR NUMBER(8) default 1 NOT NULL,
      CONSTRAINT KSEM_CTX_P1 PRIMARY KEY (ID),
      CONSTRAINT KSEM_CTX_F1 FOREIGN KEY (ENUM_TABLE_ID) REFERENCES KSEM_ENUM_TABLE_T (ID),
      CONSTRAINT KSEM_CTX_C1 UNIQUE (CTX_KEY, CTX_VAL)
)
/
CREATE SEQUENCE KSEM_CTX_S INCREMENT BY 1 START WITH 2020 NOMAXVALUE NOCYCLE NOCACHE ORDER
/
CREATE TABLE KSEM_ENUM_VAL_T
(
      ID NUMBER(19),
      ENUM_TABLE_ID NUMBER(19),
      CD VARCHAR2(255),
      ABBREV_VAL VARCHAR2(255),
      VAL VARCHAR2(255),
      ACTV_IND NUMBER(1) default 1,
      EFF_DT TIMESTAMP,
      EXPIR_DT TIMESTAMP,
      SORT_KEY NUMBER(19),
      OBJ_ID VARCHAR(36) default SYS_GUID() NOT NULL,
      VER_NBR NUMBER(8) default 1 NOT NULL,
      CONSTRAINT KSEM_ENUM_VAL_P1 PRIMARY KEY (ID),
      CONSTRAINT KSEM_ENUM_VAL_F1 FOREIGN KEY (ENUM_TABLE_ID) REFERENCES KSEM_ENUM_TABLE_T (ID)
)
/
CREATE SEQUENCE KSEM_ENUM_VAL_S INCREMENT BY 1 START WITH 2020 NOMAXVALUE NOCYCLE NOCACHE ORDER
/
CREATE TABLE KSEM_CTX_JN_ENUM_VAL_T 
( 
      ENUM_VAL_ID NUMBER(19) NOT NULL, 
      CTX_ID NUMBER(19) NOT NULL,
      ACTV_IND NUMBER(1) default 1,
      OBJ_ID VARCHAR(36) default SYS_GUID() NOT NULL,
      VER_NBR NUMBER(8) default 1 NOT NULL,
      CONSTRAINT KSEM_CTX_JN_ENUM_VAL_F1 FOREIGN KEY (CTX_ID) REFERENCES KSEM_CTX_T (ID), 
      CONSTRAINT KSEM_CTX_JN_ENUM_VAL_F2 FOREIGN KEY (ENUM_VAL_ID) REFERENCES KSEM_ENUM_VAL_T (ID) 
)
/
insert into KSEM_ENUM_TABLE_T (ID, ENUM_KEY, NAME, DESCR) values (1, 'kuali.lu.subjectArea', 'Subject Area', 'Subject Area for Learning Units')
/
insert into KSEM_ENUM_TABLE_T (ID, ENUM_KEY, NAME, DESCR) values (2, 'kuali.lu.campusLocation', 'Campus Location', 'Campus Location Codes and Translations')
/
insert into KSEM_ENUM_TABLE_T (ID, ENUM_KEY, NAME, DESCR) values (3, 'kuali.atptype.duration', 'ATP Duration', 'Academic Time Period durations')
/
insert into KSEM_ENUM_TABLE_T (ID, ENUM_KEY, NAME, DESCR) values (4, 'kuali.state', 'State Code', 'State Codes for Proposals')
/
insert into KSEM_ENUM_TABLE_T (ID, ENUM_KEY, NAME, DESCR) values (5, 'kuali.lu.fee.feeType', 'Learning Unit Fee Type', 'Fee types for Learning Units')
/
insert into KSEM_ENUM_TABLE_T (ID, ENUM_KEY, NAME, DESCR) values (6, 'kuali.lu.fee.rateType', 'Learning Unit Rate Type', 'Rate types for Learning Units')
/


INSERT INTO KSEM_CTX_T (CTX_KEY,CTX_VAL,ID,ENUM_TABLE_ID)
  VALUES ('kuali.lu.subjectArea', 'default', '1', 1)
/
INSERT INTO KSEM_CTX_T (CTX_KEY,CTX_VAL,ID,ENUM_TABLE_ID)
  VALUES ('kuali.lu.campusLocation', 'default', '2', 2)
/
INSERT INTO KSEM_CTX_T (CTX_KEY,CTX_VAL,ID,ENUM_TABLE_ID)
  VALUES ('kuali.atptype.duration', 'default', '3', 3)
/
INSERT INTO KSEM_CTX_T (CTX_KEY,CTX_VAL,ID,ENUM_TABLE_ID)
  VALUES ('kuali.state', 'default', '4', 4)
/
INSERT INTO KSEM_CTX_T (CTX_KEY,CTX_VAL,ID,ENUM_TABLE_ID)
  VALUES ('kuali.lu.fee.feeType', 'default', '5', 5)
/
INSERT INTO KSEM_CTX_T (CTX_KEY,CTX_VAL,ID,ENUM_TABLE_ID)
  VALUES ('kuali.lu.fee.rateType', 'default', '6', 6)
/


insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (1, 1, 'ROBT', 'ROBT', 'Robotics', 1, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (10, 1, 'BOTA', 'BOTA', 'Botany', 10, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (11, 1, 'CHEE', 'CHEE', 'Chemical', 11, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (12, 1, 'CHEM', 'CHEM', 'Chemistry', 12, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (13, 1, 'CIVI', 'CIVI', 'Civil', 13, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (14, 1, 'CSCI', 'CSCI', 'CompSci', 14, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (15, 1, 'EDUC', 'EDUC', 'Education', 15, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (16, 1, 'ENGL', 'ENGL', 'English', 16, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (17, 1, 'FINA', 'FINA', 'Finance', 17, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (18, 1, 'FREN', 'FREN', 'French', 18, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (19, 1, 'GEOG', 'GEOG', 'Geography', 19, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (2, 1, 'CMPS', 'CMPS', 'CompSci', 2, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (20, 1, 'GEOL', 'GEOL', 'Geology', 20, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (21, 1, 'HIST', 'HIST', 'History', 21, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (22, 1, 'INTB', 'INTB', 'InternationalBusiness', 22, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (23, 1, 'LING', 'LING', 'Linguistics', 23, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (24, 1, 'MARK', 'MARK', 'Marketing ', 24, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (25, 1, 'MENG', 'MENG', 'Mechanical', 25, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (26, 1, 'MUSC', 'MUSC', 'Music', 26, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (27, 1, 'PHIL', 'PHIL', 'Philosophy', 27, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (28, 1, 'POLI', 'POLI', 'PolySci', 28, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (29, 1, 'PSYC', 'PSYC', 'Psychology', 29, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (3, 1, 'MECH', 'MECH', 'Mechanical', 3, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (30, 1, 'PUAD', 'PUAD', 'PubAdmin', 30, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (31, 1, 'SOCI', 'SOCI', 'Sociology', 31, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (32, 1, 'SOWK', 'SOWK', 'Social Work', 32, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (33, 2, 'NORTH', 'North', 'North Campus', 31, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (34, 2, 'SOUTH', 'South', 'South Campus', 32, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (35, 3, 'kuali.atp.duration.day', 'per day', 'per day', 35, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (36, 3, 'kuali.atp.duration.week', 'per week', 'per week', 36, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (37, 3, 'kuali.atp.duration.month', 'per month', 'per month', 37, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (38, 4, 'template', 'template', 'A template holds configuration for defaults for creating a new course', 38, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (39, 4, 'draft.private', 'draft.private', 'Exploratory/Private scratch pad', 39, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (4, 1, 'AACH', 'AACH', 'Architecture', 4, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (40, 4, 'draft.public', 'draft.public', 'Entered as draft but not yet submitted', 40, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (41, 4, 'submitted', 'submitted', 'Submitted but not yet approved', 41, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (42, 4, 'withdrawn', 'withdrawn', 'Withdrawn (anytime before activated)', 42, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (43, 4, 'approved', 'approved', 'Approved', 43, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (44, 4, 'rejected', 'rejected', 'Not approved (rejected)', 44, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (45, 4, 'activated', 'activated', 'Activated and ready to be published', 45, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (46, 4, 'retired', 'retired', 'Retired/No longer active', 46, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (47, 5, 'kuali.enum.type.feeTypes.labFee', 'Lab Fee', 'Laboratory Fee', 47, TO_TIMESTAMP('2010-04-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2011-04-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (48, 5, 'kuali.enum.type.feeTypes.materialFee', 'Material Fee', 'Materials Fee', 48, TO_TIMESTAMP('2010-04-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2011-04-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (49, 5, 'kuali.enum.type.feeTypes.studioFee', 'Studio Fee', 'Studio Fee', 49, TO_TIMESTAMP('2010-04-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2011-04-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (5, 1, 'ACCT', 'ACCT', 'Accounting', 5, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (50, 5, 'kuali.enum.type.feeTypes.fieldTripFee', 'Field Trip Fee', 'Field Trip Fee', 50, TO_TIMESTAMP('2010-04-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2011-04-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (51, 5, 'kuali.enum.type.feeTypes.fieldStudyFee', 'Field Study Fee', 'Field Study Fee', 51, TO_TIMESTAMP('2010-04-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2011-04-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (52, 5, 'kuali.enum.type.feeTypes.administrativeFee', 'Admin Fee', 'Administrative Fee', 52, TO_TIMESTAMP('2010-04-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2011-04-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (53, 5, 'kuali.enum.type.feeTypes.coopFee', 'Coop Fee', 'Coop Fee', 53, TO_TIMESTAMP('2010-04-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2011-04-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (54, 5, 'kuali.enum.type.feeTypes.greensFee', 'Greens Fee', 'Greens Fee', 54, TO_TIMESTAMP('2010-04-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2011-04-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (55, 6, 'variableRateFee', 'Variable Rate Fee', 'Variable Rate Fee', 55, TO_TIMESTAMP('2010-04-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2011-04-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (56, 6, 'fixedRateFee', 'Fixed Rate Fee', 'Fixed Rate Fee', 56, TO_TIMESTAMP('2010-04-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2011-04-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (57, 6, 'multipleRateFee', 'Multiple Rate Fee', 'Multiple Rate Fee', 57, TO_TIMESTAMP('2010-04-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2011-04-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (58, 6, 'perCreditFee', 'Per Credit Fee', 'Per Credit Fee', 58, TO_TIMESTAMP('2010-04-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2011-04-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (59, 1, 'AASP', 'AASP', 'African American Studies', 59, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (6, 1, 'ARTS', 'ARTS', 'FineArts', 6, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (60, 1, 'AAST', 'AAST', 'Asian American Studies', 60, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (7, 1, 'BENG', 'BENG', 'Biomed', 7, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (8, 1, 'BIOC', 'BIOC', 'Biochemistry', 8, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/
insert into KSEM_ENUM_VAL_T (ID, ENUM_TABLE_ID, CD, ABBREV_VAL, VAL, SORT_KEY, EFF_DT, EXPIR_DT) values (9, 1, 'BIOL', 'BIOL', 'Biology', 9, TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
/


insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (1, 1)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (2, 1)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (3, 1)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (4, 1)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (5, 1)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (6, 1)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (7, 1)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (8, 1)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (9, 1)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (10, 1)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (11, 1)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (12, 1)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (13, 1)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (14, 1)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (15, 1)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (16, 1)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (17, 1)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (18, 1)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (19, 1)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (20, 1)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (21, 1)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (22, 1)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (23, 1)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (24, 1)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (25, 1)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (26, 1)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (27, 1)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (28, 1)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (29, 1)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (30, 1)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (31, 1)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (32, 1)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (59, 1)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (60, 1)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (33, 2)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (34, 2)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (35, 3)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (36, 3)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (37, 3)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (38, 4)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (39, 4)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (40, 4)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (41, 4)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (42, 4)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (43, 4)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (44, 4)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (45, 4)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (46, 4)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (47, 5)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (48, 5)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (49, 5)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (50, 5)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (51, 5)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (52, 5)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (53, 5)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (54, 5)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (55, 6)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (56, 6)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (57, 6)
/
insert into KSEM_CTX_JN_ENUM_VAL_T (ENUM_VAL_ID, CTX_ID) values (58, 6)
/