
package org.kuali.student.core.organization.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.1.3
 * Fri Feb 06 10:08:00 EST 2009
 * Generated source version: 2.1.3
 */

@XmlRootElement(name = "getOrgTree", namespace = "http://student.kuali.org/wsdl/organization")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getOrgTree", namespace = "http://student.kuali.org/wsdl/organization", propOrder = {"rootOrgId","orgHierarchyId","maxLevels"})

public class GetOrgTree {

    @XmlElement(name = "rootOrgId")
    private java.lang.String rootOrgId;
    @XmlElement(name = "orgHierarchyId")
    private java.lang.String orgHierarchyId;
    @XmlElement(name = "maxLevels")
    private int maxLevels;

    public java.lang.String getRootOrgId() {
        return this.rootOrgId;
    }

    public void setRootOrgId(java.lang.String newRootOrgId)  {
        this.rootOrgId = newRootOrgId;
    }

    public java.lang.String getOrgHierarchyId() {
        return this.orgHierarchyId;
    }

    public void setOrgHierarchyId(java.lang.String newOrgHierarchyId)  {
        this.orgHierarchyId = newOrgHierarchyId;
    }

    public int getMaxLevels() {
        return this.maxLevels;
    }

    public void setMaxLevels(int newMaxLevels)  {
        this.maxLevels = newMaxLevels;
    }

}

