
package org.kuali.student.core.organization.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.1.3
 * Wed Jan 21 13:23:57 EST 2009
 * Generated source version: 2.1.3
 */

@XmlRootElement(name = "getOrgType", namespace = "http://student.kuali.org/wsdl/organization")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getOrgType", namespace = "http://student.kuali.org/wsdl/organization")

public class GetOrgType {

    @XmlElement(name = "orgTypeKey")
    private java.lang.String orgTypeKey;

    public java.lang.String getOrgTypeKey() {
        return this.orgTypeKey;
    }

    public void setOrgTypeKey(java.lang.String newOrgTypeKey)  {
        this.orgTypeKey = newOrgTypeKey;
    }

}

