
package org.kuali.student.rules.factfinder.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.1
 * Fri Oct 17 14:37:23 EDT 2008
 * Generated source version: 2.1
 */

@XmlRootElement(name = "fetchFact", namespace = "http://student.kuali.org/poc/wsdl/brms/factfinder")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fetchFact", namespace = "http://student.kuali.org/poc/wsdl/brms/factfinder", propOrder = {"arg0","arg1"})

public class FetchFact {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;
    @XmlElement(name = "arg1")
    private org.kuali.student.rules.factfinder.dto.FactStructureDTO arg1;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

    public org.kuali.student.rules.factfinder.dto.FactStructureDTO getArg1() {
        return this.arg1;
    }

    public void setArg1(org.kuali.student.rules.factfinder.dto.FactStructureDTO newArg1)  {
        this.arg1 = newArg1;
    }

}

