INSERT INTO KSOR_ORG (CREATETIME,EFF_DT,ID,LNG_NAME,OBJ_ID,SHRT_NAME,ST,TYPE,UPDATETIME,VER_NBR)
  VALUES (TO_DATE ('2010-11-01', 'YYYY-MM-DD'), TO_DATE ('2000-01-01', 'YYYY-MM-DD'), 'ORG-ID-CEEB', 'The College Board', SYS_GUID (), 'CEEB', 'Active', 'kuali.org.TestingService', TO_DATE ('2010-11-01', 'YYYY-MM-DD'), 0)
/
INSERT INTO KSOR_ORG (CREATETIME,EFF_DT,ID,LNG_NAME,OBJ_ID,SHRT_NAME,ST,TYPE,UPDATETIME,VER_NBR)
  VALUES (TO_DATE ('2010-11-01', 'YYYY-MM-DD'), TO_DATE ('2000-01-01', 'YYYY-MM-DD'), 'ORG-ID-ETS', 'Educational Testing Board', SYS_GUID (), 'ETS', 'Active', 'kuali.org.TestingService', TO_DATE ('2010-11-01', 'YYYY-MM-DD'), 0)
/
INSERT INTO KSOR_ORG (CREATETIME,EFF_DT,ID,LNG_NAME,OBJ_ID,SHRT_NAME,ST,TYPE,UPDATETIME,VER_NBR)
  VALUES (TO_DATE ('2010-11-01', 'YYYY-MM-DD'), TO_DATE ('2000-01-01', 'YYYY-MM-DD'), 'ORG-ID-ACT', 'ACT, Inc', SYS_GUID (), 'ACT', 'Active', 'kuali.org.TestingService', TO_DATE ('2010-11-01', 'YYYY-MM-DD'), 0)
/
