package prerequisiterules
import java.util.*;
import org.kuali.student.rules.internal.common.entity.ComparisonOperator;
import org.kuali.student.rules.internal.common.statement.*;
import org.kuali.student.rules.internal.common.facts.FactRequest;
import org.kuali.student.rules.util.FactContainer;
import org.kuali.student.rules.util.FactContainer.State;


rule "MATH103_2003S_2003W_14506_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "MATH103_2003S_2003W_14506", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("MATH100,MATH102,MATH104,MATH111,MATH120,MATH180,MATH184".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "MATH103_2003S_2003W_14506"
	when
        FactContainer( id == "MATH103_2003S_2003W_14506", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHYS438_2003W_null_19320_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHYS438_2003W_null_19320", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHYS101,PHYS107".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHYS438_2003W_null_19320"
	when
        FactContainer( id == "PHYS438_2003W_null_19320", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "ARCH500_2003W_null_1086_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "ARCH500_2003W_null_1086", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("ARCH502".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "ARCH500_2003W_null_1086"
	when
        FactContainer( id == "ARCH500_2003W_null_1086", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "ARCH501_2003W_null_1087_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "ARCH501_2003W_null_1087", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("ARCH500".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "ARCH501_2003W_null_1087"
	when
        FactContainer( id == "ARCH501_2003W_null_1087", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "ARCH517_2003W_null_1122_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "ARCH517_2003W_null_1122", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("ARCH515".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "ARCH517_2003W_null_1122"
	when
        FactContainer( id == "ARCH517_2003W_null_1122", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "ARCH520_2003W_null_1123_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "ARCH520_2003W_null_1123", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("ARCH501".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "ARCH520_2003W_null_1123"
	when
        FactContainer( id == "ARCH520_2003W_null_1123", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "ARCH521_2003W_null_1124_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "ARCH521_2003W_null_1124", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("ARCH520".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "ARCH521_2003W_null_1124"
	when
        FactContainer( id == "ARCH521_2003W_null_1124", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "ARCH523_2003W_null_1126_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "ARCH523_2003W_null_1126", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("ARCH504,ARCH505".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "ARCH523_2003W_null_1126"
	when
        FactContainer( id == "ARCH523_2003W_null_1126", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "ARCH540_2003W_null_1148_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "ARCH540_2003W_null_1148", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("ARCH521".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "ARCH540_2003W_null_1148"
	when
        FactContainer( id == "ARCH540_2003W_null_1148", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "ARCH556_2003W_2005S_1168_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "ARCH556_2003W_2005S_1168", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("ARCH555".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "ARCH556_2003W_2005S_1168"
	when
        FactContainer( id == "ARCH556_2003W_2005S_1168", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "COMM444_2003W_null_4889_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "COMM444_2003W_null_4889", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("COMM295,ECON201,ECON301".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "COMM444_2003W_null_4889"
	when
        FactContainer( id == "COMM444_2003W_null_4889", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "CHEM307_2003W_2004S_3356_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "CHEM307_2003W_2004S_3356", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0*P1");
    	    	   		
		SubsetProposition propositionP1 = new SubsetProposition("P1", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("MATH200,MATH217,MATH226,MATH253".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP1.apply();
        prop.addProposition(propositionP1);      
		   		   		   		   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("CHEM304".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "CHEM307_2003W_2004S_3356"
	when
        FactContainer( id == "CHEM307_2003W_2004S_3356", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
                     and
                     Proposition( propositionName == "P1" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "CHEM320_2003W_2004S_3377_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "CHEM320_2003W_2004S_3377", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0*P1");
    	    	   		
		SubsetProposition propositionP1 = new SubsetProposition("P1", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("MATH152,MATH221,MATH223".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP1.apply();
        prop.addProposition(propositionP1);      
		   		   		   		   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("CHEM312,PHYS304".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "CHEM320_2003W_2004S_3377"
	when
        FactContainer( id == "CHEM320_2003W_2004S_3377", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
                     and
                     Proposition( propositionName == "P1" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "CHEM312_2003W_2004S_3370_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "CHEM312_2003W_2004S_3370", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("((P0+P1+P2)*P3)");
    	    	   		
		SubsetProposition propositionP1 = new SubsetProposition("P1", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("CHEM121,CHEM123".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP1.apply();
        prop.addProposition(propositionP1);      
		   		   		   		   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("SCIE001".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		   		
		SubsetProposition propositionP3 = new SubsetProposition("P3", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("MATH101,MATH103,MATH105,MATH121".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP3.apply();
        prop.addProposition(propositionP3);      
		   		   		   		   		
		SubsetProposition propositionP2 = new SubsetProposition("P2", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("CHEM111,CHEM113".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP2.apply();
        prop.addProposition(propositionP2);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "CHEM312_2003W_2004S_3370"
	when
        FactContainer( id == "CHEM312_2003W_2004S_3370", state == FactContainer.State.DONE, prop : propositionContainer)

             (
                     (
                     Proposition( propositionName == "P0" && result == true ) from prop.propositions
                     or
                     Proposition( propositionName == "P1" && result == true ) from prop.propositions
                     or
                     Proposition( propositionName == "P2" && result == true ) from prop.propositions
                     )
                     and
                     Proposition( propositionName == "P3" && result == true ) from prop.propositions
                     )
            	then
   		prop.setRuleResult(true);
	end		


rule "EECE453_2003W_null_7158_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "EECE453_2003W_null_7158", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0*P1");
    	    	   		
		SubsetProposition propositionP1 = new SubsetProposition("P1", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("STAT251,MATH318".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP1.apply();
        prop.addProposition(propositionP1);      
		   		   		   		   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("EECE359".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "EECE453_2003W_null_7158"
	when
        FactContainer( id == "EECE453_2003W_null_7158", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
                     and
                     Proposition( propositionName == "P1" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "EECE315_2003W_2006S_7127_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "EECE315_2003W_2006S_7127", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("(P0*P1+P2)");
    	    	   		
		SubsetProposition propositionP1 = new SubsetProposition("P1", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("CPSC252".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP1.apply();
        prop.addProposition(propositionP1);      
		   		   		   		   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("EECE259,EECE202".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		   		
		SubsetProposition propositionP2 = new SubsetProposition("P2", ComparisonOperator.EQUAL_TO, "3", new HashSet(Arrays.asList("CPSC128,CPSC216,EECE256".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP2.apply();
        prop.addProposition(propositionP2);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "EECE315_2003W_2006S_7127"
	when
        FactContainer( id == "EECE315_2003W_2006S_7127", state == FactContainer.State.DONE, prop : propositionContainer)

             (
                     Proposition( propositionName == "P0" && result == true ) from prop.propositions
                     and
                     Proposition( propositionName == "P1" && result == true ) from prop.propositions
                     or
                     Proposition( propositionName == "P2" && result == true ) from prop.propositions
                     )
            	then
   		prop.setRuleResult(true);
	end		


rule "EECE320_2003W_2006S_7128_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "EECE320_2003W_2006S_7128", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("(P0*P1)+P2");
    	    	   		
		SubsetProposition propositionP1 = new SubsetProposition("P1", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("CPSC252".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP1.apply();
        prop.addProposition(propositionP1);      
		   		   		   		   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("EECE256,EECE201".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		   		
		SubsetProposition propositionP2 = new SubsetProposition("P2", ComparisonOperator.EQUAL_TO, "3", new HashSet(Arrays.asList("CPSC128,CPSC216,EECE256".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP2.apply();
        prop.addProposition(propositionP2);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "EECE320_2003W_2006S_7128"
	when
        FactContainer( id == "EECE320_2003W_2006S_7128", state == FactContainer.State.DONE, prop : propositionContainer)

             (
                     Proposition( propositionName == "P0" && result == true ) from prop.propositions
                     and
                     Proposition( propositionName == "P1" && result == true ) from prop.propositions
                     )
                     or
                     Proposition( propositionName == "P2" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "EECE356_2003W_2004S_7133_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "EECE356_2003W_2004S_7133", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("(P0*P1)+P2");
    	    	   		
		SubsetProposition propositionP1 = new SubsetProposition("P1", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("EECE253,EECE263".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP1.apply();
        prop.addProposition(propositionP1);      
		   		   		   		   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("EECE254".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		   		
		SubsetProposition propositionP2 = new SubsetProposition("P2", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("EECE202".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP2.apply();
        prop.addProposition(propositionP2);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "EECE356_2003W_2004S_7133"
	when
        FactContainer( id == "EECE356_2003W_2004S_7133", state == FactContainer.State.DONE, prop : propositionContainer)

             (
                     Proposition( propositionName == "P0" && result == true ) from prop.propositions
                     and
                     Proposition( propositionName == "P1" && result == true ) from prop.propositions
                     )
                     or
                     Proposition( propositionName == "P2" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "EECE360_2003W_2005S_7135_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "EECE360_2003W_2005S_7135", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("EECE202,EECE253,EECE263".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "EECE360_2003W_2005S_7135"
	when
        FactContainer( id == "EECE360_2003W_2005S_7135", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "EPSE440_2003W_null_8403_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "EPSE440_2003W_null_8403", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "3", new HashSet(Arrays.asList("EPSE348,EPSE406,EPSE420".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "EPSE440_2003W_null_8403"
	when
        FactContainer( id == "EPSE440_2003W_null_8403", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "EPSE441_2003W_null_8406_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "EPSE441_2003W_null_8406", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "3", new HashSet(Arrays.asList("EPSE348,EPSE406,EPSE420".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "EPSE441_2003W_null_8406"
	when
        FactContainer( id == "EPSE441_2003W_null_8406", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "CIVL210_2003W_null_3857_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "CIVL210_2003W_null_3857", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("CIVL230,MECH260".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "CIVL210_2003W_null_3857"
	when
        FactContainer( id == "CIVL210_2003W_null_3857", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "COMM295_2002W_2004S_4628_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "COMM295_2002W_2004S_4628", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "3", new HashSet(Arrays.asList("ECON101,ECON102,MATH105".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "COMM295_2002W_2004S_4628"
	when
        FactContainer( id == "COMM295_2002W_2004S_4628", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "COMM408_2002W_2006S_4833_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "COMM408_2002W_2006S_4833", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0*P1");
    	    	   		
		SubsetProposition propositionP1 = new SubsetProposition("P1", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("COMM295,ECON201,ECON301".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP1.apply();
        prop.addProposition(propositionP1);      
		   		   		   		   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("COMM297".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "COMM408_2002W_2006S_4833"
	when
        FactContainer( id == "COMM408_2002W_2006S_4833", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
                     and
                     Proposition( propositionName == "P1" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "ECON407_1998S_null_6173_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "ECON407_1998S_null_6173", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0*P1*P2");
    	    	   		
		SubsetProposition propositionP1 = new SubsetProposition("P1", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("ECON202,ECON207,ECON302,ECON305".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP1.apply();
        prop.addProposition(propositionP1);      
		   		   		   		   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("ECON201,ECON206,ECON301,ECON304".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		   		
		SubsetProposition propositionP2 = new SubsetProposition("P2", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("ECON303,ECON306".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP2.apply();
        prop.addProposition(propositionP2);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "ECON407_1998S_null_6173"
	when
        FactContainer( id == "ECON407_1998S_null_6173", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
                     and
                     Proposition( propositionName == "P1" && result == true ) from prop.propositions
                     and
                     Proposition( propositionName == "P2" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "COMM465_2002W_2004S_4952_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "COMM465_2002W_2004S_4952", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("(P0*P1+P2)");
    	    	   		
		SubsetProposition propositionP1 = new SubsetProposition("P1", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("ECON101,ECON102".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP1.apply();
        prop.addProposition(propositionP1);      
		   		   		   		   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("COMM457".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		   		
		SubsetProposition propositionP2 = new SubsetProposition("P2", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("ECON100".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP2.apply();
        prop.addProposition(propositionP2);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "COMM465_2002W_2004S_4952"
	when
        FactContainer( id == "COMM465_2002W_2004S_4952", state == FactContainer.State.DONE, prop : propositionContainer)

             (
                     Proposition( propositionName == "P0" && result == true ) from prop.propositions
                     and
                     Proposition( propositionName == "P1" && result == true ) from prop.propositions
                     or
                     Proposition( propositionName == "P2" && result == true ) from prop.propositions
                     )
            	then
   		prop.setRuleResult(true);
	end		


rule "COMM473_2003W_2004S_4972_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "COMM473_2003W_2004S_4972", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0+P1+P2+P3+P4");
    	    	   		
		SubsetProposition propositionP4 = new SubsetProposition("P4", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("ECON310,ECON102".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP4.apply();
        prop.addProposition(propositionP4);      
		   		   		   		   		
		SubsetProposition propositionP1 = new SubsetProposition("P1", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("ECON100".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP1.apply();
        prop.addProposition(propositionP1);      
		   		   		   		   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("ECON101,ECON102".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		   		
		SubsetProposition propositionP3 = new SubsetProposition("P3", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("ECON101,ECON311".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP3.apply();
        prop.addProposition(propositionP3);      
		   		   		   		   		
		SubsetProposition propositionP2 = new SubsetProposition("P2", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("ECON310,ECON311".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP2.apply();
        prop.addProposition(propositionP2);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "COMM473_2003W_2004S_4972"
	when
        FactContainer( id == "COMM473_2003W_2004S_4972", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
                     or
                     Proposition( propositionName == "P1" && result == true ) from prop.propositions
                     or
                     Proposition( propositionName == "P2" && result == true ) from prop.propositions
                     or
                     Proposition( propositionName == "P3" && result == true ) from prop.propositions
                     or
                     Proposition( propositionName == "P4" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "GRS 390_2003W_null_23682_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "GRS 390_2003W_null_23682", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("GRS 290".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "GRS 390_2003W_null_23682"
	when
        FactContainer( id == "GRS 390_2003W_null_23682", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "GRS 490_2003W_null_23683_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "GRS 490_2003W_null_23683", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("GRS 390".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "GRS 490_2003W_null_23683"
	when
        FactContainer( id == "GRS 490_2003W_null_23683", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "OCCH512_2003W_2005S_17396_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "OCCH512_2003W_2005S_17396", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("OCCH501,HCEP535".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "OCCH512_2003W_2005S_17396"
	when
        FactContainer( id == "OCCH512_2003W_2005S_17396", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PATH447_2003W_null_17853_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PATH447_2003W_null_17853", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("PATH427,PATH467".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PATH447_2003W_null_17853"
	when
        FactContainer( id == "PATH447_2003W_null_17853", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "EPSE524_2003W_null_8489_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "EPSE524_2003W_null_8489", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("EPSE518,EPSE522".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "EPSE524_2003W_null_8489"
	when
        FactContainer( id == "EPSE524_2003W_null_8489", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "COMM447_2003W_null_4899_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "COMM447_2003W_null_4899", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("COMM295,ECON201,ECON301".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "COMM447_2003W_null_4899"
	when
        FactContainer( id == "COMM447_2003W_null_4899", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "EPSE317_2003W_null_8298_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "EPSE317_2003W_null_8298", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("EPSE306,EPSE313".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "EPSE317_2003W_null_8298"
	when
        FactContainer( id == "EPSE317_2003W_null_8298", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "ANTH541_1991S_null_825_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "ANTH541_1991S_null_825", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("ANTH431".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "ANTH541_1991S_null_825"
	when
        FactContainer( id == "ANTH541_1991S_null_825", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "FNH 325_2004W_null_9155_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "FNH 325_2004W_null_9155", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "3", new HashSet(Arrays.asList("FNH 300,FNH 301,FNH 302".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "FNH 325_2004W_null_9155"
	when
        FactContainer( id == "FNH 325_2004W_null_9155", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "FNH 326_2004W_null_24821_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "FNH 326_2004W_null_24821", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("FNH 325".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "FNH 326_2004W_null_24821"
	when
        FactContainer( id == "FNH 326_2004W_null_24821", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "FNH 425_2004W_null_9169_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "FNH 425_2004W_null_9169", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("FNH 325,FNH 326".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "FNH 425_2004W_null_9169"
	when
        FactContainer( id == "FNH 425_2004W_null_9169", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHAR302_2004S_2008S_24842_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHAR302_2004S_2008S_24842", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHAR201".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHAR302_2004S_2008S_24842"
	when
        FactContainer( id == "PHAR302_2004S_2008S_24842", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHAR303_2004S_2007S_24843_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHAR303_2004S_2007S_24843", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHAR202".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHAR303_2004S_2007S_24843"
	when
        FactContainer( id == "PHAR303_2004S_2007S_24843", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHAR315_2004S_null_18093_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHAR315_2004S_null_18093", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("PHAR321,PHAR341".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHAR315_2004S_null_18093"
	when
        FactContainer( id == "PHAR315_2004S_null_18093", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHAR321_2004W_null_24844_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHAR321_2004W_null_24844", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHAR220".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHAR321_2004W_null_24844"
	when
        FactContainer( id == "PHAR321_2004W_null_24844", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHAR322_2003W_null_24845_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHAR322_2003W_null_24845", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHAR220".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHAR322_2003W_null_24845"
	when
        FactContainer( id == "PHAR322_2003W_null_24845", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHAR323_2003W_null_24846_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHAR323_2003W_null_24846", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("PHAR321,PHAR322".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHAR323_2003W_null_24846"
	when
        FactContainer( id == "PHAR323_2003W_null_24846", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHAR330_2003W_null_24847_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHAR330_2003W_null_24847", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHAR321".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHAR330_2003W_null_24847"
	when
        FactContainer( id == "PHAR330_2003W_null_24847", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHAR341_2004W_2008S_24848_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHAR341_2004W_2008S_24848", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "3", new HashSet(Arrays.asList("PHAR241,PHYL301,PHYL302".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHAR341_2004W_2008S_24848"
	when
        FactContainer( id == "PHAR341_2004W_2008S_24848", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHAR342_2004W_null_24849_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHAR342_2004W_null_24849", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHAR341".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHAR342_2004W_null_24849"
	when
        FactContainer( id == "PHAR342_2004W_null_24849", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHAR352_2004W_null_18111_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHAR352_2004W_null_18111", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHAR351".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHAR352_2004W_null_18111"
	when
        FactContainer( id == "PHAR352_2004W_null_18111", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHAR362_2004W_2008S_24850_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHAR362_2004W_2008S_24850", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHAR361".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHAR362_2004W_2008S_24850"
	when
        FactContainer( id == "PHAR362_2004W_2008S_24850", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHAR399_2004W_null_24853_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHAR399_2004W_null_24853", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHAR299".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHAR399_2004W_null_24853"
	when
        FactContainer( id == "PHAR399_2004W_null_24853", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "AGRO324_2004W_null_23383_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "AGRO324_2004W_null_23383", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("(P0*P1+P2)");
    	    	   		
		SubsetProposition propositionP1 = new SubsetProposition("P1", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("CHEM123".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP1.apply();
        prop.addProposition(propositionP1);      
		   		   		   		   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("BIOL121".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		   		
		SubsetProposition propositionP2 = new SubsetProposition("P2", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("CHEM111,CHEM113".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP2.apply();
        prop.addProposition(propositionP2);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "AGRO324_2004W_null_23383"
	when
        FactContainer( id == "AGRO324_2004W_null_23383", state == FactContainer.State.DONE, prop : propositionContainer)

             (
                     Proposition( propositionName == "P0" && result == true ) from prop.propositions
                     and
                     Proposition( propositionName == "P1" && result == true ) from prop.propositions
                     or
                     Proposition( propositionName == "P2" && result == true ) from prop.propositions
                     )
            	then
   		prop.setRuleResult(true);
	end		


rule "CHBE345_2004W_2005S_24864_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "CHBE345_2004W_2005S_24864", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("CHBE351".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "CHBE345_2004W_2005S_24864"
	when
        FactContainer( id == "CHBE345_2004W_2005S_24864", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "EECE355_2004W_2007S_24865_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "EECE355_2004W_2007S_24865", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("EECE263".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "EECE355_2004W_2007S_24865"
	when
        FactContainer( id == "EECE355_2004W_2007S_24865", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "EECE363_2004W_2007S_24866_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "EECE363_2004W_2007S_24866", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("EECE263".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "EECE363_2004W_2007S_24866"
	when
        FactContainer( id == "EECE363_2004W_2007S_24866", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "EECE418_2004W_null_7153_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "EECE418_2004W_null_7153", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0*P1");
    	    	   		
		SubsetProposition propositionP1 = new SubsetProposition("P1", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("CPSC310,CPSC352,EECE310,EECE314".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP1.apply();
        prop.addProposition(propositionP1);      
		   		   		   		   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("EECE320,CPSC220,CPSC221".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "EECE418_2004W_null_7153"
	when
        FactContainer( id == "EECE418_2004W_null_7153", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
                     and
                     Proposition( propositionName == "P1" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "EECE440_2004W_null_23401_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "EECE440_2004W_null_23401", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0*P1");
    	    	   		
		SubsetProposition propositionP1 = new SubsetProposition("P1", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("CPSC310,CPSC352,EECE310".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP1.apply();
        prop.addProposition(propositionP1);      
		   		   		   		   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("EECE320,CPSC220,CPSC221".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "EECE440_2004W_null_23401"
	when
        FactContainer( id == "EECE440_2004W_null_23401", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
                     and
                     Proposition( propositionName == "P1" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "EECE443_2004W_null_7155_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "EECE443_2004W_null_7155", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("CPSC310,CPSC352,EECE310,EECE314".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "EECE443_2004W_null_7155"
	when
        FactContainer( id == "EECE443_2004W_null_7155", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "EECE494_2004W_null_7188_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "EECE494_2004W_null_7188", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("EECE315,CPSC315,CPSC313".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "EECE494_2004W_null_7188"
	when
        FactContainer( id == "EECE494_2004W_null_7188", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "MECH364_2004W_2005S_15040_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "MECH364_2004W_2005S_15040", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("MECH265".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "MECH364_2004W_2005S_15040"
	when
        FactContainer( id == "MECH364_2004W_2005S_15040", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "MECH366_2004W_2005S_24882_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "MECH366_2004W_2005S_24882", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "5", new HashSet(Arrays.asList("EECE263,MECH260,MECH265,MECH270,MECH280".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "MECH366_2004W_2005S_24882"
	when
        FactContainer( id == "MECH366_2004W_2005S_24882", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "SOCI470_1992W_2004S_21749_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "SOCI470_1992W_2004S_21749", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("SOCI100,SOCI300".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "SOCI470_1992W_2004S_21749"
	when
        FactContainer( id == "SOCI470_1992W_2004S_21749", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "BUSI470_2003W_null_24901_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "BUSI470_2003W_null_24901", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("BUSI370,COMM473".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "BUSI470_2003W_null_24901"
	when
        FactContainer( id == "BUSI470_2003W_null_24901", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "EECE423_2004W_2006S_24332_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "EECE423_2004W_2006S_24332", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("(P0+P1+P2)*P3");
    	    	   		
		SubsetProposition propositionP1 = new SubsetProposition("P1", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("CPSC128,CPSC216".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP1.apply();
        prop.addProposition(propositionP1);      
		   		   		   		   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("CPSC252".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		   		
		SubsetProposition propositionP3 = new SubsetProposition("P3", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("STAT251,MATH318".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP3.apply();
        prop.addProposition(propositionP3);      
		   		   		   		   		
		SubsetProposition propositionP2 = new SubsetProposition("P2", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("CPSC211,CPSC221".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP2.apply();
        prop.addProposition(propositionP2);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "EECE423_2004W_2006S_24332"
	when
        FactContainer( id == "EECE423_2004W_2006S_24332", state == FactContainer.State.DONE, prop : propositionContainer)

             (
                     Proposition( propositionName == "P0" && result == true ) from prop.propositions
                     or
                     Proposition( propositionName == "P1" && result == true ) from prop.propositions
                     or
                     Proposition( propositionName == "P2" && result == true ) from prop.propositions
                     )
                     and
                     Proposition( propositionName == "P3" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "MECH325_2005W_2006S_24902_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "MECH325_2005W_2006S_24902", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "4", new HashSet(Arrays.asList("MECH220,MECH221,MECH222,MECH223".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "MECH325_2005W_2006S_24902"
	when
        FactContainer( id == "MECH325_2005W_2006S_24902", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "MECH326_2005W_2006S_24903_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "MECH326_2005W_2006S_24903", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "4", new HashSet(Arrays.asList("MECH220,MECH221,MECH222,MECH223".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "MECH326_2005W_2006S_24903"
	when
        FactContainer( id == "MECH326_2005W_2006S_24903", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "MECH327_2005W_2007S_24904_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "MECH327_2005W_2007S_24904", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("MECH222,PHYS257,CHBE241".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "MECH327_2005W_2007S_24904"
	when
        FactContainer( id == "MECH327_2005W_2007S_24904", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "MECH489_2005W_2006S_24906_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "MECH489_2005W_2006S_24906", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0*P1");
    	    	   		
		SubsetProposition propositionP1 = new SubsetProposition("P1", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("MECH327,MECH370".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP1.apply();
        prop.addProposition(propositionP1);      
		   		   		   		   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("MECH375,MECH380".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "MECH489_2005W_2006S_24906"
	when
        FactContainer( id == "MECH489_2005W_2006S_24906", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
                     and
                     Proposition( propositionName == "P1" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "FMST415_2004S_null_24909_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "FMST415_2004S_null_24909", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("FMST436".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "FMST415_2004S_null_24909"
	when
        FactContainer( id == "FMST415_2004S_null_24909", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "WMST410_2004W_null_24911_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "WMST410_2004W_null_24911", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("WMST100".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "WMST410_2004W_null_24911"
	when
        FactContainer( id == "WMST410_2004W_null_24911", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "WMST411_2004W_null_24912_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "WMST411_2004W_null_24912", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("WMST100".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "WMST411_2004W_null_24912"
	when
        FactContainer( id == "WMST411_2004W_null_24912", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "EOSC541_2003W_null_24919_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "EOSC541_2003W_null_24919", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("(P0+P1)*P2");
    	    	   		
		SubsetProposition propositionP1 = new SubsetProposition("P1", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("EOSC540".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP1.apply();
        prop.addProposition(propositionP1);      
		   		   		   		   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("EOSC430".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		   		
		SubsetProposition propositionP2 = new SubsetProposition("P2", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("EOSC533".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP2.apply();
        prop.addProposition(propositionP2);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "EOSC541_2003W_null_24919"
	when
        FactContainer( id == "EOSC541_2003W_null_24919", state == FactContainer.State.DONE, prop : propositionContainer)

             (
                     Proposition( propositionName == "P0" && result == true ) from prop.propositions
                     or
                     Proposition( propositionName == "P1" && result == true ) from prop.propositions
                     )
                     and
                     Proposition( propositionName == "P2" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "MECH479_2005W_2006S_15156_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "MECH479_2005W_2006S_15156", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0*P1");
    	    	   		
		SubsetProposition propositionP1 = new SubsetProposition("P1", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("MECH327,MECH370".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP1.apply();
        prop.addProposition(propositionP1);      
		   		   		   		   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("MECH375,MECH380".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "MECH479_2005W_2006S_15156"
	when
        FactContainer( id == "MECH479_2005W_2006S_15156", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
                     and
                     Proposition( propositionName == "P1" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "COGS300_2004S_null_24929_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "COGS300_2004S_null_24929", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("COGS200".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "COGS300_2004S_null_24929"
	when
        FactContainer( id == "COGS300_2004S_null_24929", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "COGS401_2004S_null_24930_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "COGS401_2004S_null_24930", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("COGS300".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "COGS401_2004S_null_24930"
	when
        FactContainer( id == "COGS401_2004S_null_24930", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "COGS402_2004S_null_24931_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "COGS402_2004S_null_24931", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("COGS300".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "COGS402_2004S_null_24931"
	when
        FactContainer( id == "COGS402_2004S_null_24931", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "CPSC410_2004W_null_5459_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "CPSC410_2004W_null_5459", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0+P1");
    	    	   		
		SubsetProposition propositionP1 = new SubsetProposition("P1", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("EECE310,EECE315".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP1.apply();
        prop.addProposition(propositionP1);      
		   		   		   		   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("CPSC310".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "CPSC410_2004W_null_5459"
	when
        FactContainer( id == "CPSC410_2004W_null_5459", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
                     or
                     Proposition( propositionName == "P1" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "CPSC415_2004W_null_5471_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "CPSC415_2004W_null_5471", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0+P1");
    	    	   		
		SubsetProposition propositionP1 = new SubsetProposition("P1", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("EECE315".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP1.apply();
        prop.addProposition(propositionP1);      
		   		   		   		   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("CPSC313,CPSC315".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "CPSC415_2004W_null_5471"
	when
        FactContainer( id == "CPSC415_2004W_null_5471", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
                     or
                     Proposition( propositionName == "P1" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "CPSC425_2004W_2005S_24941_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "CPSC425_2004W_2005S_24941", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0*P1");
    	    	   		
		SubsetProposition propositionP1 = new SubsetProposition("P1", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("MATH200,MATH221".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP1.apply();
        prop.addProposition(propositionP1);      
		   		   		   		   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("CPSC216,CPSC221".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "CPSC425_2004W_2005S_24941"
	when
        FactContainer( id == "CPSC425_2004W_2005S_24941", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
                     and
                     Proposition( propositionName == "P1" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "THTR305_2004W_null_22757_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "THTR305_2004W_null_22757", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("THTR205".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "THTR305_2004W_null_22757"
	when
        FactContainer( id == "THTR305_2004W_null_22757", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "THTR306_2004W_null_24964_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "THTR306_2004W_null_24964", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("THTR205".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "THTR306_2004W_null_24964"
	when
        FactContainer( id == "THTR306_2004W_null_24964", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "THTR405_2004W_null_22822_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "THTR405_2004W_null_22822", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("THTR305".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "THTR405_2004W_null_22822"
	when
        FactContainer( id == "THTR405_2004W_null_22822", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "THTR406_2004W_null_24966_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "THTR406_2004W_null_24966", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("THTR306".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "THTR406_2004W_null_24966"
	when
        FactContainer( id == "THTR406_2004W_null_24966", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "THTR407_2004W_null_24967_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "THTR407_2004W_null_24967", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("THTR307".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "THTR407_2004W_null_24967"
	when
        FactContainer( id == "THTR407_2004W_null_24967", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "THTR450_2004W_null_22848_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "THTR450_2004W_null_22848", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("THTR350".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "THTR450_2004W_null_22848"
	when
        FactContainer( id == "THTR450_2004W_null_22848", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "THTR452_2004W_null_22854_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "THTR452_2004W_null_22854", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("THTR352".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "THTR452_2004W_null_22854"
	when
        FactContainer( id == "THTR452_2004W_null_22854", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "THTR454_2004W_null_22860_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "THTR454_2004W_null_22860", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("THTR354".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "THTR454_2004W_null_22860"
	when
        FactContainer( id == "THTR454_2004W_null_22860", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "THTR456_2004W_null_22862_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "THTR456_2004W_null_22862", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("THTR356".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "THTR456_2004W_null_22862"
	when
        FactContainer( id == "THTR456_2004W_null_22862", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "THTR499_2004W_2008S_22881_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "THTR499_2004W_2008S_22881", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("THTR399".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "THTR499_2004W_2008S_22881"
	when
        FactContainer( id == "THTR499_2004W_2008S_22881", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "LING431_2004W_2005S_14213_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "LING431_2004W_2005S_14213", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("LING311".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "LING431_2004W_2005S_14213"
	when
        FactContainer( id == "LING431_2004W_2005S_14213", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "LING432_2004W_2005S_14215_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "LING432_2004W_2005S_14215", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("LING300".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "LING432_2004W_2005S_14215"
	when
        FactContainer( id == "LING432_2004W_2005S_14215", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "LING451_2004W_null_14235_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "LING451_2004W_null_14235", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("LING311".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "LING451_2004W_null_14235"
	when
        FactContainer( id == "LING451_2004W_null_14235", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "LING452_2004W_null_14236_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "LING452_2004W_null_14236", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("LING300".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "LING452_2004W_null_14236"
	when
        FactContainer( id == "LING452_2004W_null_14236", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "LING300_2004W_null_14161_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "LING300_2004W_null_14161", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0+P1");
    	    	   		
		SubsetProposition propositionP1 = new SubsetProposition("P1", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("ENGL329".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP1.apply();
        prop.addProposition(propositionP1);      
		   		   		   		   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("LING201".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "LING300_2004W_null_14161"
	when
        FactContainer( id == "LING300_2004W_null_14161", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
                     or
                     Proposition( propositionName == "P1" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "LING311_2004W_null_14168_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "LING311_2004W_null_14168", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0+P1");
    	    	   		
		SubsetProposition propositionP1 = new SubsetProposition("P1", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("ENGL329".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP1.apply();
        prop.addProposition(propositionP1);      
		   		   		   		   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("LING200".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "LING311_2004W_null_14168"
	when
        FactContainer( id == "LING311_2004W_null_14168", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
                     or
                     Proposition( propositionName == "P1" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "LING305_2004W_null_14164_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "LING305_2004W_null_14164", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("LING200,LING201".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "LING305_2004W_null_14164"
	when
        FactContainer( id == "LING305_2004W_null_14164", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "LING316_2004W_null_14175_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "LING316_2004W_null_14175", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("LING200".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "LING316_2004W_null_14175"
	when
        FactContainer( id == "LING316_2004W_null_14175", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "LING319_2004W_2005S_14181_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "LING319_2004W_2005S_14181", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("LING200,LING201".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "LING319_2004W_2005S_14181"
	when
        FactContainer( id == "LING319_2004W_2005S_14181", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "LING327_2004W_null_24981_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "LING327_2004W_null_24981", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("LING300".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "LING327_2004W_null_24981"
	when
        FactContainer( id == "LING327_2004W_null_24981", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "ECED425_2003W_2006S_5975_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "ECED425_2003W_2006S_5975", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("ECED405".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "ECED425_2003W_2006S_5975"
	when
        FactContainer( id == "ECED425_2003W_2006S_5975", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "ECED443_2003W_2006W_5981_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "ECED443_2003W_2006W_5981", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("ECED405,ECED433".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "ECED443_2003W_2006W_5981"
	when
        FactContainer( id == "ECED443_2003W_2006W_5981", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		
