package prerequisiterules
import java.util.*;
import org.kuali.student.rules.internal.common.entity.ComparisonOperator;
import org.kuali.student.rules.internal.common.statement.*;
import org.kuali.student.rules.internal.common.facts.FactRequest;
import org.kuali.student.rules.util.FactContainer;
import org.kuali.student.rules.util.FactContainer.State;


rule "PHIL426_1994W_2001S_18789_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHIL426_1994W_2001S_18789", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHIL340".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHIL426_1994W_2001S_18789"
	when
        FactContainer( id == "PHIL426_1994W_2001S_18789", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHIL343_1991S_2004W_18691_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHIL343_1991S_2004W_18691", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHIL333".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHIL343_1991S_2004W_18691"
	when
        FactContainer( id == "PHIL343_1991S_2004W_18691", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHIL363_1991S_1994S_18703_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHIL363_1991S_1994S_18703", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHIL353".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHIL363_1991S_1994S_18703"
	when
        FactContainer( id == "PHIL363_1991S_1994S_18703", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHIL383_1972W_1990W_18715_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHIL383_1972W_1990W_18715", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHIL373".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHIL383_1972W_1990W_18715"
	when
        FactContainer( id == "PHIL383_1972W_1990W_18715", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHIL394_1980W_1990W_18722_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHIL394_1980W_1990W_18722", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHIL393".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHIL394_1980W_1990W_18722"
	when
        FactContainer( id == "PHIL394_1980W_1990W_18722", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHIL401_1970W_1990W_18730_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHIL401_1970W_1990W_18730", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHIL400".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHIL401_1970W_1990W_18730"
	when
        FactContainer( id == "PHIL401_1970W_1990W_18730", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHIL402_1991S_1994S_18732_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHIL402_1991S_1994S_18732", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHIL303,PHIL305,PHIL306".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHIL402_1991S_1994S_18732"
	when
        FactContainer( id == "PHIL402_1991S_1994S_18732", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHIL303_1971W_1990W_18626_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHIL303_1971W_1990W_18626", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHIL302".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHIL303_1971W_1990W_18626"
	when
        FactContainer( id == "PHIL303_1971W_1990W_18626", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHIL305_1971W_1990W_18629_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHIL305_1971W_1990W_18629", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHIL302".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHIL305_1971W_1990W_18629"
	when
        FactContainer( id == "PHIL305_1971W_1990W_18629", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHIL306_1980W_1990W_18631_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHIL306_1980W_1990W_18631", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHIL302".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHIL306_1980W_1990W_18631"
	when
        FactContainer( id == "PHIL306_1980W_1990W_18631", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHIL311_1994W_1999W_18640_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHIL311_1994W_1999W_18640", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHIL310".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHIL311_1994W_1999W_18640"
	when
        FactContainer( id == "PHIL311_1994W_1999W_18640", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHIL314_1991S_1994S_18650_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHIL314_1991S_1994S_18650", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHIL313".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHIL314_1991S_1994S_18650"
	when
        FactContainer( id == "PHIL314_1991S_1994S_18650", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHIL323_1994W_2001S_18670_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHIL323_1994W_2001S_18670", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHIL220".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHIL323_1994W_2001S_18670"
	when
        FactContainer( id == "PHIL323_1994W_2001S_18670", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHED581_1971W_1988S_18556_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHED581_1971W_1988S_18556", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHED381".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHED581_1971W_1988S_18556"
	when
        FactContainer( id == "PHED581_1971W_1988S_18556", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHED462_1990S_1990W_18486_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHED462_1990S_1990W_18486", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("PHED391,PHED463".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHED462_1990S_1990W_18486"
	when
        FactContainer( id == "PHED462_1990S_1990W_18486", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHED463_1970W_1990W_18488_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHED463_1970W_1990W_18488", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("(P0+P1)");
    	    	   		
		SubsetProposition propositionP1 = new SubsetProposition("P1", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("ANAT390,ZOOL303".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP1.apply();
        prop.addProposition(propositionP1);      
		   		   		   		   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHED391".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHED463_1970W_1990W_18488"
	when
        FactContainer( id == "PHED463_1970W_1990W_18488", state == FactContainer.State.DONE, prop : propositionContainer)

             (
                     Proposition( propositionName == "P0" && result == true ) from prop.propositions
                     or
                     Proposition( propositionName == "P1" && result == true ) from prop.propositions
                     )
            	then
   		prop.setRuleResult(true);
	end		


rule "PHED469_1973W_1990W_18497_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHED469_1973W_1990W_18497", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("PHED370,PHED463".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHED469_1973W_1990W_18497"
	when
        FactContainer( id == "PHED469_1973W_1990W_18497", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHED469_1991S_1993W_18497_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHED469_1991S_1993W_18497", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("PHED370,PHED463".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHED469_1991S_1993W_18497"
	when
        FactContainer( id == "PHED469_1991S_1993W_18497", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHED471_1983W_1990W_18500_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHED471_1983W_1990W_18500", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHED461".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHED471_1983W_1990W_18500"
	when
        FactContainer( id == "PHED471_1983W_1990W_18500", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHED471_1991S_1993W_18500_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHED471_1991S_1993W_18500", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHED461".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHED471_1991S_1993W_18500"
	when
        FactContainer( id == "PHED471_1991S_1993W_18500", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHED473_1991S_1993W_18502_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHED473_1991S_1993W_18502", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHYS110,PHED363".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHED473_1991S_1993W_18502"
	when
        FactContainer( id == "PHED473_1991S_1993W_18502", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHED492_1991S_1993S_18510_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHED492_1991S_1993S_18510", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHED392".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHED492_1991S_1993S_18510"
	when
        FactContainer( id == "PHED492_1991S_1993S_18510", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHED492_1993W_1993W_18510_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHED492_1993W_1993W_18510", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("COMM329".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHED492_1993W_1993W_18510"
	when
        FactContainer( id == "PHED492_1993W_1993W_18510", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHED374_1989W_1990W_18432_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHED374_1989W_1990W_18432", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHED161".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHED374_1989W_1990W_18432"
	when
        FactContainer( id == "PHED374_1989W_1990W_18432", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHED375_1991S_1992W_18434_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHED375_1991S_1992W_18434", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("PHED161,PHED261".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHED375_1991S_1992W_18434"
	when
        FactContainer( id == "PHED375_1991S_1992W_18434", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHED375_1986W_1990W_18434_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHED375_1986W_1990W_18434", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("PHED161,PHED261".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHED375_1986W_1990W_18434"
	when
        FactContainer( id == "PHED375_1986W_1990W_18434", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHED381_1971W_1990W_18439_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHED381_1971W_1990W_18439", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("PHED161,PHED261".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHED381_1971W_1990W_18439"
	when
        FactContainer( id == "PHED381_1971W_1990W_18439", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHED382_1981W_1990W_18441_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHED382_1981W_1990W_18441", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHED261".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHED382_1981W_1990W_18441"
	when
        FactContainer( id == "PHED382_1981W_1990W_18441", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHED391_1970W_1990W_18446_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHED391_1970W_1990W_18446", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHED163".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHED391_1970W_1990W_18446"
	when
        FactContainer( id == "PHED391_1970W_1990W_18446", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHED392_1993W_1993W_18449_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHED392_1993W_1993W_18449", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHED261".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHED392_1993W_1993W_18449"
	when
        FactContainer( id == "PHED392_1993W_1993W_18449", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHED420_1986W_1990W_18467_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHED420_1986W_1990W_18467", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHED310,PHED320".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHED420_1986W_1990W_18467"
	when
        FactContainer( id == "PHED420_1986W_1990W_18467", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHED420_1991W_1993W_18467_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHED420_1991W_1993W_18467", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHED310,PHED320".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHED420_1991W_1993W_18467"
	when
        FactContainer( id == "PHED420_1991W_1993W_18467", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHED448_1983W_1990W_18475_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHED448_1983W_1990W_18475", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHED310".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHED448_1983W_1990W_18475"
	when
        FactContainer( id == "PHED448_1983W_1990W_18475", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHED320_1991S_1993S_18381_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHED320_1991S_1993S_18381", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHED200".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHED320_1991S_1993S_18381"
	when
        FactContainer( id == "PHED320_1991S_1993S_18381", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHED352_1986W_1990W_18400_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHED352_1986W_1990W_18400", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHED391".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHED352_1986W_1990W_18400"
	when
        FactContainer( id == "PHED352_1986W_1990W_18400", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHED360_1970W_1990W_18406_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHED360_1970W_1990W_18406", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHED261".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHED360_1970W_1990W_18406"
	when
        FactContainer( id == "PHED360_1970W_1990W_18406", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHED363_1990S_1990W_18413_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHED363_1990S_1990W_18413", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0*P1");
    	    	   		
		SubsetProposition propositionP1 = new SubsetProposition("P1", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHED391,ANAT390".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP1.apply();
        prop.addProposition(propositionP1);      
		   		   		   		   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHED163".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHED363_1990S_1990W_18413"
	when
        FactContainer( id == "PHED363_1990S_1990W_18413", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
                     and
                     Proposition( propositionName == "P1" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHED364_1973W_1990W_18415_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHED364_1973W_1990W_18415", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHED164".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHED364_1973W_1990W_18415"
	when
        FactContainer( id == "PHED364_1973W_1990W_18415", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHED364_1991S_1993W_18415_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHED364_1991S_1993W_18415", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHED164".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHED364_1991S_1993W_18415"
	when
        FactContainer( id == "PHED364_1991S_1993W_18415", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHED275_1986W_1989S_18355_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHED275_1986W_1989S_18355", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHED161".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHED275_1986W_1989S_18355"
	when
        FactContainer( id == "PHED275_1986W_1989S_18355", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHED292_1993W_1993W_18363_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHED292_1993W_1993W_18363", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHED161".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHED292_1993W_1993W_18363"
	when
        FactContainer( id == "PHED292_1993W_1993W_18363", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHED303_1986W_1990W_18371_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHED303_1986W_1990W_18371", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("PHED103,PHED391".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHED303_1986W_1990W_18371"
	when
        FactContainer( id == "PHED303_1986W_1990W_18371", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHED310_1986W_1990W_18375_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHED310_1986W_1990W_18375", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHED110".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHED310_1986W_1990W_18375"
	when
        FactContainer( id == "PHED310_1986W_1990W_18375", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHED310_1991S_1993S_18375_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHED310_1991S_1993S_18375", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHED110".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHED310_1991S_1993S_18375"
	when
        FactContainer( id == "PHED310_1991S_1993S_18375", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHAR458_1990W_1990W_18201_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHAR458_1990W_1990W_18201", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHAR351".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHAR458_1990W_1990W_18201"
	when
        FactContainer( id == "PHAR458_1990W_1990W_18201", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHAR427_1970W_1989S_18161_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHAR427_1970W_1989S_18161", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHAR320".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHAR427_1970W_1989S_18161"
	when
        FactContainer( id == "PHAR427_1970W_1989S_18161", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHAR427_1991S_1991W_18161_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHAR427_1991S_1991W_18161", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHAR320".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHAR427_1991S_1991W_18161"
	when
        FactContainer( id == "PHAR427_1991S_1991W_18161", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHAR437_1970W_1990W_18169_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHAR437_1970W_1990W_18169", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHAR320".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHAR437_1970W_1990W_18169"
	when
        FactContainer( id == "PHAR437_1970W_1990W_18169", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHAR310_1970W_1990W_18090_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHAR310_1970W_1990W_18090", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("PHAR110,PHAR210".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHAR310_1970W_1990W_18090"
	when
        FactContainer( id == "PHAR310_1970W_1990W_18090", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHAR310_1991S_1993S_18090_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHAR310_1991S_1993S_18090", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("PHAR211,PHAR311".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHAR310_1991S_1993S_18090"
	when
        FactContainer( id == "PHAR310_1991S_1993S_18090", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHAR340_1991S_1993S_18105_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHAR340_1991S_1993S_18105", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHAR335".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHAR340_1991S_1993S_18105"
	when
        FactContainer( id == "PHAR340_1991S_1993S_18105", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHAR345_1991S_1993S_18107_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHAR345_1991S_1993S_18107", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHAR340".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHAR345_1991S_1993S_18107"
	when
        FactContainer( id == "PHAR345_1991S_1993S_18107", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PCTH513_1983W_1990W_18047_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PCTH513_1983W_1990W_18047", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PCTH425".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PCTH513_1983W_1990W_18047"
	when
        FactContainer( id == "PCTH513_1983W_1990W_18047", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PETE545_1998S_null_18069_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PETE545_1998S_null_18069", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PETE508".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PETE545_1998S_null_18069"
	when
        FactContainer( id == "PETE545_1998S_null_18069", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PHAR210_1970W_1990W_18078_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PHAR210_1970W_1990W_18078", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHAR110".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PHAR210_1970W_1990W_18078"
	when
        FactContainer( id == "PHAR210_1970W_1990W_18078", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PCTH398_1997W_null_18003_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PCTH398_1997W_null_18003", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PCTH300".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PCTH398_1997W_null_18003"
	when
        FactContainer( id == "PCTH398_1997W_null_18003", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PCTH400_1983W_1990W_18006_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PCTH400_1983W_1990W_18006", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PCTH300".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PCTH400_1983W_1990W_18006"
	when
        FactContainer( id == "PCTH400_1983W_1990W_18006", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PCTH404_1983W_1990W_18010_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PCTH404_1983W_1990W_18010", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("PCTH300,BIOL300".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PCTH404_1983W_1990W_18010"
	when
        FactContainer( id == "PCTH404_1983W_1990W_18010", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PATH467_1991S_2001S_17869_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PATH467_1991S_2001S_17869", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("MICB153".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PATH467_1991S_2001S_17869"
	when
        FactContainer( id == "PATH467_1991S_2001S_17869", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PATH523_1983W_1990W_17898_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PATH523_1983W_1990W_17898", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("MICB200".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PATH523_1983W_1990W_17898"
	when
        FactContainer( id == "PATH523_1983W_1990W_17898", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PATH524_1983W_1990W_17900_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PATH524_1983W_1990W_17900", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("MICB403,PATH427".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PATH524_1983W_1990W_17900"
	when
        FactContainer( id == "PATH524_1983W_1990W_17900", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PATH524_1991S_2002W_17900_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PATH524_1991S_2002W_17900", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("MICB403,PATH427".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PATH524_1991S_2002W_17900"
	when
        FactContainer( id == "PATH524_1991S_2002W_17900", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PATH525_1970W_1990W_17902_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PATH525_1970W_1990W_17902", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PATH425,PATH500".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PATH525_1970W_1990W_17902"
	when
        FactContainer( id == "PATH525_1970W_1990W_17902", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PATH526_1991S_1999W_17904_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PATH526_1991S_1999W_17904", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("ANAT510,PHYL425".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PATH526_1991S_1999W_17904"
	when
        FactContainer( id == "PATH526_1991S_1999W_17904", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PATH375_1970W_1990W_17815_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PATH375_1970W_1990W_17815", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0*P1*P2");
    	    	   		
		SubsetProposition propositionP1 = new SubsetProposition("P1", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("CHEM103,CHEM110,CHEM120".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP1.apply();
        prop.addProposition(propositionP1);      
		   		   		   		   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("BIOL101,BIOL102".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		   		
		SubsetProposition propositionP2 = new SubsetProposition("P2", ComparisonOperator.EQUAL_TO, "4", new HashSet(Arrays.asList("PHYL301,BIOC300,ANAT390,ANAT501".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP2.apply();
        prop.addProposition(propositionP2);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PATH375_1970W_1990W_17815"
	when
        FactContainer( id == "PATH375_1970W_1990W_17815", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
                     and
                     Proposition( propositionName == "P1" && result == true ) from prop.propositions
                     and
                     Proposition( propositionName == "P2" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "PATH417_1983W_1989W_17838_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "PATH417_1983W_1989W_17838", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("MICB403".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "PATH417_1983W_1989W_17838"
	when
        FactContainer( id == "PATH417_1983W_1989W_17838", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "OCGY510_1973W_1989S_17493_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "OCGY510_1973W_1989S_17493", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("OCGY514".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "OCGY510_1973W_1989S_17493"
	when
        FactContainer( id == "OCGY510_1973W_1989S_17493", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "OCGY516_1988W_1990W_17509_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "OCGY516_1988W_1990W_17509", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("OCGY514".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "OCGY516_1988W_1990W_17509"
	when
        FactContainer( id == "OCGY516_1988W_1990W_17509", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "OCGY408_1981W_1990W_17441_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "OCGY408_1981W_1990W_17441", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("OCGY308".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "OCGY408_1981W_1990W_17441"
	when
        FactContainer( id == "OCGY408_1981W_1990W_17441", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "OCGY409_1991S_1995S_17443_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "OCGY409_1991S_1995S_17443", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("(P0+P1)");
    	    	   		
		SubsetProposition propositionP1 = new SubsetProposition("P1", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("PHYS312,CPSC122".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP1.apply();
        prop.addProposition(propositionP1);      
		   		   		   		   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("MATH316".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "OCGY409_1991S_1995S_17443"
	when
        FactContainer( id == "OCGY409_1991S_1995S_17443", state == FactContainer.State.DONE, prop : propositionContainer)

             (
                     Proposition( propositionName == "P0" && result == true ) from prop.propositions
                     or
                     Proposition( propositionName == "P1" && result == true ) from prop.propositions
                     )
            	then
   		prop.setRuleResult(true);
	end		


rule "OCGY412_1991S_1996S_17453_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "OCGY412_1991S_1996S_17453", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("MICB200".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "OCGY412_1991S_1996S_17453"
	when
        FactContainer( id == "OCGY412_1991S_1996S_17453", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "OCGY413_1981W_1989S_17456_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "OCGY413_1981W_1989S_17456", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("OCGY308,OCGY309".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "OCGY413_1981W_1989S_17456"
	when
        FactContainer( id == "OCGY413_1981W_1989S_17456", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "OCGY413_1991S_1999W_17456_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "OCGY413_1991S_1999W_17456", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("OCGY308,OCGY309".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "OCGY413_1991S_1999W_17456"
	when
        FactContainer( id == "OCGY413_1991S_1999W_17456", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "OCGY414_1988W_1990S_17459_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "OCGY414_1988W_1990S_17459", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHYS312,MATH316".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "OCGY414_1988W_1990S_17459"
	when
        FactContainer( id == "OCGY414_1988W_1990S_17459", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "OCGY414_1990W_1990W_17459_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "OCGY414_1990W_1990W_17459", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("PHYS312,MATH316,MATH251".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "OCGY414_1990W_1990W_17459"
	when
        FactContainer( id == "OCGY414_1990W_1990W_17459", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "OCGY415_1983W_1990W_17461_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "OCGY415_1983W_1990W_17461", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0*P1");
    	    	   		
		SubsetProposition propositionP1 = new SubsetProposition("P1", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("BOTA330,BIOL330,BIOL201".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP1.apply();
        prop.addProposition(propositionP1);      
		   		   		   		   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("BOTA301".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "OCGY415_1983W_1990W_17461"
	when
        FactContainer( id == "OCGY415_1983W_1990W_17461", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
                     and
                     Proposition( propositionName == "P1" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "OCGY416_1983W_1990W_17463_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "OCGY416_1983W_1990W_17463", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("GEOL426".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "OCGY416_1983W_1990W_17463"
	when
        FactContainer( id == "OCGY416_1983W_1990W_17463", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "OCCH506_1994S_1997S_17389_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "OCCH506_1994S_1997S_17389", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("OCCH502,OCCH503".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "OCCH506_1994S_1997S_17389"
	when
        FactContainer( id == "OCCH506_1994S_1997S_17389", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "OCGY308_1984W_1990W_17414_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "OCGY308_1984W_1990W_17414", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("MATH101,MATH121".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "OCGY308_1984W_1990W_17414"
	when
        FactContainer( id == "OCGY308_1984W_1990W_17414", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "OCGY309_1984W_1990W_17417_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "OCGY309_1984W_1990W_17417", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("OCGY308".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "OCGY309_1984W_1990W_17417"
	when
        FactContainer( id == "OCGY309_1984W_1990W_17417", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "OCGY309_1991S_1995S_17417_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "OCGY309_1991S_1995S_17417", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("OCGY308".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "OCGY309_1991S_1995S_17417"
	when
        FactContainer( id == "OCGY309_1991S_1995S_17417", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "OCGY401_1970W_1989S_17426_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "OCGY401_1970W_1989S_17426", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0*P1");
    	    	   		
		SubsetProposition propositionP1 = new SubsetProposition("P1", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("MATH255,MATH315".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP1.apply();
        prop.addProposition(propositionP1);      
		   		   		   		   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("OCGY308".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "OCGY401_1970W_1989S_17426"
	when
        FactContainer( id == "OCGY401_1970W_1989S_17426", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
                     and
                     Proposition( propositionName == "P1" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "OCGY403_1999W_1999W_17429_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "OCGY403_1999W_1999W_17429", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("OCGY309".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "OCGY403_1999W_1999W_17429"
	when
        FactContainer( id == "OCGY403_1999W_1999W_17429", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "OCGY405_1980W_1989S_17434_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "OCGY405_1980W_1989S_17434", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("OCGY308".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "OCGY405_1980W_1989S_17434"
	when
        FactContainer( id == "OCGY405_1980W_1989S_17434", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "OCGY405_1991S_1999S_17434_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "OCGY405_1991S_1999S_17434", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("OCGY308".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "OCGY405_1991S_1999S_17434"
	when
        FactContainer( id == "OCGY405_1991S_1999S_17434", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "OCGY406_1991S_1999W_17437_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "OCGY406_1991S_1999W_17437", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("OCGY309,BIOL305".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "OCGY406_1991S_1999W_17437"
	when
        FactContainer( id == "OCGY406_1991S_1999W_17437", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "OCGY407_1980W_1990W_17439_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "OCGY407_1980W_1990W_17439", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("OCGY308,OCGY316,CHEM301".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "OCGY407_1980W_1990W_17439"
	when
        FactContainer( id == "OCGY407_1980W_1990W_17439", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "OCCH506_1993W_1993W_17389_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "OCCH506_1993W_1993W_17389", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "2", new HashSet(Arrays.asList("OCCH502,OCCH503".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "OCCH506_1993W_1993W_17389"
	when
        FactContainer( id == "OCCH506_1993W_1993W_17389", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "NURS564_1973W_1990W_17277_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "NURS564_1973W_1990W_17277", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("NURS510".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "NURS564_1973W_1990W_17277"
	when
        FactContainer( id == "NURS564_1973W_1990W_17277", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "NURS564_1991S_1999W_17277_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "NURS564_1991S_1999W_17277", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("NURS510".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "NURS564_1991S_1999W_17277"
	when
        FactContainer( id == "NURS564_1991S_1999W_17277", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "NURS567_1997W_2000S_17279_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "NURS567_1997W_2000S_17279", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("NURS560".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "NURS567_1997W_2000S_17279"
	when
        FactContainer( id == "NURS567_1997W_2000S_17279", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "NURS574_1973W_1990W_17282_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "NURS574_1973W_1990W_17282", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "4", new HashSet(Arrays.asList("NURS510,NURS522,NURS542,NURS546".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "NURS574_1973W_1990W_17282"
	when
        FactContainer( id == "NURS574_1973W_1990W_17282", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "NURS580_1982W_1990W_17285_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "NURS580_1982W_1990W_17285", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "3", new HashSet(Arrays.asList("NURS510,NURS542,NURS564".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "NURS580_1982W_1990W_17285"
	when
        FactContainer( id == "NURS580_1982W_1990W_17285", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "NURS588_1991S_1999W_17288_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "NURS588_1991S_1999W_17288", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "5", new HashSet(Arrays.asList("NURS522,NURS542,NURS543,NURS546,NURS548".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "NURS588_1991S_1999W_17288"
	when
        FactContainer( id == "NURS588_1991S_1999W_17288", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "NURS590_1982W_1990W_17290_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "NURS590_1982W_1990W_17290", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "3", new HashSet(Arrays.asList("NURS522,NURS542,NURS546".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "NURS590_1982W_1990W_17290"
	when
        FactContainer( id == "NURS590_1982W_1990W_17290", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "NURS597_1982W_1990W_17295_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "NURS597_1982W_1990W_17295", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("NURS546".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "NURS597_1982W_1990W_17295"
	when
        FactContainer( id == "NURS597_1982W_1990W_17295", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "NURS599_1970W_1990W_17297_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "NURS599_1970W_1990W_17297", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "3", new HashSet(Arrays.asList("NURS510,NURS522,NURS542".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "NURS599_1970W_1990W_17297"
	when
        FactContainer( id == "NURS599_1970W_1990W_17297", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "NURS599_1991S_2006S_17297_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "NURS599_1991S_2006S_17297", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "6", new HashSet(Arrays.asList("NURS501,NURS502,NURS503,NURS504,NURS550,NURS551".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "NURS599_1991S_2006S_17297"
	when
        FactContainer( id == "NURS599_1991S_2006S_17297", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "NURS608_1999W_2000S_17303_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "NURS608_1999W_2000S_17303", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0");
    	    	   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "3", new HashSet(Arrays.asList("NURS501,NURS503,NURS504".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "NURS608_1999W_2000S_17303"
	when
        FactContainer( id == "NURS608_1999W_2000S_17303", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		


rule "NURS522_1973W_1990W_17248_INIT"
    no-loop true
    lock-on-active true
    when 
        cont : FactContainer( id == "NURS522_1973W_1990W_17248", state == FactContainer.State.INIT, prop : propositionContainer, req : request )
    then
    	prop.setFunctionalRuleString("P0*P1");
    	    	   		
		SubsetProposition propositionP1 = new SubsetProposition("P1", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("STAT303,HCEP400,EDPS592".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP1.apply();
        prop.addProposition(propositionP1);      
		   		   		   		   		
		SubsetProposition propositionP0 = new SubsetProposition("P0", ComparisonOperator.EQUAL_TO, "1", new HashSet(Arrays.asList("NURS510".split("\\s*,\\s*"))),  req.getLuiIds() ); 
		propositionP0.apply();
        prop.addProposition(propositionP0);      
		   		   		   		    	
        cont.setState(FactContainer.State.DONE);
        
        update(cont);
	end



rule "NURS522_1973W_1990W_17248"
	when
        FactContainer( id == "NURS522_1973W_1990W_17248", state == FactContainer.State.DONE, prop : propositionContainer)

             Proposition( propositionName == "P0" && result == true ) from prop.propositions
                     and
                     Proposition( propositionName == "P1" && result == true ) from prop.propositions
            	then
   		prop.setRuleResult(true);
	end		
