package org.kuali.student.brms.runtime.ast.success
 
import org.kuali.student.brms.internal.common.runtime.ast.BooleanNode;
 
global org.kuali.student.brms.ruleexecution.runtime.report.ast.BooleanOperators booleanOperators;

rule "AND"
	#salience 1
	#no-loop true
	when
		n : BooleanNode( label == "*", leftNode.value == true, rightNode.value == true, leftNode.nodeMessage != "null", rightNode.nodeMessage != "null" )
	then
		//String logMessage = n.getLeftNode().getNodeMessage() + " AND " + n.getRightNode().getNodeMessage();
        String logMessage = n.getLeftNode().getNodeMessage() + " " + booleanOperators.getAndOperator() + " " + n.getRightNode().getNodeMessage();
		//n.setNodeMessage(logMessage);
		
		if(n.getParent() != null && ( (n.getLabel().equals("+") && n.getParent().getLabel().equals("*")) || (n.getLabel().equals("*") && n.getParent().getLabel().equals("+")))) {
		    logMessage = "(" + logMessage + ")";
		}
		n.setNodeMessage(logMessage);
		
		BooleanNode parent = n.getParent();
		if (parent != null){
			update(parent);
		}
end

rule "OR2"
	#no-loop true
	when
		n : BooleanNode( label == "+", leftNode.value == true, rightNode.value == true, leftNode.nodeMessage != "null", rightNode.nodeMessage != "null" )
	then
		//String logMessage = n.getLeftNode().getNodeMessage() + " OR " + n.getRightNode().getNodeMessage();
        String logMessage = n.getLeftNode().getNodeMessage() + " " + booleanOperators.getOrOperator() + " " + n.getRightNode().getNodeMessage();
		//n.setNodeMessage(logMessage);

		if(n.getParent() != null && ( (n.getLabel().equals("+") && n.getParent().getLabel().equals("*")) || (n.getLabel().equals("*") && n.getParent().getLabel().equals("+")))) {
		    logMessage = "(" + logMessage + ")";
		}
		n.setNodeMessage(logMessage);
		
		BooleanNode parent = n.getParent();
		if (parent != null){
			update(parent);
		}
end

rule "OR1"
	#no-loop true
	when
		n : BooleanNode( label == "+", (leftNode.value == false && rightNode.value == true && rightNode.nodeMessage != "null" ) || 
		(leftNode.value == true && rightNode.value == false && leftNode.nodeMessage != "null") )
	then
		String logMessage = "test";
		
		if (n.getLeftNode().getValue() == true)
			logMessage = n.getLeftNode().getNodeMessage();
		else if (n.getRightNode().getValue() == true)
			logMessage = n.getRightNode().getNodeMessage();
		
		n.setNodeMessage(logMessage);
		
		BooleanNode parent = n.getParent();
		if (parent != null){
			update(parent);
		}
end
