//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.21 at 02:14:18 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://student.kuali.org/wsdl/dictionary", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.kuali.student.core.dictionary.dto;
