
package org.kuali.student.lum.course.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.kuali.student.lum.course.dto.FormatInfo;

/**
 * This class was generated by Apache CXF 2.2
 * Tue May 18 13:33:13 PDT 2010
 * Generated source version: 2.2
 */

@XmlRootElement(name = "getCourseFormatsResponse", namespace = "http://student.kuali.org/wsdl/course")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getCourseFormatsResponse", namespace = "http://student.kuali.org/wsdl/course")

public class GetCourseFormatsResponse {

    @XmlElement(name = "return")
    private java.util.List<FormatInfo> _return;

    public java.util.List<FormatInfo> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<FormatInfo> new_return)  {
        this._return = new_return;
    }

}

