
package org.kuali.student.brms.rulemanagement.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.2
 * Tue Apr 07 16:13:12 EDT 2009
 * Generated source version: 2.2
 */

@XmlRootElement(name = "getBusinessRuleByAnchorList", namespace = "http://student.kuali.org/wsdl/brms/RuleManagement")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getBusinessRuleByAnchorList", namespace = "http://student.kuali.org/wsdl/brms/RuleManagement")

public class GetBusinessRuleByAnchorList {

    @XmlElement(name = "arg0")
    private java.util.List<org.kuali.student.brms.rulemanagement.dto.BusinessRuleAnchorInfo> arg0;

    public java.util.List<org.kuali.student.brms.rulemanagement.dto.BusinessRuleAnchorInfo> getArg0() {
        return this.arg0;
    }

    public void setArg0(java.util.List<org.kuali.student.brms.rulemanagement.dto.BusinessRuleAnchorInfo> newArg0)  {
        this.arg0 = newArg0;
    }

}

