
package org.kuali.student.lum.atp.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.kuali.student.lum.atp.dto.AtpSeasonalTypeInfo;

/**
 * This class was generated by Apache CXF 2.1.3
 * Wed Nov 19 10:43:53 EST 2008
 * Generated source version: 2.1.3
 */

@XmlRootElement(name = "findAtpSeasonalTypesResponse", namespace = "http://org.kuali.student/lum/atp")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "findAtpSeasonalTypesResponse", namespace = "http://org.kuali.student/lum/atp")

public class FindAtpSeasonalTypesResponse {

    @XmlElement(name = "return")
    private java.util.List<AtpSeasonalTypeInfo> _return;

    public java.util.List<AtpSeasonalTypeInfo> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<AtpSeasonalTypeInfo> new_return)  {
        this._return = new_return;
    }

}

