
package org.kuali.student.lum.atp.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.1.3
 * Wed Nov 19 10:43:53 EST 2008
 * Generated source version: 2.1.3
 */

@XmlRootElement(name = "removeDateRange", namespace = "http://org.kuali.student/lum/atp")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "removeDateRange", namespace = "http://org.kuali.student/lum/atp")

public class RemoveDateRange {

    @XmlElement(name = "dateRangeKey")
    private java.lang.String dateRangeKey;

    public java.lang.String getDateRangeKey() {
        return this.dateRangeKey;
    }

    public void setDateRangeKey(java.lang.String newDateRangeKey)  {
        this.dateRangeKey = newDateRangeKey;
    }

}

