
package org.kuali.student.lum.atp.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.1.3
 * Wed Nov 19 10:43:53 EST 2008
 * Generated source version: 2.1.3
 */

@XmlRootElement(name = "validateAtp", namespace = "http://org.kuali.student/lum/atp")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "validateAtp", namespace = "http://org.kuali.student/lum/atp", propOrder = {"validationType","atpInfo"})

public class ValidateAtp {

    @XmlElement(name = "validationType")
    private java.lang.String validationType;
    @XmlElement(name = "atpInfo")
    private org.kuali.student.lum.atp.dto.AtpInfo atpInfo;

    public java.lang.String getValidationType() {
        return this.validationType;
    }

    public void setValidationType(java.lang.String newValidationType)  {
        this.validationType = newValidationType;
    }

    public org.kuali.student.lum.atp.dto.AtpInfo getAtpInfo() {
        return this.atpInfo;
    }

    public void setAtpInfo(org.kuali.student.lum.atp.dto.AtpInfo newAtpInfo)  {
        this.atpInfo = newAtpInfo;
    }

}

