ALTER TABLE KSCO_REFERENCE RENAME CONSTRAINT SYS_C0033779 TO KSCO_REFERENCE_U1
/
ALTER TABLE KSOR_ORG_PERS_RELTN RENAME CONSTRAINT SYS_C0011691 TO KSOR_ORG_PERS_RELTN_U1
/
ALTER TABLE KSOR_ORG_POS_RESTR RENAME CONSTRAINT SYS_C0011701 TO KSOR_ORG_POS_RESTR_U1
/
ALTER TABLE KSST_OBJ_TYP_JN_OBJ_SUB_TYP RENAME CONSTRAINT SYS_C0011792 TO KSST_OBJ_TYP_JN_OBJ_SUB_TYP_U1
/
ALTER TABLE KSST_RC_JN_RC_FIELD RENAME CONSTRAINT SYS_C0011797 TO KSST_RC_JN_RC_FIELD_U1
/
ALTER TABLE KSST_STMT_JN_STMT RENAME CONSTRAINT SYS_C0011839 TO KSST_STMT_JN_STMT_U1
/