
package org.kuali.student.authz.service.jaxws;

import java.util.Map;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.kuali.student.poc.common.ws.binding.JaxbAttributeMapListAdapter;

/**
 * This class was generated by Apache CXF 2.1
 * Fri Aug 01 15:23:19 EDT 2008
 * Generated source version: 2.1
 */

@XmlRootElement(name = "assignQualifiedRoleToGroup", namespace = "http://student.kuali.org/authz")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "assignQualifiedRoleToGroup", namespace = "http://student.kuali.org/authz", propOrder = {"groupId","roleId","qualifications"})

public class AssignQualifiedRoleToGroup {

    @XmlElement(name = "groupId")
    private java.lang.String groupId;
    @XmlElement(name = "roleId")
    private java.lang.String roleId;
    @XmlElement(name = "qualifications")
    @XmlJavaTypeAdapter(JaxbAttributeMapListAdapter.class)
    private Map<String, String> qualifications;

    public java.lang.String getGroupId() {
        return this.groupId;
    }

    public void setGroupId(java.lang.String newGroupId)  {
        this.groupId = newGroupId;
    }

    public java.lang.String getRoleId() {
        return this.roleId;
    }

    public void setRoleId(java.lang.String newRoleId)  {
        this.roleId = newRoleId;
    }

    public Map<String,String> getQualifications() {
        return this.qualifications;
    }

    public void setQualifications(Map<String,String> newQualifications)  {
        this.qualifications = newQualifications;
    }

}

