
package org.kuali.student.authz.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.kuali.student.authz.dto.PermissionDTO;

/**
 * This class was generated by Apache CXF 2.1
 * Fri Aug 01 15:23:19 EDT 2008
 * Generated source version: 2.1
 */

@XmlRootElement(name = "getPermissionsForRoleResponse", namespace = "http://student.kuali.org/authz")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getPermissionsForRoleResponse", namespace = "http://student.kuali.org/authz")

public class GetPermissionsForRoleResponse {

    @XmlElement(name = "return")
    private java.util.List<PermissionDTO> _return;

    public java.util.List<PermissionDTO> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<PermissionDTO> new_return)  {
        this._return = new_return;
    }

}

