
package org.kuali.student.authz.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.kuali.student.authz.dto.PrincipalDTO;

/**
 * This class was generated by Apache CXF 2.1
 * Wed Aug 06 13:40:13 EDT 2008
 * Generated source version: 2.1
 */

@XmlRootElement(name = "getPrincipalsResponse", namespace = "http://student.kuali.org/authz")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getPrincipalsResponse", namespace = "http://student.kuali.org/authz")

public class GetPrincipalsResponse {

    @XmlElement(name = "return")
    private java.util.List<PrincipalDTO> _return;

    public java.util.List<PrincipalDTO> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<PrincipalDTO> new_return)  {
        this._return = new_return;
    }

}

