
package org.kuali.student.authz.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.1
 * Wed Aug 06 13:40:13 EDT 2008
 * Generated source version: 2.1
 */

@XmlRootElement(name = "getRoles", namespace = "http://student.kuali.org/authz")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getRoles", namespace = "http://student.kuali.org/authz")

public class GetRoles {


}

