
package org.kuali.student.authz.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.1
 * Fri Aug 01 15:23:19 EDT 2008
 * Generated source version: 2.1
 */

@XmlRootElement(name = "isPrincipalAuthorized", namespace = "http://student.kuali.org/authz")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "isPrincipalAuthorized", namespace = "http://student.kuali.org/authz", propOrder = {"principalId","namespaceName","permissionId"})

public class IsPrincipalAuthorized {

    @XmlElement(name = "principalId")
    private java.lang.String principalId;
    @XmlElement(name = "namespaceName")
    private java.lang.String namespaceName;
    @XmlElement(name = "permissionId")
    private java.lang.String permissionId;

    public java.lang.String getPrincipalId() {
        return this.principalId;
    }

    public void setPrincipalId(java.lang.String newPrincipalId)  {
        this.principalId = newPrincipalId;
    }

    public java.lang.String getNamespaceName() {
        return this.namespaceName;
    }

    public void setNamespaceName(java.lang.String newNamespaceName)  {
        this.namespaceName = newNamespaceName;
    }

    public java.lang.String getPermissionId() {
        return this.permissionId;
    }

    public void setPermissionId(java.lang.String newPermissionId)  {
        this.permissionId = newPermissionId;
    }

}

