DECLARE temp NUMBER;
BEGIN
SELECT COUNT(*) INTO temp FROM user_tables WHERE
table_name =
'KS_DB_VERSION';
IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KS_DB_VERSION CASCADE
CONSTRAINTS
PURGE'; END IF;
END;
/

CREATE
    TABLE KS_DB_VERSION
    (
        VERSION VARCHAR2(255),
        MODULE_NAME VARCHAR2(255),
        UPGRADE_TIME TIMESTAMP(6)
    )
/

