INSERT INTO KREW_DOC_TYP_T (DOC_TYP_ID,PARNT_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,ACTV_IND,CUR_IND,DOC_TYP_DESC,LBL,PREV_DOC_TYP_VER_NBR,DOC_HDR_ID,DOC_HDLR_URL,HELP_DEF_URL,DOC_SEARCH_HELP_URL,POST_PRCSR,GRP_ID,BLNKT_APPR_GRP_ID,BLNKT_APPR_PLCY,RPT_GRP_ID,RTE_VER_NBR,NOTIFY_ADDR,SEC_XML,EMAIL_XSL,APPL_ID,OBJ_ID,VER_NBR)
VALUES (krew_doc_hdr_s.nextval,'3009','SubjectCodeMaintenanceDocument','0',1,1,'','Subject Code','','','','','','','','','','','2','','','','','2e238fac-fac5-4d43-997b-17de60ba1caf','1')
/
UPDATE KREW_DOC_TYP_T SET PARNT_ID='2681',DOC_TYP_NM='StudentAdminMaintenanceDocument',DOC_TYP_VER_NBR='0',ACTV_IND=1,CUR_IND=1,DOC_TYP_DESC='',LBL='Kuali Student Admin Maintenance Document',PREV_DOC_TYP_VER_NBR='',DOC_HDR_ID='',DOC_HDLR_URL='${application.url}/kr/maintenance.do?methodToCall=docHandler',HELP_DEF_URL='',DOC_SEARCH_HELP_URL='',POST_PRCSR='org.kuali.rice.krad.workflow.postprocessor.KualiPostProcessor',GRP_ID='',BLNKT_APPR_GRP_ID='',BLNKT_APPR_PLCY='',RPT_GRP_ID='',RTE_VER_NBR='2',NOTIFY_ADDR='',SEC_XML='',EMAIL_XSL='',APPL_ID='',OBJ_ID='2F5FDC52-1BEC-E2D5-97B1-15C46D50A563',VER_NBR='11' WHERE DOC_TYP_ID = '3009'  AND VER_NBR = '10' 
/
UPDATE KREW_DOC_TYP_PLCY_RELN_T SET PLCY_NM=1,PLCY_VAL='',OBJ_ID='A8AD6F3B-70F9-EFB0-20F6-DEEB0AF59671',VER_NBR='11' WHERE DOC_TYP_ID = '3009'  AND DOC_PLCY_NM = 'LOOK_FUTURE'  AND VER_NBR = '10' 
/
UPDATE KREW_RTE_NODE_T SET DOC_TYP_ID='3009',NM='AdHoc',TYP='org.kuali.rice.kew.engine.node.InitialNode',RTE_MTHD_NM='',FNL_APRVR_IND=0,MNDTRY_RTE_IND=0,GRP_ID='',RTE_MTHD_CD='',ACTVN_TYP='S',BRCH_PROTO_ID='',NEXT_DOC_STAT='',VER_NBR='11' WHERE RTE_NODE_ID = '2962'  AND VER_NBR = '10' 
/
UPDATE KREW_RTE_NODE_CFG_PARM_T SET RTE_NODE_ID='2962',KEY_CD='contentFragment',VAL='<start name="AdHoc"/>' WHERE RTE_NODE_CFG_PARM_ID = '2619' 
/
UPDATE KREW_RTE_NODE_CFG_PARM_T SET RTE_NODE_ID='2962',KEY_CD='ruleSelector',VAL='Template' WHERE RTE_NODE_CFG_PARM_ID = '2620' 
/
UPDATE KREW_DOC_TYP_PROC_T SET DOC_TYP_ID='3009',INIT_RTE_NODE_ID='2962',NM='PRIMARY',INIT_IND=1,VER_NBR='11' WHERE DOC_TYP_PROC_ID = '2963'  AND VER_NBR = '10' 
/
INSERT INTO KREW_DOC_TYP_T (DOC_TYP_ID,PARNT_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,ACTV_IND,CUR_IND,DOC_TYP_DESC,LBL,PREV_DOC_TYP_VER_NBR,DOC_HDR_ID,DOC_HDLR_URL,HELP_DEF_URL,DOC_SEARCH_HELP_URL,POST_PRCSR,GRP_ID,BLNKT_APPR_GRP_ID,BLNKT_APPR_PLCY,RPT_GRP_ID,RTE_VER_NBR,NOTIFY_ADDR,SEC_XML,EMAIL_XSL,APPL_ID,OBJ_ID,VER_NBR)
VALUES (krew_doc_hdr_s.nextval,'3009','SubjectCodeJoinOrgMaintenanceDocument','0',1,1,'','Subject Code Join Org Type','','','','','','','','','','','2','','','','','59f17ad8-e7ed-4496-8146-1701474481c8','1')
/
UPDATE KREW_DOC_TYP_T SET PARNT_ID='2681',DOC_TYP_NM='StudentAdminMaintenanceDocument',DOC_TYP_VER_NBR='0',ACTV_IND=1,CUR_IND=1,DOC_TYP_DESC='',LBL='Kuali Student Admin Maintenance Document',PREV_DOC_TYP_VER_NBR='',DOC_HDR_ID='',DOC_HDLR_URL='${application.url}/kr/maintenance.do?methodToCall=docHandler',HELP_DEF_URL='',DOC_SEARCH_HELP_URL='',POST_PRCSR='org.kuali.rice.krad.workflow.postprocessor.KualiPostProcessor',GRP_ID='',BLNKT_APPR_GRP_ID='',BLNKT_APPR_PLCY='',RPT_GRP_ID='',RTE_VER_NBR='2',NOTIFY_ADDR='',SEC_XML='',EMAIL_XSL='',APPL_ID='',OBJ_ID='2F5FDC52-1BEC-E2D5-97B1-15C46D50A563',VER_NBR='12' WHERE DOC_TYP_ID = '3009'  AND VER_NBR = '11' 
/
UPDATE KREW_DOC_TYP_PLCY_RELN_T SET PLCY_NM=1,PLCY_VAL='',OBJ_ID='A8AD6F3B-70F9-EFB0-20F6-DEEB0AF59671',VER_NBR='12' WHERE DOC_TYP_ID = '3009'  AND DOC_PLCY_NM = 'LOOK_FUTURE'  AND VER_NBR = '11' 
/
UPDATE KREW_RTE_NODE_T SET DOC_TYP_ID='3009',NM='AdHoc',TYP='org.kuali.rice.kew.engine.node.InitialNode',RTE_MTHD_NM='',FNL_APRVR_IND=0,MNDTRY_RTE_IND=0,GRP_ID='',RTE_MTHD_CD='',ACTVN_TYP='S',BRCH_PROTO_ID='',NEXT_DOC_STAT='',VER_NBR='12' WHERE RTE_NODE_ID = '2962'  AND VER_NBR = '11' 
/
UPDATE KREW_RTE_NODE_CFG_PARM_T SET RTE_NODE_ID='2962',KEY_CD='contentFragment',VAL='<start name="AdHoc"/>' WHERE RTE_NODE_CFG_PARM_ID = '2619' 
/
UPDATE KREW_RTE_NODE_CFG_PARM_T SET RTE_NODE_ID='2962',KEY_CD='ruleSelector',VAL='Template' WHERE RTE_NODE_CFG_PARM_ID = '2620' 
/
UPDATE KREW_DOC_TYP_PROC_T SET DOC_TYP_ID='3009',INIT_RTE_NODE_ID='2962',NM='PRIMARY',INIT_IND=1,VER_NBR='12' WHERE DOC_TYP_PROC_ID = '2963'  AND VER_NBR = '11' 
/
INSERT INTO KREW_DOC_TYP_T (DOC_TYP_ID,PARNT_ID,DOC_TYP_NM,DOC_TYP_VER_NBR,ACTV_IND,CUR_IND,DOC_TYP_DESC,LBL,PREV_DOC_TYP_VER_NBR,DOC_HDR_ID,DOC_HDLR_URL,HELP_DEF_URL,DOC_SEARCH_HELP_URL,POST_PRCSR,GRP_ID,BLNKT_APPR_GRP_ID,BLNKT_APPR_PLCY,RPT_GRP_ID,RTE_VER_NBR,NOTIFY_ADDR,SEC_XML,EMAIL_XSL,APPL_ID,OBJ_ID,VER_NBR)
VALUES (krew_doc_hdr_s.nextval,'3009','SubjectCodeTypeMaintenanceDocument','0',1,1,'','Subject Code Type','','','','','','','','','','','2','','','','','41eb416c-155a-4f62-a12e-d5462e793e9b','1')
/
UPDATE KREW_DOC_TYP_T SET PARNT_ID='2681',DOC_TYP_NM='StudentAdminMaintenanceDocument',DOC_TYP_VER_NBR='0',ACTV_IND=1,CUR_IND=1,DOC_TYP_DESC='',LBL='Kuali Student Admin Maintenance Document',PREV_DOC_TYP_VER_NBR='',DOC_HDR_ID='',DOC_HDLR_URL='${application.url}/kr/maintenance.do?methodToCall=docHandler',HELP_DEF_URL='',DOC_SEARCH_HELP_URL='',POST_PRCSR='org.kuali.rice.krad.workflow.postprocessor.KualiPostProcessor',GRP_ID='',BLNKT_APPR_GRP_ID='',BLNKT_APPR_PLCY='',RPT_GRP_ID='',RTE_VER_NBR='2',NOTIFY_ADDR='',SEC_XML='',EMAIL_XSL='',APPL_ID='',OBJ_ID='2F5FDC52-1BEC-E2D5-97B1-15C46D50A563',VER_NBR='13' WHERE DOC_TYP_ID = '3009'  AND VER_NBR = '12' 
/
UPDATE KREW_DOC_TYP_PLCY_RELN_T SET PLCY_NM=1,PLCY_VAL='',OBJ_ID='A8AD6F3B-70F9-EFB0-20F6-DEEB0AF59671',VER_NBR='13' WHERE DOC_TYP_ID = '3009'  AND DOC_PLCY_NM = 'LOOK_FUTURE'  AND VER_NBR = '12' 
/
UPDATE KREW_RTE_NODE_T SET DOC_TYP_ID='3009',NM='AdHoc',TYP='org.kuali.rice.kew.engine.node.InitialNode',RTE_MTHD_NM='',FNL_APRVR_IND=0,MNDTRY_RTE_IND=0,GRP_ID='',RTE_MTHD_CD='',ACTVN_TYP='S',BRCH_PROTO_ID='',NEXT_DOC_STAT='',VER_NBR='13' WHERE RTE_NODE_ID = '2962'  AND VER_NBR = '12' 
/
UPDATE KREW_RTE_NODE_CFG_PARM_T SET RTE_NODE_ID='2962',KEY_CD='contentFragment',VAL='<start name="AdHoc"/>' WHERE RTE_NODE_CFG_PARM_ID = '2619' 
/
UPDATE KREW_RTE_NODE_CFG_PARM_T SET RTE_NODE_ID='2962',KEY_CD='ruleSelector',VAL='Template' WHERE RTE_NODE_CFG_PARM_ID = '2620' 
/
UPDATE KREW_DOC_TYP_PROC_T SET DOC_TYP_ID='3009',INIT_RTE_NODE_ID='2962',NM='PRIMARY',INIT_IND=1,VER_NBR='13' WHERE DOC_TYP_PROC_ID = '2963'  AND VER_NBR = '12' 
/