
package org.kuali.student.poc.personidentity.person.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by the CXF 2.0.4-incubator
 * Thu Mar 27 11:42:24 EDT 2008
 * Generated source version: 2.0.4-incubator
 * 
 */

@XmlRootElement(name = "createPersonAttributeSetType", namespace = "http://student.kuali.org/poc/wsdl/personidentity/person/service")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "createPersonAttributeSetType", namespace = "http://student.kuali.org/poc/wsdl/personidentity/person/service")

public class CreatePersonAttributeSetType {

    @XmlElement(name = "attributeSetDTO")
    private org.kuali.student.poc.personidentity.person.dto.PersonAttributeSetTypeInfo attributeSetDTO;

    public org.kuali.student.poc.personidentity.person.dto.PersonAttributeSetTypeInfo getAttributeSetDTO() {
        return this.attributeSetDTO;
    }
    
    public void setAttributeSetDTO( org.kuali.student.poc.personidentity.person.dto.PersonAttributeSetTypeInfo newAttributeSetDTO ) {
        this.attributeSetDTO = newAttributeSetDTO;
    }
    
}

