

-----------------------------------------------------------------------------
-- KSEN_APPT
-----------------------------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
	SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_APPT';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_APPT CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_APPT
(
      ID VARCHAR2(255)
        , OBJ_ID VARCHAR2(255)
        , APPT_TYPE VARCHAR2(255) NOT NULL
        , APPT_STATE VARCHAR2(255) NOT NULL
        , PERS_ID VARCHAR2(255) NOT NULL
        , SLOT_ID VARCHAR2(255) NOT NULL
        , EFF_DT TIMESTAMP
        , EXPIR_DT TIMESTAMP
        , VER_NBR NUMBER(19) NOT NULL
        , CREATETIME TIMESTAMP NOT NULL
        , CREATEID VARCHAR2(255) NOT NULL
        , UPDATETIME TIMESTAMP
        , UPDATEID VARCHAR2(255)
    

)
/

ALTER TABLE KSEN_APPT
    ADD CONSTRAINT KSEN_APPTP1
PRIMARY KEY (ID)
/


CREATE INDEX KSEN_APPT_I1 
  ON KSEN_APPT 
  (APPT_TYPE)
/
CREATE INDEX KSEN_APPT_I2 
  ON KSEN_APPT 
  (PERS_ID)
/
CREATE INDEX KSEN_APPT_IF1 
  ON KSEN_APPT 
  (SLOT_ID)
/





-----------------------------------------------------------------------------
-- KSEN_APPT_ATTR
-----------------------------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
	SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_APPT_ATTR';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_APPT_ATTR CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_APPT_ATTR
(
      ID VARCHAR2(255)
        , OBJ_ID VARCHAR2(36)
        , ATTR_KEY VARCHAR2(255)
        , ATTR_VALUE VARCHAR2(4000)
        , OWNER_ID VARCHAR2(255)
    

)
/

ALTER TABLE KSEN_APPT_ATTR
    ADD CONSTRAINT KSEN_APPT_ATTRP1
PRIMARY KEY (ID)
/


CREATE INDEX KSEN_APPT_ATTR_IF1 
  ON KSEN_APPT_ATTR 
  (OWNER_ID)
/





-----------------------------------------------------------------------------
-- KSEN_APPT_SLOT
-----------------------------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
	SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_APPT_SLOT';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_APPT_SLOT CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_APPT_SLOT
(
      OBJ_ID VARCHAR2(255)
        , APPT_SLOT_TYPE VARCHAR2(255) NOT NULL
        , APPT_SLOT_STATE VARCHAR2(255) NOT NULL
        , START_DT TIMESTAMP NOT NULL
        , END_DT TIMESTAMP
        , VER_NBR NUMBER(19) NOT NULL
        , CREATETIME TIMESTAMP NOT NULL
        , CREATEID VARCHAR2(255) NOT NULL
        , UPDATETIME TIMESTAMP
        , UPDATEID VARCHAR2(255)
        , ID VARCHAR2(255)
        , APPT_WINDOW_ID VARCHAR2(255) NOT NULL
    

)
/

ALTER TABLE KSEN_APPT_SLOT
    ADD CONSTRAINT KSEN_APPT_SLOTP1
PRIMARY KEY (ID)
/


CREATE INDEX KSEN_APPT_SLOT_IF1 
  ON KSEN_APPT_SLOT 
  (APPT_WINDOW_ID)
/





-----------------------------------------------------------------------------
-- KSEN_APPT_SLOT_ATTR
-----------------------------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
	SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_APPT_SLOT_ATTR';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_APPT_SLOT_ATTR CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_APPT_SLOT_ATTR
(
      ID VARCHAR2(255)
        , OBJ_ID VARCHAR2(36)
        , ATTR_KEY VARCHAR2(255)
        , ATTR_VALUE VARCHAR2(4000)
        , OWNER_ID VARCHAR2(255)
    

)
/

ALTER TABLE KSEN_APPT_SLOT_ATTR
    ADD CONSTRAINT KSEN_APPT_SLOT_ATTRP1
PRIMARY KEY (ID)
/


CREATE INDEX KSEN_APPT_SLOT_ATTR_IF1 
  ON KSEN_APPT_SLOT_ATTR 
  (OWNER_ID)
/





-----------------------------------------------------------------------------
-- KSEN_APPT_WINDOW
-----------------------------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
	SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_APPT_WINDOW';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_APPT_WINDOW CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_APPT_WINDOW
(
      ID VARCHAR2(255)
        , OBJ_ID VARCHAR2(255)
        , APPT_WINDOW_TYPE VARCHAR2(255) NOT NULL
        , APPT_WINDOW_STATE VARCHAR2(255) NOT NULL
        , NAME VARCHAR2(255) NOT NULL
        , DESCR_PLAIN VARCHAR2(4000)
        , DESCR_FORMATTED VARCHAR2(4000)
        , START_DT TIMESTAMP
        , END_DT TIMESTAMP
        , SR_WEEKDAYS VARCHAR2(255)
        , SR_START_TIME_MS NUMBER(22)
        , SR_END_TIME_MS NUMBER(22)
        , SR_START_INTVL_DUR_TYPE VARCHAR2(255)
        , SR_START_INTVL_TIME_QTY NUMBER(22)
        , SR_DUR_TYPE VARCHAR2(255)
        , SR_DUR_TIME_QTY NUMBER(22)
        , PRD_MSTONE_ID VARCHAR2(255)
        , ASSIGNED_POPULATION_ID VARCHAR2(255)
        , ASSIGNED_ORDER_TYPE VARCHAR2(255)
        , MAX_APPT_PER_SLOT NUMBER(22)
        , VER_NBR NUMBER(19) NOT NULL
        , CREATETIME TIMESTAMP NOT NULL
        , CREATEID VARCHAR2(255) NOT NULL
        , UPDATETIME TIMESTAMP
        , UPDATEID VARCHAR2(255)
    

)
/

ALTER TABLE KSEN_APPT_WINDOW
    ADD CONSTRAINT KSEN_APPT_WINDOWP1
PRIMARY KEY (ID)
/


CREATE INDEX KSEN_APPT_WINDOW_I1 
  ON KSEN_APPT_WINDOW 
  (APPT_WINDOW_TYPE)
/
CREATE INDEX KSEN_APPT_WINDOW_I2 
  ON KSEN_APPT_WINDOW 
  (ASSIGNED_POPULATION_ID)
/
CREATE INDEX KSEN_APPT_WINDOW_I3 
  ON KSEN_APPT_WINDOW 
  (PRD_MSTONE_ID)
/





-----------------------------------------------------------------------------
-- KSEN_APPT_WINDOW_ATTR
-----------------------------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
	SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_APPT_WINDOW_ATTR';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_APPT_WINDOW_ATTR CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_APPT_WINDOW_ATTR
(
      ID VARCHAR2(255)
        , OBJ_ID VARCHAR2(36)
        , ATTR_KEY VARCHAR2(255)
        , ATTR_VALUE VARCHAR2(4000)
        , OWNER_ID VARCHAR2(255)
    

)
/

ALTER TABLE KSEN_APPT_WINDOW_ATTR
    ADD CONSTRAINT KSEN_APPT_WINDOW_ATTRP1
PRIMARY KEY (ID)
/


CREATE INDEX KSEN_APPT_WINDOW_ATTR_IF1 
  ON KSEN_APPT_WINDOW_ATTR 
  (OWNER_ID)
/

