
package org.kuali.student.poc.wsdl.personidentity.person.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by the CXF 2.0.4-incubator
 * Thu Mar 27 10:13:52 EDT 2008
 * Generated source version: 2.0.4-incubator
 * 
 */

@XmlRootElement(name = "deletePersonRelation", namespace = "http://student.kuali.org/poc/wsdl/personidentity/person")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "deletePersonRelation", namespace = "http://student.kuali.org/poc/wsdl/personidentity/person")

public class DeletePersonRelation {

    @XmlElement(name = "personRelationId")
    private java.lang.Long personRelationId;

    public java.lang.Long getPersonRelationId() {
        return this.personRelationId;
    }
    
    public void setPersonRelationId( java.lang.Long newPersonRelationId ) {
        this.personRelationId = newPersonRelationId;
    }
    
}

