
package org.kuali.student.poc.wsdl.personidentity.person.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by the CXF 2.0.4-incubator
 * Thu Mar 27 10:13:52 EDT 2008
 * Generated source version: 2.0.4-incubator
 * 
 */

@XmlRootElement(name = "updatePerson", namespace = "http://student.kuali.org/poc/wsdl/personidentity/person")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updatePerson", namespace = "http://student.kuali.org/poc/wsdl/personidentity/person")

public class UpdatePerson {

    @XmlElement(name = "personId")
    private java.lang.Long personId;
    @XmlElement(name = "personUpdateInfo")
    private org.kuali.student.poc.xsd.personidentity.person.dto.PersonUpdateInfo personUpdateInfo;

    public java.lang.Long getPersonId() {
        return this.personId;
    }
    
    public void setPersonId( java.lang.Long newPersonId ) {
        this.personId = newPersonId;
    }
    
    public org.kuali.student.poc.xsd.personidentity.person.dto.PersonUpdateInfo getPersonUpdateInfo() {
        return this.personUpdateInfo;
    }
    
    public void setPersonUpdateInfo( org.kuali.student.poc.xsd.personidentity.person.dto.PersonUpdateInfo newPersonUpdateInfo ) {
        this.personUpdateInfo = newPersonUpdateInfo;
    }
    
}

