
package org.kuali.student.poc.wsdl.learningunit.luipersonrelation.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.kuali.student.poc.xsd.learningunit.luipersonrelation.dto.LuiPersonRelationTypeInfo;

/**
 * This class was generated by the CXF 2.0.4-incubator
 * Mon Apr 28 11:57:54 EDT 2008
 * Generated source version: 2.0.4-incubator
 * 
 */

@XmlRootElement(name = "findLuiPersonRelationTypesResponse", namespace = "http://student.kuali.org/poc/wsdl/learningunit/luipersonrelation")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "findLuiPersonRelationTypesResponse", namespace = "http://student.kuali.org/poc/wsdl/learningunit/luipersonrelation")

public class FindLuiPersonRelationTypesResponse {

    @XmlElement(name = "return")
    private java.util.List<LuiPersonRelationTypeInfo> _return;

    public java.util.List<LuiPersonRelationTypeInfo> get_return() {
        return this._return;
    }
    
    public void set_return( java.util.List<LuiPersonRelationTypeInfo> new_return ) {
        this._return = new_return;
    }
    
}

