
package org.kuali.student.lum.lrc.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.2
 * Tue Apr 21 14:42:30 PDT 2009
 * Generated source version: 2.2
 */

@XmlRootElement(name = "getCreditsByKeyList", namespace = "http://service.lrc.lum.student.kuali.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getCreditsByKeyList", namespace = "http://service.lrc.lum.student.kuali.org/")

public class GetCreditsByKeyList {

    @XmlElement(name = "arg0")
    private java.util.List<java.lang.String> arg0;

    public java.util.List<java.lang.String> getArg0() {
        return this.arg0;
    }

    public void setArg0(java.util.List<java.lang.String> newArg0)  {
        this.arg0 = newArg0;
    }

}

