
package org.kuali.student.lum.lrc.service.jaxws;

import java.util.ArrayList;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.kuali.student.lum.lrc.dto.GradeTypeInfo;

/**
 * This class was generated by Apache CXF 2.2
 * Tue Apr 21 14:42:30 PDT 2009
 * Generated source version: 2.2
 */

@XmlRootElement(name = "getGradeTypesResponse", namespace = "http://service.lrc.lum.student.kuali.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getGradeTypesResponse", namespace = "http://service.lrc.lum.student.kuali.org/")

public class GetGradeTypesResponse {

    @XmlElement(name = "return")
    private java.util.List<GradeTypeInfo> _return;

    public java.util.List<GradeTypeInfo> getReturn() {
        if (_return == null) {
            _return = new ArrayList<GradeTypeInfo>(0);
        }
        return this._return;
    }

    public void setReturn(java.util.List<GradeTypeInfo> new_return)  {
        this._return = new_return;
    }

}

