Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12286','10004',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12288','10004',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12290','10004',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12291','10004',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12293','10004',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12295','10004',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12297','10004',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12310','10004',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12311','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12312','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12315','10006',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12317','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12320','10013',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12322','10009',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12324','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12326','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12327','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12329','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12333','10000',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12334','10013',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12337','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12338','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12341','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12347','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12349','10006',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12351','10006',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12358','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12360','10001',4,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12363','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12366','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12369','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12371','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12372','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12375','10013',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12384','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12386','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12389','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12391','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12394','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12399','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12404','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12407','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12408','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12411','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12414','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12417','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12419','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12422','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12425','10013',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12429','10013',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12434','10000',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12436','10000',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12439','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12441','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12444','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12446','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12448','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12450','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12455','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12456','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12458','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12461','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12465','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12468','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12471','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12474','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12478','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12481','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12483','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12486','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12491','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12495','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12498','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12500','10009',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12501','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12509','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12510','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12513','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12516','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12519','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12521','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12527','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12531','10009',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12536','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12539','10006',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12543','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12547','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12550','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12551','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12554','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12558','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12560','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12561','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12564','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12565','10000',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12568','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12576','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12579','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12581','10013',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12584','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12591','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12597','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12600','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12603','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12606','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12609','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12610','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12614','10006',4,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12616','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12620','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12622','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12624','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12628','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12631','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12636','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12641','10009',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12642','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12646','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12650','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12655','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12657','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12677','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12682','10009',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12686','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12689','10006',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12693','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12696','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12700','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12702','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12704','10001',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12725','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12730','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12734','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12736','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12738','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12741','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12743','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12749','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12756','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12792','10011',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12794','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12796','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12798','10002',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12800','10011',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12803','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12805','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12807','10011',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12809','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12811','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12816','10007',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12818','10007',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12821','10011',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12825','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12829','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12832','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12837','10011',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12839','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12843','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12847','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12848','10000',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12852','10013',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12856','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12858','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12860','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12862','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12889','10011',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12892','10011',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12896','10011',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12898','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12899','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12901','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12906','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12289','10004',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12292','10004',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12294','10004',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12287','10004',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12296','10004',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12298','10004',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12299','10013',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12300','10004',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12301','10004',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12302','10004',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12303','10004',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12304','10004',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12305','10004',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12306','10004',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12307','10004',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12308','10004',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12309','10004',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12313','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12314','10006',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12316','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12318','10013',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12319','10001',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12321','10006',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12323','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12325','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12328','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12330','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12331','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12332','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12335','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12336','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12339','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12340','10013',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12342','10006',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12343','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12344','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12345','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12346','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12348','10006',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12350','10006',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12352','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12353','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12354','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12355','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12356','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12357','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12359','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12361','10000',4,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12362','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12364','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12365','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12367','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12368','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12370','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12373','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12374','10000',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12376','10009',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12377','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12378','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12379','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12380','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12381','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12382','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12383','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12385','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12387','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12388','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12390','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12392','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12393','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12395','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12396','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12397','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12398','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12400','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12401','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12402','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12403','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12405','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12406','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12409','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12410','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12412','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12413','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12415','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12416','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12418','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12420','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12421','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12423','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12424','10000',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12427','10013',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12431','10013',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12433','10013',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12438','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12440','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12443','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12445','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12447','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12449','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12452','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12454','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12457','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12460','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12463','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12464','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12467','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12469','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12472','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12476','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12479','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12482','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12484','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12487','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12489','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12492','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12493','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12496','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12502','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12504','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12505','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12508','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12511','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12515','10000',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12517','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12518','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12522','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12524','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12525','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12528','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12529','10000',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12535','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12537','10006',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12540','10006',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12542','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12544','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12546','10006',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12549','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12552','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12553','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12556','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12559','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12562','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12563','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12566','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12567','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12569','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12570','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12571','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12572','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12573','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12574','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12575','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12577','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12578','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12580','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12582','10013',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12586','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12588','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12590','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12592','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12596','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12598','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12604','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12608','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12612','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12617','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12619','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12621','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12626','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12630','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12633','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12634','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12635','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12638','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12640','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12644','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12645','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12648','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12652','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12654','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12656','10013',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12658','10013',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12660','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12661','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12663','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12664','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12666','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12667','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12668','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12670','10004',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12671','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12673','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12674','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12676','10009',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12678','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12681','10000',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12684','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12687','10006',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12691','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12692','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12695','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12698','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12699','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12703','10001',4,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12705','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12707','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12708','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12710','10009',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12711','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12712','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12714','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12715','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12718','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12720','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12721','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12723','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12726','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12732','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12737','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12740','10001',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12742','10002',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12744','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12745','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12746','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12747','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12748','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12750','10004',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12751','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12752','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12753','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12754','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12755','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12757','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12758','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12759','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12761','10009',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12762','10000',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12764','10009',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12765','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12766','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12768','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12769','10013',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12771','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12772','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12774','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12775','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12777','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12779','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12780','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12781','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12783','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12784','10006',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12785','10006',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12786','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12788','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12790','10011',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12793','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12795','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12799','10011',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12801','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12802','10011',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12804','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12806','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12808','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12810','10011',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12812','10007',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12813','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12814','10007',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12815','10007',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12817','10007',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12819','10007',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12820','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12822','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12823','10011',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12826','10002',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12828','10011',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12830','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12836','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12841','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12845','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12850','10005',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12854','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12857','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12859','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12861','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12863','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12865','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12866','10002',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12868','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12870','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12871','10002',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12872','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12874','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12876','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12877','10011',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12879','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12881','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12882','10011',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12883','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12886','10011',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12888','10011',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12890','10011',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12893','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12895','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12897','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12900','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12902','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12903','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12904','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12905','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12907','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12909','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12911','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12426','10000',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12428','10000',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12430','10000',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12432','10000',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12435','10013',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12437','10013',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12442','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12451','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12453','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12459','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12462','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12466','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12470','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12473','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12475','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12477','10001',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12480','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12485','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12488','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12490','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12494','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12497','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12499','10013',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12503','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12506','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12507','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12512','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12514','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12520','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12523','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12526','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12530','10001',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12532','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12533','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12534','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12538','10006',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12541','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12545','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12548','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12555','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12557','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12583','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12585','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12587','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12589','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12593','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12594','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12595','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12599','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12601','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12602','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12605','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12607','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12611','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12613','10006',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12615','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12618','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12623','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12625','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12627','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12629','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12632','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12637','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12639','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12643','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12647','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12649','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12651','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12653','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12659','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12662','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12665','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12669','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12672','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12675','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12679','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12680','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12683','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12685','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12688','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12690','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12694','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12697','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12701','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12706','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12709','10001',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12713','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12716','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12717','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12719','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12722','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12724','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12727','10013',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12728','10013',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12729','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12731','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12733','10006',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12735','10000',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12739','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12760','10006',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12763','10013',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12767','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12770','10013',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12773','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12776','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12778','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12782','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12787','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12789','10011',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12791','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12797','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12824','10011',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12827','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12831','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12833','10011',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12834','10011',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12835','10011',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12838','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12840','10002',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12842','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12844','10005',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12846','10000',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12849','10011',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12851','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12853','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12855','10011',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12864','10011',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12867','10002',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12869','10011',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12873','10002',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12875','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12878','10011',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12880','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12884','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12885','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12887','10009',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12891','10011',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12894','10013',3,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12910','10013',2,null)
/
Insert into KRMS_TERM_T (TERM_ID,TERM_SPEC_ID,VER_NBR,DESC_TXT) values ('KS-KRMS-TERM-12908','10013',2,null)
/