-- non-UMD reference data
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (ACTV,COLLECTION_NM,KRMS_DSCR_TYP,KRMS_OBJ_ID,NMSPC_CD,REF_DSCR_TYP,REF_OBJ_ID,REF_OBJ_KRMS_OBJ_ID,VER_NBR) values ('N',null,'Agenda','KS-KRMS-AGENDA-10146','KS-SYS','kuali.lui.type.course.offering','c1020295-e80b-47eb-87c5-70c8f20ad153','KS-KRMS-REF-OBJ-KRMS-OBJ-10146',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (ACTV,COLLECTION_NM,KRMS_DSCR_TYP,KRMS_OBJ_ID,NMSPC_CD,REF_DSCR_TYP,REF_OBJ_ID,REF_OBJ_KRMS_OBJ_ID,VER_NBR) values ('N',null,'Agenda','KS-KRMS-AGENDA-10143','KS-SYS','kuali.lui.type.course.offering','c76c4e23-9d41-4c0e-b8bd-d51b58e01d99','KS-KRMS-REF-OBJ-KRMS-OBJ-10143',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (ACTV,COLLECTION_NM,KRMS_DSCR_TYP,KRMS_OBJ_ID,NMSPC_CD,REF_DSCR_TYP,REF_OBJ_ID,REF_OBJ_KRMS_OBJ_ID,VER_NBR) values ('N',null,'Agenda','KS-KRMS-AGENDA-10144','KS-SYS','kuali.lui.type.course.offering','d3d3a31f-b1d4-4c60-a9c9-945c49d42e28','KS-KRMS-REF-OBJ-KRMS-OBJ-10144',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (ACTV,COLLECTION_NM,KRMS_DSCR_TYP,KRMS_OBJ_ID,NMSPC_CD,REF_DSCR_TYP,REF_OBJ_ID,REF_OBJ_KRMS_OBJ_ID,VER_NBR) values ('N',null,'Agenda','KS-KRMS-AGENDA-10147','KS-SYS','kuali.lui.type.course.offering','2b7a849d-f5af-45e1-933a-fb5ae4815771','KS-KRMS-REF-OBJ-KRMS-OBJ-10147',1)
/
INSERT INTO KRMS_REF_OBJ_KRMS_OBJ_T (ACTV,COLLECTION_NM,KRMS_DSCR_TYP,KRMS_OBJ_ID,NMSPC_CD,REF_DSCR_TYP,REF_OBJ_ID,REF_OBJ_KRMS_OBJ_ID,VER_NBR) VALUES ('N',NULL,'Agenda','KS-KRMS-AGENDA-10148','KS-SYS','kuali.lui.type.course.offering','694c192c-298c-461d-ba71-8fdab674409f','KS-KRMS-REF-OBJ-KRMS-OBJ-10148',1)
/
Insert into KRMS_REF_OBJ_KRMS_OBJ_T (ACTV,COLLECTION_NM,KRMS_DSCR_TYP,KRMS_OBJ_ID,NMSPC_CD,REF_DSCR_TYP,REF_OBJ_ID,REF_OBJ_KRMS_OBJ_ID,VER_NBR) values ('N',null,'Agenda','KS-KRMS-AGENDA-10145','KS-SYS','kuali.lui.type.course.offering','d4c2352c-00b7-4bc3-9fa4-ae0dd99e3206','KS-KRMS-REF-OBJ-KRMS-OBJ-10145',1)
/
