package org.kuali.student.rules.runtime.ast
 
import org.kuali.student.rules.runtime.ast.BooleanNode;
import org.kuali.student.rules.runtime.ast.BinaryTree;
 
rule "OR"
	#salience 1
	#no-loop true
	when
		n : BooleanNode( label == "+", leftNode.value == false, rightNode.value == false, leftNode.ruleFailureMessage != "null", rightNode.ruleFailureMessage != "null" )
	then
		String logMessage = n.getLeftNode().getRuleFailureMessage() + " OR " + n.getRightNode().getRuleFailureMessage();
		n.setRuleFailureMessage(logMessage);
		#System.out.println( n.getRuleFailureMessage() + "   rule OR");
		#System.out.println( logMessage );
		
		BooleanNode parent = n.getParent();
		if (parent != null){
			update(parent);
		}
end


rule "AND2"
	#no-loop true
	when
		n : BooleanNode( label == "*", leftNode.value == false, rightNode.value == false, leftNode.ruleFailureMessage != "null", rightNode.ruleFailureMessage != "null" )
	then
		String logMessage = n.getLeftNode().getRuleFailureMessage() + " AND " + n.getRightNode().getRuleFailureMessage();
		n.setRuleFailureMessage(logMessage);
		#System.out.println( logMessage + "   rule AND2");
		
		BooleanNode parent = n.getParent();
		if (parent != null){
			update(parent);
		}
end

rule "AND1"
	#no-loop true
	when
		n : BooleanNode( label == "*", (leftNode.value == false && rightNode.value == true && leftNode.ruleFailureMessage != "null" ) || 
		(leftNode.value == true && rightNode.value == false && rightNode.ruleFailureMessage != "null") )
	then
		String logMessage = "test";
		
		if (n.getLeftNode().getValue() == false)
			logMessage = n.getLeftNode().getRuleFailureMessage();
		else if (n.getRightNode().getValue() == false)
			logMessage = n.getRightNode().getRuleFailureMessage();
		
		n.setRuleFailureMessage(logMessage);
		#System.out.println( logMessage + "   rule AND1");
		
		BooleanNode parent = n.getParent();
		if (parent != null){
			update(parent);
		}
end
