/*
 * Copyright 2009 The Kuali Foundation Licensed under the
 * Educational Community License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License. You may
 * obtain a copy of the License at
 * 
 * http://www.osedu.org/licenses/ECL-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an "AS IS"
 * BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */
package org.kuali.student.lum.lu.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.1.4
 * Tue Feb 24 12:25:30 EST 2009
 * Generated source version: 2.1.4
 */

@XmlRootElement(name = "createClu", namespace = "http://student.kuali.org/wsdl/lu")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "createClu", namespace = "http://student.kuali.org/wsdl/lu", propOrder = {"luTypeKey","cluInfo"})

public class CreateClu {

    @XmlElement(name = "luTypeKey")
    private java.lang.String luTypeKey;
    @XmlElement(name = "cluInfo")
    private org.kuali.student.lum.lu.dto.CluInfo cluInfo;

    public java.lang.String getLuTypeKey() {
        return this.luTypeKey;
    }

    public void setLuTypeKey(java.lang.String newLuTypeKey)  {
        this.luTypeKey = newLuTypeKey;
    }

    public org.kuali.student.lum.lu.dto.CluInfo getCluInfo() {
        return this.cluInfo;
    }

    public void setCluInfo(org.kuali.student.lum.lu.dto.CluInfo newCluInfo)  {
        this.cluInfo = newCluInfo;
    }

}

