
package org.kuali.student.core.proposal.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.2
 * Wed Sep 02 14:48:07 EDT 2009
 * Generated source version: 2.2
 */

@XmlRootElement(name = "updateProposalDocRelationResponse", namespace = "http://student.kuali.org/wsdl/proposal")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateProposalDocRelationResponse", namespace = "http://student.kuali.org/wsdl/proposal")

public class UpdateProposalDocRelationResponse {

    @XmlElement(name = "return")
    private org.kuali.student.core.proposal.dto.ProposalDocRelationInfo _return;

    public org.kuali.student.core.proposal.dto.ProposalDocRelationInfo getReturn() {
        return this._return;
    }

    public void setReturn(org.kuali.student.core.proposal.dto.ProposalDocRelationInfo new_return)  {
        this._return = new_return;
    }

}

