TRUNCATE TABLE KSLU_CLU_FEE_JN_CLU_FEE_REC DROP STORAGE
/
INSERT INTO KSLU_CLU_FEE_JN_CLU_FEE_REC (CLU_FEE_ID,CLU_FEE_REC_ID)
  VALUES ('FEE-2','FEE-REC-3')
/
INSERT INTO KSLU_CLU_FEE_JN_CLU_FEE_REC (CLU_FEE_ID,CLU_FEE_REC_ID)
  VALUES ('FEE-1','FEE-REC-2')
/
INSERT INTO KSLU_CLU_FEE_JN_CLU_FEE_REC (CLU_FEE_ID,CLU_FEE_REC_ID)
  VALUES ('FEE-1','FEE-REC-1')
/
