DECLARE TEMP NUMBER;
BEGIN
  SELECT COUNT(*) INTO TEMP FROM USER_TABLES WHERE TABLE_NAME = 'KSEN_CODE_GENERATOR_LOCKS';
   IF TEMP > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_CODE_GENERATOR_LOCKS CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_CODE_GENERATOR_LOCKS
(
    ID                   VARCHAR2(255) NOT NULL ,
    OBJ_ID               VARCHAR2(36) NULL ,
    CODE                 VARCHAR2(255) NOT NULL ,
    UNIQUE_KEY           VARCHAR2(255) NOT NULL ,
    NAMESPACE            VARCHAR2(255) NOT NULL
)
/

ALTER TABLE KSEN_CODE_GENERATOR_LOCKS
   ADD CONSTRAINT  KSEN_CODE_GENERATOR_LOCKS PRIMARY KEY (ID)
/

CREATE UNIQUE INDEX KSEN_CODE_GENERATOR_LOCKS_I1 ON KSEN_CODE_GENERATOR_LOCKS
(CODE   ASC,UNIQUE_KEY   ASC,NAMESPACE   ASC)
/