-- KSENROLL-10419 Adding missing indexes on some tables to speed up our queries

CREATE INDEX KSEN_SCHED_REF_OBJECT_IX1 ON KSEN_SCHED_REF_OBJECT (REF_OBJECT_ID)
/
create index KSEN_LUI_IDENT_IX1 on KSEN_LUI_IDENT (LUI_CD)
/
create index KSEN_LUI_IDENT_IX2 on KSEN_LUI_IDENT (DIVISION)
/
create index KSEN_SCHED_RQST_IX1 on KSEN_SCHED_RQST (SCHED_RQST_SET_ID)
/
