ALTER TABLE KSEN_SCHED_RQST DROP (REF_OBJECT_ID, REF_OBJECT_TYPE)
/
ALTER TABLE KSEN_SCHED_RQST ADD SCHED_RQST_SET_ID VARCHAR2(255 BYTE)
/
ALTER TABLE KSEN_SCHED_RQST ADD SCHED_ID VARCHAR2(255 BYTE)
/