DECLARE
    TABLE_ID VARCHAR2(100)    := 'KRIM_ROLE_MBR_T';
    SEQUENCE_ID VARCHAR2(100) := 'KRIM_ROLE_MBR_ID_S';
    PK VARCHAR2(100)          := 'ROLE_MBR_ID';
    STATEMENT VARCHAR2(2000);
    maxid NUMBER;
    cval NUMBER;
BEGIN
    STATEMENT:= 'SELECT MAX(TO_NUMBER('||TABLE_ID||'.'||PK||')) FROM '||TABLE_ID||' WHERE '||TABLE_ID||'.'||PK||' NOT LIKE ''KR%''';
    EXECUTE IMMEDIATE (STATEMENT) INTO maxid;
    STATEMENT := 'SELECT '|| SEQUENCE_ID ||'.NEXTVAL FROM DUAL';
    EXECUTE IMMEDIATE(STATEMENT) INTO cval;
    IF cval!=maxid
    THEN
    STATEMENT := 'ALTER SEQUENCE '|| SEQUENCE_ID || ' INCREMENT BY ' || (maxid-cval);
    EXECUTE IMMEDIATE(STATEMENT);
    STATEMENT := 'SELECT '|| SEQUENCE_ID ||'.NEXTVAL FROM DUAL';
    EXECUTE IMMEDIATE(STATEMENT) INTO cval;
    STATEMENT := 'ALTER SEQUENCE '|| SEQUENCE_ID || ' INCREMENT BY 1';
    EXECUTE IMMEDIATE(STATEMENT);
    END IF;
END;
/
DECLARE
    TABLE_ID VARCHAR2(100)    := 'KRIM_PERM_ATTR_DATA_T';
    SEQUENCE_ID VARCHAR2(100) := 'KRIM_ATTR_DATA_ID_S';
    PK VARCHAR2(100)          := 'ATTR_DATA_ID';
    STATEMENT VARCHAR2(2000);
    maxid NUMBER;
    cval NUMBER;
BEGIN
    STATEMENT:= 'SELECT MAX(TO_NUMBER('||TABLE_ID||'.'||PK||')) FROM '||TABLE_ID||' WHERE '||TABLE_ID||'.'||PK||' NOT LIKE ''KR%''';
    EXECUTE IMMEDIATE (STATEMENT) INTO maxid;
    STATEMENT := 'SELECT '|| SEQUENCE_ID ||'.NEXTVAL FROM DUAL';
    EXECUTE IMMEDIATE(STATEMENT) INTO cval;
    IF cval!=maxid
    THEN
    STATEMENT := 'ALTER SEQUENCE '|| SEQUENCE_ID || ' INCREMENT BY ' || (maxid-cval);
    EXECUTE IMMEDIATE(STATEMENT);
    STATEMENT := 'SELECT '|| SEQUENCE_ID ||'.NEXTVAL FROM DUAL';
    EXECUTE IMMEDIATE(STATEMENT) INTO cval;
    STATEMENT := 'ALTER SEQUENCE '|| SEQUENCE_ID || ' INCREMENT BY 1';
    EXECUTE IMMEDIATE(STATEMENT);
    END IF;
END;
/
DECLARE
    TABLE_ID VARCHAR2(100)    := 'KRIM_PERM_T';
    SEQUENCE_ID VARCHAR2(100) := 'KRIM_PERM_ID_S';
    PK VARCHAR2(100)          := 'PERM_ID';
    STATEMENT VARCHAR2(2000);
    maxid NUMBER;
    cval NUMBER;
BEGIN
    STATEMENT:= 'SELECT MAX(TO_NUMBER('||TABLE_ID||'.'||PK||')) FROM '||TABLE_ID||' WHERE '||TABLE_ID||'.'||PK||' NOT LIKE ''KR%''';
    EXECUTE IMMEDIATE (STATEMENT) INTO maxid;
    STATEMENT := 'SELECT '|| SEQUENCE_ID ||'.NEXTVAL FROM DUAL';
    EXECUTE IMMEDIATE(STATEMENT) INTO cval;
    IF cval!=maxid
    THEN
    STATEMENT := 'ALTER SEQUENCE '|| SEQUENCE_ID || ' INCREMENT BY ' || (maxid-cval);
    EXECUTE IMMEDIATE(STATEMENT);
    STATEMENT := 'SELECT '|| SEQUENCE_ID ||'.NEXTVAL FROM DUAL';
    EXECUTE IMMEDIATE(STATEMENT) INTO cval;
    STATEMENT := 'ALTER SEQUENCE '|| SEQUENCE_ID || ' INCREMENT BY 1';
    EXECUTE IMMEDIATE(STATEMENT);
    END IF;
END;
/
DECLARE
    TABLE_ID VARCHAR2(100)    := 'KRIM_ROLE_PERM_T';
    SEQUENCE_ID VARCHAR2(100) := 'KRIM_ROLE_PERM_ID_S';
    PK VARCHAR2(100)          := 'ROLE_PERM_ID';
    STATEMENT VARCHAR2(2000);
    maxid NUMBER;
    cval NUMBER;
BEGIN
    STATEMENT:= 'SELECT MAX(TO_NUMBER('||TABLE_ID||'.'||PK||')) FROM '||TABLE_ID||' WHERE '||TABLE_ID||'.'||PK||' NOT LIKE ''KR%''';
    EXECUTE IMMEDIATE (STATEMENT) INTO maxid;
    STATEMENT := 'SELECT '|| SEQUENCE_ID ||'.NEXTVAL FROM DUAL';
    EXECUTE IMMEDIATE(STATEMENT) INTO cval;
    IF cval!=maxid
    THEN
    STATEMENT := 'ALTER SEQUENCE '|| SEQUENCE_ID || ' INCREMENT BY ' || (maxid-cval);
    EXECUTE IMMEDIATE(STATEMENT);
    STATEMENT := 'SELECT '|| SEQUENCE_ID ||'.NEXTVAL FROM DUAL';
    EXECUTE IMMEDIATE(STATEMENT) INTO cval;
    STATEMENT := 'ALTER SEQUENCE '|| SEQUENCE_ID || ' INCREMENT BY 1';
    EXECUTE IMMEDIATE(STATEMENT);
    END IF;
END;
/
DECLARE
    TABLE_ID VARCHAR2(100)    := 'KRIM_TYP_T';
    SEQUENCE_ID VARCHAR2(100) := 'KRIM_TYP_ID_S';
    PK VARCHAR2(100)          := 'KIM_TYP_ID';
    STATEMENT VARCHAR2(2000);
    maxid NUMBER;
    cval NUMBER;
BEGIN
    STATEMENT:= 'SELECT MAX(TO_NUMBER('||TABLE_ID||'.'||PK||')) FROM '||TABLE_ID||' WHERE '||TABLE_ID||'.'||PK||' NOT LIKE ''KR%''';
    EXECUTE IMMEDIATE (STATEMENT) INTO maxid;
    STATEMENT := 'SELECT '|| SEQUENCE_ID ||'.NEXTVAL FROM DUAL';
    EXECUTE IMMEDIATE(STATEMENT) INTO cval;
    IF cval!=maxid
    THEN
    STATEMENT := 'ALTER SEQUENCE '|| SEQUENCE_ID || ' INCREMENT BY ' || (maxid-cval);
    EXECUTE IMMEDIATE(STATEMENT);
    STATEMENT := 'SELECT '|| SEQUENCE_ID ||'.NEXTVAL FROM DUAL';
    EXECUTE IMMEDIATE(STATEMENT) INTO cval;
    STATEMENT := 'ALTER SEQUENCE '|| SEQUENCE_ID || ' INCREMENT BY 1';
    EXECUTE IMMEDIATE(STATEMENT);
    END IF;
END;
/
DECLARE
    TABLE_ID VARCHAR2(100)    := 'KRIM_TYP_ATTR_T';
    SEQUENCE_ID VARCHAR2(100) := 'KRIM_TYP_ATTR_ID_S';
    PK VARCHAR2(100)          := 'KIM_TYP_ATTR_ID';
    STATEMENT VARCHAR2(2000);
    maxid NUMBER;
    cval NUMBER;
BEGIN
    STATEMENT:= 'SELECT MAX(TO_NUMBER('||TABLE_ID||'.'||PK||')) FROM '||TABLE_ID||' WHERE '||TABLE_ID||'.'||PK||' NOT LIKE ''KR%''';
    EXECUTE IMMEDIATE (STATEMENT) INTO maxid;
    STATEMENT := 'SELECT '|| SEQUENCE_ID ||'.NEXTVAL FROM DUAL';
    EXECUTE IMMEDIATE(STATEMENT) INTO cval;
    IF cval!=maxid
    THEN
    STATEMENT := 'ALTER SEQUENCE '|| SEQUENCE_ID || ' INCREMENT BY ' || (maxid-cval);
    EXECUTE IMMEDIATE(STATEMENT);
    STATEMENT := 'SELECT '|| SEQUENCE_ID ||'.NEXTVAL FROM DUAL';
    EXECUTE IMMEDIATE(STATEMENT) INTO cval;
    STATEMENT := 'ALTER SEQUENCE '|| SEQUENCE_ID || ' INCREMENT BY 1';
    EXECUTE IMMEDIATE(STATEMENT);
    END IF;
END;
/
DECLARE
    TABLE_ID VARCHAR2(100)    := 'KRIM_PERM_TMPL_T';
    SEQUENCE_ID VARCHAR2(100) := 'KRIM_PERM_TMPL_ID_S';
    PK VARCHAR2(100)          := 'PERM_TMPL_ID';
    STATEMENT VARCHAR2(2000);
    maxid NUMBER;
    cval NUMBER;
BEGIN
    STATEMENT:= 'SELECT MAX(TO_NUMBER('||TABLE_ID||'.'||PK||')) FROM '||TABLE_ID||' WHERE '||TABLE_ID||'.'||PK||' NOT LIKE ''KR%''';
    EXECUTE IMMEDIATE (STATEMENT) INTO maxid;
    STATEMENT := 'SELECT '|| SEQUENCE_ID ||'.NEXTVAL FROM DUAL';
    EXECUTE IMMEDIATE(STATEMENT) INTO cval;
    IF cval!=maxid
    THEN
    STATEMENT := 'ALTER SEQUENCE '|| SEQUENCE_ID || ' INCREMENT BY ' || (maxid-cval);
    EXECUTE IMMEDIATE(STATEMENT);
    STATEMENT := 'SELECT '|| SEQUENCE_ID ||'.NEXTVAL FROM DUAL';
    EXECUTE IMMEDIATE(STATEMENT) INTO cval;
    STATEMENT := 'ALTER SEQUENCE '|| SEQUENCE_ID || ' INCREMENT BY 1';
    EXECUTE IMMEDIATE(STATEMENT);
    END IF;
END;
/
DECLARE
    TABLE_ID VARCHAR2(100)    := 'KRIM_ATTR_DEFN_T';
    SEQUENCE_ID VARCHAR2(100) := 'KRIM_ATTR_DEFN_ID_S';
    PK VARCHAR2(100)          := 'KIM_ATTR_DEFN_ID';
    STATEMENT VARCHAR2(2000);
    maxid NUMBER;
    cval NUMBER;
BEGIN
    STATEMENT:= 'SELECT MAX(TO_NUMBER('||TABLE_ID||'.'||PK||')) FROM '||TABLE_ID||' WHERE '||TABLE_ID||'.'||PK||' NOT LIKE ''KR%''';
    EXECUTE IMMEDIATE (STATEMENT) INTO maxid;
    STATEMENT := 'SELECT '|| SEQUENCE_ID ||'.NEXTVAL FROM DUAL';
    EXECUTE IMMEDIATE(STATEMENT) INTO cval;
    IF cval!=maxid
    THEN
    STATEMENT := 'ALTER SEQUENCE '|| SEQUENCE_ID || ' INCREMENT BY ' || (maxid-cval);
    EXECUTE IMMEDIATE(STATEMENT);
    STATEMENT := 'SELECT '|| SEQUENCE_ID ||'.NEXTVAL FROM DUAL';
    EXECUTE IMMEDIATE(STATEMENT) INTO cval;
    STATEMENT := 'ALTER SEQUENCE '|| SEQUENCE_ID || ' INCREMENT BY 1';
    EXECUTE IMMEDIATE(STATEMENT);
    END IF;
END;
/
