--------------------------------------------------------
--  Constraints 
--------------------------------------------------------
CREATE UNIQUE INDEX KSEN_ATP_P ON KSEN_ATP
(ID   ASC)
/


ALTER TABLE KSEN_ATP
	ADD CONSTRAINT  KSEN_ATP_P PRIMARY KEY (ID)
/


CREATE  INDEX KSEN_ATP_I1 ON KSEN_ATP
(ATP_TYPE   ASC)
/


CREATE  INDEX KSEN_ATP_I2 ON KSEN_ATP
(ATP_CD   ASC)
/


CREATE  INDEX KSEN_ATP_I3 ON KSEN_ATP
(START_DT   ASC)
/


CREATE UNIQUE INDEX KSEN_ATP_ATTR_P ON KSEN_ATP_ATTR
(ID   ASC)
/


ALTER TABLE KSEN_ATP_ATTR
	ADD CONSTRAINT  KSEN_ATP_ATTR_P PRIMARY KEY (ID)
/


CREATE  INDEX KSEN_ATP_ATTR_IF1 ON KSEN_ATP_ATTR
(OWNER_ID   ASC)
/



CREATE UNIQUE INDEX KSEN_ATPATP_RELTN_P ON KSEN_ATPATP_RELTN
(ID   ASC)
/


ALTER TABLE KSEN_ATPATP_RELTN
	ADD CONSTRAINT  KSEN_ATPATP_RELTN_P PRIMARY KEY (ID)
/


CREATE  INDEX KSEN_ATPATP_RELTN_I1 ON KSEN_ATPATP_RELTN
(ATP_TYPE   ASC)
/


CREATE  INDEX KSEN_ATPATP_RELTN_IF1 ON KSEN_ATPATP_RELTN
(ATP_ID   ASC)
/


CREATE  INDEX KSEN_ATPATP_RELTN_IF2 ON KSEN_ATPATP_RELTN
(RELATED_ATP_ID   ASC)
/

CREATE UNIQUE INDEX KSEN_ATPATP_RELTN_ATTR_P ON KSEN_ATPATP_RELTN_ATTR
(ID   ASC)
/


ALTER TABLE KSEN_ATPATP_RELTN_ATTR
	ADD CONSTRAINT  KSEN_ATPATP_RELTN_ATTR_P PRIMARY KEY (ID)
/


CREATE  INDEX KSEN_ATPATP_RELTN_ATTR_IF1 ON KSEN_ATPATP_RELTN_ATTR
(OWNER_ID   ASC)
/




CREATE UNIQUE INDEX KSEN_ATPMSTONE_RELTN_P ON KSEN_ATPMSTONE_RELTN
(ID   ASC)
/


ALTER TABLE KSEN_ATPMSTONE_RELTN
	ADD CONSTRAINT  KSEN_ATPMSTONE_RELTN_P PRIMARY KEY (ID)
/


CREATE  INDEX KSEN_ATPMSTONE_RELTN_IF1 ON KSEN_ATPMSTONE_RELTN
(ATP_ID   ASC)
/


CREATE  INDEX KSEN_ATPMSTONE_RELTN_IF2 ON KSEN_ATPMSTONE_RELTN
(MSTONE_ID   ASC)
/


CREATE UNIQUE INDEX KSEN_MSTONE_P ON KSEN_MSTONE
(ID   ASC)
/


ALTER TABLE KSEN_MSTONE
	ADD CONSTRAINT  KSEN_MSTONE_P PRIMARY KEY (ID)
/


CREATE  INDEX KSEN_MSTONE_I1 ON KSEN_MSTONE
(MSTONE_TYPE   ASC)
/


CREATE  INDEX KSEN_MSTONE_I2 ON KSEN_MSTONE
(START_DT   ASC)
/




CREATE UNIQUE INDEX KSEN_MSTONE_ATTR_P ON KSEN_MSTONE_ATTR
(ID   ASC)
/


ALTER TABLE KSEN_MSTONE_ATTR
	ADD CONSTRAINT  KSEN_MSTONE_ATTR_P PRIMARY KEY (ID)
/


CREATE  INDEX KSEN_MSTONE_ATTR_IF1 ON KSEN_MSTONE_ATTR
(OWNER_ID   ASC)
/


ALTER TABLE KSEN_ATP_ATTR
	ADD (CONSTRAINT KSEN_ATP_ATTR_FK1 FOREIGN KEY (OWNER_ID) REFERENCES KSEN_ATP (ID))
/


ALTER TABLE KSEN_ATPATP_RELTN
	ADD (CONSTRAINT KSEN_ATPATP_RELTN_FK1 FOREIGN KEY (ATP_ID) REFERENCES KSEN_ATP (ID))
/


ALTER TABLE KSEN_ATPATP_RELTN
	ADD (CONSTRAINT KSEN_ATPATP_RELTN_FK2 FOREIGN KEY (RELATED_ATP_ID) REFERENCES KSEN_ATP (ID))
/


ALTER TABLE KSEN_ATPATP_RELTN_ATTR
	ADD (CONSTRAINT KSEN_ATPATP_RELTN_ATTR_FK1 FOREIGN KEY (OWNER_ID) REFERENCES KSEN_ATPATP_RELTN (ID))
/


ALTER TABLE KSEN_ATPMSTONE_RELTN
	ADD (CONSTRAINT KSEN_ATPMSTONE_RELTN_FK1 FOREIGN KEY (ATP_ID) REFERENCES KSEN_ATP (ID))
/


ALTER TABLE KSEN_ATPMSTONE_RELTN
	ADD (CONSTRAINT KSEN_ATPMSTONE_RELTN_FK2 FOREIGN KEY (MSTONE_ID) REFERENCES KSEN_MSTONE (ID))
/


ALTER TABLE KSEN_MSTONE_ATTR
	ADD (CONSTRAINT KSEN_MSTONE_ATTR_FK1 FOREIGN KEY (OWNER_ID) REFERENCES KSEN_MSTONE (ID))
/