
package org.kuali.student.core.atp.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.2
 * Tue Mar 31 14:06:06 EDT 2009
 * Generated source version: 2.2
 */

@XmlRootElement(name = "getAtpDurationTypeResponse", namespace = "http://student.kuali.org/core/atp")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getAtpDurationTypeResponse", namespace = "http://student.kuali.org/core/atp")

public class GetAtpDurationTypeResponse {

    @XmlElement(name = "return")
    private org.kuali.student.core.atp.dto.AtpDurationTypeInfo _return;

    public org.kuali.student.core.atp.dto.AtpDurationTypeInfo getReturn() {
        return this._return;
    }

    public void setReturn(org.kuali.student.core.atp.dto.AtpDurationTypeInfo new_return)  {
        this._return = new_return;
    }

}

