
package org.kuali.student.core.atp.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.2
 * Tue Mar 31 14:06:06 EDT 2009
 * Generated source version: 2.2
 */

@XmlRootElement(name = "removeMilestone", namespace = "http://student.kuali.org/core/atp")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "removeMilestone", namespace = "http://student.kuali.org/core/atp")

public class RemoveMilestone {

    @XmlElement(name = "milestoneKey")
    private java.lang.String milestoneKey;

    public java.lang.String getMilestoneKey() {
        return this.milestoneKey;
    }

    public void setMilestoneKey(java.lang.String newMilestoneKey)  {
        this.milestoneKey = newMilestoneKey;
    }

}

