
package org.kuali.student.core.atp.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.2
 * Tue Mar 31 14:06:06 EDT 2009
 * Generated source version: 2.2
 */

@XmlRootElement(name = "validateDateRange", namespace = "http://student.kuali.org/wsdl/atp")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "validateDateRange", namespace = "http://student.kuali.org/wsdl/atp", propOrder = {"validationType","dateRangeInfo"})

public class ValidateDateRange {

    @XmlElement(name = "validationType")
    private java.lang.String validationType;
    @XmlElement(name = "dateRangeInfo")
    private org.kuali.student.core.atp.dto.DateRangeInfo dateRangeInfo;

    public java.lang.String getValidationType() {
        return this.validationType;
    }

    public void setValidationType(java.lang.String newValidationType)  {
        this.validationType = newValidationType;
    }

    public org.kuali.student.core.atp.dto.DateRangeInfo getDateRangeInfo() {
        return this.dateRangeInfo;
    }

    public void setDateRangeInfo(org.kuali.student.core.atp.dto.DateRangeInfo newDateRangeInfo)  {
        this.dateRangeInfo = newDateRangeInfo;
    }

}

