
package org.kuali.student.core.comment.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.2
 * Fri Jun 05 15:33:47 EDT 2009
 * Generated source version: 2.2
 */

@XmlRootElement(name = "searchForTags", namespace = "http://student.kuali.org/wsdl/commentService")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "searchForTags", namespace = "http://student.kuali.org/wsdl/commentService")

public class SearchForTags {

    @XmlElement(name = "tagCriteriaInfo")
    private org.kuali.student.core.comment.dto.TagCriteriaInfo tagCriteriaInfo;

    public org.kuali.student.core.comment.dto.TagCriteriaInfo getTagCriteriaInfo() {
        return this.tagCriteriaInfo;
    }

    public void setTagCriteriaInfo(org.kuali.student.core.comment.dto.TagCriteriaInfo newTagCriteriaInfo)  {
        this.tagCriteriaInfo = newTagCriteriaInfo;
    }

}

