ALTER TABLE KREN_CHNL_PRODCR_T
    ADD CONSTRAINT KREN_CHNL_PRODCR_FK2 FOREIGN KEY (PRODCR_ID)
    REFERENCES KREN_PRODCR_T (PRODCR_ID)
/

ALTER TABLE KREN_CHNL_PRODCR_T
    ADD CONSTRAINT KREN_CHNL_PRODCR_FK1 FOREIGN KEY (CHNL_ID)
    REFERENCES KREN_CHNL_T (CHNL_ID)
/


ALTER TABLE KREN_CHNL_SUBSCRP_T
    ADD CONSTRAINT KREN_CHAN_SUBSCRP_FK1 FOREIGN KEY (CHNL_ID)
    REFERENCES KREN_CHNL_T (CHNL_ID)
/




ALTER TABLE KREN_MSG_DELIV_T
    ADD CONSTRAINT KREN_MSG_DELIV_FK1 FOREIGN KEY (MSG_ID)
    REFERENCES KREN_MSG_T (MSG_ID)
/



ALTER TABLE KREN_NTFCTN_MSG_DELIV_T
    ADD CONSTRAINT KREN_NTFCTN_MSG_DELIV_FK1 FOREIGN KEY (NTFCTN_ID)
    REFERENCES KREN_NTFCTN_T (NTFCTN_ID)
/


ALTER TABLE KREN_NTFCTN_T
    ADD CONSTRAINT KREN_NTFCTN_FK4 FOREIGN KEY (PRODCR_ID)
    REFERENCES KREN_PRODCR_T (PRODCR_ID)
/

ALTER TABLE KREN_NTFCTN_T
    ADD CONSTRAINT KREN_NTFCTN_FK3 FOREIGN KEY (PRIO_ID)
    REFERENCES KREN_PRIO_T (PRIO_ID)
/

ALTER TABLE KREN_NTFCTN_T
    ADD CONSTRAINT KREN_NTFCTN_FK2 FOREIGN KEY (CNTNT_TYP_ID)
    REFERENCES KREN_CNTNT_TYP_T (CNTNT_TYP_ID)
/

ALTER TABLE KREN_NTFCTN_T
    ADD CONSTRAINT KREN_NTFCTN_FK1 FOREIGN KEY (CHNL_ID)
    REFERENCES KREN_CHNL_T (CHNL_ID)
/





ALTER TABLE KREN_RECIP_LIST_T
    ADD CONSTRAINT KREN_RECIP_LIST_FK1 FOREIGN KEY (CHNL_ID)
    REFERENCES KREN_CHNL_T (CHNL_ID)
/



ALTER TABLE KREN_RECIP_T
    ADD CONSTRAINT KREN_RECIP_FK1 FOREIGN KEY (NTFCTN_ID)
    REFERENCES KREN_NTFCTN_T (NTFCTN_ID)
/


ALTER TABLE KREN_RVWER_T
    ADD CONSTRAINT NOTIFICATION_REVIEWERS_N_FK1 FOREIGN KEY (CHNL_ID)
    REFERENCES KREN_CHNL_T (CHNL_ID)
/


ALTER TABLE KREN_SNDR_T
    ADD CONSTRAINT KREN_SNDR_FK1 FOREIGN KEY (NTFCTN_ID)
    REFERENCES KREN_NTFCTN_T (NTFCTN_ID)
/































ALTER TABLE KREW_RTE_NODE_CFG_PARM_T
    ADD CONSTRAINT EN_RTE_NODE_CFG_PARM_TR1 FOREIGN KEY (RTE_NODE_ID)
    REFERENCES KREW_RTE_NODE_T (RTE_NODE_ID)
/












ALTER TABLE KREW_RULE_T
    ADD CONSTRAINT KREW_RULE_TR1 FOREIGN KEY (RULE_EXPR_ID)
    REFERENCES KREW_RULE_EXPR_T (RULE_EXPR_ID)
/











ALTER TABLE KRIM_DLGN_MBR_ATTR_DATA_T
    ADD CONSTRAINT KRIM_DLGN_MBR_ATTR_DATA_TR2 FOREIGN KEY (KIM_ATTR_DEFN_ID)
    REFERENCES KRIM_ATTR_DEFN_T (KIM_ATTR_DEFN_ID)
/

ALTER TABLE KRIM_DLGN_MBR_ATTR_DATA_T
    ADD CONSTRAINT KRIM_DLGN_MBR_ATTR_DATA_TR1 FOREIGN KEY (KIM_TYP_ID)
    REFERENCES KRIM_TYP_T (KIM_TYP_ID)
/


ALTER TABLE KRIM_DLGN_MBR_T
    ADD CONSTRAINT KRIM_DLGN_MBR_TR2 FOREIGN KEY (DLGN_ID)
    REFERENCES KRIM_DLGN_T (DLGN_ID)
/


ALTER TABLE KRIM_DLGN_T
    ADD CONSTRAINT KRIM_DLGN_TR1 FOREIGN KEY (ROLE_ID)
    REFERENCES KRIM_ROLE_T (ROLE_ID)
/

ALTER TABLE KRIM_DLGN_T
    ADD CONSTRAINT KRIM_DLGN_TR2 FOREIGN KEY (KIM_TYP_ID)
    REFERENCES KRIM_TYP_T (KIM_TYP_ID)
/





ALTER TABLE KRIM_ENTITY_ADDR_T
    ADD CONSTRAINT KRIM_ENTITY_ADDR_TR1 FOREIGN KEY (ENT_TYP_CD, ENTITY_ID)
    REFERENCES KRIM_ENTITY_ENT_TYP_T (ENT_TYP_CD, ENTITY_ID)
ON DELETE CASCADE
/

ALTER TABLE KRIM_ENTITY_ADDR_T
    ADD CONSTRAINT KRIM_ENTITY_ADDR_TR2 FOREIGN KEY (ADDR_TYP_CD)
    REFERENCES KRIM_ADDR_TYP_T (ADDR_TYP_CD)
/


ALTER TABLE KRIM_ENTITY_AFLTN_T
    ADD CONSTRAINT KRIM_ENTITY_AFLTN_TR1 FOREIGN KEY (ENTITY_ID)
    REFERENCES KRIM_ENTITY_T (ENTITY_ID)
ON DELETE CASCADE
/

ALTER TABLE KRIM_ENTITY_AFLTN_T
    ADD CONSTRAINT KRIM_ENTITY_AFLTN_TR2 FOREIGN KEY (AFLTN_TYP_CD)
    REFERENCES KRIM_AFLTN_TYP_T (AFLTN_TYP_CD)
/




ALTER TABLE KRIM_ENTITY_CTZNSHP_T
    ADD CONSTRAINT KRIM_ENTITY_CTZNSHP_TR1 FOREIGN KEY (ENTITY_ID)
    REFERENCES KRIM_ENTITY_T (ENTITY_ID)
ON DELETE CASCADE
/

ALTER TABLE KRIM_ENTITY_CTZNSHP_T
    ADD CONSTRAINT KRIM_ENTITY_CTZNSHP_TR2 FOREIGN KEY (CTZNSHP_STAT_CD)
    REFERENCES KRIM_CTZNSHP_STAT_T (CTZNSHP_STAT_CD)
/


ALTER TABLE KRIM_ENTITY_EMAIL_T
    ADD CONSTRAINT KRIM_ENTITY_EMAIL_TR1 FOREIGN KEY (ENT_TYP_CD, ENTITY_ID)
    REFERENCES KRIM_ENTITY_ENT_TYP_T (ENT_TYP_CD, ENTITY_ID)
ON DELETE CASCADE
/


ALTER TABLE KRIM_ENTITY_EMP_INFO_T
    ADD CONSTRAINT KRIM_ENTITY_EMP_INFO_TR4 FOREIGN KEY (ENTITY_AFLTN_ID)
    REFERENCES KRIM_ENTITY_AFLTN_T (ENTITY_AFLTN_ID)
/

ALTER TABLE KRIM_ENTITY_EMP_INFO_T
    ADD CONSTRAINT KRIM_ENTITY_EMP_INFO_TR1 FOREIGN KEY (ENTITY_ID)
    REFERENCES KRIM_ENTITY_T (ENTITY_ID)
ON DELETE CASCADE
/

ALTER TABLE KRIM_ENTITY_EMP_INFO_T
    ADD CONSTRAINT KRIM_ENTITY_EMP_INFO_TR2 FOREIGN KEY (EMP_STAT_CD)
    REFERENCES KRIM_EMP_STAT_T (EMP_STAT_CD)
/

ALTER TABLE KRIM_ENTITY_EMP_INFO_T
    ADD CONSTRAINT KRIM_ENTITY_EMP_INFO_TR3 FOREIGN KEY (EMP_TYP_CD)
    REFERENCES KRIM_EMP_TYP_T (EMP_TYP_CD)
/


ALTER TABLE KRIM_ENTITY_ENT_TYP_T
    ADD CONSTRAINT KRIM_ENTITY_ENT_TYP_TR2 FOREIGN KEY (ENT_TYP_CD)
    REFERENCES KRIM_ENT_TYP_T (ENT_TYP_CD)
/

ALTER TABLE KRIM_ENTITY_ENT_TYP_T
    ADD CONSTRAINT KRIM_ENTITY_ENT_TYP_TR1 FOREIGN KEY (ENTITY_ID)
    REFERENCES KRIM_ENTITY_T (ENTITY_ID)
ON DELETE CASCADE
/



ALTER TABLE KRIM_ENTITY_EXT_ID_T
    ADD CONSTRAINT KRIM_ENTITY_EXT_ID_TR2 FOREIGN KEY (EXT_ID_TYP_CD)
    REFERENCES KRIM_EXT_ID_TYP_T (EXT_ID_TYP_CD)
/

ALTER TABLE KRIM_ENTITY_EXT_ID_T
    ADD CONSTRAINT KRIM_ENTITY_EXT_ID_TR1 FOREIGN KEY (ENTITY_ID)
    REFERENCES KRIM_ENTITY_T (ENTITY_ID)
ON DELETE CASCADE
/


ALTER TABLE KRIM_ENTITY_NM_T
    ADD CONSTRAINT KRIM_ENTITY_NM_TR1 FOREIGN KEY (ENTITY_ID)
    REFERENCES KRIM_ENTITY_T (ENTITY_ID)
ON DELETE CASCADE
/


ALTER TABLE KRIM_ENTITY_PHONE_T
    ADD CONSTRAINT KRIM_ENTITY_PHONE_TR1 FOREIGN KEY (ENT_TYP_CD, ENTITY_ID)
    REFERENCES KRIM_ENTITY_ENT_TYP_T (ENT_TYP_CD, ENTITY_ID)
ON DELETE CASCADE
/

ALTER TABLE KRIM_ENTITY_PHONE_T
    ADD CONSTRAINT KRIM_ENTITY_PHONE_TR2 FOREIGN KEY (PHONE_TYP_CD)
    REFERENCES KRIM_PHONE_TYP_T (PHONE_TYP_CD)
/









ALTER TABLE KRIM_GRP_ATTR_DATA_T
    ADD CONSTRAINT KRIM_GRP_ATTR_DATA_TR1 FOREIGN KEY (KIM_TYP_ID)
    REFERENCES KRIM_TYP_T (KIM_TYP_ID)
/

ALTER TABLE KRIM_GRP_ATTR_DATA_T
    ADD CONSTRAINT KRIM_GRP_ATTR_DATA_TR3 FOREIGN KEY (GRP_ID)
    REFERENCES KRIM_GRP_T (GRP_ID)
ON DELETE CASCADE
/

ALTER TABLE KRIM_GRP_ATTR_DATA_T
    ADD CONSTRAINT KRIM_GRP_ATTR_DATA_TR2 FOREIGN KEY (KIM_ATTR_DEFN_ID)
    REFERENCES KRIM_ATTR_DEFN_T (KIM_ATTR_DEFN_ID)
/



ALTER TABLE KRIM_GRP_MBR_T
    ADD CONSTRAINT KRIM_GRP_MBR_TR1 FOREIGN KEY (GRP_ID)
    REFERENCES KRIM_GRP_T (GRP_ID)
ON DELETE CASCADE
/


ALTER TABLE KRIM_GRP_T
    ADD CONSTRAINT KRIM_GRP_TR1 FOREIGN KEY (KIM_TYP_ID)
    REFERENCES KRIM_TYP_T (KIM_TYP_ID)
/


ALTER TABLE KRIM_PERM_ATTR_DATA_T
    ADD CONSTRAINT KRIM_PERM_ATTR_DATA_TR1 FOREIGN KEY (KIM_TYP_ID)
    REFERENCES KRIM_TYP_T (KIM_TYP_ID)
/

ALTER TABLE KRIM_PERM_ATTR_DATA_T
    ADD CONSTRAINT KRIM_PERM_ATTR_DATA_TR3 FOREIGN KEY (PERM_ID)
    REFERENCES KRIM_PERM_T (PERM_ID)
ON DELETE CASCADE
/

ALTER TABLE KRIM_PERM_ATTR_DATA_T
    ADD CONSTRAINT KRIM_PERM_ATTR_DATA_TR2 FOREIGN KEY (KIM_ATTR_DEFN_ID)
    REFERENCES KRIM_ATTR_DEFN_T (KIM_ATTR_DEFN_ID)
/


ALTER TABLE KRIM_PERM_T
    ADD CONSTRAINT KRIM_PERM_TR1 FOREIGN KEY (PERM_TMPL_ID)
    REFERENCES KRIM_PERM_TMPL_T (PERM_TMPL_ID)
/


ALTER TABLE KRIM_PERM_TMPL_T
    ADD CONSTRAINT KRIM_PERM_TMPL_TR1 FOREIGN KEY (KIM_TYP_ID)
    REFERENCES KRIM_TYP_T (KIM_TYP_ID)
/





ALTER TABLE KRIM_PND_AFLTN_MT
    ADD CONSTRAINT KRIM_PND_AFLTN_MT_FK1 FOREIGN KEY (FDOC_NBR)
    REFERENCES KRIM_PERSON_DOCUMENT_T (FDOC_NBR)
/




















ALTER TABLE KRIM_PRNCPL_T
    ADD CONSTRAINT KRIM_PRNCPL_TR1 FOREIGN KEY (ENTITY_ID)
    REFERENCES KRIM_ENTITY_T (ENTITY_ID)
ON DELETE CASCADE
/



ALTER TABLE KRIM_ROLE_MBR_ATTR_DATA_T
    ADD CONSTRAINT KRIM_ROLE_MBR_ATTR_DATA_TR1 FOREIGN KEY (KIM_TYP_ID)
    REFERENCES KRIM_TYP_T (KIM_TYP_ID)
/

ALTER TABLE KRIM_ROLE_MBR_ATTR_DATA_T
    ADD CONSTRAINT KRIM_ROLE_MBR_ATTR_DATA_TR2 FOREIGN KEY (KIM_ATTR_DEFN_ID)
    REFERENCES KRIM_ATTR_DEFN_T (KIM_ATTR_DEFN_ID)
/


ALTER TABLE KRIM_ROLE_MBR_T
    ADD CONSTRAINT KRIM_ROLE_MBR_TR1 FOREIGN KEY (ROLE_ID)
    REFERENCES KRIM_ROLE_T (ROLE_ID)
ON DELETE CASCADE
/


ALTER TABLE KRIM_ROLE_PERM_T
    ADD CONSTRAINT KRIM_ROLE_PERM_TR1 FOREIGN KEY (PERM_ID)
    REFERENCES KRIM_PERM_T (PERM_ID)
/



ALTER TABLE KRIM_ROLE_RSP_T
    ADD CONSTRAINT KRIM_ROLE_RSP_TR1 FOREIGN KEY (RSP_ID)
    REFERENCES KRIM_RSP_T (RSP_ID)
/


ALTER TABLE KRIM_ROLE_T
    ADD CONSTRAINT KRIM_ROLE_TR1 FOREIGN KEY (KIM_TYP_ID)
    REFERENCES KRIM_TYP_T (KIM_TYP_ID)
/


ALTER TABLE KRIM_RSP_ATTR_DATA_T
    ADD CONSTRAINT KRIM_RSP_ATTR_DATA_TR3 FOREIGN KEY (RSP_ID)
    REFERENCES KRIM_RSP_T (RSP_ID)
ON DELETE CASCADE
/

ALTER TABLE KRIM_RSP_ATTR_DATA_T
    ADD CONSTRAINT KRIM_RSP_ATTR_DATA_TR1 FOREIGN KEY (KIM_TYP_ID)
    REFERENCES KRIM_TYP_T (KIM_TYP_ID)
/

ALTER TABLE KRIM_RSP_ATTR_DATA_T
    ADD CONSTRAINT KRIM_RSP_ATTR_DATA_TR2 FOREIGN KEY (KIM_ATTR_DEFN_ID)
    REFERENCES KRIM_ATTR_DEFN_T (KIM_ATTR_DEFN_ID)
/


ALTER TABLE KRIM_RSP_T
    ADD CONSTRAINT KRIM_RSP_TR1 FOREIGN KEY (RSP_TMPL_ID)
    REFERENCES KRIM_RSP_TMPL_T (RSP_TMPL_ID)
/


ALTER TABLE KRIM_RSP_TMPL_T
    ADD CONSTRAINT KRIM_RSP_TMPL_TR1 FOREIGN KEY (KIM_TYP_ID)
    REFERENCES KRIM_TYP_T (KIM_TYP_ID)
/


ALTER TABLE KRIM_TYP_ATTR_T
    ADD CONSTRAINT KRIM_TYP_ATTRIBUTE_TR1 FOREIGN KEY (KIM_TYP_ID)
    REFERENCES KRIM_TYP_T (KIM_TYP_ID)
ON DELETE CASCADE
/

ALTER TABLE KRIM_TYP_ATTR_T
    ADD CONSTRAINT KRIM_TYP_ATTR_TR2 FOREIGN KEY (KIM_ATTR_DEFN_ID)
    REFERENCES KRIM_ATTR_DEFN_T (KIM_ATTR_DEFN_ID)
ON DELETE CASCADE
/




ALTER TABLE KRNS_ATT_T
    ADD CONSTRAINT KRNS_ATT_TR1 FOREIGN KEY (NTE_ID)
    REFERENCES KRNS_NTE_T (NTE_ID)
/


ALTER TABLE KRNS_CAMPUS_T
    ADD CONSTRAINT SH_CAMPUS_TR1 FOREIGN KEY (CAMPUS_TYP_CD)
    REFERENCES KRNS_CMP_TYP_T (CAMPUS_TYP_CD)
/







ALTER TABLE KRNS_MAINT_DOC_T
    ADD CONSTRAINT KRNS_MAINT_DOC_TR1 FOREIGN KEY (DOC_HDR_ID)
    REFERENCES KRNS_DOC_HDR_T (DOC_HDR_ID)
/




ALTER TABLE KRNS_NTE_T
    ADD CONSTRAINT KRNS_NTE_TR1 FOREIGN KEY (NTE_TYP_CD)
    REFERENCES KRNS_NTE_TYP_T (NTE_TYP_CD)
/



ALTER TABLE KRNS_PARM_DTL_TYP_T
    ADD CONSTRAINT KRNS_PARM_DTL_TYP_TR1 FOREIGN KEY (NMSPC_CD)
    REFERENCES KRNS_NMSPC_T (NMSPC_CD)
/


ALTER TABLE KRNS_PARM_T
    ADD CONSTRAINT KRNS_PARM_TR2 FOREIGN KEY (PARM_TYP_CD)
    REFERENCES KRNS_PARM_TYP_T (PARM_TYP_CD)
/

ALTER TABLE KRNS_PARM_T
    ADD CONSTRAINT KRNS_PARM_TR1 FOREIGN KEY (NMSPC_CD)
    REFERENCES KRNS_NMSPC_T (NMSPC_CD)
/









ALTER TABLE KRSB_QRTZ_BLOB_TRIGGERS
    ADD CONSTRAINT KRSB_QRTZ_BLOB_TRIGGERS_TR1 FOREIGN KEY (TRIGGER_NAME, TRIGGER_GROUP)
    REFERENCES KRSB_QRTZ_TRIGGERS (TRIGGER_NAME, TRIGGER_GROUP)
/



ALTER TABLE KRSB_QRTZ_CRON_TRIGGERS
    ADD CONSTRAINT KRSB_QRTZ_CRON_TRIGGERS_TR1 FOREIGN KEY (TRIGGER_NAME, TRIGGER_GROUP)
    REFERENCES KRSB_QRTZ_TRIGGERS (TRIGGER_NAME, TRIGGER_GROUP)
/










ALTER TABLE KRSB_QRTZ_TRIGGER_LISTENERS
    ADD CONSTRAINT KRSB_QRTZ_TRIGGER_LISTENE_TR1 FOREIGN KEY (TRIGGER_NAME, TRIGGER_GROUP)
    REFERENCES KRSB_QRTZ_TRIGGERS (TRIGGER_NAME, TRIGGER_GROUP)
/





ALTER TABLE KR_POSTAL_CODE_T
    ADD CONSTRAINT KR_POSTAL_CODE_TR3 FOREIGN KEY (COUNTY_CD, POSTAL_STATE_CD, POSTAL_CNTRY_CD)
    REFERENCES KR_COUNTY_T (COUNTY_CD, STATE_CD, POSTAL_CNTRY_CD)
/

ALTER TABLE KR_POSTAL_CODE_T
    ADD CONSTRAINT KR_POSTAL_CODE_TR2 FOREIGN KEY (POSTAL_STATE_CD, POSTAL_CNTRY_CD)
    REFERENCES KR_STATE_T (POSTAL_STATE_CD, POSTAL_CNTRY_CD)
/

ALTER TABLE KR_POSTAL_CODE_T
    ADD CONSTRAINT KR_POSTAL_CODE_TR1 FOREIGN KEY (POSTAL_CNTRY_CD)
    REFERENCES KR_COUNTRY_T (POSTAL_CNTRY_CD)
/


ALTER TABLE KR_STATE_T
    ADD CONSTRAINT KR_STATE_TR1 FOREIGN KEY (POSTAL_CNTRY_CD)
    REFERENCES KR_COUNTRY_T (POSTAL_CNTRY_CD)
/


ALTER TABLE KSAP_ATP
    ADD CONSTRAINT FK91BE1D5359A216F FOREIGN KEY (TYPE)
    REFERENCES KSAP_ATP_TYPE (TYPE_KEY)
/

ALTER TABLE KSAP_ATP
    ADD CONSTRAINT FK91BE1D5E567011A FOREIGN KEY (RT_DESCR_ID)
    REFERENCES KSAP_RICH_TEXT_T (ID)
/


ALTER TABLE KSAP_ATP_ATTR
    ADD CONSTRAINT FKD2FA861BB47270E FOREIGN KEY (OWNER)
    REFERENCES KSAP_ATP (ID)
/



ALTER TABLE KSAP_ATP_DUR_TYPE_ATTR
    ADD CONSTRAINT FKF32EB20E331B319C FOREIGN KEY (OWNER)
    REFERENCES KSAP_ATP_DUR_TYPE (TYPE_KEY)
/



ALTER TABLE KSAP_ATP_SEASONAL_TYPE_ATTR
    ADD CONSTRAINT FK12F7C5CF75414156 FOREIGN KEY (OWNER)
    REFERENCES KSAP_ATP_SEASONAL_TYPE (TYPE_KEY)
/


ALTER TABLE KSAP_ATP_TYPE
    ADD CONSTRAINT FKD3033B6479EB8D2E FOREIGN KEY (SEASONAL_TYPE)
    REFERENCES KSAP_ATP_SEASONAL_TYPE (TYPE_KEY)
/

ALTER TABLE KSAP_ATP_TYPE
    ADD CONSTRAINT FKD3033B64B5EF99A1 FOREIGN KEY (DUR_TYPE)
    REFERENCES KSAP_ATP_DUR_TYPE (TYPE_KEY)
/


ALTER TABLE KSAP_ATP_TYPE_ATTR
    ADD CONSTRAINT FKF4C7CDEC3BB784E8 FOREIGN KEY (OWNER)
    REFERENCES KSAP_ATP_TYPE (TYPE_KEY)
/


ALTER TABLE KSAP_DT_RANGE
    ADD CONSTRAINT FK237F74562E3E4416 FOREIGN KEY (DT_RANGE_TYPE_ID)
    REFERENCES KSAP_DT_RANGE_TYPE (TYPE_KEY)
/

ALTER TABLE KSAP_DT_RANGE
    ADD CONSTRAINT FK237F7456E567011A FOREIGN KEY (RT_DESCR_ID)
    REFERENCES KSAP_RICH_TEXT_T (ID)
/

ALTER TABLE KSAP_DT_RANGE
    ADD CONSTRAINT FK237F7456B1104A58 FOREIGN KEY (ATP_ID)
    REFERENCES KSAP_ATP (ID)
/


ALTER TABLE KSAP_DT_RANGE_ATTR
    ADD CONSTRAINT FKBE235C3A66A1DC20 FOREIGN KEY (OWNER)
    REFERENCES KSAP_DT_RANGE (DATERANGE_KEY)
/



ALTER TABLE KSAP_DT_RANGE_TYPE_ATTR
    ADD CONSTRAINT FK249AF32D51AD60FA FOREIGN KEY (OWNER)
    REFERENCES KSAP_DT_RANGE_TYPE (TYPE_KEY)
/


ALTER TABLE KSAP_MLSTN
    ADD CONSTRAINT FK32504D66B1104A58 FOREIGN KEY (ATP_ID)
    REFERENCES KSAP_ATP (ID)
/

ALTER TABLE KSAP_MLSTN
    ADD CONSTRAINT FK32504D66E567011A FOREIGN KEY (RT_DESCR_ID)
    REFERENCES KSAP_RICH_TEXT_T (ID)
/

ALTER TABLE KSAP_MLSTN
    ADD CONSTRAINT FK32504D66C79A5A37 FOREIGN KEY (MLSTN_TYPE_ID)
    REFERENCES KSAP_MLSTN_TYPE (TYPE_KEY)
/


ALTER TABLE KSAP_MLSTN_ATTR
    ADD CONSTRAINT FKD83FAD2A36BAFF61 FOREIGN KEY (OWNER)
    REFERENCES KSAP_MLSTN (ID)
/



ALTER TABLE KSAP_MLSTN_TYPE_ATTR
    ADD CONSTRAINT FK193BB83D5E10FBBB FOREIGN KEY (OWNER)
    REFERENCES KSAP_MLSTN_TYPE (TYPE_KEY)
/



ALTER TABLE KSCO_COMMENT
    ADD CONSTRAINT FK278964D44EE07A2F FOREIGN KEY (TYPE)
    REFERENCES KSCO_COMMENT_TYPE (TYPE_KEY)
/

ALTER TABLE KSCO_COMMENT
    ADD CONSTRAINT FK278964D4CE52F9DA FOREIGN KEY (RT_DESCR_ID)
    REFERENCES KSCO_RICH_TEXT_T (ID)
/

ALTER TABLE KSCO_COMMENT
    ADD CONSTRAINT FK278964D4A44FBE52 FOREIGN KEY (REFERENCE)
    REFERENCES KSCO_REFERENCE (ID)
/


ALTER TABLE KSCO_COMMENT_ATTR
    ADD CONSTRAINT FK39D20A7C6117DFCE FOREIGN KEY (OWNER)
    REFERENCES KSCO_COMMENT (ID)
/



ALTER TABLE KSCO_COMMENT_TYPE_ATTR
    ADD CONSTRAINT FK2188DE2B54FDDDA8 FOREIGN KEY (OWNER)
    REFERENCES KSCO_COMMENT_TYPE (TYPE_KEY)
/


ALTER TABLE KSCO_REFERENCE
    ADD CONSTRAINT FK8CBAE8808E68868F FOREIGN KEY (REFERENCE_TYPE)
    REFERENCES KSCO_REFERENCE_TYPE (TYPE_KEY)
/



ALTER TABLE KSCO_REFERENCE_TYPE_ATTR
    ADD CONSTRAINT FK8E9ABAD75FB9994 FOREIGN KEY (OWNER)
    REFERENCES KSCO_REFERENCE_TYPE (TYPE_KEY)
/



ALTER TABLE KSCO_TAG
    ADD CONSTRAINT FKC77C08FA44FBE52 FOREIGN KEY (REFERENCE)
    REFERENCES KSCO_REFERENCE (ID)
/

ALTER TABLE KSCO_TAG
    ADD CONSTRAINT FKC77C08FC600F3EA FOREIGN KEY (TYPE)
    REFERENCES KSCO_TAG_TYPE (TYPE_KEY)
/


ALTER TABLE KSCO_TAG_ATTR
    ADD CONSTRAINT FKC1BECBA155D86F09 FOREIGN KEY (OWNER)
    REFERENCES KSCO_TAG (ID)
/



ALTER TABLE KSCO_TAG_TYPE_ATTR
    ADD CONSTRAINT FK43900C26CC1E5763 FOREIGN KEY (OWNER)
    REFERENCES KSCO_TAG_TYPE (TYPE_KEY)
/


ALTER TABLE KSDO_DOCUMENT
    ADD CONSTRAINT FKB5CCDBE7B107314A FOREIGN KEY (RT_DESCR_ID)
    REFERENCES KSDO_RICH_TEXT_T (ID)
/

ALTER TABLE KSDO_DOCUMENT
    ADD CONSTRAINT FKB5CCDBE723B9E99F FOREIGN KEY (TYPE)
    REFERENCES KSDO_DOCUMENT_TYPE (TYPE_KEY)
/


ALTER TABLE KSDO_DOCUMENT_ATTR
    ADD CONSTRAINT FK4E8D0749BB72873E FOREIGN KEY (OWNER)
    REFERENCES KSDO_DOCUMENT (DOC_ID)
/


ALTER TABLE KSDO_DOCUMENT_CATEGORY
    ADD CONSTRAINT FK88CC7656B107314A FOREIGN KEY (RT_DESCR_ID)
    REFERENCES KSDO_RICH_TEXT_T (ID)
/


ALTER TABLE KSDO_DOCUMENT_CATEGORY_ATTR
    ADD CONSTRAINT FKAA79A3AD5A3ED5C FOREIGN KEY (OWNER)
    REFERENCES KSDO_DOCUMENT_CATEGORY (CATEGORY_ID)
/


ALTER TABLE KSDO_DOCUMENT_JN_DOC_CATEGORY
    ADD CONSTRAINT FKDEC8A308660DD60D FOREIGN KEY (DOC_ID)
    REFERENCES KSDO_DOCUMENT (DOC_ID)
/

ALTER TABLE KSDO_DOCUMENT_JN_DOC_CATEGORY
    ADD CONSTRAINT FKDEC8A3082AF8A6A5 FOREIGN KEY (CATEGORY_ID)
    REFERENCES KSDO_DOCUMENT_CATEGORY (CATEGORY_ID)
/



ALTER TABLE KSDO_DOCUMENT_TYPE_ATTR
    ADD CONSTRAINT FK541CD97E29D74D18 FOREIGN KEY (OWNER)
    REFERENCES KSDO_DOCUMENT_TYPE (TYPE_KEY)
/



ALTER TABLE KSEM_CTX_ENT
    ADD CONSTRAINT FKF0BED564A2AE7410 FOREIGN KEY (ENUM_VAL_ENT_ID)
    REFERENCES KSEM_ENUM_VAL_ENT (ID)
/





ALTER TABLE KSEM_ENUM_VAL_FLD_ENT
    ADD CONSTRAINT FKA52CFC1D32448E4B FOREIGN KEY (ENUM_META_ENT_ID)
    REFERENCES KSEM_ENUM_META_ENT (ID)
/



ALTER TABLE KSLU_CLU
    ADD CONSTRAINT FK1C27ACBEA8DCF088 FOREIGN KEY (PRI_INSTR_ID)
    REFERENCES KSLU_CLU_INSTR (ID)
/

ALTER TABLE KSLU_CLU
    ADD CONSTRAINT FK1C27ACBE7B914161 FOREIGN KEY (LUTYPE_ID)
    REFERENCES KSLU_LUTYPE (TYPE_KEY)
/

ALTER TABLE KSLU_CLU
    ADD CONSTRAINT FK1C27ACBEABDD272F FOREIGN KEY (RT_DESCR_ID)
    REFERENCES KSLU_RICH_TEXT_T (ID)
/

ALTER TABLE KSLU_CLU
    ADD CONSTRAINT FK1C27ACBE4BA2C995 FOREIGN KEY (FEE_ID)
    REFERENCES KSLU_CLU_FEE (ID)
/

ALTER TABLE KSLU_CLU
    ADD CONSTRAINT FK1C27ACBE29BAD238 FOREIGN KEY (PRI_ADMIN_ORG_ID)
    REFERENCES KSLU_CLU_ADMIN_ORG (ID)
/

ALTER TABLE KSLU_CLU
    ADD CONSTRAINT FK1C27ACBE3C2119F2 FOREIGN KEY (OFFIC_CLU_ID)
    REFERENCES KSLU_CLU_IDENT (ID)
/

ALTER TABLE KSLU_CLU
    ADD CONSTRAINT FK1C27ACBEDB74FD61 FOREIGN KEY (ACCT_ID)
    REFERENCES KSLU_CLU_ACCT (ID)
/


ALTER TABLE KSLU_CLUCLU_RELTN
    ADD CONSTRAINT FK223044C24AF8DD33 FOREIGN KEY (CLU_ID)
    REFERENCES KSLU_CLU (ID)
/

ALTER TABLE KSLU_CLUCLU_RELTN
    ADD CONSTRAINT FK223044C28B447C7 FOREIGN KEY (RELATED_CLU_ID)
    REFERENCES KSLU_CLU (ID)
/

ALTER TABLE KSLU_CLUCLU_RELTN
    ADD CONSTRAINT FK223044C2623647AD FOREIGN KEY (LU_RELTN_TYPE_ID)
    REFERENCES KSLU_LULU_RELTN_TYPE (ID)
/


ALTER TABLE KSLU_CLUCLU_RELTN_ATTR
    ADD CONSTRAINT FK15BFEF4E2E7C6896 FOREIGN KEY (OWNER)
    REFERENCES KSLU_CLUCLU_RELTN (ID)
/


ALTER TABLE KSLU_CLURES_JN_RESOPT
    ADD CONSTRAINT FKDB4074713C2D582F FOREIGN KEY (CLU_RES_ID)
    REFERENCES KSLU_CLU_RSLT (ID)
/

ALTER TABLE KSLU_CLURES_JN_RESOPT
    ADD CONSTRAINT FKDB407471240CE2BF FOREIGN KEY (RES_OPT_ID)
    REFERENCES KSLU_RSLT_OPT (ID)
/



ALTER TABLE KSLU_CLU_ACCRED_ATTR
    ADD CONSTRAINT FK8EF5565F1CC528C8 FOREIGN KEY (OWNER)
    REFERENCES KSLU_CLU_ACCRED (ID)
/



ALTER TABLE KSLU_CLU_ACCT_ATTR
    ADD CONSTRAINT FK6ABF605C27F3734D FOREIGN KEY (OWNER)
    REFERENCES KSLU_CLU_ACCT (ID)
/


ALTER TABLE KSLU_CLU_ACCT_JN_AFFIL_ORG
    ADD CONSTRAINT FKFBE9FBD9E2723997 FOREIGN KEY (AFFIL_ORG_ID)
    REFERENCES KSLU_CLU_AFFIL_ORG (ID)
/

ALTER TABLE KSLU_CLU_ACCT_JN_AFFIL_ORG
    ADD CONSTRAINT FKFBE9FBD9CEB8394E FOREIGN KEY (CLU_ACCT_ID)
    REFERENCES KSLU_CLU_ACCT (ID)
/



ALTER TABLE KSLU_CLU_ADMIN_ORG_ATTR
    ADD CONSTRAINT FK6100AB3D66E32B0D FOREIGN KEY (OWNER)
    REFERENCES KSLU_CLU_ADMIN_ORG (ID)
/


ALTER TABLE KSLU_CLU_AFFIL_ORG
    ADD CONSTRAINT FK2D521B681375653D FOREIGN KEY (CLU_FEE_RCRD_ID)
    REFERENCES KSLU_CLU_FEE_REC (ID)
/


ALTER TABLE KSLU_CLU_ATP_TYPE_KEY
    ADD CONSTRAINT FK75D2BD1D4AF8DD33 FOREIGN KEY (CLU_ID)
    REFERENCES KSLU_CLU (ID)
/


ALTER TABLE KSLU_CLU_ATTR
    ADD CONSTRAINT FK2F5624D2A2347ED8 FOREIGN KEY (OWNER)
    REFERENCES KSLU_CLU (ID)
/



ALTER TABLE KSLU_CLU_DOC_RELTN
    ADD CONSTRAINT FK182A988B70595BBA FOREIGN KEY (DESCR)
    REFERENCES KSLU_RICH_TEXT_T (ID)
/

ALTER TABLE KSLU_CLU_DOC_RELTN
    ADD CONSTRAINT FK182A988BED9B3478 FOREIGN KEY (LU_DOC_RELTN_TYPE_ID)
    REFERENCES KSLU_CLU_DOC_RELTN_TYPE (TYPE_KEY)
/

ALTER TABLE KSLU_CLU_DOC_RELTN
    ADD CONSTRAINT FK182A988B4AF8DD33 FOREIGN KEY (CLU_ID)
    REFERENCES KSLU_CLU (ID)
/


ALTER TABLE KSLU_CLU_DOC_RELTN_ATTR
    ADD CONSTRAINT FKC53F91257F147A7A FOREIGN KEY (OWNER)
    REFERENCES KSLU_CLU_DOC_RELTN (ID)
/



ALTER TABLE KSLU_CLU_DOC_RELTN_TYPE_ATTR
    ADD CONSTRAINT FK7C02192298954254 FOREIGN KEY (OWNER)
    REFERENCES KSLU_CLU_DOC_RELTN_TYPE (TYPE_KEY)
/



ALTER TABLE KSLU_CLU_FEEREC_JN_AFFIL_ORG
    ADD CONSTRAINT FKE784DE42E2723997 FOREIGN KEY (AFFIL_ORG_ID)
    REFERENCES KSLU_CLU_AFFIL_ORG (ID)
/

ALTER TABLE KSLU_CLU_FEEREC_JN_AFFIL_ORG
    ADD CONSTRAINT FKE784DE42269273C8 FOREIGN KEY (CLU_FEE_REC_ID)
    REFERENCES KSLU_CLU_FEE_REC (ID)
/


ALTER TABLE KSLU_CLU_FEE_ATTR
    ADD CONSTRAINT FK7059258B9E29CBD4 FOREIGN KEY (OWNER)
    REFERENCES KSLU_CLU_FEE (ID)
/


ALTER TABLE KSLU_CLU_FEE_JN_CLU_FEE_REC
    ADD CONSTRAINT FKADD2F483269273C8 FOREIGN KEY (CLU_FEE_REC_ID)
    REFERENCES KSLU_CLU_FEE_REC (ID)
/

ALTER TABLE KSLU_CLU_FEE_JN_CLU_FEE_REC
    ADD CONSTRAINT FKADD2F4836C41DC08 FOREIGN KEY (CLU_FEE_ID)
    REFERENCES KSLU_CLU_FEE (ID)
/



ALTER TABLE KSLU_CLU_FEE_REC_ATTR
    ADD CONSTRAINT FK5D2F8AFA35FC0785 FOREIGN KEY (OWNER)
    REFERENCES KSLU_CLU_FEE_REC (ID)
/




ALTER TABLE KSLU_CLU_INSTR_ATTR
    ADD CONSTRAINT FK57EAE5A5AAFE4155 FOREIGN KEY (OWNER)
    REFERENCES KSLU_CLU_INSTR (ID)
/


ALTER TABLE KSLU_CLU_JN_ACCRED
    ADD CONSTRAINT FKBF0CE98A4AF8DD33 FOREIGN KEY (CLU_ID)
    REFERENCES KSLU_CLU (ID)
/

ALTER TABLE KSLU_CLU_JN_ACCRED
    ADD CONSTRAINT FKBF0CE98ADD27220C FOREIGN KEY (CLU_ACCRED_ID)
    REFERENCES KSLU_CLU_ACCRED (ID)
/


ALTER TABLE KSLU_CLU_JN_ALT_ADMIN_ORG
    ADD CONSTRAINT FK160DFC244AF8DD33 FOREIGN KEY (CLU_ID)
    REFERENCES KSLU_CLU (ID)
/

ALTER TABLE KSLU_CLU_JN_ALT_ADMIN_ORG
    ADD CONSTRAINT FK160DFC24F49AE406 FOREIGN KEY (ALT_ORG_ID)
    REFERENCES KSLU_CLU_ADMIN_ORG (ID)
/


ALTER TABLE KSLU_CLU_JN_CAMP_LOC
    ADD CONSTRAINT FKA66ED2FC4AF8DD33 FOREIGN KEY (CLU_ID)
    REFERENCES KSLU_CLU (ID)
/


ALTER TABLE KSLU_CLU_JN_CLU_IDENT
    ADD CONSTRAINT FK5DA93983704D3F12 FOREIGN KEY (ALT_CLU_ID)
    REFERENCES KSLU_CLU_IDENT (ID)
/

ALTER TABLE KSLU_CLU_JN_CLU_IDENT
    ADD CONSTRAINT FK5DA939834AF8DD33 FOREIGN KEY (CLU_ID)
    REFERENCES KSLU_CLU (ID)
/


ALTER TABLE KSLU_CLU_JN_CLU_INSTR
    ADD CONSTRAINT FK5DADFA7F4AF8DD33 FOREIGN KEY (CLU_ID)
    REFERENCES KSLU_CLU (ID)
/

ALTER TABLE KSLU_CLU_JN_CLU_INSTR
    ADD CONSTRAINT FK5DADFA7F3AECA7A3 FOREIGN KEY (CLU_INSTR_ID)
    REFERENCES KSLU_CLU_INSTR (ID)
/


ALTER TABLE KSLU_CLU_JN_ORG
    ADD CONSTRAINT FKC16C47EA4AF8DD33 FOREIGN KEY (CLU_ID)
    REFERENCES KSLU_CLU (ID)
/


ALTER TABLE KSLU_CLU_JN_SUBJ_ORG
    ADD CONSTRAINT FK336471C94AF8DD33 FOREIGN KEY (CLU_ID)
    REFERENCES KSLU_CLU (ID)
/


ALTER TABLE KSLU_CLU_LO_ALOW_RELTN_TYPE
    ADD CONSTRAINT FK43C7BA17D39B0654 FOREIGN KEY (LU_TYPE_ID)
    REFERENCES KSLU_LUTYPE (TYPE_KEY)
/

ALTER TABLE KSLU_CLU_LO_ALOW_RELTN_TYPE
    ADD CONSTRAINT FK43C7BA17D6D7B842 FOREIGN KEY (CLULO_RELTN_TYPE_ID)
    REFERENCES KSLU_CLU_LO_RELTN_TYPE (TYPE_KEY)
/


ALTER TABLE KSLU_CLU_LO_RELTN
    ADD CONSTRAINT FK1C4705584AF8DD33 FOREIGN KEY (CLU_ID)
    REFERENCES KSLU_CLU (ID)
/


ALTER TABLE KSLU_CLU_LO_RELTN_ATTR
    ADD CONSTRAINT FK9BD81C78934B6957 FOREIGN KEY (OWNER)
    REFERENCES KSLU_CLU_LO_RELTN (ID)
/



ALTER TABLE KSLU_CLU_LO_RELTN_TYPE_ATTR
    ADD CONSTRAINT FKC3AAA9AFC7CF7AB1 FOREIGN KEY (OWNER)
    REFERENCES KSLU_CLU_LO_RELTN_TYPE (TYPE_KEY)
/


ALTER TABLE KSLU_CLU_PUBL
    ADD CONSTRAINT FK2F5CF7F0A8DCF088 FOREIGN KEY (PRI_INSTR_ID)
    REFERENCES KSLU_CLU_INSTR (ID)
/


ALTER TABLE KSLU_CLU_PUBL_ATTR
    ADD CONSTRAINT FK260A08E0CA43DD2B FOREIGN KEY (OWNER)
    REFERENCES KSLU_CLU_PUBL (ID)
/


ALTER TABLE KSLU_CLU_PUBL_JN_CLU_INSTR
    ADD CONSTRAINT FKFFFBF08DA92B9CB0 FOREIGN KEY (CLU_PUBL_ID)
    REFERENCES KSLU_CLU_PUBL (ID)
/

ALTER TABLE KSLU_CLU_PUBL_JN_CLU_INSTR
    ADD CONSTRAINT FKFFFBF08D3AECA7A3 FOREIGN KEY (CLU_INSTR_ID)
    REFERENCES KSLU_CLU_INSTR (ID)
/


ALTER TABLE KSLU_CLU_RESULT_TYPE_ATTR
    ADD CONSTRAINT FK250B779535BFA5AF FOREIGN KEY (OWNER)
    REFERENCES KSLU_CLU_RSLT_TYP (TYPE_KEY)
/


ALTER TABLE KSLU_CLU_RSLT
    ADD CONSTRAINT FK2F5DDA6A4AF8DD33 FOREIGN KEY (CLU_ID)
    REFERENCES KSLU_CLU (ID)
/

ALTER TABLE KSLU_CLU_RSLT
    ADD CONSTRAINT FK2F5DDA6AABDD272F FOREIGN KEY (RT_DESCR_ID)
    REFERENCES KSLU_RICH_TEXT_T (ID)
/


ALTER TABLE KSLU_CLU_RSLT_LU_ALOW_TYPE
    ADD CONSTRAINT FK1EF46125F7EE60B9 FOREIGN KEY (CLU_RSLT_TYPE_ID)
    REFERENCES KSLU_CLU_RSLT_TYP (TYPE_KEY)
/

ALTER TABLE KSLU_CLU_RSLT_LU_ALOW_TYPE
    ADD CONSTRAINT FK1EF46125D39B0654 FOREIGN KEY (LU_TYPE_ID)
    REFERENCES KSLU_LUTYPE (TYPE_KEY)
/



ALTER TABLE KSLU_CLU_SET
    ADD CONSTRAINT FK33138D41ABDD272F FOREIGN KEY (RT_DESCR_ID)
    REFERENCES KSLU_RICH_TEXT_T (ID)
/


ALTER TABLE KSLU_CLU_SET_ATTR
    ADD CONSTRAINT FKD0611E2F9E29FCB0 FOREIGN KEY (OWNER)
    REFERENCES KSLU_CLU_SET (ID)
/


ALTER TABLE KSLU_CLU_SET_JN_CLU
    ADD CONSTRAINT FK4B9E304F8277DE88 FOREIGN KEY (CLU_SET_ID)
    REFERENCES KSLU_CLU_SET (ID)
/

ALTER TABLE KSLU_CLU_SET_JN_CLU
    ADD CONSTRAINT FK4B9E304F4AF8DD33 FOREIGN KEY (CLU_ID)
    REFERENCES KSLU_CLU (ID)
/


ALTER TABLE KSLU_CLU_SET_JN_CLU_SET
    ADD CONSTRAINT FKF58BE0529DE0B55D FOREIGN KEY (CLU_SET_PARENT_ID)
    REFERENCES KSLU_CLU_SET (ID)
/

ALTER TABLE KSLU_CLU_SET_JN_CLU_SET
    ADD CONSTRAINT FKF58BE052C56A948B FOREIGN KEY (CLU_SET_CHILD_ID)
    REFERENCES KSLU_CLU_SET (ID)
/



ALTER TABLE KSLU_CLU_SET_TYPE_ATTR
    ADD CONSTRAINT FKE9E122585012B98A FOREIGN KEY (OWNER)
    REFERENCES KSLU_CLU_SET_TYPE (TYPE_KEY)
/



ALTER TABLE KSLU_DLVMTHD_TYPE_ATTR
    ADD CONSTRAINT FK6A1B07FA59848969 FOREIGN KEY (OWNER)
    REFERENCES KSLU_DLVMTHD_TYPE (TYPE_KEY)
/



ALTER TABLE KSLU_INSTFRMT_TYPE_ATTR
    ADD CONSTRAINT FK5406B7DE709F6516 FOREIGN KEY (OWNER)
    REFERENCES KSLU_INSTFRMT_TYPE (TYPE_KEY)
/


ALTER TABLE KSLU_LO
    ADD CONSTRAINT FK116CA3915CEF039A FOREIGN KEY (LO_REPO_ID)
    REFERENCES KSLU_LO_REPOSITORY (ID)
/

ALTER TABLE KSLU_LO
    ADD CONSTRAINT FK116CA391604442A3 FOREIGN KEY (RT_DESCR_ID)
    REFERENCES KSLO_RICH_TEXT_T (ID)
/

ALTER TABLE KSLU_LO
    ADD CONSTRAINT FK116CA391F0D1299B FOREIGN KEY (LOTYPE_ID)
    REFERENCES KSLU_LO_TYPE (ID)
/



ALTER TABLE KSLU_LOLO_RELTN
    ADD CONSTRAINT FK43828D88ED64FBFA FOREIGN KEY (LO_LO_RELATION_TYPE_ID)
    REFERENCES KSLU_LOLO_RELTN_TYPE (ID)
/

ALTER TABLE KSLU_LOLO_RELTN
    ADD CONSTRAINT FK43828D88A473D327 FOREIGN KEY (RELATED_LO_ID)
    REFERENCES KSLU_LO (ID)
/

ALTER TABLE KSLU_LOLO_RELTN
    ADD CONSTRAINT FK43828D888DD0E03B FOREIGN KEY (LO_ID)
    REFERENCES KSLU_LO (ID)
/


ALTER TABLE KSLU_LOLO_RELTN_ATTR
    ADD CONSTRAINT FK267A32483FCC956 FOREIGN KEY (OWNER)
    REFERENCES KSLU_LOLO_RELTN (ID)
/



ALTER TABLE KSLU_LOLO_RELTN_TYPE_ATTR
    ADD CONSTRAINT FKC6FDB5DFC0C2C330 FOREIGN KEY (OWNER)
    REFERENCES KSLU_LOLO_RELTN_TYPE (ID)
/


ALTER TABLE KSLU_LO_ATTR
    ADD CONSTRAINT FK14C979DF8DFF0197 FOREIGN KEY (OWNER)
    REFERENCES KSLU_LO (ID)
/


ALTER TABLE KSLU_LO_CATEGORY
    ADD CONSTRAINT FK1FC1ADEC5CEF039A FOREIGN KEY (LO_REPO_ID)
    REFERENCES KSLU_LO_REPOSITORY (ID)
/

ALTER TABLE KSLU_LO_CATEGORY
    ADD CONSTRAINT FK1FC1ADEC604442A3 FOREIGN KEY (RT_DESCR_ID)
    REFERENCES KSLO_RICH_TEXT_T (ID)
/

ALTER TABLE KSLU_LO_CATEGORY
    ADD CONSTRAINT FK1FC1ADEC9FBA4F97 FOREIGN KEY (LO_CATEGORY_TYPE_ID)
    REFERENCES KSLU_LO_CATEGORY_TYPE (ID)
/


ALTER TABLE KSLU_LO_CATEGORY_ATTR
    ADD CONSTRAINT FK5F53B06484E0FEB5 FOREIGN KEY (OWNER)
    REFERENCES KSLU_LO_CATEGORY (ID)
/



ALTER TABLE KSLU_LO_CATEGORY_TYPE_ATTR
    ADD CONSTRAINT FK602AA9431FBF310F FOREIGN KEY (OWNER)
    REFERENCES KSLU_LO_CATEGORY_TYPE (ID)
/


ALTER TABLE KSLU_LO_JN_LOCATEGORY
    ADD CONSTRAINT FK931B812ECF832A9B FOREIGN KEY (LOCATEGORY_ID)
    REFERENCES KSLU_LO_CATEGORY (ID)
/

ALTER TABLE KSLU_LO_JN_LOCATEGORY
    ADD CONSTRAINT FK931B812E8DD0E03B FOREIGN KEY (LO_ID)
    REFERENCES KSLU_LO (ID)
/


ALTER TABLE KSLU_LO_REPOSITORY
    ADD CONSTRAINT FK5D0D44B8BF253DC0 FOREIGN KEY (LO_ROOT_ID)
    REFERENCES KSLU_LO (ID)
/

ALTER TABLE KSLU_LO_REPOSITORY
    ADD CONSTRAINT FK5D0D44B8604442A3 FOREIGN KEY (RT_DESCR_ID)
    REFERENCES KSLO_RICH_TEXT_T (ID)
/


ALTER TABLE KSLU_LO_REPOSITORY_ATTR
    ADD CONSTRAINT FKBF279183CCD6C01 FOREIGN KEY (OWNER)
    REFERENCES KSLU_LO_REPOSITORY (ID)
/



ALTER TABLE KSLU_LO_TYPE_ATTR
    ADD CONSTRAINT FK9BCE94A8927CF2F1 FOREIGN KEY (OWNER)
    REFERENCES KSLU_LO_TYPE (ID)
/


ALTER TABLE KSLU_LUI
    ADD CONSTRAINT FK1C27CF924AF8DD33 FOREIGN KEY (CLU_ID)
    REFERENCES KSLU_CLU (ID)
/


ALTER TABLE KSLU_LUILUI_RELTN
    ADD CONSTRAINT FK928FC44218896747 FOREIGN KEY (RELATED_LUI_ID)
    REFERENCES KSLU_LUI (ID)
/

ALTER TABLE KSLU_LUILUI_RELTN
    ADD CONSTRAINT FK928FC4422D642336 FOREIGN KEY (LULU_RELTN_TYPE_ID)
    REFERENCES KSLU_LULU_RELTN_TYPE (ID)
/

ALTER TABLE KSLU_LUILUI_RELTN
    ADD CONSTRAINT FK928FC4425ACDFCB3 FOREIGN KEY (LUI_ID)
    REFERENCES KSLU_LUI (ID)
/


ALTER TABLE KSLU_LUILUI_RELTN_ATTR
    ADD CONSTRAINT FK9AA41FCE4FA0816 FOREIGN KEY (OWNER)
    REFERENCES KSLU_LUILUI_RELTN (ID)
/


ALTER TABLE KSLU_LUI_ATTR
    ADD CONSTRAINT FK9DDEA67EA234A1AC FOREIGN KEY (OWNER)
    REFERENCES KSLU_LUI (ID)
/



ALTER TABLE KSLU_LULU_RELTN_TYPE_ATTR
    ADD CONSTRAINT FK7CF7346B8C1B35C2 FOREIGN KEY (OWNER)
    REFERENCES KSLU_LULU_RELTN_TYPE (ID)
/


ALTER TABLE KSLU_LULU_RELTN_TYPE_JN_LU_TYP
    ADD CONSTRAINT FK7FA26BD62D642336 FOREIGN KEY (LULU_RELTN_TYPE_ID)
    REFERENCES KSLU_LULU_RELTN_TYPE (ID)
/

ALTER TABLE KSLU_LULU_RELTN_TYPE_JN_LU_TYP
    ADD CONSTRAINT FK7FA26BD6D39B0654 FOREIGN KEY (LU_TYPE_ID)
    REFERENCES KSLU_LUTYPE (TYPE_KEY)
/




ALTER TABLE KSLU_LU_CD_TYPE_ATTR
    ADD CONSTRAINT FK902BC92099BB190A FOREIGN KEY (OWNER)
    REFERENCES KSLU_LU_CD_TYPE (TYPE_KEY)
/


ALTER TABLE KSLU_LU_CODE
    ADD CONSTRAINT FK1F0761954AF8DD33 FOREIGN KEY (CLU_ID)
    REFERENCES KSLU_CLU (ID)
/


ALTER TABLE KSLU_LU_CODE_ATTR
    ADD CONSTRAINT FKB708DE5BADEE1C30 FOREIGN KEY (OWNER)
    REFERENCES KSLU_LU_CODE (ID)
/


ALTER TABLE KSLU_LU_LU_ALOW_RELTN_TYPE
    ADD CONSTRAINT FKE02CEEA4636807AE FOREIGN KEY (LU_REL_TYPE_ID)
    REFERENCES KSLU_LUTYPE (TYPE_KEY)
/

ALTER TABLE KSLU_LU_LU_ALOW_RELTN_TYPE
    ADD CONSTRAINT FKE02CEEA4EBCD3FA3 FOREIGN KEY (LU_LU_RELTN_TYPE_ID)
    REFERENCES KSLU_LULU_RELTN_TYPE (ID)
/

ALTER TABLE KSLU_LU_LU_ALOW_RELTN_TYPE
    ADD CONSTRAINT FKE02CEEA4D39B0654 FOREIGN KEY (LU_TYPE_ID)
    REFERENCES KSLU_LUTYPE (TYPE_KEY)
/



ALTER TABLE KSLU_LU_PUBL_TYPE_ATTR
    ADD CONSTRAINT FK13599A4E24194CA9 FOREIGN KEY (OWNER)
    REFERENCES KSLU_LU_PUBL_TYPE (TYPE_KEY)
/


ALTER TABLE KSLU_LU_TYPE_ATTR
    ADD CONSTRAINT FK192AC52EADF5FD7D FOREIGN KEY (OWNER)
    REFERENCES KSLU_LUTYPE (TYPE_KEY)
/



ALTER TABLE KSLU_RSLTUSAGE_LU_ALOW_TYPE
    ADD CONSTRAINT FKDB2D1C5D2401DB6 FOREIGN KEY (CLU_RSLT_USAGE_TYPE_ID)
    REFERENCES KSLU_RSLT_USG_TYPE (TYPE_KEY)
/

ALTER TABLE KSLU_RSLTUSAGE_LU_ALOW_TYPE
    ADD CONSTRAINT FKDB2D1C5D39B0654 FOREIGN KEY (LU_TYPE_ID)
    REFERENCES KSLU_LUTYPE (TYPE_KEY)
/


ALTER TABLE KSLU_RSLT_COMP_USG_ALOW_TYPE
    ADD CONSTRAINT FKAAE26348A4D1EA2B FOREIGN KEY (RSLT_USG_TYPE_ID)
    REFERENCES KSLU_RSLT_USG_TYPE (TYPE_KEY)
/


ALTER TABLE KSLU_RSLT_OPT
    ADD CONSTRAINT FKA7EA546BA81D7F8F FOREIGN KEY (RES_USAGE_ID)
    REFERENCES KSLU_RSLT_USG_TYPE (TYPE_KEY)
/

ALTER TABLE KSLU_RSLT_OPT
    ADD CONSTRAINT FKA7EA546BABDD272F FOREIGN KEY (RT_DESCR_ID)
    REFERENCES KSLU_RICH_TEXT_T (ID)
/



ALTER TABLE KSLU_RSLT_USG_TYPE_ATTR
    ADD CONSTRAINT FK1E3A8058D801410A FOREIGN KEY (OWNER)
    REFERENCES KSLU_RSLT_USG_TYPE (TYPE_KEY)
/


ALTER TABLE KSLU_RSRC
    ADD CONSTRAINT FK68D4D6C04AF8DD33 FOREIGN KEY (CLU_ID)
    REFERENCES KSLU_CLU (ID)
/



ALTER TABLE KSOR_ORG
    ADD CONSTRAINT FK211C1DD01427EAF0 FOREIGN KEY (TYPE)
    REFERENCES KSOR_ORG_TYPE (TYPE_KEY)
/


ALTER TABLE KSOR_ORG_ATTR
    ADD CONSTRAINT FK15378F00716FD90F FOREIGN KEY (OWNER)
    REFERENCES KSOR_ORG (ID)
/


ALTER TABLE KSOR_ORG_HIRCHY
    ADD CONSTRAINT FKB0E5A0D2612F0463 FOREIGN KEY (ROOT_ORG)
    REFERENCES KSOR_ORG (ID)
/


ALTER TABLE KSOR_ORG_HIRCHY_ATTR
    ADD CONSTRAINT FK89519D3EA52425EC FOREIGN KEY (OWNER)
    REFERENCES KSOR_ORG_HIRCHY (ID)
/


ALTER TABLE KSOR_ORG_HIRCHY_JN_ORG_TYPE
    ADD CONSTRAINT FKE484D0831A9136F5 FOREIGN KEY (ORG_HIRCHY_ID)
    REFERENCES KSOR_ORG_HIRCHY (ID)
/

ALTER TABLE KSOR_ORG_HIRCHY_JN_ORG_TYPE
    ADD CONSTRAINT FKE484D0836D0E6D9B FOREIGN KEY (ORG_TYPE_ID)
    REFERENCES KSOR_ORG_TYPE (TYPE_KEY)
/


ALTER TABLE KSOR_ORG_JN_ORG_PERS_REL_TYPE
    ADD CONSTRAINT FK109EE902278F274D FOREIGN KEY (ORG_PERS_RELTN_TYPE_ID)
    REFERENCES KSOR_ORG_PERS_RELTN_TYPE (TYPE_KEY)
/

ALTER TABLE KSOR_ORG_JN_ORG_PERS_REL_TYPE
    ADD CONSTRAINT FK109EE9022EFC8EB2 FOREIGN KEY (ORG_ID)
    REFERENCES KSOR_ORG (ID)
/


ALTER TABLE KSOR_ORG_ORG_RELTN
    ADD CONSTRAINT FK514793C96B1D9540 FOREIGN KEY (ORG)
    REFERENCES KSOR_ORG (ID)
/

ALTER TABLE KSOR_ORG_ORG_RELTN
    ADD CONSTRAINT FK514793C9AD78532C FOREIGN KEY (RELATED_ORG)
    REFERENCES KSOR_ORG (ID)
/

ALTER TABLE KSOR_ORG_ORG_RELTN
    ADD CONSTRAINT FK514793C9F9D0C998 FOREIGN KEY (TYPE)
    REFERENCES KSOR_ORG_ORG_RELTN_TYPE (TYPE_KEY)
/


ALTER TABLE KSOR_ORG_ORG_RELTN_ATTR
    ADD CONSTRAINT FK97D3ECA7D0624BB7 FOREIGN KEY (OWNER)
    REFERENCES KSOR_ORG_ORG_RELTN (ID)
/


ALTER TABLE KSOR_ORG_ORG_RELTN_TYPE
    ADD CONSTRAINT FK97DCA1F0B59FB077 FOREIGN KEY (ORG_HIRCHY)
    REFERENCES KSOR_ORG_HIRCHY (ID)
/


ALTER TABLE KSOR_ORG_ORG_RELTN_TYPE_ATTR
    ADD CONSTRAINT FK4CC49EE0FFEE2D11 FOREIGN KEY (OWNER)
    REFERENCES KSOR_ORG_ORG_RELTN_TYPE (TYPE_KEY)
/


ALTER TABLE KSOR_ORG_PERS_RELTN
    ADD CONSTRAINT FK573FBFF96B1D9540 FOREIGN KEY (ORG)
    REFERENCES KSOR_ORG (ID)
/

ALTER TABLE KSOR_ORG_PERS_RELTN
    ADD CONSTRAINT FK573FBFF97A24137B FOREIGN KEY (ORG_PERS_RELTN_TYPE)
    REFERENCES KSOR_ORG_PERS_RELTN_TYPE (TYPE_KEY)
/


ALTER TABLE KSOR_ORG_PERS_RELTN_ATTR
    ADD CONSTRAINT FKF3FFDE77556628A0 FOREIGN KEY (OWNER)
    REFERENCES KSOR_ORG_PERS_RELTN (ID)
/



ALTER TABLE KSOR_ORG_PERS_RELTN_TYPE_ATTR
    ADD CONSTRAINT FK76574F1074776D7A FOREIGN KEY (OWNER)
    REFERENCES KSOR_ORG_PERS_RELTN_TYPE (TYPE_KEY)
/


ALTER TABLE KSOR_ORG_POS_RESTR
    ADD CONSTRAINT FK28B35D849AD356D6 FOREIGN KEY (PERS_RELTN_TYPE)
    REFERENCES KSOR_ORG_PERS_RELTN_TYPE (TYPE_KEY)
/

ALTER TABLE KSOR_ORG_POS_RESTR
    ADD CONSTRAINT FK28B35D846B1D9540 FOREIGN KEY (ORG)
    REFERENCES KSOR_ORG (ID)
/


ALTER TABLE KSOR_ORG_POS_RESTR_ATTR
    ADD CONSTRAINT FKE877FFCC58A41D9A FOREIGN KEY (OWNER)
    REFERENCES KSOR_ORG_POS_RESTR (ID)
/



ALTER TABLE KSOR_ORG_TYPE_ATTR
    ADD CONSTRAINT FKBE358C271A454E69 FOREIGN KEY (OWNER)
    REFERENCES KSOR_ORG_TYPE (TYPE_KEY)
/


ALTER TABLE KSOR_ORG_TYPE_JN_ORG_PERRL_TYP
    ADD CONSTRAINT FK10E58BE3278F274D FOREIGN KEY (ORG_PERS_RELTN_TYPE_ID)
    REFERENCES KSOR_ORG_PERS_RELTN_TYPE (TYPE_KEY)
/

ALTER TABLE KSOR_ORG_TYPE_JN_ORG_PERRL_TYP
    ADD CONSTRAINT FK10E58BE36D0E6D9B FOREIGN KEY (ORG_TYPE_ID)
    REFERENCES KSOR_ORG_TYPE (TYPE_KEY)
/


ALTER TABLE KSPR_PROPOSAL
    ADD CONSTRAINT FK1ED72A27AEB6084D FOREIGN KEY (TYPE)
    REFERENCES KSPR_PROPOSAL_TYPE (TYPE_KEY)
/


ALTER TABLE KSPR_PROPOSAL_ATTR
    ADD CONSTRAINT FK82F9A10998B52CEC FOREIGN KEY (OWNER)
    REFERENCES KSPR_PROPOSAL (PROPOSAL_ID)
/


ALTER TABLE KSPR_PROPOSAL_DOCREL
    ADD CONSTRAINT FKAFE5E579F4EE03C1 FOREIGN KEY (PROPOSAL_ID)
    REFERENCES KSPR_PROPOSAL (PROPOSAL_ID)
/

ALTER TABLE KSPR_PROPOSAL_DOCREL
    ADD CONSTRAINT FKAFE5E579E5848F8 FOREIGN KEY (RT_DESCR_ID)
    REFERENCES KSPR_RICH_TEXT_T (ID)
/

ALTER TABLE KSPR_PROPOSAL_DOCREL
    ADD CONSTRAINT FKAFE5E57989B4986F FOREIGN KEY (TYPE)
    REFERENCES KSPR_PROPOSAL_DOCREL_TYPE (ID)
/


ALTER TABLE KSPR_PROPOSAL_DOCREL_ATTR
    ADD CONSTRAINT FK10D528F785351E0E FOREIGN KEY (OWNER)
    REFERENCES KSPR_PROPOSAL_DOCREL (DOCREL_ID)
/



ALTER TABLE KSPR_PROPOSAL_DOCREL_TYPE_ATTR
    ADD CONSTRAINT FK37AC94908FD1FBE8 FOREIGN KEY (OWNER)
    REFERENCES KSPR_PROPOSAL_DOCREL_TYPE (ID)
/


ALTER TABLE KSPR_PROPOSAL_JN_ORG
    ADD CONSTRAINT FKBA219261F4EE03C1 FOREIGN KEY (PROPOSAL_ID)
    REFERENCES KSPR_PROPOSAL (PROPOSAL_ID)
/


ALTER TABLE KSPR_PROPOSAL_JN_PERSON
    ADD CONSTRAINT FK49CD2E98F4EE03C1 FOREIGN KEY (PROPOSAL_ID)
    REFERENCES KSPR_PROPOSAL (PROPOSAL_ID)
/


ALTER TABLE KSPR_PROPOSAL_JN_REFERENCE
    ADD CONSTRAINT FKF242C508B5137FA1 FOREIGN KEY (REFERENCE_ID)
    REFERENCES KSPR_PROPOSAL_REFERENCE (REFERENCE_ID)
/

ALTER TABLE KSPR_PROPOSAL_JN_REFERENCE
    ADD CONSTRAINT FKF242C508F4EE03C1 FOREIGN KEY (PROPOSAL_ID)
    REFERENCES KSPR_PROPOSAL (PROPOSAL_ID)
/


ALTER TABLE KSPR_PROPOSAL_REFERENCE
    ADD CONSTRAINT FK8762F132C914EA6 FOREIGN KEY (TYPE)
    REFERENCES KSPR_PROPOSAL_REFTYPE (TYPE_KEY)
/



ALTER TABLE KSPR_PROPOSAL_REFTYPE_ATTR
    ADD CONSTRAINT FK706DC3DB32AEB21F FOREIGN KEY (OWNER)
    REFERENCES KSPR_PROPOSAL_REFTYPE (TYPE_KEY)
/



ALTER TABLE KSPR_PROPOSAL_TYPE_ATTR
    ADD CONSTRAINT FK604A57BEB4D36BC6 FOREIGN KEY (OWNER)
    REFERENCES KSPR_PROPOSAL_TYPE (TYPE_KEY)
/





ALTER TABLE KSST_OBJECT_SUB_TYPE_ATTR
    ADD CONSTRAINT FK6822C42D41D3A583 FOREIGN KEY (OWNER)
    REFERENCES KSST_OBJECT_SUB_TYPE (TYPE_KEY)
/



ALTER TABLE KSST_OBJECT_TYPE_ATTR
    ADD CONSTRAINT FK8E00FA8C9B9EC77 FOREIGN KEY (OWNER)
    REFERENCES KSST_OBJECT_TYPE (TYPE_KEY)
/


ALTER TABLE KSST_OBJ_TYP_JN_OBJ_SUB_TYP
    ADD CONSTRAINT FKC5BC31DBE9ED08C9 FOREIGN KEY (OBJ_SUB_TYPE_ID)
    REFERENCES KSST_OBJECT_SUB_TYPE (TYPE_KEY)
/

ALTER TABLE KSST_OBJ_TYP_JN_OBJ_SUB_TYP
    ADD CONSTRAINT FKC5BC31DBD4B946BC FOREIGN KEY (OBJ_TYPE_ID)
    REFERENCES KSST_OBJECT_TYPE (TYPE_KEY)
/


ALTER TABLE KSST_RCTYP_JN_RCFLDTYP
    ADD CONSTRAINT FK63DCE85E76C3C296 FOREIGN KEY (REQ_COMP_FIELD_TYPE_ID)
    REFERENCES KSST_REQ_COM_FIELD_TYPE (ID)
/

ALTER TABLE KSST_RCTYP_JN_RCFLDTYP
    ADD CONSTRAINT FK63DCE85ECF3E3955 FOREIGN KEY (REQ_COMP_TYPE_ID)
    REFERENCES KSST_REQ_COM_TYPE (TYPE_KEY)
/


ALTER TABLE KSST_RC_JN_RC_FIELD
    ADD CONSTRAINT FK6231120F73475AAF FOREIGN KEY (REQ_COM_FIELD_ID)
    REFERENCES KSST_REQ_COM_FIELD (ID)
/

ALTER TABLE KSST_RC_JN_RC_FIELD
    ADD CONSTRAINT FK6231120FA2C14D44 FOREIGN KEY (REQ_COM_ID)
    REFERENCES KSST_REQ_COM (ID)
/


ALTER TABLE KSST_REF_STMT_REL
    ADD CONSTRAINT FK815B8C84DA6CC5CC FOREIGN KEY (REF_STMT_REL_TYPE_ID)
    REFERENCES KSST_REF_STMT_REL_TYPE (TYPE_KEY)
/

ALTER TABLE KSST_REF_STMT_REL
    ADD CONSTRAINT FK815B8C84536B9256 FOREIGN KEY (STMT_ID)
    REFERENCES KSST_STMT (ID)
/


ALTER TABLE KSST_REF_STMT_REL_ATTR
    ADD CONSTRAINT FKEC9530CC7D48EBD6 FOREIGN KEY (OWNER)
    REFERENCES KSST_REF_STMT_REL (ID)
/



ALTER TABLE KSST_REF_STMT_REL_TYPE_ATTR
    ADD CONSTRAINT FK115129DB9A39A5B0 FOREIGN KEY (OWNER)
    REFERENCES KSST_REF_STMT_REL_TYPE (TYPE_KEY)
/


ALTER TABLE KSST_REQ_COM
    ADD CONSTRAINT FK5A2429AA59395123 FOREIGN KEY (RT_DESCR_ID)
    REFERENCES KSST_RICH_TEXT_T (ID)
/

ALTER TABLE KSST_REQ_COM
    ADD CONSTRAINT FK5A2429AA2D8571A5 FOREIGN KEY (REQ_COM_TYPE_ID)
    REFERENCES KSST_REQ_COM_TYPE (TYPE_KEY)
/





ALTER TABLE KSST_REQ_COM_TYPE_ATTR
    ADD CONSTRAINT FKEBAC0F81F5BE52F7 FOREIGN KEY (OWNER)
    REFERENCES KSST_REQ_COM_TYPE (TYPE_KEY)
/


ALTER TABLE KSST_REQ_COM_TYPE_NL_TMPL
    ADD CONSTRAINT FKE878886F5BE52F7 FOREIGN KEY (OWNER)
    REFERENCES KSST_REQ_COM_TYPE (TYPE_KEY)
/



ALTER TABLE KSST_RSTMT_RTYP_JN_OSUB_TYP
    ADD CONSTRAINT FKE007888DE9ED08C9 FOREIGN KEY (OBJ_SUB_TYPE_ID)
    REFERENCES KSST_OBJECT_SUB_TYPE (TYPE_KEY)
/

ALTER TABLE KSST_RSTMT_RTYP_JN_OSUB_TYP
    ADD CONSTRAINT FKE007888DDA6CC5CC FOREIGN KEY (REF_STMT_REL_TYPE_ID)
    REFERENCES KSST_REF_STMT_REL_TYPE (TYPE_KEY)
/


ALTER TABLE KSST_RSTMT_RTYP_JN_STMT_TYP
    ADD CONSTRAINT FKA7C95964DA6CC5CC FOREIGN KEY (REF_STMT_REL_TYPE_ID)
    REFERENCES KSST_REF_STMT_REL_TYPE (TYPE_KEY)
/

ALTER TABLE KSST_RSTMT_RTYP_JN_STMT_TYP
    ADD CONSTRAINT FKA7C95964B559587 FOREIGN KEY (STMT_TYPE_ID)
    REFERENCES KSST_STMT_TYPE (TYPE_KEY)
/


ALTER TABLE KSST_STMT
    ADD CONSTRAINT FKD96C147E628FF7C1 FOREIGN KEY (PARENT_STMT_ID)
    REFERENCES KSST_STMT (ID)
/

ALTER TABLE KSST_STMT
    ADD CONSTRAINT FKD96C147E59395123 FOREIGN KEY (RT_DESCR_ID)
    REFERENCES KSST_RICH_TEXT_T (ID)
/

ALTER TABLE KSST_STMT
    ADD CONSTRAINT FKD96C147EB559587 FOREIGN KEY (STMT_TYPE_ID)
    REFERENCES KSST_STMT_TYPE (TYPE_KEY)
/


ALTER TABLE KSST_STMT_ATTR
    ADD CONSTRAINT FK275C9512CA2A9017 FOREIGN KEY (OWNER)
    REFERENCES KSST_STMT (ID)
/


ALTER TABLE KSST_STMT_JN_REQ_COM
    ADD CONSTRAINT FKF9105486536B9256 FOREIGN KEY (STMT_ID)
    REFERENCES KSST_STMT (ID)
/

ALTER TABLE KSST_STMT_JN_REQ_COM
    ADD CONSTRAINT FKF9105486A2C14D44 FOREIGN KEY (REQ_COM_ID)
    REFERENCES KSST_REQ_COM (ID)
/



ALTER TABLE KSST_STMT_TYPE_ATTR
    ADD CONSTRAINT FK96FB8155993D4171 FOREIGN KEY (OWNER)
    REFERENCES KSST_STMT_TYPE (TYPE_KEY)
/


ALTER TABLE KSST_STMT_TYP_JN_RC_TYP
    ADD CONSTRAINT FKEE1C67E3B559587 FOREIGN KEY (STMT_TYPE_ID)
    REFERENCES KSST_STMT_TYPE (TYPE_KEY)
/

ALTER TABLE KSST_STMT_TYP_JN_RC_TYP
    ADD CONSTRAINT FKEE1C67E32D8571A5 FOREIGN KEY (REQ_COM_TYPE_ID)
    REFERENCES KSST_REQ_COM_TYPE (TYPE_KEY)
/


ALTER TABLE KSST_STMT_TYP_JN_STMT_TYP
    ADD CONSTRAINT FKA518B07AB559587 FOREIGN KEY (STMT_TYPE_ID)
    REFERENCES KSST_STMT_TYPE (TYPE_KEY)
/

ALTER TABLE KSST_STMT_TYP_JN_STMT_TYP
    ADD CONSTRAINT FKA518B07A861B91E9 FOREIGN KEY (CHLD_STMT_TYPE_ID)
    REFERENCES KSST_STMT_TYPE (TYPE_KEY)
/


ALTER TABLE KSST_USAGE_TYPE_ATTR
    ADD CONSTRAINT FKC4CAC8226B3DADC5 FOREIGN KEY (OWNER)
    REFERENCES KSST_NL_USAGE_TYPE (TYPE_KEY)
/


