ALTER TABLE KSEN_LRC_RES_SCALE_ATTR RENAME COLUMN OWNER to OWNER_ID
/

ALTER TABLE KSEN_LRR_ATTR RENAME COLUMN OWNER to OWNER_ID
/

ALTER TABLE KSEN_LRR_RES_SOURCE_ATTR RENAME COLUMN OWNER to OWNER_ID
/

ALTER TABLE KSEN_LRC_RES_VALUE_ATTR RENAME COLUMN OWNER to OWNER_ID
/

ALTER TABLE KSEN_LRC_RES_VAL_GRP_ATTR RENAME COLUMN OWNER to OWNER_ID
/







