
package org.kuali.student.lum.lu.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.1.4
 * Tue Feb 24 12:25:30 EST 2009
 * Generated source version: 2.1.4
 */

@XmlRootElement(name = "createLuStatement", namespace = "http://student.kuali.org/wsdl/lu")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "createLuStatement", namespace = "http://student.kuali.org/wsdl/lu", propOrder = {"luStatementType","luStatementInfo"})

public class CreateLuStatement {

    @XmlElement(name = "luStatementType")
    private java.lang.String luStatementType;
    @XmlElement(name = "luStatementInfo")
    private org.kuali.student.lum.lu.dto.LuStatementInfo luStatementInfo;

    public java.lang.String getLuStatementType() {
        return this.luStatementType;
    }

    public void setLuStatementType(java.lang.String newLuStatementType)  {
        this.luStatementType = newLuStatementType;
    }

    public org.kuali.student.lum.lu.dto.LuStatementInfo getLuStatementInfo() {
        return this.luStatementInfo;
    }

    public void setLuStatementInfo(org.kuali.student.lum.lu.dto.LuStatementInfo newLuStatementInfo)  {
        this.luStatementInfo = newLuStatementInfo;
    }

}

