
package org.kuali.student.lum.lu.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.2
 * Wed Sep 02 13:54:20 PDT 2009
 * Generated source version: 2.2
 */

@XmlRootElement(name = "getLuStatements", namespace = "http://student.kuali.org/wsdl/lu")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getLuStatements", namespace = "http://student.kuali.org/wsdl/lu")

public class GetLuStatements {

    @XmlElement(name = "luStatementIdList")
    private java.util.List<java.lang.String> luStatementIdList;

    public java.util.List<java.lang.String> getLuStatementIdList() {
        return this.luStatementIdList;
    }

    public void setLuStatementIdList(java.util.List<java.lang.String> newLuStatementIdList)  {
        this.luStatementIdList = newLuStatementIdList;
    }

}

