
package org.kuali.student.lum.lu.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.1.4
 * Tue Feb 24 12:25:30 EST 2009
 * Generated source version: 2.1.4
 */

@XmlRootElement(name = "searchForClus", namespace = "http://student.kuali.org/wsdl/lu")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "searchForClus", namespace = "http://student.kuali.org/wsdl/lu")

public class SearchForClus {

    @XmlElement(name = "cluCriteria")
    private org.kuali.student.lum.lu.dto.CluCriteriaInfo cluCriteria;

    public org.kuali.student.lum.lu.dto.CluCriteriaInfo getCluCriteria() {
        return this.cluCriteria;
    }

    public void setCluCriteria(org.kuali.student.lum.lu.dto.CluCriteriaInfo newCluCriteria)  {
        this.cluCriteria = newCluCriteria;
    }

}

