
package org.kuali.student.brms.statement.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.2
 * Tue Jan 26 22:57:16 PST 2010
 * Generated source version: 2.2
 */

@XmlRootElement(name = "getRefStatementRelationResponse", namespace = "http://student.kuali.org/wsdl/statement")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getRefStatementRelationResponse", namespace = "http://student.kuali.org/wsdl/statement")

public class GetRefStatementRelationResponse {

    @XmlElement(name = "return")
    private org.kuali.student.brms.statement.dto.RefStatementRelationInfo _return;

    public org.kuali.student.brms.statement.dto.RefStatementRelationInfo getReturn() {
        return this._return;
    }

    public void setReturn(org.kuali.student.brms.statement.dto.RefStatementRelationInfo new_return)  {
        this._return = new_return;
    }

}

