
package org.kuali.student.common_test_tester.support.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by the CXF 2.0.4-incubator
 * Tue Apr 15 10:46:55 EDT 2008
 * Generated source version: 2.0.4-incubator
 * 
 */

@XmlRootElement(name = "saveStringResponse", namespace = "http://student.kuali.org/poc/wsdl/test/my")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "saveStringResponse", namespace = "http://student.kuali.org/poc/wsdl/test/my")

public class SaveStringResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String get_return() {
        return this._return;
    }
    
    public void set_return( java.lang.String new_return ) {
        this._return = new_return;
    }
    
}

