TRUNCATE TABLE KSDO_RICH_TEXT_T DROP STORAGE
/
INSERT INTO KSDO_RICH_TEXT_T (ID,PLAIN)
  VALUES ('RT-DESC-DOCUMENT-1','Documents attached to a proposal')
/
INSERT INTO KSDO_RICH_TEXT_T (ID,PLAIN)
  VALUES ('RT-DESC-DOCUMENT-2','Documents attached to a Course')
/
