TRUNCATE TABLE KSST_REQ_COM_FIELD DROP STORAGE
/
INSERT INTO KSST_REQ_COM_FIELD (ID,REQ_COM_FIELD_KEY,VALUE)
  VALUES ('FIELD-1','reqCompFieldType.requiredCount','1')
/
INSERT INTO KSST_REQ_COM_FIELD (ID,REQ_COM_FIELD_KEY,VALUE)
  VALUES ('FIELD-10','reqCompFieldType.cluSet','CLUSET-NL-2')
/
INSERT INTO KSST_REQ_COM_FIELD (ID,REQ_COM_FIELD_KEY,VALUE)
  VALUES ('FIELD-11','reqCompFieldType.cluSet','CLUSET-NL-2')
/
INSERT INTO KSST_REQ_COM_FIELD (ID,REQ_COM_FIELD_KEY,VALUE)
  VALUES ('FIELD-12','reqCompFieldType.cluSet','CLUSET-NL-4')
/
INSERT INTO KSST_REQ_COM_FIELD (ID,REQ_COM_FIELD_KEY,VALUE)
  VALUES ('FIELD-13','reqCompFieldType.cluSet','CLUSET-NL-5')
/
INSERT INTO KSST_REQ_COM_FIELD (ID,REQ_COM_FIELD_KEY,VALUE)
  VALUES ('FIELD-14','reqCompFieldType.cluSet','CLUSET-NL-2')
/
INSERT INTO KSST_REQ_COM_FIELD (ID,REQ_COM_FIELD_KEY,VALUE)
  VALUES ('FIELD-2','reqCompFieldType.operator','greater_than_or_equal_to')
/
INSERT INTO KSST_REQ_COM_FIELD (ID,REQ_COM_FIELD_KEY,VALUE)
  VALUES ('FIELD-3','reqCompFieldType.cluSet','CLUSET-NL-1')
/
INSERT INTO KSST_REQ_COM_FIELD (ID,REQ_COM_FIELD_KEY,VALUE)
  VALUES ('FIELD-4','reqCompFieldType.gpa','3.5')
/
INSERT INTO KSST_REQ_COM_FIELD (ID,REQ_COM_FIELD_KEY,VALUE)
  VALUES ('FIELD-5','reqCompFieldType.requiredCount','1')
/
INSERT INTO KSST_REQ_COM_FIELD (ID,REQ_COM_FIELD_KEY,VALUE)
  VALUES ('FIELD-6','reqCompFieldType.operator','greater_than_or_equal_to')
/
INSERT INTO KSST_REQ_COM_FIELD (ID,REQ_COM_FIELD_KEY,VALUE)
  VALUES ('FIELD-7','reqCompFieldType.clu','CLU-NL-3, CLU-NL-4')
/
INSERT INTO KSST_REQ_COM_FIELD (ID,REQ_COM_FIELD_KEY,VALUE)
  VALUES ('FIELD-8','reqCompFieldType.operator','greater_than_or_equal_to')
/
INSERT INTO KSST_REQ_COM_FIELD (ID,REQ_COM_FIELD_KEY,VALUE)
  VALUES ('FIELD-9','reqCompFieldType.requiredCount','2')
/
