
CREATE  INDEX KSEN_LRC_RESULT_SCALE_ATTR_IF1 ON KSEN_LRC_RESULT_SCALE_ATTR
(OWNER_ID   ASC)
/


CREATE  INDEX KSEN_LRC_RESULT_VALUE_I1 ON KSEN_LRC_RESULT_VALUE
(RESULT_VALUE_TYPE   ASC,RESULT_VALUE_STATE   ASC,RESULT_VALUE   ASC)
/


CREATE  INDEX KSEN_LRC_RESULT_VAL_IF1 ON KSEN_LRC_RESULT_VALUE
(RESULT_SCALE_ID   ASC)
/


CREATE  INDEX KSEN_LRC_RESULT_VALUE_ATTR_IF1 ON KSEN_LRC_RESULT_VALUE_ATTR
(OWNER_ID   ASC)
/


CREATE  INDEX KSEN_LRC_RVG_I1 ON KSEN_LRC_RVG
(RVG_TYPE   ASC)
/


CREATE  INDEX KSEN_LRC_RVG_IF1 ON KSEN_LRC_RVG
(RESULT_SCALE_ID   ASC)
/


CREATE  INDEX KSEN_LRC_RVG_ATTR_IF1 ON KSEN_LRC_RVG_ATTR
(OWNER_ID   ASC)
/


ALTER TABLE KSEN_LRC_RVG_RESULT_VALUE
ADD CONSTRAINT  KSEN_LRC_RVG_RV_I1 UNIQUE (RESULT_VALUE_ID,RVG_ID)
/


CREATE  INDEX KSEN_LRC_RVG_RV_IF1 ON KSEN_LRC_RVG_RESULT_VALUE
(RVG_ID   ASC)
/


CREATE  INDEX KSEN_LRC_RVG_RV_IF2 ON KSEN_LRC_RVG_RESULT_VALUE
(RESULT_VALUE_ID   ASC)
/


ALTER TABLE KSEN_LRC_RESULT_SCALE_ATTR
	ADD (CONSTRAINT KSEN_LRC_RESULT_SCALE_ATTR_FK1 FOREIGN KEY (OWNER_ID) REFERENCES KSEN_LRC_RESULT_SCALE (ID))
/


ALTER TABLE KSEN_LRC_RESULT_VALUE
	ADD (CONSTRAINT KSEN_LRC_RESULT_VAL_FK1 FOREIGN KEY (RESULT_SCALE_ID) REFERENCES KSEN_LRC_RESULT_SCALE (ID))
/


ALTER TABLE KSEN_LRC_RESULT_VALUE_ATTR
	ADD (CONSTRAINT KSEN_LRC_RESULT_VALUE_ATTR_FK1 FOREIGN KEY (OWNER_ID) REFERENCES KSEN_LRC_RESULT_VALUE (ID))
/


ALTER TABLE KSEN_LRC_RVG
	ADD (CONSTRAINT KSEN_LRC_RVG_FK1 FOREIGN KEY (RESULT_SCALE_ID) REFERENCES KSEN_LRC_RESULT_SCALE (ID))
/


ALTER TABLE KSEN_LRC_RVG_ATTR
	ADD (CONSTRAINT KSEN_LRC_RVG_ATTR_FK1 FOREIGN KEY (OWNER_ID) REFERENCES KSEN_LRC_RVG (ID))
/


ALTER TABLE KSEN_LRC_RVG_RESULT_VALUE
	ADD (CONSTRAINT KSEN_LRC_RVG_RV_FK1 FOREIGN KEY (RVG_ID) REFERENCES KSEN_LRC_RVG (ID))
/


ALTER TABLE KSEN_LRC_RVG_RESULT_VALUE
	ADD (CONSTRAINT KSEN_LRC_RVG_RV_FK2 FOREIGN KEY (RESULT_VALUE_ID) REFERENCES KSEN_LRC_RESULT_VALUE (ID))
/
