--Add users to the KS-CM User Role
INSERT INTO KRIM_ROLE_MBR_T (MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR) 
  VALUES ('fred','P','KS_SYS_KS_CM_ROLE_MEMBER_1','899',KRIM_ROLE_MBR_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_MBR_T (MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR) 
  VALUES ('fran','P','KS_SYS_KS_CM_ROLE_MEMBER_2','899',KRIM_ROLE_MBR_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_MBR_T (MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR) 
  VALUES ('eric','P','KS_SYS_KS_CM_ROLE_MEMBER_3','899',KRIM_ROLE_MBR_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_MBR_T (MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR) 
  VALUES ('edna','P','KS_SYS_KS_CM_ROLE_MEMBER_4','899',KRIM_ROLE_MBR_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_MBR_T (MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR) 
  VALUES ('dev1','P','KS_SYS_KS_CM_ROLE_MEMBER_5','899',KRIM_ROLE_MBR_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_MBR_T (MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR) 
  VALUES ('dev2','P','KS_SYS_KS_CM_ROLE_MEMBER_6','899',KRIM_ROLE_MBR_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_MBR_T (MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR) 
  VALUES ('test1','P','KS_SYS_KS_CM_ROLE_MEMBER_7','899',KRIM_ROLE_MBR_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_MBR_T (MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR) 
  VALUES ('test2','P','KS_SYS_KS_CM_ROLE_MEMBER_8','899',KRIM_ROLE_MBR_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_MBR_T (MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR) 
  VALUES ('testuser1','P','KS_SYS_KS_CM_ROLE_MEMBER_9','899',KRIM_ROLE_MBR_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_MBR_T (MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR) 
  VALUES ('testuser2','P','KS_SYS_KS_CM_ROLE_MEMBER_10','899',KRIM_ROLE_MBR_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_MBR_T (MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR) 
  VALUES ('testuser3','P','KS_SYS_KS_CM_ROLE_MEMBER_11','899',KRIM_ROLE_MBR_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_MBR_T (MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR) 
  VALUES ('testuser4','P','KS_SYS_KS_CM_ROLE_MEMBER_12','899',KRIM_ROLE_MBR_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_MBR_T (MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR) 
  VALUES ('testuser5','P','KS_SYS_KS_CM_ROLE_MEMBER_13','899',KRIM_ROLE_MBR_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_MBR_T (MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR) 
  VALUES ('testuser6','P','KS_SYS_KS_CM_ROLE_MEMBER_14','899',KRIM_ROLE_MBR_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_MBR_T (MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR) 
  VALUES ('testuser7','P','KS_SYS_KS_CM_ROLE_MEMBER_15','899',KRIM_ROLE_MBR_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_MBR_T (MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR) 
  VALUES ('testuser8','P','KS_SYS_KS_CM_ROLE_MEMBER_16','899',KRIM_ROLE_MBR_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_MBR_T (MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR) 
  VALUES ('testuser9','P','KS_SYS_KS_CM_ROLE_MEMBER_17','899',KRIM_ROLE_MBR_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_MBR_T (MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR) 
  VALUES ('user1','P','KS_SYS_KS_CM_ROLE_MEMBER_18','899',KRIM_ROLE_MBR_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_MBR_T (MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR) 
  VALUES ('user2','P','KS_SYS_KS_CM_ROLE_MEMBER_19','899',KRIM_ROLE_MBR_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_MBR_T (MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR) 
  VALUES ('user3','P','KS_SYS_KS_CM_ROLE_MEMBER_20','899',KRIM_ROLE_MBR_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_MBR_T (MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR) 
  VALUES ('user4','P','KS_SYS_KS_CM_ROLE_MEMBER_21','899',KRIM_ROLE_MBR_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_MBR_T (MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR) 
  VALUES ('user5','P','KS_SYS_KS_CM_ROLE_MEMBER_22','899',KRIM_ROLE_MBR_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_MBR_T (MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR) 
  VALUES ('user6','P','KS_SYS_KS_CM_ROLE_MEMBER_23','899',KRIM_ROLE_MBR_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_MBR_T (MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR) 
  VALUES ('user7','P','KS_SYS_KS_CM_ROLE_MEMBER_24','899',KRIM_ROLE_MBR_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_MBR_T (MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR) 
  VALUES ('user8','P','KS_SYS_KS_CM_ROLE_MEMBER_25','899',KRIM_ROLE_MBR_ID_S.NEXTVAL,1)
/
INSERT INTO KRIM_ROLE_MBR_T (MBR_ID,MBR_TYP_CD,OBJ_ID,ROLE_ID,ROLE_MBR_ID,VER_NBR) 
  VALUES ('admin','P','KS_SYS_KS_CM_ROLE_MEMBER_26','899',KRIM_ROLE_MBR_ID_S.NEXTVAL,1)
/
