
package org.kuali.student.rules.rulemanagement.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.1
 * Thu Sep 25 10:29:50 EDT 2008
 * Generated source version: 2.1
 */

@XmlRootElement(name = "fetchBusinessRuleInfoDTO", namespace = "http://student.kuali.org/poc/wsdl/brms/rulemanagement")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fetchBusinessRuleInfoDTO", namespace = "http://student.kuali.org/poc/wsdl/brms/rulemanagement")

public class FetchBusinessRuleInfoDTO {

    @XmlElement(name = "arg0")
    private org.kuali.student.rules.rulemanagement.dto.BusinessRuleAnchorDTO arg0;

    public org.kuali.student.rules.rulemanagement.dto.BusinessRuleAnchorDTO getArg0() {
        return this.arg0;
    }

    public void setArg0(org.kuali.student.rules.rulemanagement.dto.BusinessRuleAnchorDTO newArg0)  {
        this.arg0 = newArg0;
    }

}

