
package org.kuali.student.rules.rulemanagement.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.1.2
 * Fri Nov 14 10:07:45 EST 2008
 * Generated source version: 2.1.2
 */

@XmlRootElement(name = "fetchBusinessRuleInfoByAnchor", namespace = "http://student.kuali.org/poc/wsdl/brms/rulemanagement")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fetchBusinessRuleInfoByAnchor", namespace = "http://student.kuali.org/poc/wsdl/brms/rulemanagement")

public class FetchBusinessRuleInfoByAnchor {

    @XmlElement(name = "arg0")
    private org.kuali.student.rules.rulemanagement.dto.BusinessRuleAnchorDTO arg0;

    public org.kuali.student.rules.rulemanagement.dto.BusinessRuleAnchorDTO getArg0() {
        return this.arg0;
    }

    public void setArg0(org.kuali.student.rules.rulemanagement.dto.BusinessRuleAnchorDTO newArg0)  {
        this.arg0 = newArg0;
    }

}

