
package org.kuali.student.core.dictionary.service.poc.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.2
 * Fri May 28 10:41:53 EDT 2010
 * Generated source version: 2.2
 */

@XmlRootElement(name = "getObjectStructureResponse", namespace = "http://student.kuali.org/wsdl/course")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getObjectStructureResponse", namespace = "http://student.kuali.org/wsdl/course")

public class GetObjectStructureResponse {

    @XmlElement(name = "return")
    private org.kuali.student.core.dictionary.poc.dto.ObjectStructureDefinition _return;

    public org.kuali.student.core.dictionary.poc.dto.ObjectStructureDefinition getReturn() {
        return this._return;
    }

    public void setReturn(org.kuali.student.core.dictionary.poc.dto.ObjectStructureDefinition new_return)  {
        this._return = new_return;
    }

}

