

ALTER TABLE KSEN_LPR_ATTR
    ADD CONSTRAINT KSEN_LPR_ATTR_FK1 FOREIGN KEY (OWNER_ID)
    REFERENCES KSEN_LPR (ID)
/


ALTER TABLE KSEN_LPR_RESULT_VAL_GRP
    ADD CONSTRAINT KSEN_LPR_RESULT_VAL_GRP_KF1 FOREIGN KEY (LPR_ID)
    REFERENCES KSEN_LPR (ID)
/



ALTER TABLE KSEN_LPR_ROSTER_ASSO_LUI_ID
    ADD CONSTRAINT KSEN_LPR_ROSTER_ASSO_LUI_ID_FK FOREIGN KEY (LPR_ROSTER_ID)
    REFERENCES KSEN_LPR_ROSTER (ID)
/


ALTER TABLE KSEN_LPR_ROSTER_ATTR
    ADD CONSTRAINT KSEN_LPR_ROSTER_FK1 FOREIGN KEY (OWNER_ID)
    REFERENCES KSEN_LPR_ROSTER (ID)
/


ALTER TABLE KSEN_LPR_ROSTER_ENTRY
    ADD CONSTRAINT KSEN_LPR_ROSTER_ENTRY_FK2 FOREIGN KEY (LPR_ROSTER_ID)
    REFERENCES KSEN_LPR_ROSTER (ID)
/

ALTER TABLE KSEN_LPR_ROSTER_ENTRY
    ADD CONSTRAINT KSEN_LPR_ROSTER_ENTRY_FK1 FOREIGN KEY (LPR_ID)
    REFERENCES KSEN_LPR (ID)
/


ALTER TABLE KSEN_LPR_ROSTER_ENTRY_ATTR
    ADD CONSTRAINT KSEN_LPR_ROSTER_ENTRY_ATTR_FK1 FOREIGN KEY (OWNER_ID)
    REFERENCES KSEN_LPR_ROSTER_ENTRY (ID)
/



ALTER TABLE KSEN_LPR_TRANS_ATTR
    ADD CONSTRAINT KSEN_LPR_TRANS_ATTR_FK1 FOREIGN KEY (OWNER_ID)
    REFERENCES KSEN_LPR_TRANS (ID)
/


ALTER TABLE KSEN_LPR_TRANS_ITEM
    ADD CONSTRAINT KSEN_LPR_TRANS_ITEM_FK1 FOREIGN KEY (LPR_TRANS_ID)
    REFERENCES KSEN_LPR_TRANS (ID)
/


ALTER TABLE KSEN_LPR_TRANS_ITEM_ATTR
    ADD CONSTRAINT KSEN_LPR_TRANS_ITEM_ATTR_FK1 FOREIGN KEY (OWNER_ID)
    REFERENCES KSEN_LPR_TRANS_ITEM (ID)
/


ALTER TABLE KSEN_LPR_TRANS_ITEM_RQST_OPT
    ADD CONSTRAINT KSEN_LPR_LTI_RQST_OPT_FK1 FOREIGN KEY (LPR_TRANS_ITEM_ID)
    REFERENCES KSEN_LPR_TRANS_ITEM (ID)
/


ALTER TABLE KSEN_LPR_TRANS_ITEM_RVG
    ADD CONSTRAINT KSEN_LPR_LTI_RVG_FK1 FOREIGN KEY (LPR_TRANS_ITEM_ID)
    REFERENCES KSEN_LPR_TRANS_ITEM (ID)
/

