
package edu.umd.ks.poc.lum.scat.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.1
 * Wed Oct 01 16:43:07 EDT 2008
 * Generated source version: 2.1
 */

@XmlRootElement(name = "searchScats", namespace = "http://edu.umd.ks/poc/lu/service/scat")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "searchScats", namespace = "http://edu.umd.ks/poc/lu/service/scat")

public class SearchScats {

    @XmlElement(name = "searchString")
    private java.lang.String searchString;

    public java.lang.String getSearchString() {
        return this.searchString;
    }

    public void setSearchString(java.lang.String newSearchString)  {
        this.searchString = newSearchString;
    }

}

