
package org.kuali.student.wsdl.course;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.3
 * Thu Aug 26 12:54:12 EDT 2010
 * Generated source version: 2.2.3
 * 
 */

@WebFault(name = "DataValidationErrorException", targetNamespace = "http://student.kuali.org/wsdl/course")
public class DataValidationErrorException extends Exception {
    public static final long serialVersionUID = 20100826125412L;
    
    private org.kuali.student.wsdl.exceptions.DataValidationErrorException dataValidationErrorException;

    public DataValidationErrorException() {
        super();
    }
    
    public DataValidationErrorException(String message) {
        super(message);
    }
    
    public DataValidationErrorException(String message, Throwable cause) {
        super(message, cause);
    }

    public DataValidationErrorException(String message, org.kuali.student.wsdl.exceptions.DataValidationErrorException dataValidationErrorException) {
        super(message);
        this.dataValidationErrorException = dataValidationErrorException;
    }

    public DataValidationErrorException(String message, org.kuali.student.wsdl.exceptions.DataValidationErrorException dataValidationErrorException, Throwable cause) {
        super(message, cause);
        this.dataValidationErrorException = dataValidationErrorException;
    }

    public org.kuali.student.wsdl.exceptions.DataValidationErrorException getFaultInfo() {
        return this.dataValidationErrorException;
    }
}
