
package org.kuali.student.wsdl.course;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.3
 * Thu Aug 26 12:54:12 EDT 2010
 * Generated source version: 2.2.3
 * 
 */

@WebFault(name = "UnsupportedActionException", targetNamespace = "http://student.kuali.org/wsdl/course")
public class UnsupportedActionException extends Exception {
    public static final long serialVersionUID = 20100826125412L;
    
    private org.kuali.student.wsdl.exceptions.UnsupportedActionException unsupportedActionException;

    public UnsupportedActionException() {
        super();
    }
    
    public UnsupportedActionException(String message) {
        super(message);
    }
    
    public UnsupportedActionException(String message, Throwable cause) {
        super(message, cause);
    }

    public UnsupportedActionException(String message, org.kuali.student.wsdl.exceptions.UnsupportedActionException unsupportedActionException) {
        super(message);
        this.unsupportedActionException = unsupportedActionException;
    }

    public UnsupportedActionException(String message, org.kuali.student.wsdl.exceptions.UnsupportedActionException unsupportedActionException, Throwable cause) {
        super(message, cause);
        this.unsupportedActionException = unsupportedActionException;
    }

    public org.kuali.student.wsdl.exceptions.UnsupportedActionException getFaultInfo() {
        return this.unsupportedActionException;
    }
}
