#!/usr/bin/env ruby
gem 'test-unit', '1.2.3' if RUBY_VERSION.to_f >= 1.9
ENV['RSPEC'] = 'true'     # allows autotest to discover rspec
ENV['AUTOTEST'] = 'true'  # allows autotest to run w/ color on linux
cmd = case RUBY_PLATFORM
  when /mswin|mingw/
    'autotest.bat'
  when /java/
    'jruby -S autotest'
  else
    'autotest'
end
result = system cmd, *ARGV
puts "bin/autospec complete with status #{$?}"