# Copyright 2010 The Kuali Foundation Licensed under the
# Educational Community License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may
# obtain a copy of the License at
#
# http://www.osedu.org/licenses/ECL-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an "AS IS"
# BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing
# permissions and limitations under the License.

/*package hello

import org.kuali.student.brms.repository.test.Email;
import org.kuali.student.brms.repository.test.Message;

rule "EmailValidationStrictRFC2822mvel"
    salience -2
    no-loop true
    dialect "mvel"
    when
       email : Email( EmailAddress != null ) 
       message : Message()
    then
       message.setMessage( "Email valid" ); message.setValid( true );
end
 */
 
package org.kuali.student.test

import java.util.regex.Pattern;
import org.kuali.student.brms.repository.test.Email;
import org.kuali.student.brms.repository.test.Message;

rule "rule1"
    dialect "mvel"
    when
        $email: Email( average  == -1 )
    then
        //System.out.println( "1-average=" + $email.getAverage() );
        //$email.calculateAverage();
        System.out.println( "1-average=" + $email.getAverage() );
        $email.calculateAverage();
        update( $email );
end

rule "rule2"
    dialect "mvel"
    when
        $email: Email( average > -1 && average < 50 )
    then
        System.out.println( "2-average=" + $email.getAverage() );
        $email.calculateAverage();
        update( $email );
end

rule "rule3"
    dialect "mvel"
    when
        $email: Email( average >= 50 )
    then
        System.out.println( "Exit: 3-average=" + $email.getAverage() );
end
