
package org.kuali.student.core.statement.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.2
 * Wed May 12 12:54:47 PDT 2010
 * Generated source version: 2.2
 */

@XmlRootElement(name = "updateStatementTreeView", namespace = "http://student.kuali.org/wsdl/statement")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateStatementTreeView", namespace = "http://student.kuali.org/wsdl/statement", propOrder = {"statementId","statementTreeViewInfo"})

public class UpdateStatementTreeView {

    @XmlElement(name = "statementId")
    private java.lang.String statementId;
    @XmlElement(name = "statementTreeViewInfo")
    private org.kuali.student.core.statement.dto.StatementTreeViewInfo statementTreeViewInfo;

    public java.lang.String getStatementId() {
        return this.statementId;
    }

    public void setStatementId(java.lang.String newStatementId)  {
        this.statementId = newStatementId;
    }

    public org.kuali.student.core.statement.dto.StatementTreeViewInfo getStatementTreeViewInfo() {
        return this.statementTreeViewInfo;
    }

    public void setStatementTreeViewInfo(org.kuali.student.core.statement.dto.StatementTreeViewInfo newStatementTreeViewInfo)  {
        this.statementTreeViewInfo = newStatementTreeViewInfo;
    }

}

