--  INSERTING into KSEN_LUI_IDENT
INSERT INTO KSEN_LUI_IDENT (ID, CD, DIVISION, SUFX_CD, LNG_NAME, SHRT_NAME, ST, TYPE, VARTN, VER_NBR) VALUES ('LUI-IDENT-1', 'CHEM123', 'CHEM', '123', 'Chemistry I', 'Chem 123', null, null, null, 0)
/
INSERT INTO KSEN_LUI_IDENT (ID, CD, DIVISION, SUFX_CD, LNG_NAME, SHRT_NAME, ST, TYPE, VARTN, VER_NBR) VALUES ('LUI-IDENT-2', 'CHEM234', 'CHEM', '234', 'Chemistry II', 'Chem 234', null, null, null, 0)
/
