
ALTER TABLE KSEN_CWL_ACTIV_OFFER
	ADD (CONSTRAINT KSEN_CWL_ACTIV_OFFER_FK1 FOREIGN KEY (CWL_ID) REFERENCES KSEN_CWL (ID))
/

ALTER TABLE KSEN_CWL_ATTR
	ADD (CONSTRAINT KSEN_CWL_ATTR_FK1 FOREIGN KEY (OWNER_ID) REFERENCES KSEN_CWL (ID))
/

ALTER TABLE KSEN_CWL_FORMAT_OFFER
	ADD (CONSTRAINT KSEN_CWL_FORMAT_OFFER_FK1 FOREIGN KEY (CWL_ID) REFERENCES KSEN_CWL (ID))
/

ALTER TABLE KSEN_CWL_WLIST_ENTRY
	ADD (CONSTRAINT KSEN_CWL_WLIST_ENTRY_FK1 FOREIGN KEY (CWL_ID) REFERENCES KSEN_CWL (ID))
/

ALTER TABLE KSEN_CWL_WLIST_ENTRY_ATTR
	ADD (CONSTRAINT KSEN_CWL_WL_ENTRY_ATTR_FK1 FOREIGN KEY (OWNER_ID) REFERENCES KSEN_CWL_WLIST_ENTRY (ID))
/
