

ALTER TABLE KSEN_SOC_ATTR
    ADD CONSTRAINT KSEN_SOC_ATTR_FK1 FOREIGN KEY (OWNER_ID)
    REFERENCES KSEN_SOC (ID)
/


ALTER TABLE KSEN_SOC_ROR
    ADD CONSTRAINT KSEN_SOC_ROR_FK2 FOREIGN KEY (TARGET_SOC_ID)
    REFERENCES KSEN_SOC (ID)
/

ALTER TABLE KSEN_SOC_ROR
    ADD CONSTRAINT KSEN_SOC_ROR_FK1 FOREIGN KEY (SOURCE_SOC_ID)
    REFERENCES KSEN_SOC (ID)
/


ALTER TABLE KSEN_SOC_ROR_ATTR
    ADD CONSTRAINT KSEN_SOC_ROR_ATTR_FK1 FOREIGN KEY (OWNER_ID)
    REFERENCES KSEN_SOC_ROR (ID)
/


ALTER TABLE KSEN_SOC_ROR_ITEM
    ADD CONSTRAINT KSEN_SOC_ROR_ITEM_FK1 FOREIGN KEY (ROR_ID)
    REFERENCES KSEN_SOC_ROR (ID)
/


ALTER TABLE KSEN_SOC_ROR_ITEM_ATTR
    ADD CONSTRAINT KSEN_SOC_ROR_ITEM_ATTR FOREIGN KEY (OWNER_ID)
    REFERENCES KSEN_SOC_ROR_ITEM (ID)
/


ALTER TABLE KSEN_SOC_ROR_OPTION
    ADD CONSTRAINT KSEN_SOC_ROR_OPTION_FK1 FOREIGN KEY (ROR_ID)
    REFERENCES KSEN_SOC_ROR (ID)
/

