
package org.kuali.student.wsdl.proposal;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.3
 * Thu Aug 26 16:25:56 EDT 2010
 * Generated source version: 2.2.3
 * 
 */

@WebFault(name = "OperationFailedException", targetNamespace = "http://student.kuali.org/wsdl/proposal")
public class OperationFailedException extends Exception {
    public static final long serialVersionUID = 20100826162556L;
    
    private org.kuali.student.wsdl.exceptions.OperationFailedException operationFailedException;

    public OperationFailedException() {
        super();
    }
    
    public OperationFailedException(String message) {
        super(message);
    }
    
    public OperationFailedException(String message, Throwable cause) {
        super(message, cause);
    }

    public OperationFailedException(String message, org.kuali.student.wsdl.exceptions.OperationFailedException operationFailedException) {
        super(message);
        this.operationFailedException = operationFailedException;
    }

    public OperationFailedException(String message, org.kuali.student.wsdl.exceptions.OperationFailedException operationFailedException, Throwable cause) {
        super(message, cause);
        this.operationFailedException = operationFailedException;
    }

    public org.kuali.student.wsdl.exceptions.OperationFailedException getFaultInfo() {
        return this.operationFailedException;
    }
}
