
package org.kuali.student.brms.statement.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.2
 * Tue Jan 26 22:57:16 PST 2010
 * Generated source version: 2.2
 */

@XmlRootElement(name = "getRefStatementRelationsForRef", namespace = "http://student.kuali.org/wsdl/statement")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getRefStatementRelationsForRef", namespace = "http://student.kuali.org/wsdl/statement", propOrder = {"refObjectTypeKey","refObjectId"})

public class GetRefStatementRelationsForRef {

    @XmlElement(name = "refObjectTypeKey")
    private java.lang.String refObjectTypeKey;
    @XmlElement(name = "refObjectId")
    private java.lang.String refObjectId;

    public java.lang.String getRefObjectTypeKey() {
        return this.refObjectTypeKey;
    }

    public void setRefObjectTypeKey(java.lang.String newRefObjectTypeKey)  {
        this.refObjectTypeKey = newRefObjectTypeKey;
    }

    public java.lang.String getRefObjectId() {
        return this.refObjectId;
    }

    public void setRefObjectId(java.lang.String newRefObjectId)  {
        this.refObjectId = newRefObjectId;
    }

}

