
package org.kuali.student.core.enumerationmanagement.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.kuali.student.core.enumerationmanagement.dto.EnumerationMetaInfo;

/**
 * This class was generated by Apache CXF 2.2
 * Fri May 15 12:08:08 EDT 2009
 * Generated source version: 2.2
 */

@XmlRootElement(name = "getEnumerationMetasResponse", namespace = "http://student.kuali.org/wsdl/EnumerationManagementService")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getEnumerationMetasResponse", namespace = "http://student.kuali.org/wsdl/EnumerationManagementService")

public class GetEnumerationMetasResponse {

    @XmlElement(name = "return")
    private java.util.List<EnumerationMetaInfo> _return;

    public java.util.List<EnumerationMetaInfo> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<EnumerationMetaInfo> new_return)  {
        this._return = new_return;
    }

}

