
package org.kuali.student.poc.wsdl.learningunit.lu.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by the CXF 2.0.4-incubator
 * Fri Apr 18 16:30:06 EDT 2008
 * Generated source version: 2.0.4-incubator
 * 
 */

@XmlRootElement(name = "findAllowedLuLuRelationTypesForLuType", namespace = "http://student.kuali.org/poc/wsdl/learningunit/lu")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "findAllowedLuLuRelationTypesForLuType", namespace = "http://student.kuali.org/poc/wsdl/learningunit/lu")

public class FindAllowedLuLuRelationTypesForLuType {

    @XmlElement(name = "luTypeKey")
    private java.lang.String luTypeKey;
    @XmlElement(name = "relatedLuTypeKey")
    private java.lang.String relatedLuTypeKey;

    public java.lang.String getLuTypeKey() {
        return this.luTypeKey;
    }
    
    public void setLuTypeKey( java.lang.String newLuTypeKey ) {
        this.luTypeKey = newLuTypeKey;
    }
    
    public java.lang.String getRelatedLuTypeKey() {
        return this.relatedLuTypeKey;
    }
    
    public void setRelatedLuTypeKey( java.lang.String newRelatedLuTypeKey ) {
        this.relatedLuTypeKey = newRelatedLuTypeKey;
    }
    
}

