--- New SOC state for Publishing in Progress
insert into KSEN_STATE (ID, OBJ_ID, NAME, DESCR_PLAIN, DESCR_FORMATTED, LIFECYCLE_KEY, EFF_DT, EXPIR_DT, VER_NBR, CREATETIME, CREATEID, UPDATETIME, UPDATEID) values ('kuali.soc.state.publishing', null, 'Publishing In Progress', 'The system automatically sets this state when the state is set to Published. Then the system begins the verification and update of the AOs. When this process has completed, the system sets the SOC state to Published.', 'The system automatically sets this state when the state is set to Published. Then the system begins the verification and update of the AOs. When this process has completed, the system sets the SOC state to Published.', 'kuali.soc.lifecycle', null, null, 0, to_date('2012-09-05', 'YYYY-MM-DD'), 'SYSTEMLOADER', null, null)
/

--- New state lifecycle and state entries for SOC Scheduling states
insert into KSEN_STATE_LIFECYCLE (ID, OBJ_ID, NAME, DESCR_PLAIN, DESCR_FORMATTED, REF_OBJECT_URI, VER_NBR, CREATETIME, CREATEID, UPDATETIME, UPDATEID) values ('kuali.soc.scheduling.process', null, 'kuali.soc.scheduling.process', 'Set of Courses Scheduling State Lifecycle', 'Set of Courses Scheduling State Lifecycle', null, 1, to_date('2012-09-05', 'YYYY-MM-DD'), 'SYSTEMLOADER', null, null)
/
insert into KSEN_STATE (ID, OBJ_ID, NAME, DESCR_PLAIN, DESCR_FORMATTED, LIFECYCLE_KEY, EFF_DT, EXPIR_DT, VER_NBR, CREATETIME, CREATEID, UPDATETIME, UPDATEID) values ('kuali.soc.scheduling.state.notstarted', null, 'Not Started', 'The SOC has never been submitted to the scheduler', 'The SOC has never been submitted to the scheduler', 'kuali.soc.scheduling.process', null, null, 0, to_date('2012-09-05', 'YYYY-MM-DD'), 'SYSTEMLOADER', null, null)
/
insert into KSEN_STATE (ID, OBJ_ID, NAME, DESCR_PLAIN, DESCR_FORMATTED, LIFECYCLE_KEY, EFF_DT, EXPIR_DT, VER_NBR, CREATETIME, CREATEID, UPDATETIME, UPDATEID) values ('kuali.soc.scheduling.state.inprogress', null, 'In Progress', 'The SOC was submitted for mass scheduling and has not yet completed', 'The SOC was submitted for mass scheduling and has not yet completed', 'kuali.soc.scheduling.process', null, null, 0, to_date('2012-09-05', 'YYYY-MM-DD'), 'SYSTEMLOADER', null, null)
/
insert into KSEN_STATE (ID, OBJ_ID, NAME, DESCR_PLAIN, DESCR_FORMATTED, LIFECYCLE_KEY, EFF_DT, EXPIR_DT, VER_NBR, CREATETIME, CREATEID, UPDATETIME, UPDATEID) values ('kuali.soc.scheduling.state.completed', null, 'Completed', 'The SOC was submitted for mass scheduling, and the scheduling process completed', 'The SOC was submitted for mass scheduling, and the scheduling process completed', 'kuali.soc.scheduling.process', null, null, 0, to_date('2012-09-05', 'YYYY-MM-DD'), 'SYSTEMLOADER', null, null)
/