//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.29 at 10:22:39 AM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.dto.enumeration.student.kuali.org", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.kuali.student.core.enumeration.dto;
