

-----------------------------------------------------------------------------
-- KSEN_CO_AO_CLUSTER
-----------------------------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
	SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_CO_AO_CLUSTER';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_CO_AO_CLUSTER CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_CO_AO_CLUSTER
(
      ID VARCHAR2(255)
        , OBJ_ID VARCHAR2(36)
        , AO_CLUSTER_TYPE VARCHAR2(255) NOT NULL
        , AO_CLUSTER_STATE VARCHAR2(255) NOT NULL
        , NAME VARCHAR2(255)
        , DESCR_PLAIN VARCHAR2(4000)
        , DESCR_FORMATTED VARCHAR2(4000)
        , FORMAT_OFFERING_ID VARCHAR2(255) NOT NULL
        , PRIVATE_NAME VARCHAR2(255)
        , VER_NBR NUMBER(19) NOT NULL
        , CREATETIME TIMESTAMP NOT NULL
        , CREATEID VARCHAR2(255) NOT NULL
        , UPDATETIME TIMESTAMP
        , UPDATEID VARCHAR2(255)


)
/

ALTER TABLE KSEN_CO_AO_CLUSTER
    ADD CONSTRAINT KSEN_CO_AO_CLUSTERP1
PRIMARY KEY (ID)
/


CREATE INDEX KSEN_CO_AO_CLUSTER_I1
  ON KSEN_CO_AO_CLUSTER
  (FORMAT_OFFERING_ID)
/





-----------------------------------------------------------------------------
-- KSEN_CO_AO_CLUSTER_ATTR
-----------------------------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
	SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_CO_AO_CLUSTER_ATTR';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_CO_AO_CLUSTER_ATTR CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_CO_AO_CLUSTER_ATTR
(
      ID VARCHAR2(255)
        , OBJ_ID VARCHAR2(36)
        , ATTR_KEY VARCHAR2(255)
        , ATTR_VALUE VARCHAR2(4000)
        , OWNER_ID VARCHAR2(255)


)
/

ALTER TABLE KSEN_CO_AO_CLUSTER_ATTR
    ADD CONSTRAINT KSEN_CO_AO_CLUSTER_ATTRP1
PRIMARY KEY (ID)
/


CREATE INDEX KSEN_CO_AO_CLUSTER_ATTR_IF1
  ON KSEN_CO_AO_CLUSTER_ATTR
  (OWNER_ID)
/





-----------------------------------------------------------------------------
-- KSEN_CO_AO_CLUSTER_SET
-----------------------------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
	SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_CO_AO_CLUSTER_SET';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_CO_AO_CLUSTER_SET CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_CO_AO_CLUSTER_SET
(
      ID VARCHAR2(255)
        , OBJ_ID VARCHAR2(36)
        , AO_CLUSTER_ID VARCHAR2(255) NOT NULL
        , ACTIVITY_OFFERING_TYPE VARCHAR2(255) NOT NULL


)
/

ALTER TABLE KSEN_CO_AO_CLUSTER_SET
    ADD CONSTRAINT KSEN_CO_AO_CLUSTER_SETP1
PRIMARY KEY (ID)
/


CREATE INDEX KSEN_CO_AO_CLISTER_SET_IF1
  ON KSEN_CO_AO_CLUSTER_SET
  (AO_CLUSTER_ID)
/





-----------------------------------------------------------------------------
-- KSEN_CO_AO_CLUSTER_SET_AO
-----------------------------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
	SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_CO_AO_CLUSTER_SET_AO';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_CO_AO_CLUSTER_SET_AO CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_CO_AO_CLUSTER_SET_AO
(
      AOC_SET_ID VARCHAR2(255)
        , ACTIVITY_OFFERING_ID VARCHAR2(255)


)
/

ALTER TABLE KSEN_CO_AO_CLUSTER_SET_AO
    ADD CONSTRAINT KSEN_CO_AO_CLUSTER_SET_AOP1
PRIMARY KEY (AOC_SET_ID,ACTIVITY_OFFERING_ID)
/


CREATE INDEX XIF1KSEN_CO_AOC_SET_AO_IF1
  ON KSEN_CO_AO_CLUSTER_SET_AO
  (AOC_SET_ID)
/





-----------------------------------------------------------------------------
-- KSEN_CO_SEAT_POOL_DEFN
-----------------------------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
	SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_CO_SEAT_POOL_DEFN';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_CO_SEAT_POOL_DEFN CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_CO_SEAT_POOL_DEFN
(
      ID VARCHAR2(255)
        , OBJ_ID VARCHAR2(36)
        , SEAT_POOL_DEFN_TYPE VARCHAR2(255) NOT NULL
        , SEAT_POOL_DEFN_STATE VARCHAR2(255) NOT NULL
        , NAME VARCHAR2(255)
        , ACTIVITY_OFFERING_ID VARCHAR2(255)
        , EXPIR_MSTONE_TYPE VARCHAR2(255)
        , PERCENTAGE_IND NUMBER(1)
        , SEAT_LIMIT NUMBER(22)
        , PROCESSING_PRIORITY NUMBER(22)
        , POPULATION_ID VARCHAR2(255)
        , VER_NBR NUMBER(19) NOT NULL
        , CREATETIME TIMESTAMP NOT NULL
        , CREATEID VARCHAR2(255) NOT NULL
        , UPDATETIME TIMESTAMP
        , UPDATEID VARCHAR2(255)


)
/

ALTER TABLE KSEN_CO_SEAT_POOL_DEFN
    ADD CONSTRAINT KSEN_CO_SEAT_POOL_DEFNP1
PRIMARY KEY (ID)
/


CREATE INDEX KSEN_CO_SEAT_POOL_DEFN_I1
  ON KSEN_CO_SEAT_POOL_DEFN
  (ACTIVITY_OFFERING_ID)
/





-----------------------------------------------------------------------------
-- KSEN_CO_SEAT_POOL_DEFN_ATTR
-----------------------------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
	SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_CO_SEAT_POOL_DEFN_ATTR';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_CO_SEAT_POOL_DEFN_ATTR CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_CO_SEAT_POOL_DEFN_ATTR
(
      ID VARCHAR2(255)
        , OBJ_ID VARCHAR2(36)
        , ATTR_KEY VARCHAR2(255)
        , ATTR_VALUE VARCHAR2(4000)
        , OWNER_ID VARCHAR2(255)


)
/

ALTER TABLE KSEN_CO_SEAT_POOL_DEFN_ATTR
    ADD CONSTRAINT KSEN_CO_SEAT_POOL_DEFN_ATTRP1
PRIMARY KEY (ID)
/


CREATE INDEX KSEN_CO_SPD_ATTR_IF1
  ON KSEN_CO_SEAT_POOL_DEFN_ATTR
  (OWNER_ID)
/

