
package org.kuali.student.rules.factfinder.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.1.2
 * Tue Jan 20 15:52:41 EST 2009
 * Generated source version: 2.1.2
 */

@XmlRootElement(name = "fetchFact", namespace = "http://student.kuali.org/wsdl/brms/FactFinder")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fetchFact", namespace = "http://student.kuali.org/wsdl/brms/FactFinder", propOrder = {"factTypeKey","factStructure"})

public class FetchFact {

    @XmlElement(name = "factTypeKey")
    private java.lang.String factTypeKey;
    @XmlElement(name = "factStructure")
    private org.kuali.student.rules.factfinder.dto.FactStructureDTO factStructure;

    public java.lang.String getFactTypeKey() {
        return this.factTypeKey;
    }

    public void setFactTypeKey(java.lang.String newFactTypeKey)  {
        this.factTypeKey = newFactTypeKey;
    }

    public org.kuali.student.rules.factfinder.dto.FactStructureDTO getFactStructure() {
        return this.factStructure;
    }

    public void setFactStructure(org.kuali.student.rules.factfinder.dto.FactStructureDTO newFactStructure)  {
        this.factStructure = newFactStructure;
    }

}

