
package org.kuali.student.rules.factfinder.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.1.2
 * Tue Jan 20 15:52:41 EST 2009
 * Generated source version: 2.1.2
 */

@XmlRootElement(name = "findFactTypes", namespace = "http://student.kuali.org/wsdl/brms/FactFinder")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "findFactTypes", namespace = "http://student.kuali.org/wsdl/brms/FactFinder")

public class FindFactTypes {


}

