DECLARE TEMP NUMBER;
BEGIN
  SELECT COUNT(*) INTO TEMP FROM USER_TABLES WHERE TABLE_NAME = 'KSEN_HOLD';
	IF TEMP > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_HOLD CASCADE CONSTRAINTS PURGE'; END IF;
END;
/




CREATE TABLE KSEN_HOLD
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	HOLD_TYPE            VARCHAR2(255) NOT NULL ,
	HOLD_STATE           VARCHAR2(255) NOT NULL ,
	NAME                 VARCHAR2(255) NULL ,
	DESCR_PLAIN          VARCHAR2(4000) NULL ,
	DESCR_FORMATTED      VARCHAR2(4000) NULL ,
	ISSUE_ID             VARCHAR2(55) NOT NULL ,
	PERS_ID              VARCHAR2(255) NOT NULL ,
	EFF_DT               TIMESTAMP(6) NOT NULL ,
	RELEASED_DT          TIMESTAMP(6) NULL ,
	VER_NBR              NUMBER(19) NOT NULL ,
	CREATETIME           TIMESTAMP(6) NOT NULL ,
	CREATEID             VARCHAR2(255) NOT NULL ,
	UPDATETIME           TIMESTAMP(6) NULL ,
	UPDATEID             VARCHAR2(255) NULL 
)
/



CREATE UNIQUE INDEX KSEN_HOLD_P ON KSEN_HOLD
(ID   ASC)
/



ALTER TABLE KSEN_HOLD
	ADD CONSTRAINT  KSEN_HOLD_P PRIMARY KEY (ID)   USING INDEX KSEN_HOLD_P
/



DECLARE TEMP NUMBER;
BEGIN
  SELECT COUNT(*) INTO TEMP FROM USER_TABLES WHERE TABLE_NAME = 'KSEN_HOLD_ATTR';
	IF TEMP > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_HOLD_ATTR CASCADE CONSTRAINTS PURGE'; END IF;
END;
/




CREATE TABLE KSEN_HOLD_ATTR
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	ATTR_KEY             VARCHAR2(255) NULL ,
	ATTR_VALUE           VARCHAR2(4000) NULL ,
	OWNER_ID             VARCHAR2(255) NULL 
)
/



CREATE UNIQUE INDEX KSEN_HOLD_ATTR_P ON KSEN_HOLD_ATTR
(ID   ASC)
/



ALTER TABLE KSEN_HOLD_ATTR
	ADD CONSTRAINT  KSEN_HOLD_ATTR_P PRIMARY KEY (ID)   USING INDEX KSEN_HOLD_ATTR_P
/



DECLARE TEMP NUMBER;
BEGIN
  SELECT COUNT(*) INTO TEMP FROM USER_TABLES WHERE TABLE_NAME = 'KSEN_HOLD_ISSUE';
	IF TEMP > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_HOLD_ISSUE CASCADE CONSTRAINTS PURGE'; END IF;
END;
/




CREATE TABLE KSEN_HOLD_ISSUE
(
	ID                   VARCHAR2(55) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	HOLD_ISSUE_TYPE      VARCHAR2(255) NOT NULL ,
	HOLD_ISSUE_STATE     VARCHAR2(255) NOT NULL ,
	NAME                 VARCHAR2(255) NULL ,
	DESCR_PLAIN          VARCHAR2(4000) NULL ,
	DESCR_FORMATTED      VARCHAR2(255) NULL ,
	ORG_ID               VARCHAR2(255) NULL ,
	VER_NBR              NUMBER(19) NOT NULL ,
	CREATETIME           TIMESTAMP(6) NOT NULL ,
	CREATEID             VARCHAR2(255) NOT NULL ,
	UPDATETIME           TIMESTAMP(6) NULL ,
	UPDATEID             VARCHAR2(255) NULL 
)
/



CREATE UNIQUE INDEX KSEN_HOLD_ISSUE_P ON KSEN_HOLD_ISSUE
(ID   ASC)
/



ALTER TABLE KSEN_HOLD_ISSUE
	ADD CONSTRAINT  KSEN_HOLD_ISSUE_P PRIMARY KEY (ID)   USING INDEX KSEN_HOLD_ISSUE_P
/



DECLARE TEMP NUMBER;
BEGIN
  SELECT COUNT(*) INTO TEMP FROM USER_TABLES WHERE TABLE_NAME = 'KSEN_HOLD_ISSUE_ATTR';
	IF TEMP > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_HOLD_ISSUE_ATTR CASCADE CONSTRAINTS PURGE'; END IF;
END;
/




CREATE TABLE KSEN_HOLD_ISSUE_ATTR
(
	ID                   VARCHAR2(255) NOT NULL ,
	OBJ_ID               VARCHAR2(36) NULL ,
	ATTR_KEY             VARCHAR2(255) NULL ,
	ATTR_VALUE           VARCHAR2(4000) NULL ,
	OWNER_ID             VARCHAR2(55) NULL 
)
/



CREATE UNIQUE INDEX KSEN_HOLD_ISSUE_ATTR_P ON KSEN_HOLD_ISSUE_ATTR
(ID   ASC)
/



ALTER TABLE KSEN_HOLD_ISSUE_ATTR
	ADD CONSTRAINT  KSEN_HOLD_ISSUE_ATTR_P PRIMARY KEY (ID)   USING INDEX KSEN_HOLD_ISSUE_ATTR_P
/



