

-----------------------------------------------------------------------------
-- KSEN_ATP
-----------------------------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
	SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_ATP';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_ATP CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_ATP
(
      ID VARCHAR2(255)
        , OBJ_ID VARCHAR2(36)
        , ATP_TYPE VARCHAR2(255) NOT NULL
        , ATP_STATE VARCHAR2(255) NOT NULL
        , NAME VARCHAR2(255)
        , DESCR_PLAIN VARCHAR2(4000) NOT NULL
        , DESCR_FORMATTED VARCHAR2(4000)
        , ATP_CD VARCHAR2(255)
        , END_DT TIMESTAMP NOT NULL
        , START_DT TIMESTAMP NOT NULL
        , ADMIN_ORG_ID VARCHAR2(50)
        , VER_NBR NUMBER(19) NOT NULL
        , CREATETIME TIMESTAMP NOT NULL
        , CREATEID VARCHAR2(255) NOT NULL
        , UPDATETIME TIMESTAMP
        , UPDATEID VARCHAR2(255)
    

)
/

ALTER TABLE KSEN_ATP
    ADD CONSTRAINT KSEN_ATPP1
PRIMARY KEY (ID)
/


CREATE INDEX KSEN_ATP_I1 
  ON KSEN_ATP 
  (ATP_TYPE)
/
CREATE INDEX KSEN_ATP_I2 
  ON KSEN_ATP 
  (ATP_CD)
/
CREATE INDEX KSEN_ATP_I3 
  ON KSEN_ATP 
  (START_DT)
/





-----------------------------------------------------------------------------
-- KSEN_ATPATP_RELTN
-----------------------------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
	SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_ATPATP_RELTN';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_ATPATP_RELTN CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_ATPATP_RELTN
(
      ID VARCHAR2(255)
        , OBJ_ID VARCHAR2(36)
        , ATP_TYPE VARCHAR2(255) NOT NULL
        , ATP_STATE VARCHAR2(255) NOT NULL
        , ATP_ID VARCHAR2(255) NOT NULL
        , RELATED_ATP_ID VARCHAR2(255) NOT NULL
        , EFF_DT TIMESTAMP
        , EXPIR_DT TIMESTAMP
        , VER_NBR NUMBER(19) NOT NULL
        , CREATETIME TIMESTAMP NOT NULL
        , CREATEID VARCHAR2(255) NOT NULL
        , UPDATETIME TIMESTAMP
        , UPDATEID VARCHAR2(255)
    

)
/

ALTER TABLE KSEN_ATPATP_RELTN
    ADD CONSTRAINT KSEN_ATPATP_RELTNP1
PRIMARY KEY (ID)
/


CREATE INDEX KSEN_ATPATP_RELTN_I1 
  ON KSEN_ATPATP_RELTN 
  (ATP_TYPE)
/
CREATE INDEX KSEN_ATPATP_RELTN_IF1 
  ON KSEN_ATPATP_RELTN 
  (ATP_ID)
/
CREATE INDEX KSEN_ATPATP_RELTN_IF2 
  ON KSEN_ATPATP_RELTN 
  (RELATED_ATP_ID)
/





-----------------------------------------------------------------------------
-- KSEN_ATPATP_RELTN_ATTR
-----------------------------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
	SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_ATPATP_RELTN_ATTR';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_ATPATP_RELTN_ATTR CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_ATPATP_RELTN_ATTR
(
      ID VARCHAR2(255)
        , OBJ_ID VARCHAR2(36)
        , ATTR_KEY VARCHAR2(255)
        , ATTR_VALUE VARCHAR2(4000)
        , OWNER_ID VARCHAR2(255)
    

)
/

ALTER TABLE KSEN_ATPATP_RELTN_ATTR
    ADD CONSTRAINT KSEN_ATPATP_RELTN_ATTRP1
PRIMARY KEY (ID)
/


CREATE INDEX KSEN_ATPATP_RELTN_ATTR_IF1 
  ON KSEN_ATPATP_RELTN_ATTR 
  (OWNER_ID)
/





-----------------------------------------------------------------------------
-- KSEN_ATPMSTONE_RELTN
-----------------------------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
	SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_ATPMSTONE_RELTN';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_ATPMSTONE_RELTN CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_ATPMSTONE_RELTN
(
      ID VARCHAR2(255)
        , OBJ_ID VARCHAR2(36)
        , VER_NBR NUMBER(19) NOT NULL
        , CREATEID VARCHAR2(255) NOT NULL
        , CREATETIME TIMESTAMP NOT NULL
        , UPDATEID VARCHAR2(255)
        , UPDATETIME TIMESTAMP
        , ATP_ID VARCHAR2(255)
        , MSTONE_ID VARCHAR2(255)
    

)
/

ALTER TABLE KSEN_ATPMSTONE_RELTN
    ADD CONSTRAINT KSEN_ATPMSTONE_RELTNP1
PRIMARY KEY (ID)
/


CREATE INDEX KSEN_ATPMSTONE_RELTN_IF1 
  ON KSEN_ATPMSTONE_RELTN 
  (ATP_ID)
/
CREATE INDEX KSEN_ATPMSTONE_RELTN_IF2 
  ON KSEN_ATPMSTONE_RELTN 
  (MSTONE_ID)
/





-----------------------------------------------------------------------------
-- KSEN_ATP_ATTR
-----------------------------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
	SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_ATP_ATTR';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_ATP_ATTR CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_ATP_ATTR
(
      ID VARCHAR2(255)
        , OBJ_ID VARCHAR2(36)
        , ATTR_KEY VARCHAR2(255)
        , ATTR_VALUE VARCHAR2(4000)
        , OWNER_ID VARCHAR2(255)
    

)
/

ALTER TABLE KSEN_ATP_ATTR
    ADD CONSTRAINT KSEN_ATP_ATTRP1
PRIMARY KEY (ID)
/


CREATE INDEX KSEN_ATP_ATTR_IF1 
  ON KSEN_ATP_ATTR 
  (OWNER_ID)
/


-----------------------------------------------------------------------------
-- KSEN_MSTONE
-----------------------------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
	SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_MSTONE';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_MSTONE CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_MSTONE
(
      ID VARCHAR2(255)
        , OBJ_ID VARCHAR2(36)
        , MSTONE_TYPE VARCHAR2(255) NOT NULL
        , MSTONE_STATE VARCHAR2(255) NOT NULL
        , NAME VARCHAR2(255)
        , DESCR_PLAIN VARCHAR2(4000) NOT NULL
        , DESCR_FORMATTED VARCHAR2(4000)
        , IS_ALL_DAY NUMBER(1) NOT NULL
        , IS_INSTRCT_DAY NUMBER(1) NOT NULL
        , IS_RELATIVE NUMBER(1) NOT NULL
        , RELATIVE_ANCHOR_MSTONE_ID VARCHAR2(255)
        , IS_DATE_RANGE NUMBER(1) NOT NULL
        , START_DT TIMESTAMP
        , END_DT TIMESTAMP
        , VER_NBR NUMBER(19) NOT NULL
        , CREATETIME TIMESTAMP NOT NULL
        , CREATEID VARCHAR2(255) NOT NULL
        , UPDATETIME TIMESTAMP
        , UPDATEID VARCHAR2(255)


)
/

ALTER TABLE KSEN_MSTONE
    ADD CONSTRAINT KSEN_MSTONEP1
PRIMARY KEY (ID)
/


CREATE INDEX KSEN_MSTONE_I1
  ON KSEN_MSTONE
  (MSTONE_TYPE)
/
CREATE INDEX KSEN_MSTONE_I2
  ON KSEN_MSTONE
  (START_DT)
/





-----------------------------------------------------------------------------
-- KSEN_MSTONE_ATTR
-----------------------------------------------------------------------------
DECLARE temp NUMBER;
BEGIN
	SELECT COUNT(*) INTO temp FROM user_tables WHERE table_name = 'KSEN_MSTONE_ATTR';
	IF temp > 0 THEN EXECUTE IMMEDIATE 'DROP TABLE KSEN_MSTONE_ATTR CASCADE CONSTRAINTS PURGE'; END IF;
END;
/

CREATE TABLE KSEN_MSTONE_ATTR
(
      ID VARCHAR2(255)
        , OBJ_ID VARCHAR2(36)
        , ATTR_KEY VARCHAR2(255)
        , ATTR_VALUE VARCHAR2(4000)
        , OWNER_ID VARCHAR2(255)


)
/

ALTER TABLE KSEN_MSTONE_ATTR
    ADD CONSTRAINT KSEN_MSTONE_ATTRP1
PRIMARY KEY (ID)
/


CREATE INDEX KSEN_MSTONE_ATTR_IF1
  ON KSEN_MSTONE_ATTR
  (OWNER_ID)
/
