
ALTER TABLE KSPR_PROPOSAL
    ADD CONSTRAINT KSPR_PROPOSAL_FK1 FOREIGN KEY (TYPE)
    REFERENCES KSPR_PROPOSAL_TYPE (TYPE_KEY)
/


ALTER TABLE KSPR_PROPOSAL_ATTR
    ADD CONSTRAINT KSPR_PROPOSAL_ATTR_FK1 FOREIGN KEY (OWNER)
    REFERENCES KSPR_PROPOSAL (PROPOSAL_ID)
/


ALTER TABLE KSPR_PROPOSAL_JN_ORG
    ADD CONSTRAINT KSPR_PROPOSAL_JN_ORG_FK1 FOREIGN KEY (PROPOSAL_ID)
    REFERENCES KSPR_PROPOSAL (PROPOSAL_ID)
/


ALTER TABLE KSPR_PROPOSAL_JN_PERSON
    ADD CONSTRAINT KSPR_PROPOSAL_JN_PERSON_FK1 FOREIGN KEY (PROPOSAL_ID)
    REFERENCES KSPR_PROPOSAL (PROPOSAL_ID)
/


ALTER TABLE KSPR_PROPOSAL_JN_REFERENCE
    ADD CONSTRAINT KSPR_PROPOSAL_JN_REFERENCE_FK1 FOREIGN KEY (REFERENCE_ID)
    REFERENCES KSPR_PROPOSAL_REFERENCE (REFERENCE_ID)
/

ALTER TABLE KSPR_PROPOSAL_JN_REFERENCE
    ADD CONSTRAINT KSPR_PROPOSAL_JN_REFERENCE_FK2 FOREIGN KEY (PROPOSAL_ID)
    REFERENCES KSPR_PROPOSAL (PROPOSAL_ID)
/


ALTER TABLE KSPR_PROPOSAL_REFERENCE
    ADD CONSTRAINT KSPR_PROPOSAL_REFERENCE_FK1 FOREIGN KEY (TYPE)
    REFERENCES KSPR_PROPOSAL_REFTYPE (TYPE_KEY)
/



ALTER TABLE KSPR_PROPOSAL_REFTYPE_ATTR
    ADD CONSTRAINT KSPR_PROPOSAL_REFTYPE_ATTR_FK1 FOREIGN KEY (OWNER)
    REFERENCES KSPR_PROPOSAL_REFTYPE (TYPE_KEY)
/



ALTER TABLE KSPR_PROPOSAL_TYPE_ATTR
    ADD CONSTRAINT KSPR_PROPOSAL_TYPE_ATTR_FK1 FOREIGN KEY (OWNER)
    REFERENCES KSPR_PROPOSAL_TYPE (TYPE_KEY)
/

