
package org.kuali.student.core.dictionary.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.1.3
 * Tue Nov 18 17:03:46 EST 2008
 * Generated source version: 2.1.3
 */

@XmlRootElement(name = "fetchObjectStructureResponse", namespace = "http://org.kuali.student/core/dictionary")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fetchObjectStructureResponse", namespace = "http://org.kuali.student/core/dictionary")

public class FetchObjectStructureResponse {

    @XmlElement(name = "return")
    private org.kuali.student.core.dictionary.dto.ObjectStructure _return;

    public org.kuali.student.core.dictionary.dto.ObjectStructure getReturn() {
        return this._return;
    }

    public void setReturn(org.kuali.student.core.dictionary.dto.ObjectStructure new_return)  {
        this._return = new_return;
    }

}

