
package org.kuali.student.lum.lu.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.2
 * Tue May 12 16:31:26 EDT 2009
 * Generated source version: 2.2
 */

@XmlRootElement(name = "getNaturalLanguageForStatementInfoAsTree", namespace = "http://student.kuali.org/lum/lu")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getNaturalLanguageForStatementInfoAsTree", namespace = "http://student.kuali.org/lum/lu", propOrder = {"arg0","arg1","arg2"})

public class GetNaturalLanguageForStatementInfoAsTree {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;
    @XmlElement(name = "arg1")
    private org.kuali.student.lum.lu.dto.LuStatementInfo arg1;
    @XmlElement(name = "arg2")
    private java.lang.String arg2;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

    public org.kuali.student.lum.lu.dto.LuStatementInfo getArg1() {
        return this.arg1;
    }

    public void setArg1(org.kuali.student.lum.lu.dto.LuStatementInfo newArg1)  {
        this.arg1 = newArg1;
    }

    public java.lang.String getArg2() {
        return this.arg2;
    }

    public void setArg2(java.lang.String newArg2)  {
        this.arg2 = newArg2;
    }

}

