--Agendas and References
INSERT INTO KRMS_AGENDA_T (ACTV,AGENDA_ID,CNTXT_ID,INIT_AGENDA_ITM_ID,NM,TYP_ID,VER_NBR)
  VALUES ('Y','KS-KRMS-AGENDA-11923','KS-KRMS-CNTXT-10002',null,'Fall Standard Final Exam Rules',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.agenda.type.final.exam.standard'),0)
/
INSERT INTO KRMS_REF_OBJ_KRMS_OBJ_T (ACTV,COLLECTION_NM,KRMS_DSCR_TYP,KRMS_OBJ_ID,NMSPC_CD,REF_DSCR_TYP,REF_OBJ_ID,REF_OBJ_KRMS_OBJ_ID,VER_NBR)
  VALUES ('Y','FinalExamMatrix','Agenda','KS-KRMS-AGENDA-11923','KS-SYS','http://student.kuali.org/wsdl/type/TypeInfo','kuali.atp.type.Fall','KS-KRMS-REF-OBJ-KRMS-OBJ-11914',0)
/

--Day 1 8:00-10:00
Insert into KRMS_RULE_T (ACTV,DESC_TXT,NM,NMSPC_CD,PROP_ID,RULE_ID,TYP_ID,VER_NBR) 
  values ('Y',null,concat(concat('kuali.atp.type.Fall:',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.rule.type.final.exam.standard')), ':1'),'KS-SYS',null,'KS-KRMS-RULE-12037',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.rule.type.final.exam.standard'),1)
/
INSERT INTO KRMS_AGENDA_ITM_T (AGENDA_ID,AGENDA_ITM_ID,RULE_ID,VER_NBR)
  VALUES ('KS-KRMS-AGENDA-11923','KS-KRMS-AGENDA-ITM-12031','KS-KRMS-RULE-12037',1)
/
UPDATE KRMS_AGENDA_T set INIT_AGENDA_ITM_ID = 'KS-KRMS-AGENDA-ITM-12031' WHERE AGENDA_ID = 'KS-KRMS-AGENDA-11923'
/
Insert into KRMS_PROP_T (CMPND_OP_CD,DESC_TXT,PROP_ID,RULE_ID,TYP_ID,VER_NBR,DSCRM_TYP_CD,CMPND_SEQ_NO) values (null,'Final exam timeslot','KS-KRMS-PROP-14726','KS-KRMS-RULE-12037',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.proposition.type.final.exam.timeslot'),1,'S',1)
/
UPDATE KRMS_RULE_T set PROP_ID = 'KS-KRMS-PROP-14726' where RULE_ID like 'KS-KRMS-RULE-12037'
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('T','KS-KRMS-TERM-13422','KS-KRMS-PROP-14726','KS-KRMS-PROP-PARM-20258',1,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('C','true','KS-KRMS-PROP-14726','KS-KRMS-PROP-PARM-20259',2,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('O','=','KS-KRMS-PROP-14726','KS-KRMS-PROP-PARM-20260',3,2)
/

--Day 2 8:00-10:00
Insert into KRMS_RULE_T (ACTV,DESC_TXT,NM,NMSPC_CD,PROP_ID,RULE_ID,TYP_ID,VER_NBR) 
  values ('Y',null,concat(concat('kuali.atp.type.Fall:',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.rule.type.final.exam.standard')), ':2'),'KS-SYS',null,'KS-KRMS-RULE-12040',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.rule.type.final.exam.standard'),1)
/
INSERT INTO KRMS_AGENDA_ITM_T (AGENDA_ID,AGENDA_ITM_ID,RULE_ID,VER_NBR)
  VALUES ('KS-KRMS-AGENDA-11923','KS-KRMS-AGENDA-ITM-12034','KS-KRMS-RULE-12040',1)
/
UPDATE KRMS_AGENDA_ITM_T set WHEN_FALSE = 'KS-KRMS-AGENDA-ITM-12034' WHERE AGENDA_ITM_ID = 'KS-KRMS-AGENDA-ITM-12031'
/
Insert into KRMS_PROP_T (CMPND_OP_CD,DESC_TXT,PROP_ID,RULE_ID,TYP_ID,VER_NBR,DSCRM_TYP_CD,CMPND_SEQ_NO) 
  values (null,'Final exam timeslot','KS-KRMS-PROP-14731','KS-KRMS-RULE-12040',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.proposition.type.final.exam.timeslot'),1,'S',1)
/
UPDATE KRMS_RULE_T set PROP_ID = 'KS-KRMS-PROP-14731' where RULE_ID like 'KS-KRMS-RULE-12040'
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('T','KS-KRMS-TERM-13426','KS-KRMS-PROP-14731','KS-KRMS-PROP-PARM-20270',1,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('C','true','KS-KRMS-PROP-14731','KS-KRMS-PROP-PARM-20271',2,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('O','=','KS-KRMS-PROP-14731','KS-KRMS-PROP-PARM-20272',3,2)
/

--Day 2 13:30-15:30
Insert into KRMS_RULE_T (ACTV,DESC_TXT,NM,NMSPC_CD,PROP_ID,RULE_ID,TYP_ID,VER_NBR) 
  values ('Y',null,concat(concat('kuali.atp.type.Fall:',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.rule.type.final.exam.standard')), ':3'),'KS-SYS',null,'KS-KRMS-RULE-12042',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.rule.type.final.exam.standard'),1)
/
INSERT INTO KRMS_AGENDA_ITM_T (AGENDA_ID,AGENDA_ITM_ID,RULE_ID,VER_NBR)
  VALUES ('KS-KRMS-AGENDA-11923','KS-KRMS-AGENDA-ITM-12036','KS-KRMS-RULE-12042',1)
/
UPDATE KRMS_AGENDA_ITM_T set WHEN_FALSE = 'KS-KRMS-AGENDA-ITM-12036' WHERE AGENDA_ITM_ID = 'KS-KRMS-AGENDA-ITM-12034'
/
Insert into KRMS_PROP_T (CMPND_OP_CD,DESC_TXT,PROP_ID,RULE_ID,TYP_ID,VER_NBR,DSCRM_TYP_CD,CMPND_SEQ_NO) 
values (null,'Final exam timeslot','KS-KRMS-PROP-14733','KS-KRMS-RULE-12042',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.proposition.type.final.exam.timeslot'),1,'S',1)
/
UPDATE KRMS_RULE_T set PROP_ID = 'KS-KRMS-PROP-14733' where RULE_ID like 'KS-KRMS-RULE-12042'
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('T','KS-KRMS-TERM-13427','KS-KRMS-PROP-14733','KS-KRMS-PROP-PARM-20276',1,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('C','true','KS-KRMS-PROP-14733','KS-KRMS-PROP-PARM-20277',2,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('O','=','KS-KRMS-PROP-14733','KS-KRMS-PROP-PARM-20278',3,2)
/

--Day 4 8:00-10:00
Insert into KRMS_RULE_T (ACTV,DESC_TXT,NM,NMSPC_CD,PROP_ID,RULE_ID,TYP_ID,VER_NBR) 
  values ('Y',null,concat(concat('kuali.atp.type.Fall:',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.rule.type.final.exam.standard')), ':4'),'KS-SYS',null,'KS-KRMS-RULE-12043',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.rule.type.final.exam.standard'),1)
/
INSERT INTO KRMS_AGENDA_ITM_T (AGENDA_ID,AGENDA_ITM_ID,RULE_ID,VER_NBR)
  VALUES ('KS-KRMS-AGENDA-11923','KS-KRMS-AGENDA-ITM-12037','KS-KRMS-RULE-12043',1)
/
UPDATE KRMS_AGENDA_ITM_T set WHEN_FALSE = 'KS-KRMS-AGENDA-ITM-12037' WHERE AGENDA_ITM_ID = 'KS-KRMS-AGENDA-ITM-12036'
/
Insert into KRMS_PROP_T (CMPND_OP_CD,DESC_TXT,PROP_ID,RULE_ID,TYP_ID,VER_NBR,DSCRM_TYP_CD,CMPND_SEQ_NO) 
  values (null,'Final exam timeslot','KS-KRMS-PROP-14735','KS-KRMS-RULE-12043',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.proposition.type.final.exam.timeslot'),1,'S',1)
/
UPDATE KRMS_RULE_T set PROP_ID = 'KS-KRMS-PROP-14735' where RULE_ID like 'KS-KRMS-RULE-12043'
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('T','KS-KRMS-TERM-13428','KS-KRMS-PROP-14735','KS-KRMS-PROP-PARM-20279',1,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('C','true','KS-KRMS-PROP-14735','KS-KRMS-PROP-PARM-20280',2,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('O','=','KS-KRMS-PROP-14735','KS-KRMS-PROP-PARM-20281',3,2)
/

--Day 4 10:30-12:30
Insert into KRMS_RULE_T (ACTV,DESC_TXT,NM,NMSPC_CD,PROP_ID,RULE_ID,TYP_ID,VER_NBR) 
  values ('Y',null,concat(concat('kuali.atp.type.Fall:',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.rule.type.final.exam.standard')), ':5'),'KS-SYS',null,'KS-KRMS-RULE-12044',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.rule.type.final.exam.standard'),1)
/
INSERT INTO KRMS_AGENDA_ITM_T (AGENDA_ID,AGENDA_ITM_ID,RULE_ID,VER_NBR)
  VALUES ('KS-KRMS-AGENDA-11923','KS-KRMS-AGENDA-ITM-12038','KS-KRMS-RULE-12044',1)
/
UPDATE KRMS_AGENDA_ITM_T set WHEN_FALSE = 'KS-KRMS-AGENDA-ITM-12038' WHERE AGENDA_ITM_ID = 'KS-KRMS-AGENDA-ITM-12037'
/
Insert into KRMS_PROP_T (CMPND_OP_CD,DESC_TXT,PROP_ID,RULE_ID,TYP_ID,VER_NBR,DSCRM_TYP_CD,CMPND_SEQ_NO) 
  values (null,'Final exam timeslot','KS-KRMS-PROP-14736','KS-KRMS-RULE-12044',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.proposition.type.final.exam.timeslot'),1,'S',1)
/
UPDATE KRMS_RULE_T set PROP_ID = 'KS-KRMS-PROP-14736' where RULE_ID like 'KS-KRMS-RULE-12044'
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('T','KS-KRMS-TERM-13430','KS-KRMS-PROP-14736','KS-KRMS-PROP-PARM-20282',1,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('C','true','KS-KRMS-PROP-14736','KS-KRMS-PROP-PARM-20283',2,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('O','=','KS-KRMS-PROP-14736','KS-KRMS-PROP-PARM-20284',3,2)
/

--Day 5 10:30-12:30
Insert into KRMS_RULE_T (ACTV,DESC_TXT,NM,NMSPC_CD,PROP_ID,RULE_ID,TYP_ID,VER_NBR) 
  values ('Y',null,concat(concat('kuali.atp.type.Fall:',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.rule.type.final.exam.standard')), ':6'),'KS-SYS',null,'KS-KRMS-RULE-12046',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.rule.type.final.exam.standard'),1)
/
INSERT INTO KRMS_AGENDA_ITM_T (AGENDA_ID,AGENDA_ITM_ID,RULE_ID,VER_NBR)
  VALUES ('KS-KRMS-AGENDA-11923','KS-KRMS-AGENDA-ITM-12040','KS-KRMS-RULE-12046',1)
/
UPDATE KRMS_AGENDA_ITM_T set WHEN_FALSE = 'KS-KRMS-AGENDA-ITM-12040' WHERE AGENDA_ITM_ID = 'KS-KRMS-AGENDA-ITM-12038'
/
Insert into KRMS_PROP_T (CMPND_OP_CD,DESC_TXT,PROP_ID,RULE_ID,TYP_ID,VER_NBR,DSCRM_TYP_CD,CMPND_SEQ_NO) 
  values (null,'Final exam timeslot','KS-KRMS-PROP-14738','KS-KRMS-RULE-12046',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.proposition.type.final.exam.timeslot'),1,'S',1)
/
UPDATE KRMS_RULE_T set PROP_ID = 'KS-KRMS-PROP-14738' where RULE_ID like 'KS-KRMS-RULE-12046'
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('T','KS-KRMS-TERM-13431','KS-KRMS-PROP-14738','KS-KRMS-PROP-PARM-20288',1,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('C','true','KS-KRMS-PROP-14738','KS-KRMS-PROP-PARM-20289',2,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('O','=','KS-KRMS-PROP-14738','KS-KRMS-PROP-PARM-20290',3,2)
/

--Day 5 13:30-15:30
Insert into KRMS_RULE_T (ACTV,DESC_TXT,NM,NMSPC_CD,PROP_ID,RULE_ID,TYP_ID,VER_NBR) 
  values ('Y',null,concat(concat('kuali.atp.type.Fall:',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.rule.type.final.exam.standard')), ':7'),'KS-SYS',null,'KS-KRMS-RULE-12049',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.rule.type.final.exam.standard'),1)
/
INSERT INTO KRMS_AGENDA_ITM_T (AGENDA_ID,AGENDA_ITM_ID,RULE_ID,VER_NBR)
  VALUES ('KS-KRMS-AGENDA-11923','KS-KRMS-AGENDA-ITM-12043','KS-KRMS-RULE-12049',1)
/
UPDATE KRMS_AGENDA_ITM_T set WHEN_FALSE = 'KS-KRMS-AGENDA-ITM-12043' WHERE AGENDA_ITM_ID = 'KS-KRMS-AGENDA-ITM-12040'
/
Insert into KRMS_PROP_T (CMPND_OP_CD,DESC_TXT,PROP_ID,RULE_ID,TYP_ID,VER_NBR,DSCRM_TYP_CD,CMPND_SEQ_NO) 
  values (null,'Final exam timeslot','KS-KRMS-PROP-14741','KS-KRMS-RULE-12049',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.proposition.type.final.exam.timeslot'),1,'S',1)
/
UPDATE KRMS_RULE_T set PROP_ID = 'KS-KRMS-PROP-14741' where RULE_ID like 'KS-KRMS-RULE-12049'
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('T','KS-KRMS-TERM-13435','KS-KRMS-PROP-14741','KS-KRMS-PROP-PARM-20297',1,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('C','true','KS-KRMS-PROP-14741','KS-KRMS-PROP-PARM-20298',2,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('O','=','KS-KRMS-PROP-14741','KS-KRMS-PROP-PARM-20299',3,2)
/

--Day 5 16:00-18:00
Insert into KRMS_RULE_T (ACTV,DESC_TXT,NM,NMSPC_CD,PROP_ID,RULE_ID,TYP_ID,VER_NBR) 
  values ('Y',null,concat(concat('kuali.atp.type.Fall:',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.rule.type.final.exam.standard')), ':8'),'KS-SYS',null,'KS-KRMS-RULE-12051',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.rule.type.final.exam.standard'),1)
/
INSERT INTO KRMS_AGENDA_ITM_T (AGENDA_ID,AGENDA_ITM_ID,RULE_ID,VER_NBR)
  VALUES ('KS-KRMS-AGENDA-11923','KS-KRMS-AGENDA-ITM-12045','KS-KRMS-RULE-12051',1)
/
UPDATE KRMS_AGENDA_ITM_T set WHEN_FALSE = 'KS-KRMS-AGENDA-ITM-12045' WHERE AGENDA_ITM_ID = 'KS-KRMS-AGENDA-ITM-12043'
/
Insert into KRMS_PROP_T (CMPND_OP_CD,DESC_TXT,PROP_ID,RULE_ID,TYP_ID,VER_NBR,DSCRM_TYP_CD,CMPND_SEQ_NO) 
  values (null,'Final exam timeslot','KS-KRMS-PROP-14743','KS-KRMS-RULE-12051',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.proposition.type.final.exam.timeslot'),1,'S',1)
/
UPDATE KRMS_RULE_T set PROP_ID = 'KS-KRMS-PROP-14743' where RULE_ID like 'KS-KRMS-RULE-12051'
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('T','KS-KRMS-TERM-13437','KS-KRMS-PROP-14743','KS-KRMS-PROP-PARM-20303',1,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('C','true','KS-KRMS-PROP-14743','KS-KRMS-PROP-PARM-20304',2,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('O','=','KS-KRMS-PROP-14743','KS-KRMS-PROP-PARM-20305',3,2)
/

--Day 6 10:30-12:30
Insert into KRMS_RULE_T (ACTV,DESC_TXT,NM,NMSPC_CD,PROP_ID,RULE_ID,TYP_ID,VER_NBR) 
  values ('Y',null,concat(concat('kuali.atp.type.Fall:',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.rule.type.final.exam.standard')), ':9'),'KS-SYS',null,'KS-KRMS-RULE-12053',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.rule.type.final.exam.standard'),1)
/
INSERT INTO KRMS_AGENDA_ITM_T (AGENDA_ID,AGENDA_ITM_ID,RULE_ID,VER_NBR)
  VALUES ('KS-KRMS-AGENDA-11923','KS-KRMS-AGENDA-ITM-12047','KS-KRMS-RULE-12053',1)
/
UPDATE KRMS_AGENDA_ITM_T set WHEN_FALSE = 'KS-KRMS-AGENDA-ITM-12047' WHERE AGENDA_ITM_ID = 'KS-KRMS-AGENDA-ITM-12045'
/
Insert into KRMS_PROP_T (CMPND_OP_CD,DESC_TXT,PROP_ID,RULE_ID,TYP_ID,VER_NBR,DSCRM_TYP_CD,CMPND_SEQ_NO) 
  values (null,'Final exam timeslot','KS-KRMS-PROP-14745','KS-KRMS-RULE-12053',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.proposition.type.final.exam.timeslot'),1,'S',1)
/
UPDATE KRMS_RULE_T set PROP_ID = 'KS-KRMS-PROP-14745' where RULE_ID like 'KS-KRMS-RULE-12053'
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('T','KS-KRMS-TERM-13439','KS-KRMS-PROP-14745','KS-KRMS-PROP-PARM-20309',1,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('C','true','KS-KRMS-PROP-14745','KS-KRMS-PROP-PARM-20310',2,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('O','=','KS-KRMS-PROP-14745','KS-KRMS-PROP-PARM-20311',3,2)
/

--Day 6 13:30-15:30
Insert into KRMS_RULE_T (ACTV,DESC_TXT,NM,NMSPC_CD,PROP_ID,RULE_ID,TYP_ID,VER_NBR) 
  values ('Y',null,concat(concat('kuali.atp.type.Fall:',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.rule.type.final.exam.standard')), ':10'),'KS-SYS',null,'KS-KRMS-RULE-12056',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.rule.type.final.exam.standard'),1)
/
INSERT INTO KRMS_AGENDA_ITM_T (AGENDA_ID,AGENDA_ITM_ID,RULE_ID,VER_NBR)
  VALUES ('KS-KRMS-AGENDA-11923','KS-KRMS-AGENDA-ITM-12048','KS-KRMS-RULE-12056',1)
/
UPDATE KRMS_AGENDA_ITM_T set WHEN_FALSE = 'KS-KRMS-AGENDA-ITM-12048' WHERE AGENDA_ITM_ID = 'KS-KRMS-AGENDA-ITM-12047'
/
Insert into KRMS_PROP_T (CMPND_OP_CD,DESC_TXT,PROP_ID,RULE_ID,TYP_ID,VER_NBR,DSCRM_TYP_CD,CMPND_SEQ_NO) 
  values (null,'Final exam timeslot','KS-KRMS-PROP-14749','KS-KRMS-RULE-12056',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.proposition.type.final.exam.timeslot'),1,'S',1)
/
UPDATE KRMS_RULE_T set PROP_ID = 'KS-KRMS-PROP-14749' where RULE_ID like 'KS-KRMS-RULE-12056'
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('T','KS-KRMS-TERM-13440','KS-KRMS-PROP-14749','KS-KRMS-PROP-PARM-20318',1,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('C','true','KS-KRMS-PROP-14749','KS-KRMS-PROP-PARM-20319',2,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('O','=','KS-KRMS-PROP-14749','KS-KRMS-PROP-PARM-20320',3,2)
/

--Day 4 16:00-18:00
Insert into KRMS_RULE_T (ACTV,DESC_TXT,NM,NMSPC_CD,PROP_ID,RULE_ID,TYP_ID,VER_NBR) 
  values ('Y',null,concat(concat('kuali.atp.type.Fall:',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.rule.type.final.exam.standard')), ':11'),'KS-SYS',null,'KS-KRMS-RULE-12057',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.rule.type.final.exam.standard'),1)
/
INSERT INTO KRMS_AGENDA_ITM_T (AGENDA_ID,AGENDA_ITM_ID,RULE_ID,VER_NBR)
  VALUES ('KS-KRMS-AGENDA-11923','KS-KRMS-AGENDA-ITM-12049','KS-KRMS-RULE-12057',1)
/
UPDATE KRMS_AGENDA_ITM_T set WHEN_FALSE = 'KS-KRMS-AGENDA-ITM-12049' WHERE AGENDA_ITM_ID = 'KS-KRMS-AGENDA-ITM-12048'
/
Insert into KRMS_PROP_T (CMPND_OP_CD,DESC_TXT,PROP_ID,RULE_ID,TYP_ID,VER_NBR,DSCRM_TYP_CD,CMPND_SEQ_NO) 
  values (null,'Final exam timeslot','KS-KRMS-PROP-14750','KS-KRMS-RULE-12057',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.proposition.type.final.exam.timeslot'),1,'S',1)
/
Insert into KRMS_PROP_T (CMPND_OP_CD,DESC_TXT,PROP_ID,RULE_ID,TYP_ID,VER_NBR,DSCRM_TYP_CD,CMPND_SEQ_NO) 
  values (null,'Final exam timeslot','KS-KRMS-PROP-14751','KS-KRMS-RULE-12057',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.proposition.type.final.exam.timeslot'),1,'S',2)
/
Insert into KRMS_PROP_T (CMPND_OP_CD,DESC_TXT,PROP_ID,RULE_ID,TYP_ID,VER_NBR,DSCRM_TYP_CD,CMPND_SEQ_NO) 
  values ('|','Must meet 1 of the following','KS-KRMS-PROP-14752','KS-KRMS-RULE-12057','10077',1,'C',1)
/
Insert into KRMS_CMPND_PROP_PROPS_T (CMPND_PROP_ID,PROP_ID) values ('KS-KRMS-PROP-14752','KS-KRMS-PROP-14750')
/
Insert into KRMS_CMPND_PROP_PROPS_T (CMPND_PROP_ID,PROP_ID) values ('KS-KRMS-PROP-14752','KS-KRMS-PROP-14751')
/
UPDATE KRMS_RULE_T set PROP_ID = 'KS-KRMS-PROP-14752' where RULE_ID like 'KS-KRMS-RULE-12057'
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('T','KS-KRMS-TERM-13443','KS-KRMS-PROP-14750','KS-KRMS-PROP-PARM-20321',1,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('C','true','KS-KRMS-PROP-14750','KS-KRMS-PROP-PARM-20322',2,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('O','=','KS-KRMS-PROP-14750','KS-KRMS-PROP-PARM-20323',3,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('T','KS-KRMS-TERM-13444','KS-KRMS-PROP-14751','KS-KRMS-PROP-PARM-20324',1,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('C','true','KS-KRMS-PROP-14751','KS-KRMS-PROP-PARM-20325',2,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('O','=','KS-KRMS-PROP-14751','KS-KRMS-PROP-PARM-20326',3,2)
/

--Day 6 8:00-10:00
Insert into KRMS_RULE_T (ACTV,DESC_TXT,NM,NMSPC_CD,PROP_ID,RULE_ID,TYP_ID,VER_NBR) 
  values ('Y',null,concat(concat('kuali.atp.type.Fall:',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.rule.type.final.exam.standard')), ':12'),'KS-SYS',null,'KS-KRMS-RULE-12058',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.rule.type.final.exam.standard'),1)
/
INSERT INTO KRMS_AGENDA_ITM_T (AGENDA_ID,AGENDA_ITM_ID,RULE_ID,VER_NBR)
  VALUES ('KS-KRMS-AGENDA-11923','KS-KRMS-AGENDA-ITM-12050','KS-KRMS-RULE-12058',1)
/
UPDATE KRMS_AGENDA_ITM_T set WHEN_FALSE = 'KS-KRMS-AGENDA-ITM-12050' WHERE AGENDA_ITM_ID = 'KS-KRMS-AGENDA-ITM-12049'
/
Insert into KRMS_PROP_T (CMPND_OP_CD,DESC_TXT,PROP_ID,RULE_ID,TYP_ID,VER_NBR,DSCRM_TYP_CD,CMPND_SEQ_NO) 
  values (null,'Final exam timeslot','KS-KRMS-PROP-14753','KS-KRMS-RULE-12058',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.proposition.type.final.exam.timeslot'),1,'S',1)
/
Insert into KRMS_PROP_T (CMPND_OP_CD,DESC_TXT,PROP_ID,RULE_ID,TYP_ID,VER_NBR,DSCRM_TYP_CD,CMPND_SEQ_NO) 
  values (null,'Final exam timeslot','KS-KRMS-PROP-14754','KS-KRMS-RULE-12058',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.proposition.type.final.exam.timeslot'),1,'S',2)
/
Insert into KRMS_PROP_T (CMPND_OP_CD,DESC_TXT,PROP_ID,RULE_ID,TYP_ID,VER_NBR,DSCRM_TYP_CD,CMPND_SEQ_NO) 
  values ('|','Must meet 1 of the following','KS-KRMS-PROP-14755','KS-KRMS-RULE-12058','10077',1,'C',1)
/
Insert into KRMS_CMPND_PROP_PROPS_T (CMPND_PROP_ID,PROP_ID) values ('KS-KRMS-PROP-14755','KS-KRMS-PROP-14753')
/
Insert into KRMS_CMPND_PROP_PROPS_T (CMPND_PROP_ID,PROP_ID) values ('KS-KRMS-PROP-14755','KS-KRMS-PROP-14754')
/
UPDATE KRMS_RULE_T set PROP_ID = 'KS-KRMS-PROP-14755' where RULE_ID like 'KS-KRMS-RULE-12058'
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('T','KS-KRMS-TERM-13445','KS-KRMS-PROP-14753','KS-KRMS-PROP-PARM-20327',1,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('C','true','KS-KRMS-PROP-14753','KS-KRMS-PROP-PARM-20328',2,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('O','=','KS-KRMS-PROP-14753','KS-KRMS-PROP-PARM-20329',3,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('T','KS-KRMS-TERM-13446','KS-KRMS-PROP-14754','KS-KRMS-PROP-PARM-20330',1,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('C','true','KS-KRMS-PROP-14754','KS-KRMS-PROP-PARM-20331',2,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('O','=','KS-KRMS-PROP-14754','KS-KRMS-PROP-PARM-20332',3,2)
/

--Day 5 8:00-10:00
Insert into KRMS_RULE_T (ACTV,DESC_TXT,NM,NMSPC_CD,PROP_ID,RULE_ID,TYP_ID,VER_NBR) 
  values ('Y',null,concat(concat('kuali.atp.type.Fall:',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.rule.type.final.exam.standard')), ':13'),'KS-SYS',null,'KS-KRMS-RULE-12060',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.rule.type.final.exam.standard'),1)
/
INSERT INTO KRMS_AGENDA_ITM_T (AGENDA_ID,AGENDA_ITM_ID,RULE_ID,VER_NBR)
  VALUES ('KS-KRMS-AGENDA-11923','KS-KRMS-AGENDA-ITM-12051','KS-KRMS-RULE-12060',1)
/
UPDATE KRMS_AGENDA_ITM_T set WHEN_FALSE = 'KS-KRMS-AGENDA-ITM-12051' WHERE AGENDA_ITM_ID = 'KS-KRMS-AGENDA-ITM-12050'
/
Insert into KRMS_PROP_T (CMPND_OP_CD,DESC_TXT,PROP_ID,RULE_ID,TYP_ID,VER_NBR,DSCRM_TYP_CD,CMPND_SEQ_NO) 
  values (null,'Final exam timeslot','KS-KRMS-PROP-14759','KS-KRMS-RULE-12060',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.proposition.type.final.exam.timeslot'),1,'S',1)
/
Insert into KRMS_PROP_T (CMPND_OP_CD,DESC_TXT,PROP_ID,RULE_ID,TYP_ID,VER_NBR,DSCRM_TYP_CD,CMPND_SEQ_NO) 
  values (null,'Final exam timeslot','KS-KRMS-PROP-14760','KS-KRMS-RULE-12060',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.proposition.type.final.exam.timeslot'),1,'S',2)
/
Insert into KRMS_PROP_T (CMPND_OP_CD,DESC_TXT,PROP_ID,RULE_ID,TYP_ID,VER_NBR,DSCRM_TYP_CD,CMPND_SEQ_NO) 
  values ('|','Must meet 1 of the following','KS-KRMS-PROP-14761','KS-KRMS-RULE-12060','10077',1,'C',1)
/
Insert into KRMS_CMPND_PROP_PROPS_T (CMPND_PROP_ID,PROP_ID) values ('KS-KRMS-PROP-14761','KS-KRMS-PROP-14759')
/
Insert into KRMS_CMPND_PROP_PROPS_T (CMPND_PROP_ID,PROP_ID) values ('KS-KRMS-PROP-14761','KS-KRMS-PROP-14760')
/
UPDATE KRMS_RULE_T set PROP_ID = 'KS-KRMS-PROP-14761' where RULE_ID like 'KS-KRMS-RULE-12060'
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('T','KS-KRMS-TERM-13449','KS-KRMS-PROP-14759','KS-KRMS-PROP-PARM-20338',1,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('C','true','KS-KRMS-PROP-14759','KS-KRMS-PROP-PARM-20339',2,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('O','=','KS-KRMS-PROP-14759','KS-KRMS-PROP-PARM-20340',3,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('T','KS-KRMS-TERM-13450','KS-KRMS-PROP-14760','KS-KRMS-PROP-PARM-20341',1,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('C','true','KS-KRMS-PROP-14760','KS-KRMS-PROP-PARM-20342',2,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('O','=','KS-KRMS-PROP-14760','KS-KRMS-PROP-PARM-20343',3,2)
/

--EPM
--Day 1 10:30-12:30
Insert into KRMS_RULE_T (ACTV,DESC_TXT,NM,NMSPC_CD,PROP_ID,RULE_ID,TYP_ID,VER_NBR) 
  values ('Y',null,concat(concat('kuali.atp.type.Fall:',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.rule.type.final.exam.standard')), ':14'),'KS-SYS',null,'KS-KRMS-RULE-12054',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.rule.type.final.exam.standard'),1)
/
INSERT INTO KRMS_AGENDA_ITM_T (AGENDA_ID,AGENDA_ITM_ID,RULE_ID,VER_NBR)
  VALUES ('KS-KRMS-AGENDA-11923','KS-KRMS-AGENDA-ITM-12052','KS-KRMS-RULE-12054',1)
/
UPDATE KRMS_AGENDA_ITM_T set WHEN_FALSE = 'KS-KRMS-AGENDA-ITM-12052' WHERE AGENDA_ITM_ID = 'KS-KRMS-AGENDA-ITM-12051'
/

Insert into KRMS_PROP_T (CMPND_OP_CD,DESC_TXT,PROP_ID,RULE_ID,TYP_ID,VER_NBR,DSCRM_TYP_CD,CMPND_SEQ_NO) 
  values (null,'Final exam timeslot','KS-KRMS-PROP-14746','KS-KRMS-RULE-12054',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.proposition.type.final.exam.timeslot'),1,'S',1)
/
Insert into KRMS_PROP_T (CMPND_OP_CD,DESC_TXT,PROP_ID,RULE_ID,TYP_ID,VER_NBR,DSCRM_TYP_CD,CMPND_SEQ_NO) 
  values (null,'Final exam timeslot','KS-KRMS-PROP-14747','KS-KRMS-RULE-12054',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.proposition.type.final.exam.timeslot'),1,'S',2)
/
Insert into KRMS_PROP_T (CMPND_OP_CD,DESC_TXT,PROP_ID,RULE_ID,TYP_ID,VER_NBR,DSCRM_TYP_CD,CMPND_SEQ_NO) 
  values ('|','Must meet 1 of the following','KS-KRMS-PROP-14748','KS-KRMS-RULE-12054','10077',1,'C',1)
/
Insert into KRMS_CMPND_PROP_PROPS_T (CMPND_PROP_ID,PROP_ID) values ('KS-KRMS-PROP-14748','KS-KRMS-PROP-14746')
/
Insert into KRMS_CMPND_PROP_PROPS_T (CMPND_PROP_ID,PROP_ID) values ('KS-KRMS-PROP-14748','KS-KRMS-PROP-14747')
/
UPDATE KRMS_RULE_T set PROP_ID = 'KS-KRMS-PROP-14748' where RULE_ID like 'KS-KRMS-RULE-12054'
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('T','KS-KRMS-TERM-13441','KS-KRMS-PROP-14746','KS-KRMS-PROP-PARM-20312',1,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('C','true','KS-KRMS-PROP-14746','KS-KRMS-PROP-PARM-20313',2,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('O','=','KS-KRMS-PROP-14746','KS-KRMS-PROP-PARM-20314',3,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('T','KS-KRMS-TERM-13442','KS-KRMS-PROP-14747','KS-KRMS-PROP-PARM-20315',1,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('C','true','KS-KRMS-PROP-14747','KS-KRMS-PROP-PARM-20316',2,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('O','=','KS-KRMS-PROP-14747','KS-KRMS-PROP-PARM-20317',3,2)
/


--Day 3 08:00-10:00
Insert into KRMS_RULE_T (ACTV,DESC_TXT,NM,NMSPC_CD,PROP_ID,RULE_ID,TYP_ID,VER_NBR) 
  values ('Y',null,concat(concat('kuali.atp.type.Fall:',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.rule.type.final.exam.standard')), ':15'),'KS-SYS',null,'KS-KRMS-RULE-12059',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.rule.type.final.exam.standard'),1)
/
INSERT INTO KRMS_AGENDA_ITM_T (AGENDA_ID,AGENDA_ITM_ID,RULE_ID,VER_NBR)
  VALUES ('KS-KRMS-AGENDA-11923','KS-KRMS-AGENDA-ITM-12053','KS-KRMS-RULE-12059',1)
/
UPDATE KRMS_AGENDA_ITM_T set WHEN_FALSE = 'KS-KRMS-AGENDA-ITM-12053' WHERE AGENDA_ITM_ID = 'KS-KRMS-AGENDA-ITM-12052'
/

Insert into KRMS_PROP_T (CMPND_OP_CD,DESC_TXT,PROP_ID,RULE_ID,TYP_ID,VER_NBR,DSCRM_TYP_CD,CMPND_SEQ_NO) 
  values (null,'Final exam timeslot','KS-KRMS-PROP-14756','KS-KRMS-RULE-12059',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.proposition.type.final.exam.timeslot'),1,'S',1)
/
Insert into KRMS_PROP_T (CMPND_OP_CD,DESC_TXT,PROP_ID,RULE_ID,TYP_ID,VER_NBR,DSCRM_TYP_CD,CMPND_SEQ_NO) 
  values (null,'Final exam timeslot','KS-KRMS-PROP-14757','KS-KRMS-RULE-12059',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.proposition.type.final.exam.timeslot'),1,'S',2)
/
Insert into KRMS_PROP_T (CMPND_OP_CD,DESC_TXT,PROP_ID,RULE_ID,TYP_ID,VER_NBR,DSCRM_TYP_CD,CMPND_SEQ_NO) 
  values ('|','Must meet 1 of the following','KS-KRMS-PROP-14758','KS-KRMS-RULE-12059','10077',1,'C',1)
/
Insert into KRMS_CMPND_PROP_PROPS_T (CMPND_PROP_ID,PROP_ID) values ('KS-KRMS-PROP-14758','KS-KRMS-PROP-14756')
/
Insert into KRMS_CMPND_PROP_PROPS_T (CMPND_PROP_ID,PROP_ID) values ('KS-KRMS-PROP-14758','KS-KRMS-PROP-14757')
/
UPDATE KRMS_RULE_T set PROP_ID = 'KS-KRMS-PROP-14758' where RULE_ID like 'KS-KRMS-RULE-12059'
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('T','KS-KRMS-TERM-13447','KS-KRMS-PROP-14756','KS-KRMS-PROP-PARM-20356',1,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('C','true','KS-KRMS-PROP-14756','KS-KRMS-PROP-PARM-20333',2,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('O','=','KS-KRMS-PROP-14756','KS-KRMS-PROP-PARM-20334',3,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('T','KS-KRMS-TERM-13448','KS-KRMS-PROP-14757','KS-KRMS-PROP-PARM-20335',1,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('C','true','KS-KRMS-PROP-14757','KS-KRMS-PROP-PARM-20336',2,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('O','=','KS-KRMS-PROP-14757','KS-KRMS-PROP-PARM-20337',3,2)
/


--Day 3 13:30-15:30
Insert into KRMS_RULE_T (ACTV,DESC_TXT,NM,NMSPC_CD,PROP_ID,RULE_ID,TYP_ID,VER_NBR) 
  values ('Y',null,concat(concat('kuali.atp.type.Fall:',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.rule.type.final.exam.standard')), ':16'),'KS-SYS',null,'KS-KRMS-RULE-12061',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.rule.type.final.exam.standard'),1)
/
INSERT INTO KRMS_AGENDA_ITM_T (AGENDA_ID,AGENDA_ITM_ID,RULE_ID,VER_NBR)
  VALUES ('KS-KRMS-AGENDA-11923','KS-KRMS-AGENDA-ITM-12054','KS-KRMS-RULE-12061',1)
/
UPDATE KRMS_AGENDA_ITM_T set WHEN_FALSE = 'KS-KRMS-AGENDA-ITM-12054' WHERE AGENDA_ITM_ID = 'KS-KRMS-AGENDA-ITM-12053'
/

Insert into KRMS_PROP_T (CMPND_OP_CD,DESC_TXT,PROP_ID,RULE_ID,TYP_ID,VER_NBR,DSCRM_TYP_CD,CMPND_SEQ_NO) 
  values (null,'Final exam timeslot','KS-KRMS-PROP-14762','KS-KRMS-RULE-12061',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.proposition.type.final.exam.timeslot'),1,'S',1)
/
Insert into KRMS_PROP_T (CMPND_OP_CD,DESC_TXT,PROP_ID,RULE_ID,TYP_ID,VER_NBR,DSCRM_TYP_CD,CMPND_SEQ_NO) 
  values (null,'Final exam timeslot','KS-KRMS-PROP-14763','KS-KRMS-RULE-12061',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.proposition.type.final.exam.timeslot'),1,'S',2)
/
Insert into KRMS_PROP_T (CMPND_OP_CD,DESC_TXT,PROP_ID,RULE_ID,TYP_ID,VER_NBR,DSCRM_TYP_CD,CMPND_SEQ_NO) 
  values ('|','Must meet 1 of the following','KS-KRMS-PROP-14764','KS-KRMS-RULE-12061','10077',1,'C',1)
/
Insert into KRMS_CMPND_PROP_PROPS_T (CMPND_PROP_ID,PROP_ID) values ('KS-KRMS-PROP-14764','KS-KRMS-PROP-14762')
/
Insert into KRMS_CMPND_PROP_PROPS_T (CMPND_PROP_ID,PROP_ID) values ('KS-KRMS-PROP-14764','KS-KRMS-PROP-14763')
/
UPDATE KRMS_RULE_T set PROP_ID = 'KS-KRMS-PROP-14764' where RULE_ID like 'KS-KRMS-RULE-12061'
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('T','KS-KRMS-TERM-13451','KS-KRMS-PROP-14762','KS-KRMS-PROP-PARM-20344',1,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('C','true','KS-KRMS-PROP-14762','KS-KRMS-PROP-PARM-20345',2,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('O','=','KS-KRMS-PROP-14762','KS-KRMS-PROP-PARM-20346',3,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('T','KS-KRMS-TERM-13452','KS-KRMS-PROP-14763','KS-KRMS-PROP-PARM-20347',1,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('C','true','KS-KRMS-PROP-14763','KS-KRMS-PROP-PARM-20348',2,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('O','=','KS-KRMS-PROP-14763','KS-KRMS-PROP-PARM-20349',3,2)
/


--Day 4 13:30-15:30
Insert into KRMS_RULE_T (ACTV,DESC_TXT,NM,NMSPC_CD,PROP_ID,RULE_ID,TYP_ID,VER_NBR) 
  values ('Y',null,concat(concat('kuali.atp.type.Fall:',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.rule.type.final.exam.standard')), ':17'),'KS-SYS',null,'KS-KRMS-RULE-12062',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.rule.type.final.exam.standard'),1)
/
INSERT INTO KRMS_AGENDA_ITM_T (AGENDA_ID,AGENDA_ITM_ID,RULE_ID,VER_NBR)
  VALUES ('KS-KRMS-AGENDA-11923','KS-KRMS-AGENDA-ITM-12055','KS-KRMS-RULE-12062',1)
/
UPDATE KRMS_AGENDA_ITM_T set WHEN_FALSE = 'KS-KRMS-AGENDA-ITM-12055' WHERE AGENDA_ITM_ID = 'KS-KRMS-AGENDA-ITM-12054'
/

Insert into KRMS_PROP_T (CMPND_OP_CD,DESC_TXT,PROP_ID,RULE_ID,TYP_ID,VER_NBR,DSCRM_TYP_CD,CMPND_SEQ_NO) 
  values (null,'Final exam timeslot','KS-KRMS-PROP-14765','KS-KRMS-RULE-12062',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.proposition.type.final.exam.timeslot'),1,'S',1)
/
Insert into KRMS_PROP_T (CMPND_OP_CD,DESC_TXT,PROP_ID,RULE_ID,TYP_ID,VER_NBR,DSCRM_TYP_CD,CMPND_SEQ_NO) 
  values (null,'Final exam timeslot','KS-KRMS-PROP-14766','KS-KRMS-RULE-12062',(SELECT TYP_ID FROM KRMS_TYP_T WHERE NM = 'kuali.krms.proposition.type.final.exam.timeslot'),1,'S',2)
/
Insert into KRMS_PROP_T (CMPND_OP_CD,DESC_TXT,PROP_ID,RULE_ID,TYP_ID,VER_NBR,DSCRM_TYP_CD,CMPND_SEQ_NO) 
  values ('|','Must meet 1 of the following','KS-KRMS-PROP-14767','KS-KRMS-RULE-12062','10077',1,'C',1)
/
Insert into KRMS_CMPND_PROP_PROPS_T (CMPND_PROP_ID,PROP_ID) values ('KS-KRMS-PROP-14767','KS-KRMS-PROP-14765')
/
Insert into KRMS_CMPND_PROP_PROPS_T (CMPND_PROP_ID,PROP_ID) values ('KS-KRMS-PROP-14767','KS-KRMS-PROP-14766')
/
UPDATE KRMS_RULE_T set PROP_ID = 'KS-KRMS-PROP-14767' where RULE_ID like 'KS-KRMS-RULE-12062'
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('T','KS-KRMS-TERM-13453','KS-KRMS-PROP-14765','KS-KRMS-PROP-PARM-20350',1,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('C','true','KS-KRMS-PROP-14765','KS-KRMS-PROP-PARM-20351',2,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('O','=','KS-KRMS-PROP-14765','KS-KRMS-PROP-PARM-20352',3,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('T','KS-KRMS-TERM-13454','KS-KRMS-PROP-14766','KS-KRMS-PROP-PARM-20353',1,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('C','true','KS-KRMS-PROP-14766','KS-KRMS-PROP-PARM-20354',2,2)
/
Insert into KRMS_PROP_PARM_T (PARM_TYP_CD,PARM_VAL,PROP_ID,PROP_PARM_ID,SEQ_NO,VER_NBR) values ('O','=','KS-KRMS-PROP-14766','KS-KRMS-PROP-PARM-20355',3,2)
/
