INSERT INTO KSEN_TYPE (CREATEID,CREATETIME,DESCR_FORMATTED,DESCR_PLAIN,NAME,REF_OBJECT_URI,SERVICE_URI,TYPE_KEY,VER_NBR) VALUES ('SYSTEMLOADER',TO_DATE( '20130930000000', 'YYYYMMDDHH24MISS' ),'TimeSlots grouping type', 'TimeSlots grouping type','TimeSlot Group','http://student.kuali.org/wsdl/scheduling/TimeSlotInfo','http://student.kuali.org/wsdl/scheduling/SchedulingService','kuali.scheduling.type.time.slot',0)
/
INSERT INTO KSEN_TYPETYPE_RELTN (CREATEID,CREATETIME,ID,OWNER_TYPE_ID,RANK,RELATED_TYPE_ID,TYPETYPE_RELTN_STATE,TYPETYPE_RELTN_TYPE,VER_NBR) VALUES ('SYSTEMLOADER',TO_DATE( '20130930000000', 'YYYYMMDDHH24MISS' ),'kuali.type.type.relation.type.group.kuali.scheduling.type.time.slot.kuali.scheduling.time.slot.type.activityoffering.standard.fullterm.fall','kuali.scheduling.type.time.slot',0,'kuali.scheduling.time.slot.type.activityoffering.standard.fullterm.fall','kuali.type.type.relation.state.active','kuali.type.type.relation.type.group',0)
/
INSERT INTO KSEN_TYPETYPE_RELTN (CREATEID,CREATETIME,ID,OWNER_TYPE_ID,RANK,RELATED_TYPE_ID,TYPETYPE_RELTN_STATE,TYPETYPE_RELTN_TYPE,VER_NBR) VALUES ('SYSTEMLOADER',TO_DATE( '20130930000000', 'YYYYMMDDHH24MISS' ),'kuali.type.type.relation.type.group.kuali.scheduling.type.time.slot.kuali.scheduling.time.slot.type.activityoffering.standard.fullterm.spring','kuali.scheduling.type.time.slot',0,'kuali.scheduling.time.slot.type.activityoffering.standard.fullterm.spring','kuali.type.type.relation.state.active','kuali.type.type.relation.type.group',0)
/
INSERT INTO KSEN_TYPETYPE_RELTN (CREATEID,CREATETIME,ID,OWNER_TYPE_ID,RANK,RELATED_TYPE_ID,TYPETYPE_RELTN_STATE,TYPETYPE_RELTN_TYPE,VER_NBR) VALUES ('SYSTEMLOADER',TO_DATE( '20130930000000', 'YYYYMMDDHH24MISS' ),'kuali.type.type.relation.type.group.kuali.scheduling.type.time.slot.kuali.scheduling.time.slot.type.activityoffering.adhoc','kuali.scheduling.type.time.slot',0,'kuali.scheduling.time.slot.type.activityoffering.adhoc','kuali.type.type.relation.state.active','kuali.type.type.relation.type.group',0)
/
INSERT INTO KSEN_TYPETYPE_RELTN (CREATEID,CREATETIME,ID,OWNER_TYPE_ID,RANK,RELATED_TYPE_ID,TYPETYPE_RELTN_STATE,TYPETYPE_RELTN_TYPE,VER_NBR) VALUES ('SYSTEMLOADER',TO_DATE( '20130930000000', 'YYYYMMDDHH24MISS' ),'kuali.type.type.relation.type.group.kuali.scheduling.type.time.slot.kuali.scheduling.time.slot.type.activityoffering.tba','kuali.scheduling.type.time.slot',0,'kuali.scheduling.time.slot.type.activityoffering.tba','kuali.type.type.relation.state.active','kuali.type.type.relation.type.group',0)
/
INSERT INTO KSEN_TYPETYPE_RELTN (CREATEID,CREATETIME,ID,OWNER_TYPE_ID,RANK,RELATED_TYPE_ID,TYPETYPE_RELTN_STATE,TYPETYPE_RELTN_TYPE,VER_NBR) VALUES ('SYSTEMLOADER',TO_DATE( '20130930000000', 'YYYYMMDDHH24MISS' ),'kuali.type.type.relation.type.allowed.atp2timeslot.kuali.atp.type.fall.kuali.scheduling.time.slot.type.activityoffering.standard.fullterm.fall','kuali.atp.type.Fall',0,'kuali.scheduling.time.slot.type.activityoffering.standard.fullterm.fall','kuali.type.type.relation.state.active','kuali.type.type.relation.type.allowed.atp2timeslot',0)
/
INSERT INTO KSEN_TYPETYPE_RELTN (CREATEID,CREATETIME,ID,OWNER_TYPE_ID,RANK,RELATED_TYPE_ID,TYPETYPE_RELTN_STATE,TYPETYPE_RELTN_TYPE,VER_NBR) VALUES ('SYSTEMLOADER',TO_DATE( '20130930000000', 'YYYYMMDDHH24MISS' ),'kuali.type.type.relation.type.allowed.atp2timeslot.kuali.atp.type.spring.kuali.scheduling.time.slot.type.activityoffering.standard.fullterm.spring','kuali.atp.type.Spring',0,'kuali.scheduling.time.slot.type.activityoffering.standard.fullterm.spring','kuali.type.type.relation.state.active','kuali.type.type.relation.type.allowed.atp2timeslot',0)
/
