Insert into KSEN_STATE_LIFECYCLE (CREATEID,CREATETIME,DESCR_FORMATTED,DESCR_PLAIN,ID,NAME,OBJ_ID,REF_OBJECT_URI,UPDATEID,UPDATETIME,VER_NBR)
values ('SYSTEMLOADER',to_timestamp('20/SEP/13 13:00:00.000000000','DD/MON/RR HH24:MI:SS.FF'),'Lifecycle for exam offering','Lifecycle for exam offering','kuali.exam.offering.lifecycle','Lifecycle for exam offering',SYS_GUID(),null,null,null,1)
/

Insert into KSEN_STATE_LIFECYCLE (CREATEID,CREATETIME,DESCR_FORMATTED,DESCR_PLAIN,ID,NAME,OBJ_ID,REF_OBJECT_URI,UPDATEID,UPDATETIME,VER_NBR)
values ('SYSTEMLOADER',to_timestamp('20/SEP/13 13:00:00.000000000','DD/MON/RR HH24:MI:SS.FF'),'Lifecycle for exam offering scheduling','Lifecycle for exam offering scheduling','kuali.exam.offering.scheduling.lifecycle','Lifecycle for exam offering scheduling',SYS_GUID(),null,null,null,1)
/

Insert into KSEN_STATE (CREATEID,CREATETIME,DESCR_FORMATTED,DESCR_PLAIN,EFF_DT,EXPIR_DT,ID,IS_INITIAL_STATE,LIFECYCLE_KEY,NAME,OBJ_ID,UPDATEID,UPDATETIME,VER_NBR)
values ('SYSTEMLOADER',to_timestamp('20/SEP/13 13:00:00.000000000','DD/MON/RR HH24:MI:SS.FF'),'An Exam Offering that has been newly created (either via Rollover or individual creation) that is not ready for scheduling or any other downstream process or was changed back to the Draft state by the user. Cannot interact with the Scheduler or the Publishing Process.','An Exam Offering that has been newly created (either via Rollover or individual creation) that is not ready for scheduling or any other downstream process or was changed back to the Draft state by the user. Cannot interact with the Scheduler or the Publishing Process.',null,null,'kuali.lui.exam.offering.state.draft',0,'kuali.exam.offering.lifecycle','Draft',SYS_GUID(),null,null,0)
/

Insert into KSEN_STATE (CREATEID,CREATETIME,DESCR_FORMATTED,DESCR_PLAIN,EFF_DT,EXPIR_DT,ID,IS_INITIAL_STATE,LIFECYCLE_KEY,NAME,OBJ_ID,UPDATEID,UPDATETIME,VER_NBR)
values ('SYSTEMLOADER',to_timestamp('20/SEP/13 13:00:00.000000000','DD/MON/RR HH24:MI:SS.FF'),'An Exam Offering with Actual Delivery Logistics that was successfully published. This publishing may have been done through the initial Publish process or afterwards depending on the business process of the institution. The Exam Offering is now available for registration purposes (based on assumption students will be registered in exams).','An Exam Offering with Actual Delivery Logistics that was successfully published. This publishing may have been done through the initial Publish process or afterwards depending on the business process of the institution. The Exam Offering is now available for registration purposes (based on assumption students will be registered in exams).',null,null,'kuali.lui.exam.offering.state.offered',0,'kuali.exam.offering.lifecycle','Offered',SYS_GUID(),null,null,0)
/

Insert into KSEN_STATE (CREATEID,CREATETIME,DESCR_FORMATTED,DESCR_PLAIN,EFF_DT,EXPIR_DT,ID,IS_INITIAL_STATE,LIFECYCLE_KEY,NAME,OBJ_ID,UPDATEID,UPDATETIME,VER_NBR)
values ('SYSTEMLOADER',to_timestamp('20/SEP/13 13:00:00.000000000','DD/MON/RR HH24:MI:SS.FF'),'An Exam Offering for which registration has been suspended. This may be due to the fact that the associated CO/AO of the exam has been suspended or because the exam offering was suspended uniquely. Students currently registered for the Exam Offering remain registered, and rooms associated with Actual Delivery Logistics are retained.','An Exam Offering for which registration has been suspended. This may be due to the fact that the associated CO/AO of the exam has been suspended or because the exam offering was suspended uniquely. Students currently registered for the Exam Offering remain registered, and rooms associated with Actual Delivery Logistics are retained.',null,null,'kuali.lui.exam.offering.state.suspended',0,'kuali.exam.offering.lifecycle','Suspended',SYS_GUID(),null,null,0)
/

Insert into KSEN_STATE (CREATEID,CREATETIME,DESCR_FORMATTED,DESCR_PLAIN,EFF_DT,EXPIR_DT,ID,IS_INITIAL_STATE,LIFECYCLE_KEY,NAME,OBJ_ID,UPDATEID,UPDATETIME,VER_NBR)
values ('SYSTEMLOADER',to_timestamp('20/SEP/13 13:00:00.000000000','DD/MON/RR HH24:MI:SS.FF'),'An Exam Offering for which registration has been canceled. This may be due to the fact that the associated CO/AO of the exam has been canceled or because the exam offering was canceled uniquely. Students will not remain enrolled, and rooms associated with Actual Delivery Logistics are released.','An Exam Offering for which registration has been canceled. This may be due to the fact that the associated CO/AO of the exam has been canceled or because the exam offering was canceled uniquely. Students will not remain enrolled, and rooms associated with Actual Delivery Logistics are released.',null,null,'kuali.lui.exam.offering.state.canceled',0,'kuali.exam.offering.lifecycle','Canceled',SYS_GUID(),null,null,0)
/

Insert into KSEN_STATE (CREATEID,CREATETIME,DESCR_FORMATTED,DESCR_PLAIN,EFF_DT,EXPIR_DT,ID,IS_INITIAL_STATE,LIFECYCLE_KEY,NAME,OBJ_ID,UPDATEID,UPDATETIME,VER_NBR)
values ('SYSTEMLOADER',to_timestamp('20/SEP/13 13:00:00.000000000','DD/MON/RR HH24:MI:SS.FF'),'No EO Component Scheduling State is Scheduled, nor Error, nor Unscheduled;  only EO Component Scheduling States of Exempt exist.  Delivery Logistics are TBA (may be departmentally owned) and do not require interaction with the Scheduler. EO State can become Offered.','No EO Component Scheduling State is Scheduled, nor Error, nor Unscheduled;  only EO Component Scheduling States of Exempt exist.  Delivery Logistics are TBA (may be departmentally owned) and do not require interaction with the Scheduler. EO State can become Offered.',null,null,'kuali.lui.exam.offering.scheduling.state.exempt',0,'kuali.exam.offering.scheduling.lifecycle','Exempt',SYS_GUID(),null,null,0)
/

Insert into KSEN_STATE (CREATEID,CREATETIME,DESCR_FORMATTED,DESCR_PLAIN,EFF_DT,EXPIR_DT,ID,IS_INITIAL_STATE,LIFECYCLE_KEY,NAME,OBJ_ID,UPDATEID,UPDATETIME,VER_NBR)
values ('SYSTEMLOADER',to_timestamp('20/SEP/13 13:00:00.000000000','DD/MON/RR HH24:MI:SS.FF'),'At least one EO Component Scheduling State is Scheduled and no EO Component Scheduling State is Error.  Exam Offering has non-TBA Requested Delivery Logistics that successfully interacted with the Scheduler to assign Actual Delivery Logistics that include a Room. EO State can become Offered.','At least one EO Component Scheduling State is Scheduled and no EO Component Scheduling State is Error.  Exam Offering has non-TBA Requested Delivery Logistics that successfully interacted with the Scheduler to assign Actual Delivery Logistics that include a Room. EO State can become Offered.',null,null,'kuali.lui.exam.offering.scheduling.state.scheduled',0,'kuali.exam.offering.scheduling.lifecycle','Scheduled',SYS_GUID(),null,null,0)
/

Insert into KSEN_STATE (CREATEID,CREATETIME,DESCR_FORMATTED,DESCR_PLAIN,EFF_DT,EXPIR_DT,ID,IS_INITIAL_STATE,LIFECYCLE_KEY,NAME,OBJ_ID,UPDATEID,UPDATETIME,VER_NBR)
values ('SYSTEMLOADER',to_timestamp('20/SEP/13 13:00:00.000000000','DD/MON/RR HH24:MI:SS.FF'),'No EO Component Scheduling State is Scheduled nor Error; EO Component Scheduling State may, but need not be, Exempt.  The Exam Offering has not interacted with the Scheduler to assign Actual Delivery Logistics. This may be because the Mass Scheduling Event has not occurred, the Exam Offering has no Requested Delivery Logistics, or the Exam Offering was Canceled. EO State cannot become Offered.','No EO Component Scheduling State is Scheduled nor Error; EO Component Scheduling State may, but need not be, Exempt.  The Exam Offering has not interacted with the Scheduler to assign Actual Delivery Logistics. This may be because the Mass Scheduling Event has not occurred, the Exam Offering has no Requested Delivery Logistics, or the Exam Offering was Canceled. EO State cannot become Offered.',null,null,'kuali.lui.exam.offering.scheduling.state.unscheduled',0,'kuali.exam.offering.scheduling.lifecycle','Unscheduled',SYS_GUID(),null,null,0)
/

Insert into KSEN_STATE (CREATEID,CREATETIME,DESCR_FORMATTED,DESCR_PLAIN,EFF_DT,EXPIR_DT,ID,IS_INITIAL_STATE,LIFECYCLE_KEY,NAME,OBJ_ID,UPDATEID,UPDATETIME,VER_NBR)
values ('SYSTEMLOADER',to_timestamp('20/SEP/13 13:00:00.000000000','DD/MON/RR HH24:MI:SS.FF'),'At least one (1) EO Component Scheduling State is Error, regardless of any other EO Component Scheduling State. Valid Requested Delivery Logistics interacted with the Scheduler but failed to assign Actual Delivery Logistics, either due to a conflict or lack of data. EO State cannot become Offered.','At least one (1) EO Component Scheduling State is Error, regardless of any other EO Component Scheduling State. Valid Requested Delivery Logistics interacted with the Scheduler but failed to assign Actual Delivery Logistics, either due to a conflict or lack of data. EO State cannot become Offered.',null,null,'kuali.lui.exam.offering.scheduling.state.error',0,'kuali.exam.offering.scheduling.lifecycle','Error',SYS_GUID(),null,null,0)
/

Insert into KSEN_STATE (CREATEID,CREATETIME,DESCR_FORMATTED,DESCR_PLAIN,EFF_DT,EXPIR_DT,ID,IS_INITIAL_STATE,LIFECYCLE_KEY,NAME,OBJ_ID,UPDATEID,UPDATETIME,VER_NBR)
values ('SYSTEMLOADER',to_timestamp('20/SEP/13 13:00:00.000000000','DD/MON/RR HH24:MI:SS.FF'),'Despite being marked as on-matrix the associated AO time slot or Course does not exist in the matrix so no RDL data could be populated for the EO.','Despite being marked as on-matrix the associated AO time slot or Course does not exist in the matrix so no RDL data could be populated for the EO.',null,null,'kuali.lui.exam.offering.scheduling.state.matrix.error',0,'kuali.exam.offering.scheduling.lifecycle','Matrix Error',SYS_GUID(),null,null,0)
/