
package org.kuali.student.lum.lu.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.2
 * Thu Jan 21 10:05:23 PST 2010
 * Generated source version: 2.2
 */

@XmlRootElement(name = "createCluResult", namespace = "http://student.kuali.org/wsdl/lu")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "createCluResult", namespace = "http://student.kuali.org/wsdl/lu", propOrder = {"cluId","cluResultType","cluResultInfo"})

public class CreateCluResult {

    @XmlElement(name = "cluId")
    private java.lang.String cluId;
    @XmlElement(name = "cluResultType")
    private java.lang.String cluResultType;
    @XmlElement(name = "cluResultInfo")
    private org.kuali.student.lum.lu.dto.CluResultInfo cluResultInfo;

    public java.lang.String getCluId() {
        return this.cluId;
    }

    public void setCluId(java.lang.String newCluId)  {
        this.cluId = newCluId;
    }

    public java.lang.String getCluResultType() {
        return this.cluResultType;
    }

    public void setCluResultType(java.lang.String newCluResultType)  {
        this.cluResultType = newCluResultType;
    }

    public org.kuali.student.lum.lu.dto.CluResultInfo getCluResultInfo() {
        return this.cluResultInfo;
    }

    public void setCluResultInfo(org.kuali.student.lum.lu.dto.CluResultInfo newCluResultInfo)  {
        this.cluResultInfo = newCluResultInfo;
    }

}

