
package org.kuali.student.lum.lu.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.2
 * Thu Jan 21 10:05:23 PST 2010
 * Generated source version: 2.2
 */

@XmlRootElement(name = "createCluPublication", namespace = "http://student.kuali.org/wsdl/lu")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "createCluPublication", namespace = "http://student.kuali.org/wsdl/lu", propOrder = {"cluId","luPublicationType","cluPublicationInfo"})

public class CreateCluPublication {

    @XmlElement(name = "cluId")
    private java.lang.String cluId;
    @XmlElement(name = "luPublicationType")
    private java.lang.String luPublicationType;
    @XmlElement(name = "cluPublicationInfo")
    private org.kuali.student.lum.lu.dto.CluPublicationInfo cluPublicationInfo;

    public java.lang.String getCluId() {
        return this.cluId;
    }

    public void setCluId(java.lang.String newCluId)  {
        this.cluId = newCluId;
    }

    public java.lang.String getLuPublicationType() {
        return this.luPublicationType;
    }

    public void setLuPublicationType(java.lang.String newLuPublicationType)  {
        this.luPublicationType = newLuPublicationType;
    }

    public org.kuali.student.lum.lu.dto.CluPublicationInfo getCluPublicationInfo() {
        return this.cluPublicationInfo;
    }

    public void setCluPublicationInfo(org.kuali.student.lum.lu.dto.CluPublicationInfo newCluPublicationInfo)  {
        this.cluPublicationInfo = newCluPublicationInfo;
    }

}

