
package org.kuali.student.lum.lu.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.2
 * Thu Jan 21 10:05:23 PST 2010
 * Generated source version: 2.2
 */

@XmlRootElement(name = "updateCluPublication", namespace = "http://student.kuali.org/wsdl/lu")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateCluPublication", namespace = "http://student.kuali.org/wsdl/lu", propOrder = {"cluPublicationId","cluPublicationInfo"})

public class UpdateCluPublication {

    @XmlElement(name = "cluPublicationId")
    private java.lang.String cluPublicationId;
    @XmlElement(name = "cluPublicationInfo")
    private org.kuali.student.lum.lu.dto.CluPublicationInfo cluPublicationInfo;

    public java.lang.String getCluPublicationId() {
        return this.cluPublicationId;
    }

    public void setCluPublicationId(java.lang.String newCluPublicationId)  {
        this.cluPublicationId = newCluPublicationId;
    }

    public org.kuali.student.lum.lu.dto.CluPublicationInfo getCluPublicationInfo() {
        return this.cluPublicationInfo;
    }

    public void setCluPublicationInfo(org.kuali.student.lum.lu.dto.CluPublicationInfo newCluPublicationInfo)  {
        this.cluPublicationInfo = newCluPublicationInfo;
    }

}

