
package org.kuali.student.security.trust.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.2
 * Wed Jun 09 11:32:58 EDT 2010
 * Generated source version: 2.2
 */

@XmlRootElement(name = "RequestSecurityTokenResponse", namespace = "http://schemas.xmlsoap.org/ws/2005/02/trust/wsdl")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestSecurityTokenResponse", namespace = "http://schemas.xmlsoap.org/ws/2005/02/trust/wsdl")

public class RequestSecurityTokenResponse {

    @XmlElement(name = "RequestSecurityTokenResponse")
    private org.kuali.student.security.trust.dto.RequestSecurityTokenResponseType RequestSecurityTokenResponse;

    public org.kuali.student.security.trust.dto.RequestSecurityTokenResponseType getRequestSecurityTokenResponse() {
        return this.RequestSecurityTokenResponse;
    }

    public void setRequestSecurityTokenResponse(org.kuali.student.security.trust.dto.RequestSecurityTokenResponseType newRequestSecurityTokenResponse)  {
        this.RequestSecurityTokenResponse = newRequestSecurityTokenResponse;
    }

}

