
package org.kuali.student.wsdl.enumerationmanagement;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.3
 * Thu Aug 26 12:54:13 EDT 2010
 * Generated source version: 2.2.3
 * 
 */

@WebFault(name = "DoesNotExistException", targetNamespace = "http://student.kuali.org/wsdl/enumerationmanagement")
public class DoesNotExistException extends Exception {
    public static final long serialVersionUID = 20100826125413L;
    
    private org.kuali.student.wsdl.exceptions.DoesNotExistException doesNotExistException;

    public DoesNotExistException() {
        super();
    }
    
    public DoesNotExistException(String message) {
        super(message);
    }
    
    public DoesNotExistException(String message, Throwable cause) {
        super(message, cause);
    }

    public DoesNotExistException(String message, org.kuali.student.wsdl.exceptions.DoesNotExistException doesNotExistException) {
        super(message);
        this.doesNotExistException = doesNotExistException;
    }

    public DoesNotExistException(String message, org.kuali.student.wsdl.exceptions.DoesNotExistException doesNotExistException, Throwable cause) {
        super(message, cause);
        this.doesNotExistException = doesNotExistException;
    }

    public org.kuali.student.wsdl.exceptions.DoesNotExistException getFaultInfo() {
        return this.doesNotExistException;
    }
}
