
package org.kuali.student.core.search.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.1.3
 * Tue Jan 27 08:59:03 EST 2009
 * Generated source version: 2.1.3
 */

@XmlRootElement(name = "getSearchCriteriaType", namespace = "http://org.kuali.student/core/search")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getSearchCriteriaType", namespace = "http://org.kuali.student/core/search")

public class GetSearchCriteriaType {

    @XmlElement(name = "searchCriteriaTypeKey")
    private java.lang.String searchCriteriaTypeKey;

    public java.lang.String getSearchCriteriaTypeKey() {
        return this.searchCriteriaTypeKey;
    }

    public void setSearchCriteriaTypeKey(java.lang.String newSearchCriteriaTypeKey)  {
        this.searchCriteriaTypeKey = newSearchCriteriaTypeKey;
    }

}

