
package org.kuali.student.core.search.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.2
 * Fri Feb 26 11:02:00 EST 2010
 * Generated source version: 2.2
 */

@XmlRootElement(name = "searchResponse", namespace = "http://student.kuali.org/wsdl/organization")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "searchResponse", namespace = "http://student.kuali.org/wsdl/organization")

public class SearchResponse {

    @XmlElement(name = "return")
    private org.kuali.student.core.search.dto.SearchResult _return;

    public org.kuali.student.core.search.dto.SearchResult getReturn() {
        return this._return;
    }

    public void setReturn(org.kuali.student.core.search.dto.SearchResult new_return)  {
        this._return = new_return;
    }

}

